#!/usr/bin/env python3
"""Join the executable digests this survey's committed evidence records (jit:3be770d5).

Writes `dev/bench_results/3be770d5/preparation/executable-identity.md`. For
every executable of the harness it reports the digest the measurements
recorded, the digest the current build identity records, and whether the two
agree. Measured digests come from the arm descriptors of each committed
campaign receipt and from the identity line of the first profile series'
`repetitions.log`; nothing is typed in, and an executable no measurement
recorded is named as such.

The table is what shows which executables a source change moved: a change
confined to one binary leaves every other measured digest equal to the current
one, so a campaign that re-measures those arms measures the bytes its
predecessor did.

Usage (from the worktree root): executable-identity.py
"""

import json
import pathlib

RESULTS = pathlib.Path("dev/bench_results/3be770d5")
PREPARATION = RESULTS / "preparation"
IDENTITY = PREPARATION / "build-identity.json"
OUTPUT = PREPARATION / "executable-identity.md"


def measured():
    """Digest of each executable as a committed measurement recorded it."""
    records = {}
    for receipt_path in sorted(RESULTS.glob("*-3be770d5-ldpc-steady-*/receipt.json")):
        receipt = json.loads(receipt_path.read_text())
        for arm in receipt["arms"].values():
            name = pathlib.Path(arm["executable_path"]).name
            records.setdefault(name, {}).setdefault(arm["executable_sha256"], set()).add(
                receipt_path.parent.name)
    for log in sorted(RESULTS.glob("*-steady-profile/repetitions.log")):
        for line in log.read_text().splitlines():
            fields = line.split()
            if len(fields) < 3 or fields[1] != "start":
                continue
            for field in fields:
                if "=" not in field:
                    continue
                name, _, digest = field.partition("=")
                if len(digest) == 64:
                    records.setdefault(name, {}).setdefault(digest, set()).add(log.parent.name)
            break
    return records


def main():
    current = json.loads(IDENTITY.read_text())["executables"]
    records = measured()
    lines = ["# Executable identity across this survey's measurements", "",
             "> **Diátaxis Type:** Reference", "",
             f"Generated by `dev/active/3be770d5/survey/executable-identity.py` from the "
             f"committed campaign receipts, the profile series' `repetitions.log` and "
             f"[{IDENTITY.name}]({IDENTITY.name}). Each measured digest is the one the named "
             "artifact itself carries.", "",
             "| Executable | Digest in the current build identity | Measured digest | Recorded by | Same |",
             "|---|---|---|---|---|"]
    for name, digest in current.items():
        seen = records.get(name)
        if not seen:
            lines.append(f"| `{name}` | `{digest}` | — | no measurement records it | — |")
            continue
        for measured_digest, sources in sorted(seen.items()):
            where = ", ".join(f"`{source}`" for source in sorted(sources))
            lines.append(f"| `{name}` | `{digest}` | `{measured_digest}` | {where} | "
                         f"{measured_digest == digest} |")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(OUTPUT)


if __name__ == "__main__":
    main()
