#!/usr/bin/env python3
"""Project the host conditions a profile series ran under (jit:3be770d5).

Reads a series directory's `repetitions.log` and `host.txt` and writes
`<series>-conditions.md` beside the directory: one row per session with its
duration and the load averages the launcher recorded at its boundaries, and
the host record's governor, SMT and load-at-start lines. It reads a completed
series and writes outside it, so a series' own bytes stay as its run left
them.

The table exists so two series of the same cases can be compared under like
conditions. It does not isolate outside interference: the cases include
twelve- and twenty-four-worker rows, so a one-minute load average taken at a
session boundary is dominated by the series' own preceding work. What it
bounds is how much load a session started and finished under, which is
comparable between series because the cases and their order are identical.

Usage (from the worktree root): session-conditions.py <series-dir>
"""

import datetime
import pathlib
import re
import sys

LOAD = re.compile(r"load=\[([0-9.]+) ([0-9.]+) ([0-9.]+)\]")
UPTIME = re.compile(r"load average: *([0-9.]+), *([0-9.]+), *([0-9.]+)")


def stamp(text):
    return datetime.datetime.fromisoformat(text.replace("Z", "+00:00"))


def sessions(log):
    """Each completed session as (name, start, done, load at each)."""
    started = {}
    for line in log.read_text().splitlines():
        fields = line.split()
        if len(fields) < 3 or not fields[0].startswith("rep-"):
            continue
        load = LOAD.search(line)
        if fields[1] == "start":
            started[fields[0]] = (stamp(fields[2]), load.groups() if load else None)
        elif fields[1] == "done" and fields[0] in started:
            start, at_start = started.pop(fields[0])
            yield fields[0], start, stamp(fields[2]), at_start, load.groups() if load else None


def host_lines(host):
    """The host record's settings and its load average at start."""
    text = host.read_text()
    smt = re.search(r"## smt\n(\S+)", text)
    governors = sorted({line.split()[-1] for line in text.splitlines()
                        if "scaling_governor" in line})
    start = UPTIME.search(text[text.find("## load average at start"):]) if \
        "## load average at start" in text else None
    return smt.group(1) if smt else "unrecorded", governors, start.groups() if start else None


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    series = pathlib.Path(sys.argv[1].rstrip("/"))
    output = series.with_name(series.name + "-conditions.md")
    smt, governors, at_start = host_lines(series / "host.txt")
    rows = list(sessions(series / "repetitions.log"))
    lines = [f"# Host conditions of `{series.name}`", "",
             "> **Diátaxis Type:** Reference", "",
             f"Generated by `dev/active/3be770d5/survey/session-conditions.py` from "
             f"`{series.name}/repetitions.log` and its `host.txt`. Methods and what these "
             "numbers do and do not bound are in the generator's docstring. These are "
             "conditions, not measurements: no row here is evidence about a decoder.", "",
             f"SMT `{smt}`; scaling governor {', '.join(f'`{name}`' for name in governors)}; "
             f"load average before the first session "
             f"{', '.join(at_start) if at_start else 'unrecorded'} over 1, 5 and 15 minutes.", "",
             "| Session | Start (UTC) | Minutes | Load at start (1/5/15) | Load at end (1/5/15) |",
             "|---|---|---:|---|---|"]
    for name, start, done, load_start, load_done in rows:
        minutes = (done - start).total_seconds() / 60
        lines.append(f"| `{name}` | {start.strftime('%Y-%m-%dT%H:%M:%SZ')} | {minutes:.1f} | "
                     f"{' / '.join(load_start) if load_start else '—'} | "
                     f"{' / '.join(load_done) if load_done else '—'} |")
    lines += ["", f"Completed sessions: {len(rows)}."]
    output.write_text("\n".join(lines) + "\n")
    print(output)


if __name__ == "__main__":
    main()
