-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace gf2_core

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 768:0-768:37
    Name pattern: [core::ops::arith::AddAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- [gf2_core::field::poly::FieldPoly]
    Source: 'crates/gf2-core/src/field/poly.rs', lines 467:0-469:1
    Visibility: public -/
structure field.poly.FieldPoly (F : Type) (Clause0_Characteristic : Type)
  (Clause0_Wide : Type) where
  coeffs : alloc.vec.Vec F

/-- [gf2_core::field::vec::FieldVec]
    Source: 'crates/gf2-core/src/field/vec.rs', lines 30:0-32:1
    Visibility: public -/
structure field.vec.FieldVec (F : Type) (Clause0_Characteristic : Type)
  (Clause0_Wide : Type) where
  data : alloc.vec.Vec F

/-- [gf2_core::field::matrix::FieldMatrix]
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 302:0-306:1
    Visibility: public -/
structure field.matrix.FieldMatrix (F : Type) (Clause0_Characteristic : Type)
  (Clause0_Wide : Type) where
  rows : Std.Usize
  cols : Std.Usize
  data : field.vec.FieldVec F Clause0_Characteristic Clause0_Wide

/-- Trait declaration: [gf2_core::field::matrix::BasisReducer]
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 59:0-94:1
    Visibility: public -/
structure field.matrix.BasisReducer (Self : Type) (F : Type)
  (Self_Clause1_Characteristic : Type) (Self_Clause1_Wide : Type) where
  traitsFiniteFieldInst : field.traits.FiniteField F
    Self_Clause1_Characteristic Self_Clause1_Wide
  push_col : Self → Slice F → Result Self
  push_col_with_pivot_row : Self → Slice F → Std.Usize → Result Self
  «reduce» : Self → Slice F → Slice Std.Usize → Result ((alloc.vec.Vec F) ×
    (alloc.vec.Vec F))
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool

/-- Trait declaration: [gf2_core::field::matrix::PackedMatvec]
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 108:0-113:1
    Visibility: public -/
structure field.matrix.PackedMatvec (Self : Type) (F : Type)
  (Self_Clause1_Characteristic : Type) (Self_Clause1_Wide : Type) where
  traitsFiniteFieldInst : field.traits.FiniteField F
    Self_Clause1_Characteristic Self_Clause1_Wide
  matvec : Self → Slice F → Slice F → Result (Slice F)

/-- Trait declaration: [gf2_core::field::matrix::ChainPolyArith]
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 136:0-181:1
    Visibility: public -/
structure field.matrix.ChainPolyArith (Self : Type) (F : Type)
  (Self_Clause1_Characteristic : Type) (Self_Clause1_Wide : Type) where
  traitsFiniteFieldInst : field.traits.FiniteField F
    Self_Clause1_Characteristic Self_Clause1_Wide
  push_one : Self → Result Self
  shift_x_last_into : Self → alloc.vec.Vec Std.U8 → Result (alloc.vec.Vec
    Std.U8)
  sub_scaled_into : Self → alloc.vec.Vec Std.U8 → F → Std.Usize → Result (Self
    × (alloc.vec.Vec Std.U8))
  push_buf : Self → Slice Std.U8 → Result Self
  finish_buf : Self → Slice Std.U8 → F → Result (field.poly.FieldPoly F
    Self_Clause1_Characteristic Self_Clause1_Wide)
  alloc_buf : Self → Std.Usize → Result (alloc.vec.Vec Std.U8)
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool

/-- Trait declaration: [gf2_core::field::traits::FiniteField]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 44:0-989:1
    Visibility: public -/
structure field.traits.FiniteField (Self : Type) (Self_Characteristic : Type)
  (Self_Wide : Type) where
  WINOGRAD_THRESHOLD : Result Std.Usize
  TRI_BASE_THRESHOLD : Result Std.Usize
  PLE_BASE_COLS : Result Std.Usize
  PLE_PANEL_COLS : Result Std.Usize
  corecloneCloneInst : core.clone.Clone Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corecmpEqInst : core.cmp.Eq Self
  corehashHashInst : core.hash.Hash Self
  corefmtDebugInst : core.fmt.Debug Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  coreopsarithAddSelfSharedSelfSelfInst : core.ops.arith.Add Self Self Self
  coreopsarithSubInst : core.ops.arith.Sub Self Self Self
  coreopsarithSubSelfSharedSelfSelfInst : core.ops.arith.Sub Self Self Self
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  coreopsarithMulSelfSharedSelfSelfInst : core.ops.arith.Mul Self Self Self
  coreopsarithDivInst : core.ops.arith.Div Self Self Self
  coreopsarithDivSelfSharedSelfSelfInst : core.ops.arith.Div Self Self Self
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self Self
  coreopsarithAddAssignSelfSharedSelfInst : core.ops.arith.AddAssign Self Self
  corecloneCloneInst : core.clone.Clone Self_Characteristic
  corefmtDebugInst : core.fmt.Debug Self_Characteristic
  corecmpPartialEqInst : core.cmp.PartialEq Self_Characteristic
    Self_Characteristic
  corecmpEqInst : core.cmp.Eq Self_Characteristic
  corecloneCloneInst : core.clone.Clone Self_Wide
  coreopsarithAddInst : core.ops.arith.Add Self_Wide Self_Wide Self_Wide
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self_Wide Self_Wide
  characteristic : Self → Result Self_Characteristic
  extension_degree : Self → Result Std.Usize
  is_zero : Self → Result Bool
  is_one : Self → Result Bool
  inv : Self → Result (Option Self)
  zero_like : Self → Result Self
  one_like : Self → Result Self
  zero_hint : Result (Option Self)
  cardinality_log2_hint : Result (Option Std.U32)
  to_wide : Self → Result Self_Wide
  mul_to_wide : Self → Self → Result Self_Wide
  mul_product_sum_wide : Self → Self → Result Self_Wide
  reduce_wide : Self_Wide → Result Self
  reduce_product_sum_wide : Self_Wide → Result Self
  try_gf2m_u64_batch_dot_product : Slice Self → Slice Self → Self →
    alloc.vec.Vec Std.U64 → alloc.vec.Vec Std.U64 → alloc.vec.Vec Std.U64 →
    Result ((Option Self) × (alloc.vec.Vec Std.U64) × (alloc.vec.Vec Std.U64) ×
    (alloc.vec.Vec Std.U64))
  try_fp_simd_dot_product : Slice Self → Slice Self → alloc.vec.Vec Std.U16 →
    alloc.vec.Vec Std.U16 → Result ((Option Self) × (alloc.vec.Vec Std.U16) ×
    (alloc.vec.Vec Std.U16))
  try_pack_fp_medium_u16 : Slice Self → alloc.vec.Vec Std.U16 → Result ((Option
    Unit) × (alloc.vec.Vec Std.U16))
  try_fp_simd_dot_packed_u16 : Slice Std.U16 → Slice Std.U16 → Result (Option
    Self)
  try_simd_dot_product : Slice Self → Slice Self → Result (Option Self)
  try_simd_gemm_classical : Slice Self → Slice Self → Std.Usize → Std.Usize →
    Std.Usize → Slice Self → Result (Bool × (Slice Self))
  has_simd_gemm_classical : Result Bool
  try_make_basis_reducer : Std.Usize → Result (Option  sorry
    try_make_chain_poly_arith : Std.Usize → Result (Option  sorry
      chain_poly_arith_available : Result Bool
      try_simd_axpy : Slice Self → Self → Slice Self → Result (Bool × (Slice
        Self))
      try_prepack_matvec : Slice Self → Std.Usize → Std.Usize → Result (Option 
        sorry
        try_simd_matvec : Slice Self → Slice Self → Std.Usize → Std.Usize →
          Slice Self → Result (Bool × (Slice Self))
        try_simd_spmm : Slice Std.Usize → Slice Std.Usize → Slice Self → Slice
          Self → Std.Usize → Std.Usize → Slice Self → Result (Bool × (Slice
          Self))
        try_extension_wiedemann_minpoly : field.matrix.FieldMatrix Self
          Self_Characteristic Self_Wide → Result (Option (field.poly.FieldPoly
          Self Self_Characteristic Self_Wide))
        max_unreduced_additions : Result Std.Usize
        theorem_4_operand_bound : Result Std.U128
        try_simd_ple_panel_base : Slice Self → Std.Usize → Std.Usize →
          Std.Usize → Std.Usize → Slice Std.Usize → alloc.vec.Vec Std.Usize →
          Result ((Option Std.Usize) × (Slice Self) × (Slice Std.Usize) ×
          (alloc.vec.Vec Std.Usize)) has_simd_ple_panel_base : Result Bool
      /-- [gf2_core::field::batch_ops::InPlaceMode]
          Source: 'crates/gf2-core/src/field/batch_ops.rs', lines 352:0-354:1 -/
      @[discriminant isize]
      inductive field.batch_ops.InPlaceMode where
      | Yes : field.batch_ops.InPlaceMode
end gf2_core
