#!/usr/bin/env python3
"""Projects the v3 receipts of the bit-storage survey into one Markdown table set.

Reads every finalized receipt directory named on the command line together
with its acceptance summary and prints, per receipt, one row per cell: the
arms and the routes they observed themselves taking, the per-arm median of
the per-execution medians in nanoseconds per call, the acceptance tool's
speedup of medians with its interval at the corrected per-comparison
confidence, the decision and outcome, the flagged-window count, and the
baseline arm's reported setup/conversion phases. Every figure comes from the
receipt or the summary it sits beside; nothing is carried in from prose.

Usage: summarize-receipts.py <receipt-dir>...
"""

import json
import pathlib
import statistics
import sys


def ns(value):
    if value >= 1e6:
        return f"{value / 1e6:.3f} ms"
    if value >= 1e3:
        return f"{value / 1e3:.2f} us"
    return f"{value:.1f} ns"


def conversion_text(conversion):
    if not conversion:
        return "none reported"
    parts = []
    for key in ("setup_ns", "pack_ns", "unpack_ns", "batch_fill_ns", "dispatch_ns"):
        value = conversion.get(key, 0)
        if value:
            parts.append(f"{key[:-3]} {ns(value)}")
    return ", ".join(parts) if parts else "all phases 0"


def main():
    dirs = [pathlib.Path(arg) for arg in sys.argv[1:]]
    if not dirs:
        sys.exit(__doc__)
    print("# Protocol-v3 receipts of the bit-storage consumer survey")
    print()
    print(
        "Generated by `dev/active/04b85d10/survey/summarize-receipts.py` from the "
        "receipts and acceptance summaries it names. Speedups are baseline median "
        "over candidate median; values above one favour the candidate. Intervals are "
        "the acceptance tool's whole-pair percentile bootstrap at the corrected "
        "per-comparison confidence shown in each receipt heading. Per-arm medians are "
        "the median over pairs of each execution's median nanoseconds per call."
    )
    for directory in dirs:
        receipt = json.loads((directory / "receipt.json").read_text(encoding="utf-8"))
        summary = json.loads((directory / "acceptance-summary.json").read_text(encoding="utf-8"))
        family = summary["family"]
        print()
        print(f"## `{directory.name}`")
        print()
        print(
            f"Campaign `{receipt['campaign_id']}`, label `{receipt['label']}`, verdict "
            f"**{summary['verdict']}**, qualifies {summary['qualifies']}, findings "
            f"{len(summary['findings'])}, receipt digest `{summary['receipt_sha256']}`. "
            f"Family `{family['family_id']}`: {family['comparisons']} comparisons, attempt "
            f"alpha {family['family_alpha']}, per-comparison confidence "
            f"{family['per_comparison_confidence']:.6f}. Toolchain `{receipt['toolchain']}`."
        )
        arms = receipt["arms"]
        digests = {arm["executable_sha256"] for arm in arms.values()}
        print(
            f"Arm executables: {len(arms)} arms over {len(digests)} distinct executable "
            f"digest(s) `{', '.join(sorted(d[:16] for d in digests))}`."
        )
        print()
        print("| Cell | Baseline arm (observed route) | Candidate arm (observed route) | Baseline median | Candidate median | Speedup | Interval | Decision | Outcome | Flagged | Baseline conversion phases |")
        print("|---|---|---|---:|---:|---:|---|---|---|---:|---|")
        cells_by_id = {cell["cell_id"]: cell for cell in summary["cells"]}
        for cell in receipt["cells"]:
            accepted = cells_by_id[cell["cell_id"]]
            pairs = cell.get("pairs") or []
            if not pairs:
                print(
                    f"| `{cell['cell_id']}` | {cell['baseline_arm']} | {cell['candidate_arm']} | "
                    f"unavailable | unavailable | n/a | n/a | n/a | {accepted['outcome']} | n/a | "
                    f"{cell.get('unavailable_reason') or ''} |"
                )
                continue
            base = statistics.median(p["baseline"]["ns_per_call"] for p in pairs)
            cand = statistics.median(p["candidate"]["ns_per_call"] for p in pairs)
            base_paths = sorted({p["baseline"]["selected_path"] for p in pairs})
            cand_paths = sorted({p["candidate"]["selected_path"] for p in pairs})
            interval = accepted["interval"]
            decision = accepted["decision"] or "n/a"
            print(
                f"| `{cell['cell_id']}` | {cell['baseline_arm']} ({', '.join(base_paths)}) | "
                f"{cell['candidate_arm']} ({', '.join(cand_paths)}) | {ns(base)} | {ns(cand)} | "
                f"{interval['estimate']:.4f} | [{interval['lower']:.4f}, {interval['upper']:.4f}] | "
                f"{decision} | **{accepted['outcome']}** | "
                f"{accepted['flagged_windows']}/{accepted['total_windows']} | "
                f"{conversion_text(pairs[0]['baseline'].get('conversion'))} |"
            )


if __name__ == "__main__":
    main()
