#!/usr/bin/env python3
"""Projects the v3 receipts of the bit-storage survey into one Markdown table set.

Reads every finalized receipt directory named on the command line together
with its acceptance summary and prints, per receipt, one row per cell: the
arms and the routes they observed themselves taking, the fixture seed and the
pair-order and resampling seed beside their generators, the per-arm median of
the per-execution medians in nanoseconds per call with its order-statistic
interval, the acceptance tool's speedup of medians with its interval at the
corrected per-comparison confidence, the decision and outcome, the
flagged-window count, and the baseline arm's reported setup and conversion
probes as medians over its executions with the same order-statistic interval.
Every figure comes from the receipt, its snapshots or the summary it sits
beside; nothing is carried in from prose.

Usage: summarize-receipts.py <receipt-dir>...
"""

import json
import pathlib
import statistics
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from intervals import median_interval  # noqa: E402

HARNESS_LOCK = "inputs/producing/dev/active/04b85d10/survey/gf2-side/Cargo.lock"
ABTEST = "dev/tools/tuning-campaign-support/src/abtest.rs"
# Workloads whose fixture is deterministic, so their seed draws nothing.
UNSEEDED = {"zero-test", "field-id-hint"}


def ns(value):
    if value >= 1e6:
        return f"{value / 1e6:.3f} ms"
    if value >= 1e3:
        return f"{value / 1e3:.2f} us"
    return f"{value:.1f} ns"


def ns_interval(values):
    median, lower, upper, _ = median_interval(values)
    return f"{ns(median)} [{ns(lower)}, {ns(upper)}]"


def conversion_text(conversions):
    """Median and interval of each probe an arm reported in every execution."""
    if not conversions or not all(conversions):
        return "none reported"
    parts = []
    for key in ("setup_ns", "pack_ns", "unpack_ns", "batch_fill_ns", "dispatch_ns"):
        values = [conversion.get(key, 0) for conversion in conversions]
        if max(values):
            parts.append(f"{key[:-3]} {ns_interval(values)}")
    return ", ".join(parts) if parts else "all phases 0"


def locked_versions(directory):
    """Versions of the fixture generator's crates in the receipt's own lockfile."""
    text = (directory / HARNESS_LOCK).read_text(encoding="utf-8")
    versions = {}
    for block in text.split("[[package]]"):
        lines = [line.strip() for line in block.splitlines()]
        for name in ("rand", "rand_chacha", "rand_core"):
            if f'name = "{name}"' in lines:
                version = next(line for line in lines if line.startswith("version = "))
                versions.setdefault(name, []).append(version.split('"')[1])
    for name in ("rand", "rand_chacha", "rand_core"):
        if len(versions.get(name, [])) != 1:
            sys.exit(f"{directory / HARNESS_LOCK} resolves {name} to {versions.get(name)}")
    return {name: found[0] for name, found in versions.items()}


def main():
    dirs = [pathlib.Path(arg) for arg in sys.argv[1:]]
    if not dirs:
        sys.exit(__doc__)
    print("# Protocol-v3 receipts of the bit-storage consumer survey")
    print()
    print(
        "Generated by `dev/active/04b85d10/survey/summarize-receipts.py` from the "
        "receipts, their input snapshots and the acceptance summaries it names. Speedups "
        "are baseline median over candidate median; values above one favour the candidate. "
        "Speedup intervals are the acceptance tool's whole-pair percentile bootstrap at the "
        "corrected per-comparison confidence shown in each receipt heading. Per-arm medians "
        "are the median over the n pairs of each execution's median nanoseconds per call, "
        "with the distribution-free order-statistic interval for a median "
        "([x(7), x(18)] at n = 24, coverage 97.7%; `dev/active/04b85d10/survey/intervals.py`). "
        "Conversion probes are the baseline arm's reports, one per execution, summarized the "
        "same way."
    )
    print()
    print(
        "Seeds and generators. The fixture seed is the addendum cell's `workload.seed`; "
        "`gf2_core` `BitVec::random_seeded` and `BitMatrix::random_seeded` turn it, and the "
        "per-row, per-block and per-bank offsets of it that `prepare` in "
        "`dev/active/04b85d10/survey/gf2-side/src/lib.rs` defines, into fixture words "
        "through `rand::rngs::StdRng::seed_from_u64` (ChaCha12, the 32-byte key expanded "
        "from the seed by PCG32) and `Rng::fill`, at the crate versions each receipt's "
        "snapshotted harness lockfile resolves (named in each heading). A seed marked "
        "unused belongs to a deterministic fixture that draws nothing. The "
        "order and bootstrap seed is the acceptance interval's `seed`: "
        "SplitMix64 over the campaign seed XOR the first eight bytes of the SHA-256 of the "
        "cell key; it seeds the xoshiro256** generator of "
        f"`{ABTEST}` that counterbalances the pair order and draws the bootstrap resamples, "
        "at the file digest each heading names."
    )
    print()
    print(
        "What the frozen harness's conversion probes time: `setup` is one-shot fixture or "
        "code construction; for the packed BCH cells `pack` is one `encode_workspace()` "
        "construction, because the families pack messages inside the timed call, and "
        "`batch_fill` regenerates the batch with the fixture generator, a harness cost a "
        "consumer replaces with a copy of its own data; `dispatch` is the family selection "
        "`encode_batch_into` performs per call. Two corrections to the frozen receipts: "
        "their LDPC `setup` probe constructed the DVB-T2 short-frame code whatever the "
        "declared length, so for the $n = 64800$ cells it times the short code, not the "
        "normal one; and their LDPC `unpack` proxy appended 32448 bits (507 words) where "
        "the syndrome has 32400. The harness now constructs the declared code and appends "
        "one bit per check; the receipts keep their bytes."
    )
    for directory in dirs:
        receipt = json.loads((directory / "receipt.json").read_text(encoding="utf-8"))
        summary = json.loads((directory / "acceptance-summary.json").read_text(encoding="utf-8"))
        addendum = json.loads(
            (directory / "inputs" / "family-addendum.json").read_text(encoding="utf-8")
        )
        workloads = {cell["cell_id"]: cell["workload"] for cell in addendum["cells"]}
        versions = locked_versions(directory)
        abtest = receipt["source"]["producing"]["behavior_sha256"][ABTEST]
        family = summary["family"]
        print()
        print(f"## `{directory.name}`")
        print()
        print(
            f"Campaign `{receipt['campaign_id']}`, label `{receipt['label']}`, verdict "
            f"**{summary['verdict']}**, qualifies {summary['qualifies']}, findings "
            f"{len(summary['findings'])}, receipt digest `{summary['receipt_sha256']}`. "
            f"Family `{family['family_id']}`: {family['comparisons']} comparisons, attempt "
            f"alpha {family['family_alpha']}, per-comparison confidence "
            f"{family['per_comparison_confidence']:.6f}. Toolchain `{receipt['toolchain']}`. "
            f"Campaign seed {receipt['campaign_seed']}; fixture generator rand "
            f"{versions['rand']} StdRng (rand_chacha {versions['rand_chacha']}, rand_core "
            f"{versions['rand_core']}); order and bootstrap generator xoshiro256** of "
            f"`{ABTEST}` SHA-256 `{abtest[:16]}`."
        )
        arms = receipt["arms"]
        digests = {arm["executable_sha256"] for arm in arms.values()}
        print(
            f"Arm executables: {len(arms)} arms over {len(digests)} distinct executable "
            f"digest(s) `{', '.join(sorted(d[:16] for d in digests))}`."
        )
        print()
        print("| Cell | Baseline arm (observed route) | Candidate arm (observed route) | Fixture seed | Order and bootstrap seed | Pairs | Baseline median [interval] | Candidate median [interval] | Speedup | Interval | Decision | Outcome | Flagged | Baseline conversion probes, median [interval] |")
        print("|---|---|---|---|---:|---:|---:|---:|---:|---|---|---|---:|---|")
        cells_by_id = {cell["cell_id"]: cell for cell in summary["cells"]}
        for cell in receipt["cells"]:
            accepted = cells_by_id[cell["cell_id"]]
            workload = workloads[cell["cell_id"]]
            if workload["identity"] in UNSEEDED:
                fixture = f"{workload['seed']} (unused)"
            else:
                fixture = f"{workload['seed']} (rand {versions['rand']} StdRng)"
            pairs = cell.get("pairs") or []
            if not pairs:
                print(
                    f"| `{cell['cell_id']}` | {cell['baseline_arm']} | {cell['candidate_arm']} | "
                    f"{fixture} | n/a | 0 | unavailable | unavailable | n/a | n/a | n/a | "
                    f"{accepted['outcome']} | n/a | {cell.get('unavailable_reason') or ''} |"
                )
                continue
            base = [p["baseline"]["ns_per_call"] for p in pairs]
            cand = [p["candidate"]["ns_per_call"] for p in pairs]
            base_paths = sorted({p["baseline"]["selected_path"] for p in pairs})
            cand_paths = sorted({p["candidate"]["selected_path"] for p in pairs})
            interval = accepted["interval"]
            decision = accepted["decision"] or "n/a"
            print(
                f"| `{cell['cell_id']}` | {cell['baseline_arm']} ({', '.join(base_paths)}) | "
                f"{cell['candidate_arm']} ({', '.join(cand_paths)}) | {fixture} | "
                f"{interval['seed']} (xoshiro256**) | {len(pairs)} | "
                f"{ns_interval(base)} | {ns_interval(cand)} | "
                f"{interval['estimate']:.4f} | [{interval['lower']:.4f}, {interval['upper']:.4f}] | "
                f"{decision} | **{accepted['outcome']}** | "
                f"{accepted['flagged_windows']}/{accepted['total_windows']} | "
                f"{conversion_text([p['baseline'].get('conversion') for p in pairs])} |"
            )


if __name__ == "__main__":
    main()
