RUSTUP_TOOLCHAIN=1.95.0 charon cargo \
  --preset aeneas \
  --rustc-arg=--cfg=verify_lean \
  --start-from 'gf2_core::gfp' \
  --start-from 'gf2_core::gfpn' \
  --start-from 'gf2_core::gf2m::mul_raw' \
  --opaque 'gf2_core::field' \
  --opaque 'gf2_core::gf2m::field' \
  --opaque 'gf2_core::gf2m::generation' \
  --opaque 'gf2_core::gf2m::uint_ext' \
  --opaque 'gf2_core::gf2m::thread_safety_tests' \
  --opaque 'gf2_core::gf2m::barrett' \
  --opaque 'gf2_core::gfpn::batch' \
  --opaque 'gf2_core::gfp::simd_ops' \
  --opaque 'gf2_core::gfp::specialized::batch_mul_mersenne31' \
  --opaque 'gf2_core::gfp::specialized::batch_mul_add_mersenne31' \
  --opaque 'gf2_core::gfp::specialized::batch_dot_mersenne31' \
  --opaque 'gf2_core::bitvec' \
  --opaque 'gf2_core::bitslice' \
  --opaque 'gf2_core::matrix' \
  --opaque 'gf2_core::sparse' \
  --opaque 'gf2_core::alg' \
  --opaque 'gf2_core::compute' \
  --opaque 'gf2_core::kernels' \
  --opaque 'gf2_core::primitive_polys' \
  --opaque 'gf2_core::io' \
  --opaque 'gf2_core::macros' \
  --dest-file dev/active/7d7c647c/probes/S2_gf2_core.llbc \
  -- --manifest-path crates/gf2-core/Cargo.toml --no-default-features
