#!/usr/bin/env python3
"""Project this issue's committed receipts into evidence tables.

Usage: dev/active/53c5a8c0/survey/summarize.py

Reads only committed receipts, acceptance summaries, receipt-local input
snapshots, frozen addenda, the committed ledgers, the holdout declaration, the
resolution derivation records and the validation record, and writes
`dev/bench_results/53c5a8c0/tables.md`. Every number in the output is recomputed
or projected from those files; nothing is transcribed by hand.

Speedups, intervals, decisions and outcomes come from the acceptance summaries
that `benchmark-acceptance` recomputes from the raw pairs. The reciprocal
columns are algebraic transformations of the same estimate and endpoints and add
no samples. Per-arm call times, window counts, selected paths and conversion
diagnostics are descriptive summaries of the per-execution values in
`receipt.json`; they carry no interval and decide nothing.

The two families keep separate sections throughout, because a raw independent
carry-less batch, a reduced element-wise batch, a GF(2^m) dot product, an
unreduced long polynomial product and a whole-consumer wide-field product are
distinct operations and no table averages across them.
"""

import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir, os.pardir))
BENCH = os.path.join(ROOT, "dev", "bench_results", "53c5a8c0")
ACTIVE = os.path.join(ROOT, "dev", "active", "53c5a8c0")

CROSSOVER_SMOKE = "2026-09-13-53c5a8c0-crossover-wire-smoke"
CROSSOVER_PILOT = "2026-09-13-53c5a8c0-crossover-pilot"
CROSSOVER_PILOT_R2 = "2026-09-13-53c5a8c0-crossover-pilot-r2"
CROSSOVER_CONFIRMATION = "2026-09-13-53c5a8c0-crossover-confirmation"
POLYNOMIAL_PILOT = "2026-09-13-53c5a8c0-polynomial-pilot"
POLYNOMIAL_CONFIRMATION = "2026-09-13-53c5a8c0-polynomial-confirmation"

RECEIPTS = [
    CROSSOVER_SMOKE,
    CROSSOVER_PILOT,
    CROSSOVER_PILOT_R2,
    CROSSOVER_CONFIRMATION,
    POLYNOMIAL_PILOT,
    POLYNOMIAL_CONFIRMATION,
]

ADDENDA = [
    ("Crossover exploratory pilot", "addendum-v4-crossover-pilot.json"),
    ("Crossover resolution pilot", "addendum-v4-crossover-pilot-r2.json"),
    ("Crossover confirmation", "addendum-v4-crossover-confirmation.json"),
    ("Polynomial exploratory pilot", "addendum-v4-polynomial-pilot.json"),
    ("Polynomial confirmation", "addendum-v4-polynomial-confirmation.json"),
]

# The confirmations and the pilot each one derives its declared resolution from.
RESOLUTION_PAIRS = [
    ("gf2m-clmul-crossover", CROSSOVER_CONFIRMATION, CROSSOVER_PILOT_R2,
     "addendum-v4-crossover-confirmation.json"),
    ("wide-polynomial-competitiveness", POLYNOMIAL_CONFIRMATION, POLYNOMIAL_PILOT,
     "addendum-v4-polynomial-confirmation.json"),
]

LEDGERS = [
    ("gf2m-clmul-crossover", "gf2m-clmul-crossover-ledger.jsonl", CROSSOVER_CONFIRMATION),
    ("wide-polynomial-competitiveness", "wide-polynomial-competitiveness-ledger.jsonl",
     POLYNOMIAL_CONFIRMATION),
]

TAIL_DRAWS_REQUIRED = 20.0

PREAMBLE = [
    "> **Diátaxis Type:** Reference",
    "",
    "Generated by `dev/active/53c5a8c0/survey/summarize.py` from the committed receipts,",
    "acceptance summaries, receipt-local snapshots, frozen addenda, family ledgers, holdout",
    "declaration, resolution derivation records and validation record named in each table.",
    "",
    "Direction of every crossover cell: speedup is `median(element path) / median(batched path)`,",
    "so above 1 means the batched path takes less time at that size. Direction of every",
    "polynomial cell: speedup is `median(gf2) / median(gf2x)`, so below 1 means gf2 takes less",
    "time at that width. The `field-dot-16-holdout` cell swaps its arms by declaration, so its",
    "speedup is `median(batched path) / median(element path)`; the arm columns name the sides.",
    "",
    "The candidate-over-baseline column is the algebraic reciprocal of the same estimate and",
    "endpoints, not a new sample. Relative half-width is",
    "`max(estimate - lower, upper - estimate) / estimate`. Per-arm call times, selected paths",
    "and conversion diagnostics are descriptive: they carry no interval and decide nothing.",
    "",
]


def load(directory, *name):
    with open(os.path.join(BENCH, directory, *name), encoding="utf-8") as handle:
        return json.load(handle)


def load_active(*name):
    with open(os.path.join(ACTIVE, *name), encoding="utf-8") as handle:
        return json.load(handle)


def table(lines, header, rows):
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")


def fmt_interval(interval):
    return "{:.4f} [{:.4f}, {:.4f}]".format(
        interval["estimate"], interval["lower"], interval["upper"]
    )


def fmt_reciprocal(interval):
    return "{:.4f} [{:.4f}, {:.4f}]".format(
        1.0 / interval["estimate"], 1.0 / interval["upper"], 1.0 / interval["lower"]
    )


def relative_half_width(interval):
    estimate = interval["estimate"]
    return max(estimate - interval["lower"], interval["upper"] - estimate) / estimate


def source_line(directory):
    summary = load(directory, "acceptance-summary.json")
    receipt = load(directory, "receipt.json")
    family = summary["family"]
    return summary, receipt, (
        "Source: `{}/acceptance-summary.json` (receipt `{}`), label **{}**, verdict "
        "**{}**, qualifies for production selection {}, {} findings, {} sessions, resumed "
        "{}. Family `{}`: {} reserved comparisons, family-wise alpha {:g}, per-comparison "
        "confidence {:.6f}, {} bootstrap resamples. Addendum `{}` pinned at `{}`.".format(
            directory,
            summary["receipt_sha256"],
            summary["label"],
            summary["verdict"],
            str(summary["qualifies"]).lower(),
            len(summary["findings"]),
            summary["sessions"],
            str(summary["resumed"]).lower(),
            family["family_id"],
            family["comparisons"],
            family["family_alpha"],
            family["per_comparison_confidence"],
            family["bootstrap_resamples"],
            receipt["addendum"]["path"],
            receipt["addendum"]["sha256"],
        )
    )


def cell_decisions(lines, directory):
    """Every cell of one receipt: arms, samples, interval, decision, outcome."""
    summary, receipt, header = source_line(directory)
    lines += [header, ""]
    cells = {cell["cell_id"]: cell for cell in receipt["cells"]}
    rows = []
    for verdict in summary["cells"]:
        cell = cells[verdict["cell_id"]]
        interval = verdict["interval"]
        rows.append([
            "`{}`".format(verdict["cell_id"]),
            verdict["role"],
            verdict["objective"],
            "`{}`".format(cell["baseline_arm"]),
            "`{}`".format(cell["candidate_arm"]),
            str(verdict["pairs"]),
            "{}/{}".format(verdict["flagged_windows"], verdict["total_windows"]),
            fmt_interval(interval),
            fmt_reciprocal(interval),
            "{:.4f}".format(relative_half_width(interval)),
            verdict["decision"],
            "**{}**".format(verdict["outcome"]),
            ", ".join("`{}`".format(name) for name in verdict["unresolved_settings"]) or "-",
        ])
    table(lines, [
        "Cell", "Role", "Objective", "Baseline arm", "Candidate arm", "Pairs",
        "Flagged windows", "Speedup [interval]", "Candidate/baseline time ratio [interval]",
        "Relative half-width", "Decision", "Outcome", "Unresolved settings",
    ], rows)
    return summary, receipt


def findings(lines, summary):
    if not summary["findings"]:
        lines += ["The acceptance summary records no findings.", ""]
        return
    table(lines, ["Rule", "Severity", "Cell", "Message"], [[
        finding["rule"],
        finding["severity"],
        "`{}`".format(finding["cell"]) if finding.get("cell") else "-",
        finding["message"],
    ] for finding in summary["findings"]])


def arm_medians(lines, receipt):
    """Descriptive per-arm call time, selected path and observed placement."""
    rows = []
    for cell in receipt["cells"]:
        for side in ("baseline", "candidate"):
            executions = [pair[side] for pair in cell["pairs"]]
            if not executions:
                continue
            per_call = [execution["ns_per_call"] for execution in executions]
            paths = sorted({execution["selected_path"] for execution in executions})
            arm = cell[side + "_arm"]
            rows.append([
                "`{}`".format(cell["cell_id"]),
                side,
                "`{}`".format(arm),
                "`{}`".format(receipt["arms"][arm]["build"]),
                str(len(executions)),
                "{:.4f}".format(statistics.median(per_call)),
                "{:.4f}-{:.4f}".format(min(per_call), max(per_call)),
                ", ".join("`{}`".format(path.split(" library=")[0]) for path in paths),
                ", ".join(sorted({str(e["workers_observed"]) for e in executions})),
                ", ".join(sorted({e["cache_state_applied"] for e in executions})),
            ])
    table(lines, [
        "Cell", "Side", "Arm", "Build", "Executions", "Median ns/call", "Call range ns",
        "Selected path", "Workers observed", "Cache state applied",
    ], rows)


def diagnostics(lines, receipt):
    """Untimed conversion accounting: setup, packing, extraction, reduction."""
    rows = []
    for cell in receipt["cells"]:
        for side in ("baseline", "candidate"):
            conversions = [pair[side]["conversion"] for pair in cell["pairs"]]
            if not conversions:
                continue
            def median(key):
                return statistics.median(entry[key] for entry in conversions)
            rows.append([
                "`{}`".format(cell["cell_id"]),
                side,
                "`{}`".format(cell[side + "_arm"]),
                "{:.0f}".format(median("setup_ns")),
                "{:.0f}".format(median("pack_ns")),
                "{:.0f}".format(median("batch_fill_ns")),
                "{:.0f}".format(median("unpack_ns")),
                "{:.0f}".format(median("dispatch_ns")),
            ])
    table(lines, [
        "Cell", "Side", "Arm", "Median setup ns", "Median pack ns",
        "Median one-call ns", "Median reduction or extraction ns", "Median dispatch ns",
    ], rows)


def family_accounting(lines, directory, summary, receipt):
    """P-20 tail support, recomputed from the receipt-local ledger prefix."""
    lines += [
        "Source: `{}/inputs/trial-ledger.jsonl`, the receipt-local ledger prefix pinned by "
        "`receipt.trial_ledger.sha256` = `{}`, and the frozen addendum snapshot beside "
        "it.".format(directory, receipt["trial_ledger"]["sha256"]),
        "",
    ]
    entries = []
    with open(os.path.join(BENCH, directory, "inputs", "trial-ledger.jsonl"),
              encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    table(lines, ["Sequence", "Campaign", "Protocol", "Reserved comparisons",
                  "Candidate identities"], [[
        str(entry["sequence"]),
        "`{}`".format(entry["campaign"]),
        str(entry["protocol_version"]),
        str(entry["comparisons"]),
        str(len(entry["candidates"])),
    ] for entry in entries])

    addendum = load(directory, "inputs", "family-addendum.json")
    alpha = addendum["family_wise"]["alpha"]
    comparisons = sum(entry["comparisons"] for entry in entries)
    attempts = sum(1 for entry in entries if entry["comparisons"] > 0)
    attempt_alpha = alpha / (attempts * (attempts + 1))
    corrected = attempt_alpha / comparisons
    resamples = receipt["settings"]["bootstrap_resamples"]
    draws = resamples * corrected / 2.0
    agrees = (
        abs(summary["family"]["family_alpha"] - attempt_alpha) < 1e-12
        and abs(summary["family"]["per_comparison_confidence"] - (1.0 - corrected)) < 1e-12
        and summary["family"]["comparisons"] == comparisons
    )
    # The bound on the next attempt of the same family, from the same arithmetic:
    # one more attempt raises t by one, and the largest m that still draws twenty
    # replicates per tail is the floor of resamples x attempt alpha / (2 x 20).
    next_attempts = attempts + 1
    next_alpha = alpha / (next_attempts * (next_attempts + 1))
    next_max = int(resamples * next_alpha / (2.0 * TAIL_DRAWS_REQUIRED))
    table(lines, ["Quantity", "Value", "Derivation"], [
        ["family alpha", "{:g}".format(alpha), "frozen addendum `family_wise.alpha`"],
        ["m (reserved comparisons)", str(comparisons), "sum of ledger `comparisons`"],
        ["t (non-exploratory attempts)", str(attempts),
         "ledger entries with `comparisons` > 0"],
        ["attempt alpha", "{:.6f}".format(attempt_alpha), "alpha / (t (t + 1))"],
        ["corrected alpha", "{:.7f}".format(corrected), "attempt alpha / m"],
        ["per-comparison confidence", "{:.6f}".format(1.0 - corrected),
         "1 - corrected alpha"],
        ["bootstrap resamples", str(resamples), "frozen shared setting"],
        ["expected draws per tail", "{:.2f}".format(draws),
         "resamples x corrected alpha / 2"],
        ["required draws per tail", "{:g}".format(TAIL_DRAWS_REQUIRED), "protocol P-20"],
        ["tail condition", "holds" if draws >= TAIL_DRAWS_REQUIRED else "fails",
         "expected draws at or above required"],
        ["summary agrees", "yes" if agrees else "no",
         "`family` block of the acceptance summary"],
        ["t for a further attempt", str(next_attempts), "t + 1"],
        ["attempt alpha then", "{:.6f}".format(next_alpha),
         "alpha / (t' (t' + 1))"],
        ["m admitted then", str(next_max),
         "floor(resamples x attempt alpha then / (2 x required draws))"],
    ])


def sessions(lines, directory, receipt):
    lines += [
        "Source: `{}/receipt.json`; toolchain `{}`; execution log `{}` with SHA-256 "
        "`{}`.".format(
            directory, receipt["toolchain"], receipt["execution_log"]["path"],
            receipt["execution_log"]["sha256"],
        ),
        "",
    ]
    rows = []
    for index, host in enumerate(receipt.get("session_hosts") or [receipt["host"]], start=1):
        rows.append([
            str(index),
            host["observed_utc"],
            host["hostname"],
            host["cpu_model"],
            host["os_kernel"],
            ", ".join(sorted(set(host["governors"].values()))),
            "active" if host["smt_active"] else "inactive",
            str(len(host["affinity"])),
            " / ".join("{:.2f}".format(value) for value in host["load_average"]),
        ])
    table(lines, [
        "Session", "Observed", "Host", "CPU", "Kernel", "Governors", "SMT",
        "CPUs in mask", "Load average 1/5/15 min",
    ], rows)


def resolution_rows(lines):
    """Each confirmation's declared resolution against its pilot's widest interval."""
    lines += [
        "A confirmation's declared `effect.measurement_resolution` must be at or above the "
        "widest relative bootstrap half-width its pinned pilot receipt observed, and its "
        "equivalence margin strictly above one plus that resolution. Both are recomputed "
        "here from the pilot's own acceptance summary rather than read from the derivation "
        "record.",
        "",
    ]
    rows = []
    for family, confirmation, pilot, addendum_name in RESOLUTION_PAIRS:
        addendum = load_active(addendum_name)
        effect = addendum["effect"]
        evidence = effect["resolution_evidence"]
        pilot_summary = load(pilot, "acceptance-summary.json")
        pilot_receipt_digest = pilot_summary["receipt_sha256"]
        widest_cell, widest = max(
            ((cell["cell_id"], relative_half_width(cell["interval"]))
             for cell in pilot_summary["cells"]),
            key=lambda entry: entry[1],
        )
        declared = effect["measurement_resolution"]
        margin = effect["equivalence_margin"]
        rows.append([
            "`{}`".format(family),
            "`{}`".format(confirmation),
            "`{}`".format(evidence["receipt"]),
            "yes" if evidence["sha256"] == pilot_receipt_digest else "no",
            "`{}`".format(widest_cell),
            "{:.6f}".format(widest),
            "{:.10g}".format(declared),
            "yes" if declared >= widest else "no",
            "{:g}".format(margin),
            "yes" if margin > 1.0 + declared else "no",
        ])
    table(lines, [
        "Family", "Confirmation", "Pinned pilot receipt", "Digest matches that pilot",
        "Widest pilot cell", "Its relative half-width", "Declared resolution",
        "Declared at or above widest", "Equivalence margin",
        "Margin above 1 + resolution",
    ], rows)


def declared_effects(lines):
    rows = []
    for label, name in ADDENDA:
        addendum = load_active(name)
        effect = addendum["effect"]
        resolution = effect["measurement_resolution"]
        evidence = effect["resolution_evidence"]
        rows.append([
            label,
            "`{}`".format(name),
            "{:g}".format(effect["worthwhile_speedup"]),
            "{:g}".format(effect["equivalence_margin"]),
            "{:g}".format(effect["material_gap_threshold"]),
            "{:.10g}".format(resolution) if resolution is not None else "not declared",
            "`{}`".format(evidence["sha256"]) if evidence else "-",
            str(len(addendum["cells"])),
        ])
    table(lines, [
        "Addendum role", "File", "Worthwhile speedup", "Equivalence margin",
        "Material-gap threshold", "Declared measurement resolution",
        "Resolution evidence receipt", "Cells",
    ], rows)


def holdout(lines):
    declaration = load_active("survey", "holdout-cells.json")
    lines += [
        "Source: `dev/active/53c5a8c0/survey/holdout-cells.json`, committed before the "
        "crossover pilot ran and carried into the confirmation addendum by the canonical "
        "freezer.",
        "",
    ]
    table(lines, ["Cell", "Objective", "Role", "Regime", "Operation", "Size", "Seed",
                  "Metric kind", "Baseline arm", "Candidate arm"], [[
        "`{}`".format(cell["cell_id"]),
        cell["objective"],
        cell["role"],
        cell["regime"],
        "`{}`".format(cell["case"]["kind"]),
        ", ".join("{} {}".format(key, value)
                  for key, value in sorted(cell["case"].items())
                  if key not in ("kind", "seed")),
        str(cell["case"]["seed"]),
        cell["metric_kind"],
        "`{}`".format(cell["baseline_arm"]),
        "`{}`".format(cell["candidate_arm"]),
    ] for cell in declaration["cells"]])
    lines += [
        "Declared family: `{}`. Declared rationale: {}".format(
            declaration["family"], declaration["rationale"]
        ),
        "",
    ]


def ledger_chains(lines):
    lines += [
        "Source: the two committed append-only family ledgers under "
        "`dev/bench_results/53c5a8c0/`. A reservation is spent whether its campaign "
        "completes or not.",
        "",
    ]
    rows = []
    for family, name, _confirmation in LEDGERS:
        with open(os.path.join(BENCH, name), encoding="utf-8") as handle:
            entries = [json.loads(line) for line in handle if line.strip()]
        for entry in entries:
            rows.append([
                "`{}`".format(family),
                str(entry["sequence"]),
                "`{}`".format(entry["campaign"]),
                str(entry["protocol_version"]),
                str(entry["comparisons"]),
                "`{}`".format(entry["addendum_sha256"]),
            ])
    table(lines, ["Family", "Sequence", "Campaign", "Protocol",
                  "Reserved comparisons", "Addendum SHA-256"], rows)


def executables(lines):
    rows = []
    for directory in RECEIPTS:
        receipt = load(directory, "receipt.json")
        for name, arm in sorted(receipt["arms"].items()):
            rows.append([
                "`{}`".format(directory),
                "`{}`".format(name),
                arm["build"],
                "`{}`".format(os.path.basename(arm["executable_path"])),
                "`{}`".format(arm["executable_sha256"]),
                ", ".join("{}={}".format(key, value)
                          for key, value in sorted((arm["environment"] or {}).items())) or "-",
            ])
    table(lines, ["Receipt", "Arm", "Build", "Executable", "Executable SHA-256",
                  "Environment"], rows)


def validation(lines):
    record = load_active("survey", "validation.json")
    lines += [
        "Source: `dev/active/53c5a8c0/survey/validation.json`, written by "
        "`dev/active/53c5a8c0/survey/run-validation.sh` from the `crossover-validate` "
        "runs of both build variants. Overall passed: {}.".format(
            str(record["passed"]).lower()
        ),
        "",
    ]
    rows = []
    for variant, body in sorted(record["variants"].items()):
        for check in body["checks"]:
            rows.append([
                variant,
                check["name"],
                str(check["cases"]),
                str(len(check["failures"])),
            ])
    table(lines, ["Build variant", "Check", "Cases", "Failures"], rows)


def asm_bodies(lines):
    """Instruction-mix rows of the committed assembly artefacts."""
    lines += [
        "Source: the committed artefacts under `dev/active/53c5a8c0/survey/asm/`, whose "
        "derived annotation blocks `dev/active/53c5a8c0/survey/annotate-asm.py` counts from "
        "the disassembly above each block. The rows below are read back out of those "
        "blocks, so this table adds no count of its own.",
        "",
    ]
    wanted = ("instructions", "stack frame bytes", "frame stores", "frame loads",
              "backward branches")
    rows = []
    for name in sorted(os.listdir(os.path.join(ACTIVE, "survey", "asm"))):
        path = os.path.join(ACTIVE, "survey", "asm", name)
        body = None
        counted = {}
        clmul = 0
        for line in open(path, encoding="utf-8"):
            if line.startswith(";=== derived annotation for "):
                if body:
                    rows.append(_asm_row(name, body, counted, clmul, wanted))
                body = line[len(";=== derived annotation for "):].rstrip(" =\n")
                counted, clmul = {}, 0
            elif body and line.startswith("; "):
                text = line[2:].rstrip("\n")
                label, _, value = text.rpartition("  ")
                label, value = label.strip(), value.strip()
                if not value.isdigit():
                    continue
                if label in wanted:
                    counted[label] = value
                if "carry-less multiply" in label:
                    clmul += int(value)
        if body:
            rows.append(_asm_row(name, body, counted, clmul, wanted))
    table(lines, ["Artefact", "Body", "Instructions", "Stack frame bytes",
                  "Frame stores", "Frame loads", "Backward branches",
                  "Carry-less multiply instructions"], rows)


def _asm_row(artefact, body, counted, clmul, wanted):
    return (
        ["`{}`".format(artefact), "`{}`".format(body)]
        + [counted.get(label, "0") for label in wanted]
        + [str(clmul)]
    )


def write(path, lines):
    text = "\n".join(lines).rstrip("\n") + "\n"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def family_section(lines, title, confirmation, pilots):
    lines += ["## {}".format(title), "", "### Confirmation", ""]
    summary, receipt = cell_decisions(lines, confirmation)
    lines += ["#### Findings", ""]
    findings(lines, summary)
    lines += ["#### Family accounting and P-20 tail support", ""]
    family_accounting(lines, confirmation, summary, receipt)
    lines += ["#### Per-arm call time and selected path", ""]
    arm_medians(lines, receipt)
    lines += ["#### Untimed conversion diagnostics", ""]
    diagnostics(lines, receipt)
    lines += ["#### Sessions and host", ""]
    sessions(lines, confirmation, receipt)
    for label, directory in pilots:
        lines += ["### {}".format(label), ""]
        _, pilot_receipt = cell_decisions(lines, directory)
        lines += ["#### Per-arm call time and selected path", ""]
        arm_medians(lines, pilot_receipt)
        lines += ["#### Untimed conversion diagnostics", ""]
        diagnostics(lines, pilot_receipt)


def main():
    lines = ["# Carry-less crossover and polynomial competitiveness evidence tables", ""]
    lines += PREAMBLE

    family_section(
        lines,
        "Family `gf2m-clmul-crossover`",
        CROSSOVER_CONFIRMATION,
        [
            ("Resolution pilot", CROSSOVER_PILOT_R2),
            ("Exploratory pilot", CROSSOVER_PILOT),
            ("Wire smoke", CROSSOVER_SMOKE),
        ],
    )
    family_section(
        lines,
        "Family `wide-polynomial-competitiveness`",
        POLYNOMIAL_CONFIRMATION,
        [("Exploratory pilot", POLYNOMIAL_PILOT)],
    )

    lines += ["## Measurement resolution", ""]
    resolution_rows(lines)

    lines += ["## Frozen margins and declared resolution", ""]
    declared_effects(lines)

    lines += ["## Holdout declaration", ""]
    holdout(lines)

    lines += ["## Family ledger chains", ""]
    ledger_chains(lines)

    lines += ["## Arm executables", ""]
    executables(lines)

    lines += ["## Correctness validation", ""]
    validation(lines)

    lines += ["## Release assembly of the measured gf2 paths", ""]
    asm_bodies(lines)

    write(os.path.join(BENCH, "tables.md"), lines)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
