#!/usr/bin/env bash
# Per-call runtime dispatch cost beside the whole per-call cost of the
# operation, for every population-count arm (jit:26465e6c).
#
#   dev/active/26465e6c/survey/probe-dispatch.sh > dispatch-probe.log
#
# This is a SUPPORTING MEASUREMENT, not a protocol receipt. No addendum governs
# it; it is not paired, interleaved, counterbalanced or bootstrapped, and no
# adoption decision rests on it. It exists to answer one question the receipts
# cannot: how much of a kernel-isolated arm's per-call time is runtime backend
# resolution rather than work. That matters because the direct-kernel arms
# resolve their function pointer through gf2_kernels_simd::detect() inside the
# timed body, so a reader is entitled to ask whether the small-input cells
# measure the kernel or the dispatch.
#
# Run it under the CCX1 mutex so it does not compete with a measurement run.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GF2_SIDE="${HERE}/gf2-side/target/release/popcount-gf2-side"
[[ -x "${GF2_SIDE}" ]] || { echo "missing binary: ${GF2_SIDE}" >&2; exit 2; }

echo "# Per-call dispatch cost beside the whole per-call cost of the operation."
echo "# jit:26465e6c supporting measurement, NOT a protocol receipt: no addendum"
echo "# governs it, it is not paired or bootstrapped, and no adoption decision"
echo "# rests on it. Each figure is a mean over a calibrated probe loop."
echo "# host: $(uname -srm)"
echo "# cpu: $(awk -F': ' '/^model name/ { print $2; exit }' /proc/cpuinfo)"
echo "# generated by dev/active/26465e6c/survey/probe-dispatch.sh"
echo "# load: $(uptime | sed 's/.*load average/load average/')"
for arm in production-dispatch nibble-lut scalar-popcnt compiler-count-ones; do
  GF2_POPCOUNT_ARM="${arm}" "${GF2_SIDE}" --dispatch-probe
done
