-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Gf2Core.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open gf2_core

/-- [core::cmp::impls::{impl core::cmp::Eq for u64}::assert_fields_are_eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1906:12-1906:32
    Name pattern: [core::cmp::impls::{core::cmp::Eq<u64>}::assert_fields_are_eq]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::Eq<u64>}::assert_fields_are_eq"]
axiom U64.Insts.CoreCmpEq.assert_fields_are_eq : Std.U64 → Result Unit

/-- [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field]:
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 132:4-132:76
    Name pattern: [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field]
    Visibility: public -/
@[rust_fun
  "core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field"]
axiom core.fmt.builders.DebugStruct.field
  :
  core.fmt.builders.DebugStruct → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) →
    Result (core.fmt.builders.DebugStruct × (core.fmt.builders.DebugStruct →
    core.fmt.builders.DebugStruct) × (core.fmt.builders.DebugStruct →
    core.fmt.builders.DebugStruct → (core.fmt.builders.DebugStruct ×
    core.fmt.builders.DebugStruct)))

/-- [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish]:
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 244:4-244:43
    Name pattern: [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish]
    Visibility: public -/
@[rust_fun
  "core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish"]
axiom core.fmt.builders.DebugStruct.finish
  :
  core.fmt.builders.DebugStruct → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.builders.DebugStruct ×
    (core.fmt.builders.DebugStruct → core.fmt.builders.DebugStruct))

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2448:4-2448:76
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct"]
axiom core.fmt.Formatter.debug_struct
  :
  core.fmt.Formatter → Str → Result (core.fmt.builders.DebugStruct ×
    (core.fmt.builders.DebugStruct → core.fmt.Formatter))

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2473:4-2480:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str
    → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::hash::impls::{impl core::hash::Hash for u64}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u64>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u64>}::hash"]
axiom U64.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U64 → H → Result H

/-- [core::num::{u64}::trailing_zeros]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 177:8-177:48
    Name pattern: [core::num::{u64}::trailing_zeros]
    Visibility: public -/
@[rust_fun "core::num::{u64}::trailing_zeros"]
axiom core.num.U64.trailing_zeros : Std.U64 → Result Std.U32

/-- [core::num::{u128}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2516:8-2516:60
    Name pattern: [core::num::{u128}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u128}::saturating_mul"]
axiom core.num.U128.saturating_mul : Std.U128 → Std.U128 → Result Std.U128

/-- [core::num::{u64}::wrapping_neg]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2792:8-2792:47
    Name pattern: [core::num::{u64}::wrapping_neg]
    Visibility: public -/
@[rust_fun "core::num::{u64}::wrapping_neg"]
axiom core.num.U64.wrapping_neg : Std.U64 → Result Std.U64

/-- [core::num::{u64}::is_power_of_two]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3859:8-3859:50
    Name pattern: [core::num::{u64}::is_power_of_two]
    Visibility: public -/
@[rust_fun "core::num::{u64}::is_power_of_two"]
axiom core.num.U64.is_power_of_two : Std.U64 → Result Bool

/-- [core::ops::arith::{impl core::ops::arith::Add<u128, u128> for u128}::add]:
    Source: '/rustc/library/core/src/ops/arith.rs', lines 104:12-104:41
    Name pattern: [core::ops::arith::{core::ops::arith::Add<u128, u128, u128>}::add]
    Visibility: public -/
@[rust_fun "core::ops::arith::{core::ops::arith::Add<u128, u128, u128>}::add"]
axiom U128.Insts.CoreOpsArithAddU128U128.add
  : Std.U128 → Std.U128 → Result Std.U128

/-- [core::ops::arith::{impl core::ops::arith::AddAssign<u128> for u128}::add_assign]:
    Source: '/rustc/library/core/src/ops/arith.rs', lines 790:12-790:47
    Name pattern: [core::ops::arith::{core::ops::arith::AddAssign<u128, u128>}::add_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::arith::{core::ops::arith::AddAssign<u128, u128>}::add_assign"]
axiom U128.Insts.CoreOpsArithAddAssignU128.add_assign
  : Std.U128 → Std.U128 → Result Std.U128

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<T>}::and_then]:
    Source: '/rustc/library/core/src/option.rs', lines 1538:4-1540:61
    Name pattern: [core::option::{core::option::Option<@T>}::and_then]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::and_then"]
axiom core.option.Option.and_then
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTOptionInst :
  core.ops.function.FnOnce F T (Option U)) :
  Option T → F → Result (Option U)

/-- [core::result::{impl core::ops::try_trait::Try for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2177:4-2177:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTry.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{impl core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2192:4-2192:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [gf2_core::field::traits::FiniteField::zero_hint]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 147:4-149:5
    Visibility: public -/
axiom field.traits.FiniteField.zero_hint.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) :
  Result (Option Self)

/-- [gf2_core::field::traits::FiniteField::cardinality_log2_hint]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 180:4-182:5
    Visibility: public -/
axiom field.traits.FiniteField.cardinality_log2_hint.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) :
  Result (Option Std.U32)

/-- [gf2_core::field::traits::FiniteField::mul_product_sum_wide]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 270:4-272:5
    Visibility: public -/
axiom field.traits.FiniteField.mul_product_sum_wide.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) :
  Self → Self → Result Clause0_Wide

/-- [gf2_core::field::traits::FiniteField::reduce_product_sum_wide]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 320:4-322:5
    Visibility: public -/
axiom field.traits.FiniteField.reduce_product_sum_wide.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) :
  Clause0_Wide → Result Self

/-- [gf2_core::field::traits::FiniteField::theorem_4_operand_bound]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 803:4-805:5
    Visibility: public -/
axiom field.traits.FiniteField.theorem_4_operand_bound.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) :
  Result Std.U128

/-- [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 825:4-825:42
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.WINOGRAD_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 858:4-858:40
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.TRI_BASE_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 892:4-892:35
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_BASE_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_PANEL_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 926:4-926:54
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_PANEL_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::gfp::specialized::batch_mul_mersenne31]:
    Source: 'crates/gf2-core/src/gfp/specialized.rs', lines 588:0-604:1
    Visibility: public -/
axiom gfp.specialized.batch_mul_mersenne31
  : Slice Std.U32 → Slice Std.U32 → Slice Std.U32 → Result (Slice Std.U32)

/-- [gf2_core::gfp::specialized::batch_mul_add_mersenne31]:
    Source: 'crates/gf2-core/src/gfp/specialized.rs', lines 640:0-662:1
    Visibility: public -/
axiom gfp.specialized.batch_mul_add_mersenne31
  : Slice Std.U32 → Slice Std.U32 → Slice Std.U32 → Result (Slice Std.U32)

/-- [gf2_core::gfp::specialized::batch_dot_mersenne31]:
    Source: 'crates/gf2-core/src/gfp/specialized.rs', lines 699:0-719:1
    Visibility: public -/
axiom gfp.specialized.batch_dot_mersenne31
  : Slice Std.U32 → Slice Std.U32 → Result Std.U32

/-- [gf2_core::gfpn::cubic::{impl core::cmp::Eq for gf2_core::gfpn::cubic::CubicExtWide<W>}::assert_fields_are_eq]:
    Source: 'crates/gf2-core/src/gfpn/cubic.rs', lines 184:0-184:37
    Visibility: public -/
axiom gfpn.cubic.CubicExtWide.Insts.CoreCmpEq.assert_fields_are_eq
  {W : Type} (corecmpEqInst : core.cmp.Eq W) :
  gfpn.cubic.CubicExtWide W → Result Unit

/-- [gf2_core::gfpn::cubic::{impl core::cmp::Eq for gf2_core::gfpn::cubic::CubicExt<C, Clause0_BaseField, Clause0_Clause0_Clause0_Characteristic, Clause0_Clause0_Clause0_Wide>}::assert_fields_are_eq]:
    Source: 'crates/gf2-core/src/gfpn/cubic.rs', lines 275:0-275:40
    Visibility: public -/
axiom gfpn.cubic.CubicExt.Insts.CoreCmpEq.assert_fields_are_eq
  {C : Type} {Clause0_BaseField : Type} {Clause0_Clause0_Clause0_Characteristic
  : Type} {Clause0_Clause0_Clause0_Wide : Type} (ext_configExtConfigInst :
  gfpn.ext_config.ExtConfig C Clause0_BaseField
  Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide) :
  gfpn.cubic.CubicExt C Clause0_BaseField
    Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide →
    Result Unit

/-- [gf2_core::gfpn::cubic::{impl gf2_core::field::traits::FiniteField<Clause0_Clause0_Clause0_Characteristic, gf2_core::gfpn::cubic::CubicExtWide<Clause0_Clause0_Clause0_Wide>> for gf2_core::gfpn::cubic::CubicExt<C, Clause0_BaseField, Clause0_Clause0_Clause0_Characteristic, Clause0_Clause0_Clause0_Wide>}::theorem_4_operand_bound]:
    Source: 'crates/gf2-core/src/gfpn/cubic.rs', lines 633:0-751:1
    Visibility: public -/
axiom
  gfpn.cubic.CubicExt.Insts.Gf2_coreFieldTraitsFiniteFieldClause0_Clause0_Clause0_CharacteristicCubicExtWide.theorem_4_operand_bound
  {C : Type} {Clause0_BaseField : Type} {Clause0_Clause0_Clause0_Characteristic
  : Type} {Clause0_Clause0_Clause0_Wide : Type} (ext_configExtConfigInst :
  gfpn.ext_config.ExtConfig C Clause0_BaseField
  Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide) :
  Result Std.U128

/-- [gf2_core::gfpn::quadratic::{impl core::cmp::Eq for gf2_core::gfpn::quadratic::QuadraticExtWide<W>}::assert_fields_are_eq]:
    Source: 'crates/gf2-core/src/gfpn/quadratic.rs', lines 167:0-167:41
    Visibility: public -/
axiom gfpn.quadratic.QuadraticExtWide.Insts.CoreCmpEq.assert_fields_are_eq
  {W : Type} (corecmpEqInst : core.cmp.Eq W) :
  gfpn.quadratic.QuadraticExtWide W → Result Unit

/-- [gf2_core::gfpn::quadratic::{impl core::cmp::Eq for gf2_core::gfpn::quadratic::QuadraticExt<C, Clause0_BaseField, Clause0_Clause0_Clause0_Characteristic, Clause0_Clause0_Clause0_Wide>}::assert_fields_are_eq]:
    Source: 'crates/gf2-core/src/gfpn/quadratic.rs', lines 253:0-253:44
    Visibility: public -/
axiom gfpn.quadratic.QuadraticExt.Insts.CoreCmpEq.assert_fields_are_eq
  {C : Type} {Clause0_BaseField : Type} {Clause0_Clause0_Clause0_Characteristic
  : Type} {Clause0_Clause0_Clause0_Wide : Type} (ext_configExtConfigInst :
  gfpn.ext_config.ExtConfig C Clause0_BaseField
  Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide) :
  gfpn.quadratic.QuadraticExt C Clause0_BaseField
    Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide →
    Result Unit

/-- [gf2_core::gfpn::quadratic::{impl gf2_core::field::traits::FiniteField<Clause0_Clause0_Clause0_Characteristic, gf2_core::gfpn::quadratic::QuadraticExtWide<Clause0_Clause0_Clause0_Wide>> for gf2_core::gfpn::quadratic::QuadraticExt<C, Clause0_BaseField, Clause0_Clause0_Clause0_Characteristic, Clause0_Clause0_Clause0_Wide>}::theorem_4_operand_bound]:
    Source: 'crates/gf2-core/src/gfpn/quadratic.rs', lines 582:0-696:1
    Visibility: public -/
axiom
  gfpn.quadratic.QuadraticExt.Insts.Gf2_coreFieldTraitsFiniteFieldClause0_Clause0_Clause0_CharacteristicQuadraticExtWide.theorem_4_operand_bound
  {C : Type} {Clause0_BaseField : Type} {Clause0_Clause0_Clause0_Characteristic
  : Type} {Clause0_Clause0_Clause0_Wide : Type} (ext_configExtConfigInst :
  gfpn.ext_config.ExtConfig C Clause0_BaseField
  Clause0_Clause0_Clause0_Characteristic Clause0_Clause0_Clause0_Wide) :
  Result Std.U128

