-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: function definitions
import Aeneas
import Gf2Core.Types
import Gf2Core.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace gf2_core

/- Trait implementation: [core::fmt::num::imp::{core::fmt::Display for u64}]
   Source: '/rustc/library/core/src/fmt/num.rs', lines 134:8-134:39
   Name pattern: [core::fmt::Display<u64>] -/
@[reducible, rust_trait_impl "core::fmt::Display<u64>"]
def U64.Insts.CoreFmtDisplay : core.fmt.Display Std.U64 := {
  fmt := core.fmt.num.imp.DisplayU64.fmt
}

/- Trait implementation: [core::ops::arith::{core::ops::arith::Add<u128, u128> for u128}]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 99:8-99:29
   Name pattern: [core::ops::arith::Add<u128, u128, u128>] -/
@[reducible, rust_trait_impl "core::ops::arith::Add<u128, u128, u128>"]
def U128.Insts.CoreOpsArithAddU128U128 : core.ops.arith.Add Std.U128 Std.U128
  Std.U128 := {
  add := U128.Insts.CoreOpsArithAddU128U128.add
}

/- Trait implementation: [core::ops::arith::{core::ops::arith::AddAssign<u128> for u128}]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 787:8-787:35
   Name pattern: [core::ops::arith::AddAssign<u128, u128>] -/
@[reducible, rust_trait_impl "core::ops::arith::AddAssign<u128, u128>"]
def U128.Insts.CoreOpsArithAddAssignU128 : core.ops.arith.AddAssign Std.U128
  Std.U128 := {
  add_assign := U128.Insts.CoreOpsArithAddAssignU128.add_assign
}

/- [gf2_core::gfp::{core::clone::Clone for gf2_core::gfp::Fp<P>}::clone]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:9-71:14 -/
def gfp.Fp.Insts.CoreCloneClone.clone
  {P : Std.U64} (self : gfp.Fp P) : Result (gfp.Fp P) := do
  ok self

/- Trait implementation: [gf2_core::gfp::{core::clone::Clone for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:9-71:14 -/
@[reducible]
def gfp.Fp.Insts.CoreCloneClone (P : Std.U64) : core.clone.Clone (gfp.Fp P)
  := {
  clone := gfp.Fp.Insts.CoreCloneClone.clone
}

/- Trait implementation: [gf2_core::gfp::{core::marker::Copy for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:16-71:20 -/
@[reducible]
def gfp.Fp.Insts.CoreMarkerCopy (P : Std.U64) : core.marker.Copy (gfp.Fp P)
  := {
  cloneInst := gfp.Fp.Insts.CoreCloneClone P
}

/- Trait implementation: [gf2_core::gfp::{core::marker::StructuralPartialEq for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:22-71:31 -/
@[reducible]
def gfp.Fp.Insts.CoreMarkerStructuralPartialEq (P : Std.U64) :
  core.marker.StructuralPartialEq (gfp.Fp P) := {
}

/- [gf2_core::gfp::{core::cmp::PartialEq<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::eq]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:22-71:31 -/
def gfp.Fp.Insts.CoreCmpPartialEqFp.eq
  {P : Std.U64} (self : gfp.Fp P) (other : gfp.Fp P) : Result Bool := do
  ok (self = other)

/- Trait implementation: [gf2_core::gfp::{core::cmp::PartialEq<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:22-71:31 -/
@[reducible]
def gfp.Fp.Insts.CoreCmpPartialEqFp (P : Std.U64) : core.cmp.PartialEq (gfp.Fp
  P) (gfp.Fp P) := {
  eq := gfp.Fp.Insts.CoreCmpPartialEqFp.eq
}

/- [gf2_core::gfp::{core::cmp::Eq for gf2_core::gfp::Fp<P>}::assert_receiver_is_total_eq]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:33-71:35 -/
def gfp.Fp.Insts.CoreCmpEq.assert_receiver_is_total_eq
  {P : Std.U64} (self : gfp.Fp P) : Result Unit := do
  ok ()

/- Trait implementation: [gf2_core::gfp::{core::cmp::Eq for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:33-71:35 -/
@[reducible]
def gfp.Fp.Insts.CoreCmpEq (P : Std.U64) : core.cmp.Eq (gfp.Fp P) := {
  partialEqInst := gfp.Fp.Insts.CoreCmpPartialEqFp P
  assert_receiver_is_total_eq :=
    gfp.Fp.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/- [gf2_core::gfp::{core::hash::Hash for gf2_core::gfp::Fp<P>}::hash]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:37-71:41 -/
def gfp.Fp.Insts.CoreHashHash.hash
  {__H : Type} {P : Std.U64} (corehashHasherInst : core.hash.Hasher __H)
  (self : gfp.Fp P) (state : __H) :
  Result __H
  := do
  U64.Insts.CoreHashHash.hash corehashHasherInst self state

/- Trait implementation: [gf2_core::gfp::{core::hash::Hash for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 71:37-71:41 -/
@[reducible]
def gfp.Fp.Insts.CoreHashHash (P : Std.U64) : core.hash.Hash (gfp.Fp P) := {
  hash := fun {__H : Type} (corehashHasherInst : core.hash.Hasher __H) =>
    gfp.Fp.Insts.CoreHashHash.hash corehashHasherInst
}

/- [gf2_core::gfp::montgomery::compute_p_inv]: loop 0:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 55:4-58:5 -/
def gfp.montgomery.compute_p_inv_loop
  (p : Std.U64) (inv : Std.U64) (i : Std.I32) : Result Std.U64 := do
  loop
    (fun (inv1, i1) =>
      if i1 < 6#i32
      then
        do
        let i2 ← lift (core.num.U64.wrapping_mul p inv1)
        let i3 ← lift (core.num.U64.wrapping_sub 2#u64 i2)
        let inv2 ← lift (core.num.U64.wrapping_mul inv1 i3)
        let i4 ← i1 + 1#i32
        ok (cont (inv2, i4))
      else ok (done inv1))
    (inv, i)

/- [gf2_core::gfp::montgomery::compute_p_inv]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 52:0-61:1 -/
def gfp.montgomery.compute_p_inv (p : Std.U64) : Result Std.U64 := do
  let inv ← gfp.montgomery.compute_p_inv_loop p 1#u64 0#i32
  core.num.U64.wrapping_neg inv

/- [gf2_core::gfp::montgomery::{gf2_core::gfp::montgomery::MontConsts<P>}::P_INV]
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 22:4-22:44 -/
@[global_simps, irreducible]
def gfp.montgomery.MontConsts.P_INV (P : Std.U64) : Result Std.U64 :=
  gfp.montgomery.compute_p_inv P

/- [gf2_core::gfp::montgomery::redc]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 74:0-83:1 -/
def gfp.montgomery.redc (P : Std.U64) (t : Std.U128) : Result Std.U64 := do
  let t_lo ← lift (UScalar.cast .U64 t)
  let i ← gfp.montgomery.MontConsts.P_INV P
  let m ← lift (core.num.U64.wrapping_mul t_lo i)
  let i1 ← lift (UScalar.cast .U128 m)
  let i2 ← lift (UScalar.cast .U128 P)
  let mp ← i1 * i2
  let i3 ← t + mp
  let i4 ← i3 >>> 64#i32
  let u ← lift (UScalar.cast .U64 i4)
  let (result, borrow) ← core.num.U64.overflowing_sub u P
  let i5 ← lift (UScalar.cast_fromBool .U64 borrow)
  let i6 ← core.num.U64.wrapping_neg i5
  let correction ← lift (i6 &&& P)
  ok (core.num.U64.wrapping_add result correction)

/- [gf2_core::gfp::montgomery::from_mont]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 101:0-103:1 -/
def gfp.montgomery.from_mont (P : Std.U64) (a : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U128 a)
  gfp.montgomery.redc P i

/- [gf2_core::gfp::{gf2_core::gfp::Fp<P>}::value]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 126:4-132:5 -/
def gfp.Fp.value {P : Std.U64} (self : gfp.Fp P) : Result Std.U64 := do
  if P = 2#u64
  then ok self
  else gfp.montgomery.from_mont P self

/- [gf2_core::gfp::{core::fmt::Debug for gf2_core::gfp::Fp<P>}::fmt]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 75:4-77:5 -/
def gfp.Fp.Insts.CoreFmtDebug.fmt
  {P : Std.U64} (self : gfp.Fp P) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let i ← gfp.Fp.value self
  let a ← core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay P
  let a1 ← core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay i
  let a2 ←
    core.fmt.Arguments.new
      (Array.make 12#usize [
        3#u8, 70#u8, 112#u8, 60#u8, 192#u8, 2#u8, 62#u8, 40#u8, 192#u8, 1#u8,
        41#u8, 0#u8
        ]) (Array.make 2#usize [ a, a1 ])
  core.fmt.Formatter.write_fmt f a2

/- Trait implementation: [gf2_core::gfp::{core::fmt::Debug for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 74:0-78:1 -/
@[reducible]
def gfp.Fp.Insts.CoreFmtDebug (P : Std.U64) : core.fmt.Debug (gfp.Fp P) := {
  fmt := gfp.Fp.Insts.CoreFmtDebug.fmt
}

/- [gf2_core::gfp::{gf2_core::gfp::Fp<P>}::VALIDATED]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 82:4-88:6 -/
@[global_simps, irreducible]
def gfp.Fp.VALIDATED (P : Std.U64) : Result Unit := do
  massert (P > 1#u64)
  let i ← 1#u64 <<< 63#i32
  massert (P <= i)

/- [gf2_core::gfp::montgomery::compute_r_mod_p]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 30:0-32:1 -/
def gfp.montgomery.compute_r_mod_p (p : Std.U64) : Result Std.U64 := do
  let i ← 1#u128 <<< 64#i32
  let i1 ← lift (UScalar.cast .U128 p)
  let i2 ← i % i1
  ok (UScalar.cast .U64 i2)

/- [gf2_core::gfp::montgomery::compute_r2_mod_p]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 39:0-42:1 -/
def gfp.montgomery.compute_r2_mod_p (p : Std.U64) : Result Std.U64 := do
  let i ← gfp.montgomery.compute_r_mod_p p
  let r ← lift (UScalar.cast .U128 i)
  let i1 ← r * r
  let i2 ← lift (UScalar.cast .U128 p)
  let i3 ← i1 % i2
  ok (UScalar.cast .U64 i3)

/- [gf2_core::gfp::montgomery::{gf2_core::gfp::montgomery::MontConsts<P>}::R2_MOD_P]
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 19:4-19:50 -/
@[global_simps, irreducible]
def gfp.montgomery.MontConsts.R2_MOD_P (P : Std.U64) : Result Std.U64 :=
  gfp.montgomery.compute_r2_mod_p P

/- [gf2_core::gfp::montgomery::to_mont]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 91:0-93:1 -/
def gfp.montgomery.to_mont (P : Std.U64) (a : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U128 a)
  let i1 ← gfp.montgomery.MontConsts.R2_MOD_P P
  let i2 ← lift (UScalar.cast .U128 i1)
  let i3 ← i * i2
  gfp.montgomery.redc P i3

/- [gf2_core::gfp::{gf2_core::gfp::Fp<P>}::new]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 105:4-114:5 -/
def gfp.Fp.new (P : Std.U64) (value : Std.U64) : Result (gfp.Fp P) := do
  gfp.Fp.VALIDATED P
  let reduced ← value % P
  if P = 2#u64
  then ok reduced
  else let i ← gfp.montgomery.to_mont P reduced
       ok i

/- [gf2_core::gfp::{core::fmt::Display for gf2_core::gfp::Fp<P>}::fmt]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 136:4-138:5 -/
def gfp.Fp.Insts.CoreFmtDisplay.fmt
  {P : Std.U64} (self : gfp.Fp P) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let args ← gfp.Fp.value self
  let a ← core.fmt.rt.Argument.new_display U64.Insts.CoreFmtDisplay args
  let a1 ←
    core.fmt.Arguments.new (Array.make 2#usize [ 192#u8, 0#u8 ])
      (Array.make 1#usize [ a ])
  core.fmt.Formatter.write_fmt f a1

/- Trait implementation: [gf2_core::gfp::{core::fmt::Display for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 135:0-139:1 -/
@[reducible]
def gfp.Fp.Insts.CoreFmtDisplay (P : Std.U64) : core.fmt.Display (gfp.Fp P)
  := {
  fmt := gfp.Fp.Insts.CoreFmtDisplay.fmt
}

/- [gf2_core::gfp::montgomery::mont_add]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 111:0-116:1 -/
def gfp.montgomery.mont_add
  (P : Std.U64) (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let sum ← a + b
  let (result, borrow) ← core.num.U64.overflowing_sub sum P
  let i ← lift (UScalar.cast_fromBool .U64 borrow)
  let i1 ← core.num.U64.wrapping_neg i
  let correction ← lift (i1 &&& P)
  ok (core.num.U64.wrapping_add result correction)

/- [gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 154:4-156:5 -/
def gfp.Fp.Insts.CoreOpsArithAddFpFp.add
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  let i ← gfp.montgomery.mont_add P self rhs
  ok i

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 145:0-157:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithAddFpFp (P : Std.U64) : core.ops.arith.Add (gfp.Fp
  P) (gfp.Fp P) (gfp.Fp P) := {
  add := gfp.Fp.Insts.CoreOpsArithAddFpFp.add
}

/- [gf2_core::gfp::montgomery::mont_sub]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 124:0-128:1 -/
def gfp.montgomery.mont_sub
  (P : Std.U64) (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let (result, borrow) ← core.num.U64.overflowing_sub a b
  let i ← lift (UScalar.cast_fromBool .U64 borrow)
  let i1 ← core.num.U64.wrapping_neg i
  let correction ← lift (i1 &&& P)
  ok (core.num.U64.wrapping_add result correction)

/- [gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::sub]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 168:4-170:5 -/
def gfp.Fp.Insts.CoreOpsArithSubFpFp.sub
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  let i ← gfp.montgomery.mont_sub P self rhs
  ok i

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 159:0-171:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithSubFpFp (P : Std.U64) : core.ops.arith.Sub (gfp.Fp
  P) (gfp.Fp P) (gfp.Fp P) := {
  sub := gfp.Fp.Insts.CoreOpsArithSubFpFp.sub
}

/- [gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::mul]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 184:4-190:5 -/
def gfp.Fp.Insts.CoreOpsArithMulFpFp.mul
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  if P = 2#u64
  then let i ← lift (self &&& rhs)
       ok i
  else
    let i ← lift (UScalar.cast .U128 self)
    let i1 ← lift (UScalar.cast .U128 rhs)
    let i2 ← i * i1
    let i3 ← gfp.montgomery.redc P i2
    ok i3

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 173:0-191:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithMulFpFp (P : Std.U64) : core.ops.arith.Mul (gfp.Fp
  P) (gfp.Fp P) (gfp.Fp P) := {
  mul := gfp.Fp.Insts.CoreOpsArithMulFpFp.mul
}

/- [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::neg]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 204:4-210:5 -/
def gfp.Fp.Insts.CoreOpsArithNegFp.neg
  {P : Std.U64} (self : gfp.Fp P) : Result (gfp.Fp P) := do
  if self = 0#u64
  then ok self
  else let i ← P - self
       ok i

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 193:0-211:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithNegFp (P : Std.U64) : core.ops.arith.Neg (gfp.Fp
  P) (gfp.Fp P) := {
  neg := gfp.Fp.Insts.CoreOpsArithNegFp.neg
}

/- [gf2_core::gfp::montgomery::{gf2_core::gfp::montgomery::MontConsts<P>}::R_MOD_P]
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 16:4-16:48 -/
@[global_simps, irreducible]
def gfp.montgomery.MontConsts.R_MOD_P (P : Std.U64) : Result Std.U64 :=
  gfp.montgomery.compute_r_mod_p P

/- [gf2_core::gfp::montgomery::mod_pow_mont]: loop 0:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 141:4-149:5 -/
def gfp.montgomery.mod_pow_mont_loop
  (P : Std.U64) (base : Std.U64) (exp : Std.U64) (result : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (base1, exp1, result1) =>
      if exp1 > 0#u64
      then
        do
        let i ← lift (exp1 &&& 1#u64)
        let result2 ←
          if i = 1#u64
          then
            let i1 ← lift (UScalar.cast .U128 result1)
            let i2 ← lift (UScalar.cast .U128 base1)
            let i3 ← i1 * i2
            gfp.montgomery.redc P i3
          else ok result1
        let exp2 ← exp1 >>> 1#i32
        if exp2 > 0#u64
        then
          let i1 ← lift (UScalar.cast .U128 base1)
          let i2 ← lift (UScalar.cast .U128 base1)
          let i3 ← i1 * i2
          let base2 ← gfp.montgomery.redc P i3
          ok (cont (base2, exp2, result2))
        else ok (cont (base1, exp2, result2))
      else ok (done result1))
    (base, exp, result)

/- [gf2_core::gfp::montgomery::mod_pow_mont]:
   Source: 'crates/gf2-core/src/gfp/montgomery.rs', lines 139:0-151:1 -/
def gfp.montgomery.mod_pow_mont
  (P : Std.U64) (base : Std.U64) (exp : Std.U64) : Result Std.U64 := do
  let result ← gfp.montgomery.MontConsts.R_MOD_P P
  gfp.montgomery.mod_pow_mont_loop P base exp result

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::inv]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 363:4-371:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.inv
  {P : Std.U64} (self : gfp.Fp P) : Result (Option (gfp.Fp P)) := do
  if self = 0#u64
  then ok none
  else
    if P = 2#u64
    then ok (some 1#u64)
    else
      let i ← P - 2#u64
      let i1 ← gfp.montgomery.mod_pow_mont P self i
      ok (some i1)

/- [gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::div]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 227:4-229:5 -/
def gfp.Fp.Insts.CoreOpsArithDivFpFp.div
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  let o ← gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.inv rhs
  let f ← core.option.Option.expect o (toStr "division by zero in Fp")
  gfp.Fp.Insts.CoreOpsArithMulFpFp.mul self f

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 213:0-230:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithDivFpFp (P : Std.U64) : core.ops.arith.Div (gfp.Fp
  P) (gfp.Fp P) (gfp.Fp P) := {
  div := gfp.Fp.Insts.CoreOpsArithDivFpFp.div
}

/- [gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add_assign]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 238:4-240:5 -/
def gfp.Fp.Insts.CoreOpsArithAddAssignFp.add_assign
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithAddFpFp.add self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 236:0-241:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithAddAssignFp (P : Std.U64) :
  core.ops.arith.AddAssign (gfp.Fp P) (gfp.Fp P) := {
  add_assign := gfp.Fp.Insts.CoreOpsArithAddAssignFp.add_assign
}

/- [gf2_core::gfp::{core::ops::arith::AddAssign<&0 (gf2_core::gfp::Fp<P>)> for gf2_core::gfp::Fp<P>}::add_assign]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 245:4-247:5 -/
def gfp.Fp.Insts.CoreOpsArithAddAssignShared0Fp.add_assign
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithAddFpFp.add self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::AddAssign<&0 (gf2_core::gfp::Fp<P>)> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 243:0-248:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithAddAssignShared0Fp (P : Std.U64) :
  core.ops.arith.AddAssign (gfp.Fp P) (gfp.Fp P) := {
  add_assign := gfp.Fp.Insts.CoreOpsArithAddAssignShared0Fp.add_assign
}

/- [gf2_core::gfp::{core::ops::arith::Add<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 257:4-259:5 -/
def gfp.Fp.Insts.CoreOpsArithAddShared0FpFp.add
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithAddFpFp.add self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Add<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 254:0-260:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithAddShared0FpFp (P : Std.U64) : core.ops.arith.Add
  (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  add := gfp.Fp.Insts.CoreOpsArithAddShared0FpFp.add
}

/- [gf2_core::gfp::{core::ops::arith::Add<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}::add]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 265:4-267:5 -/
def Shared0Fp.Insts.CoreOpsArithAddShared0FpFp.add
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithAddFpFp.add self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Add<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 262:0-268:1 -/
@[reducible]
def Shared0Fp.Insts.CoreOpsArithAddShared0FpFp (P : Std.U64) :
  core.ops.arith.Add (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  add := Shared0Fp.Insts.CoreOpsArithAddShared0FpFp.add
}

/- [gf2_core::gfp::{core::ops::arith::Sub<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::sub]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 273:4-275:5 -/
def gfp.Fp.Insts.CoreOpsArithSubShared0FpFp.sub
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithSubFpFp.sub self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Sub<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 270:0-276:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithSubShared0FpFp (P : Std.U64) : core.ops.arith.Sub
  (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  sub := gfp.Fp.Insts.CoreOpsArithSubShared0FpFp.sub
}

/- [gf2_core::gfp::{core::ops::arith::Sub<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}::sub]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 281:4-283:5 -/
def Shared0Fp.Insts.CoreOpsArithSubShared0FpFp.sub
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithSubFpFp.sub self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Sub<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 278:0-284:1 -/
@[reducible]
def Shared0Fp.Insts.CoreOpsArithSubShared0FpFp (P : Std.U64) :
  core.ops.arith.Sub (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  sub := Shared0Fp.Insts.CoreOpsArithSubShared0FpFp.sub
}

/- [gf2_core::gfp::{core::ops::arith::Mul<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::mul]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 289:4-291:5 -/
def gfp.Fp.Insts.CoreOpsArithMulShared0FpFp.mul
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithMulFpFp.mul self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Mul<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 286:0-292:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithMulShared0FpFp (P : Std.U64) : core.ops.arith.Mul
  (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  mul := gfp.Fp.Insts.CoreOpsArithMulShared0FpFp.mul
}

/- [gf2_core::gfp::{core::ops::arith::Mul<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}::mul]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 297:4-299:5 -/
def Shared0Fp.Insts.CoreOpsArithMulShared0FpFp.mul
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithMulFpFp.mul self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Mul<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 294:0-300:1 -/
@[reducible]
def Shared0Fp.Insts.CoreOpsArithMulShared0FpFp (P : Std.U64) :
  core.ops.arith.Mul (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  mul := Shared0Fp.Insts.CoreOpsArithMulShared0FpFp.mul
}

/- [gf2_core::gfp::{core::ops::arith::Div<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::div]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 305:4-307:5 -/
def gfp.Fp.Insts.CoreOpsArithDivShared0FpFp.div
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithDivFpFp.div self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Div<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 302:0-308:1 -/
@[reducible]
def gfp.Fp.Insts.CoreOpsArithDivShared0FpFp (P : Std.U64) : core.ops.arith.Div
  (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  div := gfp.Fp.Insts.CoreOpsArithDivShared0FpFp.div
}

/- [gf2_core::gfp::{core::ops::arith::Div<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}::div]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 313:4-315:5 -/
def Shared0Fp.Insts.CoreOpsArithDivShared0FpFp.div
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithDivFpFp.div self rhs

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Div<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 310:0-316:1 -/
@[reducible]
def Shared0Fp.Insts.CoreOpsArithDivShared0FpFp (P : Std.U64) :
  core.ops.arith.Div (gfp.Fp P) (gfp.Fp P) (gfp.Fp P) := {
  div := Shared0Fp.Insts.CoreOpsArithDivShared0FpFp.div
}

/- [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}::neg]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 321:4-323:5 -/
def Shared0Fp.Insts.CoreOpsArithNegFp.neg
  {P : Std.U64} (self : gfp.Fp P) : Result (gfp.Fp P) := do
  gfp.Fp.Insts.CoreOpsArithNegFp.neg self

/- Trait implementation: [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<P>> for &0 (gf2_core::gfp::Fp<P>)}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 318:0-324:1 -/
@[reducible]
def Shared0Fp.Insts.CoreOpsArithNegFp (P : Std.U64) : core.ops.arith.Neg
  (gfp.Fp P) (gfp.Fp P) := {
  neg := Shared0Fp.Insts.CoreOpsArithNegFp.neg
}

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::max_unreduced_additions]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 402:4-413:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.max_unreduced_additions
  (P : Std.U64) : Result Std.Usize := do
  let i ← lift (UScalar.cast .U128 P)
  let i1 ← i - 1#u128
  let i2 ← lift (UScalar.cast .U128 P)
  let i3 ← i2 - 1#u128
  let max_product ← i1 * i3
  if max_product = 0#u128
  then ok core.num.Usize.MAX
  else
    let k ← core.num.U128.MAX / max_product
    let i4 ← lift (UScalar.cast .U128 core.num.Usize.MAX)
    if k > i4
    then ok core.num.Usize.MAX
    else ok (UScalar.cast .Usize k)

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::reduce_wide]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 398:4-400:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.reduce_wide
  (P : Std.U64) (wide : Std.U128) : Result (gfp.Fp P) := do
  let i ← lift (UScalar.cast .U128 P)
  let i1 ← wide % i
  let i2 ← lift (UScalar.cast .U64 i1)
  gfp.Fp.new P i2

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::mul_to_wide]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 393:4-395:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.mul_to_wide
  {P : Std.U64} (self : gfp.Fp P) (rhs : gfp.Fp P) : Result Std.U128 := do
  let i ← gfp.Fp.value self
  let i1 ← lift (UScalar.cast .U128 i)
  let i2 ← gfp.Fp.value rhs
  let i3 ← lift (UScalar.cast .U128 i2)
  i1 * i3

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::to_wide]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 388:4-390:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.to_wide
  {P : Std.U64} (self : gfp.Fp P) : Result Std.U128 := do
  let i ← gfp.Fp.value self
  ok (UScalar.cast .U128 i)

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::one_like]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 379:4-385:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.one_like
  {P : Std.U64} (self : gfp.Fp P) : Result (gfp.Fp P) := do
  if P = 2#u64
  then ok 1#u64
  else let i ← gfp.montgomery.MontConsts.R_MOD_P P
       ok i

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::zero_like]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 374:4-376:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.zero_like
  {P : Std.U64} (self : gfp.Fp P) : Result (gfp.Fp P) := do
  ok 0#u64

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::is_one]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 350:4-356:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_one
  {P : Std.U64} (self : gfp.Fp P) : Result Bool := do
  if P = 2#u64
  then ok (self = 1#u64)
  else let i ← gfp.montgomery.MontConsts.R_MOD_P P
       ok (self = i)

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::is_zero]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 345:4-347:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_zero
  {P : Std.U64} (self : gfp.Fp P) : Result Bool := do
  ok (self = 0#u64)

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::extension_degree]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 340:4-342:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.extension_degree
  {P : Std.U64} (self : gfp.Fp P) : Result Std.Usize := do
  ok 1#usize

/- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::characteristic]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 335:4-337:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.characteristic
  {P : Std.U64} (self : gfp.Fp P) : Result Std.U64 := do
  ok P

/- Trait implementation: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 330:0-414:1 -/
@[reducible]
def gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128 (P : Std.U64) :
  field.traits.FiniteField (gfp.Fp P) Std.U64 Std.U128 := {
  corecloneCloneInst := gfp.Fp.Insts.CoreCloneClone P
  corecmpPartialEqInst := gfp.Fp.Insts.CoreCmpPartialEqFp P
  corecmpEqInst := gfp.Fp.Insts.CoreCmpEq P
  corehashHashInst := gfp.Fp.Insts.CoreHashHash P
  corefmtDebugInst := gfp.Fp.Insts.CoreFmtDebug P
  coreopsarithAddInst := gfp.Fp.Insts.CoreOpsArithAddFpFp P
  coreopsarithAddSelfSharedSelfSelfInst :=
    gfp.Fp.Insts.CoreOpsArithAddShared0FpFp P
  coreopsarithSubInst := gfp.Fp.Insts.CoreOpsArithSubFpFp P
  coreopsarithSubSelfSharedSelfSelfInst :=
    gfp.Fp.Insts.CoreOpsArithSubShared0FpFp P
  coreopsarithMulInst := gfp.Fp.Insts.CoreOpsArithMulFpFp P
  coreopsarithMulSelfSharedSelfSelfInst :=
    gfp.Fp.Insts.CoreOpsArithMulShared0FpFp P
  coreopsarithDivInst := gfp.Fp.Insts.CoreOpsArithDivFpFp P
  coreopsarithDivSelfSharedSelfSelfInst :=
    gfp.Fp.Insts.CoreOpsArithDivShared0FpFp P
  coreopsarithNegInst := gfp.Fp.Insts.CoreOpsArithNegFp P
  coreopsarithAddAssignInst := gfp.Fp.Insts.CoreOpsArithAddAssignFp P
  coreopsarithAddAssignSelfSharedSelfInst :=
    gfp.Fp.Insts.CoreOpsArithAddAssignShared0Fp P
  corecloneCloneCharacteristicInst := core.clone.CloneU64
  corefmtDebugCharacteristicInst := core.fmt.DebugU64
  corecmpPartialEqCharacteristicInst := core.cmp.PartialEqU64
  corecmpEqCharacteristicInst := core.cmp.EqU64
  corecloneCloneWideInst := core.clone.CloneU128
  coreopsarithAddWideInst := U128.Insts.CoreOpsArithAddU128U128
  coreopsarithAddAssignWideInst := U128.Insts.CoreOpsArithAddAssignU128
  characteristic :=
    gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.characteristic
  extension_degree :=
    gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.extension_degree
  is_zero := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_zero
  is_one := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_one
  inv := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.inv
  zero_like := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.zero_like
  one_like := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.one_like
  to_wide := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.to_wide
  mul_to_wide := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.mul_to_wide
  reduce_wide := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.reduce_wide
    P
  max_unreduced_additions :=
    gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.max_unreduced_additions
    P
}

/- [gf2_core::gfp::{gf2_core::field::traits::ConstField<u64, u128> for gf2_core::gfp::Fp<P>}::order]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 440:4-442:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.order
  (P : Std.U64) : Result Std.U128 := do
  ok (UScalar.cast .U128 P)

/- [gf2_core::gfp::{gf2_core::field::traits::ConstField<u64, u128> for gf2_core::gfp::Fp<P>}::one]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 429:4-437:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.one
  (P : Std.U64) : Result (gfp.Fp P) := do
  gfp.Fp.VALIDATED P
  if P = 2#u64
  then ok 1#u64
  else let i ← gfp.montgomery.MontConsts.R_MOD_P P
       ok i

/- [gf2_core::gfp::{gf2_core::field::traits::ConstField<u64, u128> for gf2_core::gfp::Fp<P>}::zero]:
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 422:4-426:5 -/
def gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.zero
  (P : Std.U64) : Result (gfp.Fp P) := do
  gfp.Fp.VALIDATED P
  ok 0#u64

/- Trait implementation: [gf2_core::gfp::{gf2_core::field::traits::ConstField<u64, u128> for gf2_core::gfp::Fp<P>}]
   Source: 'crates/gf2-core/src/gfp/mod.rs', lines 420:0-443:1 -/
@[reducible]
def gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128 (P : Std.U64) :
  field.traits.ConstField (gfp.Fp P) Std.U64 Std.U128 := {
  FiniteFieldInst := gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128 P
  coremarkerCopyInst := gfp.Fp.Insts.CoreMarkerCopy P
  zero := gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.zero P
  one := gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.one P
  order := gfp.Fp.Insts.Gf2_coreFieldTraitsConstFieldU64U128.order P
}

/- [gf2_core::simd::maybe_simd]:
   Source: 'crates/gf2-core/src/lib.rs', lines 82:4-84:5 -/
def simd.maybe_simd : Result (Option Unit) := do
  ok none

end gf2_core
