-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [core::fmt::builders::DebugStruct]
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 88:0-88:34
    Name pattern: [core::fmt::builders::DebugStruct]
    Visibility: public -/
@[rust_type "core::fmt::builders::DebugStruct"]
axiom core.fmt.builders.DebugStruct : Type

/-- [core::iter::adapters::zip::Zip]
    Source: '/rustc/library/core/src/iter/adapters/zip.rs', lines 15:0-15:20
    Name pattern: [core::iter::adapters::zip::Zip]
    Visibility: public -/
@[rust_type "core::iter::adapters::zip::Zip"]
axiom core.iter.adapters.zip.Zip (A : Type) (B : Type) : Type

/-- [gf2_core::gf2m::field::Gf2mElement_]
    Source: 'crates/gf2-core/src/gf2m/field.rs', lines 206:0-209:1
    Visibility: public -/
axiom gf2m.field.Gf2mElement_ {V : Type} (uint_extUintExtInst :
  gf2m.uint_ext.UintExt V) : Type

