-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_algebra]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Gf2Algebra.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open gf2_algebra

/-- [core::array::from_fn]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 109:0-111:52
    Name pattern: [core::array::from_fn]
    Visibility: public -/
@[rust_fun "core::array::from_fn"]
axiom core.array.from_fn
  {T : Type} {F : Type} (N : Std.Usize) (opsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) :
  F → Result (Array T N)

/-- [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field]:
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 132:4-132:76
    Name pattern: [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field]
    Visibility: public -/
@[rust_fun
  "core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::field"]
axiom core.fmt.builders.DebugStruct.field
  :
  core.fmt.builders.DebugStruct → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) →
    Result (core.fmt.builders.DebugStruct × (core.fmt.builders.DebugStruct →
    core.fmt.builders.DebugStruct))

/-- [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish]:
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 244:4-244:43
    Name pattern: [core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish]
    Visibility: public -/
@[rust_fun
  "core::fmt::builders::{core::fmt::builders::DebugStruct<'a, 'b>}::finish"]
axiom core.fmt.builders.DebugStruct.finish
  :
  core.fmt.builders.DebugStruct → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.builders.DebugStruct)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2441:4-2441:76
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct"]
axiom core.fmt.Formatter.debug_struct
  :
  core.fmt.Formatter → Str → Result (core.fmt.builders.DebugStruct ×
    core.fmt.Formatter)

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 79:4-79:64
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.next
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Result ((Option (Std.Usize ×
    Clause0_Item)) × (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {B : Type} {I : Type} {F : Type} {B1 : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B1 B) :
  core.iter.adapters.map.Map I F → Result B1

/-- [core::iter::range::{core::iter::range::Step for u64}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 289:16-289:74
    Name pattern: [core::iter::range::{core::iter::range::Step<u64>}::backward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u64>}::backward_checked"]
axiom U64.Insts.CoreIterRangeStep.backward_checked
  : Std.U64 → Std.Usize → Result (Option Std.U64)

/-- [core::iter::range::{core::iter::range::Step for u64}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 281:16-281:73
    Name pattern: [core::iter::range::{core::iter::range::Step<u64>}::forward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u64>}::forward_checked"]
axiom U64.Insts.CoreIterRangeStep.forward_checked
  : Std.U64 → Std.Usize → Result (Option Std.U64)

/-- [core::iter::range::{core::iter::range::Step for u64}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 270:16-270:84
    Name pattern: [core::iter::range::{core::iter::range::Step<u64>}::steps_between]
    Visibility: public -/
@[rust_fun "core::iter::range::{core::iter::range::Step<u64>}::steps_between"]
axiom U64.Insts.CoreIterRangeStep.steps_between
  : Std.U64 → Std.U64 → Result (Std.Usize × (Option Std.Usize))

/-- [core::iter::range::{core::iter::range::Step for u128}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 388:16-388:74
    Name pattern: [core::iter::range::{core::iter::range::Step<u128>}::backward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u128>}::backward_checked"]
axiom U128.Insts.CoreIterRangeStep.backward_checked
  : Std.U128 → Std.Usize → Result (Option Std.U128)

/-- [core::iter::range::{core::iter::range::Step for u128}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 383:16-383:73
    Name pattern: [core::iter::range::{core::iter::range::Step<u128>}::forward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u128>}::forward_checked"]
axiom U128.Insts.CoreIterRangeStep.forward_checked
  : Std.U128 → Std.Usize → Result (Option Std.U128)

/-- [core::iter::range::{core::iter::range::Step for u128}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 370:16-370:84
    Name pattern: [core::iter::range::{core::iter::range::Step<u128>}::steps_between]
    Visibility: public -/
@[rust_fun "core::iter::range::{core::iter::range::Step<u128>}::steps_between"]
axiom U128.Insts.CoreIterRangeStep.steps_between
  : Std.U128 → Std.U128 → Result (Std.Usize × (Option Std.Usize))

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::all]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::all]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::all"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.all
  {A : Type} {F : Type} (StepInst : core.iter.range.Step A)
  (opsfunctionFnMutFTupleABoolInst : core.ops.function.FnMut F A Bool) :
  core.ops.range.Range A → F → Result (Bool × (core.ops.range.Range A))

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::collect]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::collect]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::collect"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.collect
  {A : Type} {B : Type} (StepInst : core.iter.range.Step A)
  (traitscollectFromIteratorInst : core.iter.traits.collect.FromIterator B A) :
  core.ops.range.Range A → Result B

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::map]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::map]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::map"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.map
  {A : Type} {B : Type} {F : Type} (StepInst : core.iter.range.Step A)
  (opsfunctionFnMutFTupleABInst : core.ops.function.FnMut F A B) :
  core.ops.range.Range A → F → Result (core.iter.adapters.map.Map
    (core.ops.range.Range A) F)

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 789:4-792:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::enumerate]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 1005:4-1007:20
    Name pattern: [core::iter::traits::iterator::Iterator::enumerate]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::enumerate"]
axiom core.iter.traits.iterator.Iterator.enumerate.default
  {Self : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) :
  Self → Result (core.iter.adapters.enumerate.Enumerate Self)

/-- [core::iter::traits::iterator::Iterator::all]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 2809:4-2812:37
    Name pattern: [core::iter::traits::iterator::Iterator::all]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::all"]
axiom core.iter.traits.iterator.Iterator.all.default
  {Self : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBoolInst : core.ops.function.FnMut F
  Clause0_Item Bool) :
  Self → F → Result (Bool × Self)

/-- [core::num::{u128}::trailing_zeros]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 174:8-174:48
    Name pattern: [core::num::{u128}::trailing_zeros]
    Visibility: public -/
@[rust_fun "core::num::{u128}::trailing_zeros"]
axiom core.num.U128.trailing_zeros : Std.U128 → Result Std.U32

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3597:8-3597:54
    Name pattern: [core::num::{usize}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{usize}::div_ceil"]
axiom core.num.Usize.div_ceil : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::ops::arith::{core::ops::arith::Add<u128, u128> for u128}::add]:
    Source: '/rustc/library/core/src/ops/arith.rs', lines 105:12-105:41
    Name pattern: [core::ops::arith::{core::ops::arith::Add<u128, u128, u128>}::add]
    Visibility: public -/
@[rust_fun "core::ops::arith::{core::ops::arith::Add<u128, u128, u128>}::add"]
axiom U128.Insts.CoreOpsArithAddU128U128.add
  : Std.U128 → Std.U128 → Result Std.U128

/-- [core::ops::arith::{core::ops::arith::AddAssign<u128> for u128}::add_assign]:
    Source: '/rustc/library/core/src/ops/arith.rs', lines 791:12-791:47
    Name pattern: [core::ops::arith::{core::ops::arith::AddAssign<u128, u128>}::add_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::arith::{core::ops::arith::AddAssign<u128, u128>}::add_assign"]
axiom U128.Insts.CoreOpsArithAddAssignU128.add_assign
  : Std.U128 → Std.U128 → Result Std.U128

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::new]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 390:4-390:50
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new]
    Visibility: public -/
@[rust_fun "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new"]
axiom core.ops.range.RangeInclusive.new
  {Idx : Type} : Idx → Idx → Result (core.ops.range.RangeInclusive Idx)

/-- [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::contains]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 522:4-525:44
    Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains]
    Visibility: public -/
@[rust_fun
  "core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains"]
axiom core.ops.range.RangeInclusive.contains
  {Idx : Type} {U : Type} (cmpPartialOrdInst : core.cmp.PartialOrd Idx Idx)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd Idx U) (cmpPartialOrdInst2 :
  core.cmp.PartialOrd U Idx) :
  core.ops.range.RangeInclusive Idx → U → Result Bool

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::all]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 309:12-312:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
  {T : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBoolInst :
  core.ops.function.FnMut F T Bool) :
  core.slice.iter.Iter T → F → Result (Bool × (core.slice.iter.Iter T))

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::collect]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.collect
  {T : Type} {B : Type} (itertraitscollectFromIteratorBSharedATInst :
  core.iter.traits.collect.FromIterator B T) :
  core.slice.iter.Iter T → Result B

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::map]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
  {T : Type} {B : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBInst :
  core.ops.function.FnMut F T B) :
  core.slice.iter.Iter T → F → Result (core.iter.adapters.map.Map
    (core.slice.iter.Iter T) F)

/-- [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 797:4-797:35
    Name pattern: [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
    Visibility: public -/
@[trait_default, rust_const
  "gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD"]
axiom gf2_core.field.traits.FiniteField.WINOGRAD_THRESHOLD.default {Self :
  Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst
  : gf2_core.field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 830:4-830:35
    Name pattern: [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
    Visibility: public -/
@[trait_default, rust_const
  "gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD"]
axiom gf2_core.field.traits.FiniteField.TRI_BASE_THRESHOLD.default {Self :
  Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst
  : gf2_core.field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 864:4-864:30
    Name pattern: [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
    Visibility: public -/
@[trait_default, rust_const
  "gf2_core::field::traits::FiniteField::PLE_BASE_COLS"]
axiom gf2_core.field.traits.FiniteField.PLE_BASE_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  gf2_core.field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::gfp::{core::clone::Clone for gf2_core::gfp::Fp<P>}::clone]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 133:9-133:14
    Name pattern: [gf2_core::gfp::{core::clone::Clone<gf2_core::gfp::Fp<@P>>}::clone]
    Visibility: public -/
@[rust_fun "gf2_core::gfp::{core::clone::Clone<gf2_core::gfp::Fp<@P>>}::clone"]
axiom gf2_core.gfp.Fp.Insts.CoreCloneClone.clone
  {P : Std.U64} : gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::cmp::PartialEq<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::eq]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 133:22-133:31
    Name pattern: [gf2_core::gfp::{core::cmp::PartialEq<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::eq]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::cmp::PartialEq<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::eq"]
axiom gf2_core.gfp.Fp.Insts.CoreCmpPartialEqFp.eq
  {P : Std.U64} : gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result Bool

/-- [gf2_core::gfp::{core::hash::Hash for gf2_core::gfp::Fp<P>}::hash]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 133:37-133:41
    Name pattern: [gf2_core::gfp::{core::hash::Hash<gf2_core::gfp::Fp<@P>>}::hash]
    Visibility: public -/
@[rust_fun "gf2_core::gfp::{core::hash::Hash<gf2_core::gfp::Fp<@P>>}::hash"]
axiom gf2_core.gfp.Fp.Insts.CoreHashHash.hash
  {__H : Type} {P : Std.U64} (corehashHasherInst : core.hash.Hasher __H) :
  gf2_core.gfp.Fp P → __H → Result __H

/-- [gf2_core::gfp::{core::fmt::Debug for gf2_core::gfp::Fp<P>}::fmt]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 137:4-137:60
    Name pattern: [gf2_core::gfp::{core::fmt::Debug<gf2_core::gfp::Fp<@P>>}::fmt]
    Visibility: public -/
@[rust_fun "gf2_core::gfp::{core::fmt::Debug<gf2_core::gfp::Fp<@P>>}::fmt"]
axiom gf2_core.gfp.Fp.Insts.CoreFmtDebug.fmt
  {P : Std.U64} :
  gf2_core.gfp.Fp P → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [gf2_core::gfp::{gf2_core::gfp::Fp<P>}::new]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 167:4-167:40
    Name pattern: [gf2_core::gfp::{gf2_core::gfp::Fp<@P>}::new]
    Visibility: public -/
@[rust_fun "gf2_core::gfp::{gf2_core::gfp::Fp<@P>}::new"]
axiom gf2_core.gfp.Fp.new (P : Std.U64) : Std.U64 → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{gf2_core::gfp::Fp<P>}::value]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 190:4-190:35
    Name pattern: [gf2_core::gfp::{gf2_core::gfp::Fp<@P>}::value]
    Visibility: public -/
@[rust_fun "gf2_core::gfp::{gf2_core::gfp::Fp<@P>}::value"]
axiom gf2_core.gfp.Fp.value {P : Std.U64} : gf2_core.gfp.Fp P → Result Std.U64

/-- [gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 322:4-322:35
    Name pattern: [gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithAddFpFp.add
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::sub]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 340:4-340:35
    Name pattern: [gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::sub]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::sub"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithSubFpFp.sub
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::mul]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 363:4-363:35
    Name pattern: [gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::mul]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::mul"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithMulFpFp.mul
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::neg]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 385:4-385:24
    Name pattern: [gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::neg]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Neg<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::neg"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithNegFp.neg
  {P : Std.U64} : gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<P>, gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::div]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 408:4-408:35
    Name pattern: [gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::div]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::div"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithDivFpFp.div
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add_assign]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 419:4-419:39
    Name pattern: [gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add_assign]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add_assign"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithAddAssignFp.add_assign
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::AddAssign<&0 (gf2_core::gfp::Fp<P>)> for gf2_core::gfp::Fp<P>}::add_assign]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 426:4-426:40
    Name pattern: [gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>>}::add_assign]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::AddAssign<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>>}::add_assign"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithAddAssignShared0Fp.add_assign
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Add<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::add]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 438:4-438:38
    Name pattern: [gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Add<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::add"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithAddShared0FpFp.add
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Sub<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::sub]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 454:4-454:38
    Name pattern: [gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::sub]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Sub<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::sub"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithSubShared0FpFp.sub
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Mul<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::mul]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 470:4-470:38
    Name pattern: [gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::mul]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Mul<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::mul"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithMulShared0FpFp.mul
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{core::ops::arith::Div<&0 (gf2_core::gfp::Fp<P>), gf2_core::gfp::Fp<P>> for gf2_core::gfp::Fp<P>}::div]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 486:4-486:38
    Name pattern: [gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::div]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{core::ops::arith::Div<gf2_core::gfp::Fp<@P>, &'0 gf2_core::gfp::Fp<@P>, gf2_core::gfp::Fp<@P>>}::div"]
axiom gf2_core.gfp.Fp.Insts.CoreOpsArithDivShared0FpFp.div
  {P : Std.U64} :
  gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::max_unreduced_additions]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 672:4-672:41
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::max_unreduced_additions]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::max_unreduced_additions"]
axiom
  gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.max_unreduced_additions
  (P : Std.U64) : Result Std.Usize

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::reduce_wide]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 634:4-634:39
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::reduce_wide]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::reduce_wide"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.reduce_wide
  (P : Std.U64) : Std.U128 → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::mul_to_wide]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 604:4-604:45
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::mul_to_wide]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::mul_to_wide"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.mul_to_wide
  {P : Std.U64} : gf2_core.gfp.Fp P → gf2_core.gfp.Fp P → Result Std.U128

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::to_wide]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 599:4-599:29
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::to_wide]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::to_wide"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.to_wide
  {P : Std.U64} : gf2_core.gfp.Fp P → Result Std.U128

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::one_like]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 575:4-575:30
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::one_like]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::one_like"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.one_like
  {P : Std.U64} : gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::zero_like]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 570:4-570:31
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::zero_like]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::zero_like"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.zero_like
  {P : Std.U64} : gf2_core.gfp.Fp P → Result (gf2_core.gfp.Fp P)

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::inv]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 544:4-544:33
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::inv]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::inv"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.inv
  {P : Std.U64} : gf2_core.gfp.Fp P → Result (Option (gf2_core.gfp.Fp P))

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::is_one]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 531:4-531:28
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::is_one]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::is_one"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_one
  {P : Std.U64} : gf2_core.gfp.Fp P → Result Bool

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::is_zero]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 526:4-526:29
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::is_zero]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::is_zero"]
axiom gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.is_zero
  {P : Std.U64} : gf2_core.gfp.Fp P → Result Bool

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::extension_degree]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 521:4-521:39
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::extension_degree]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::extension_degree"]
axiom
  gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.extension_degree
  {P : Std.U64} : gf2_core.gfp.Fp P → Result Std.Usize

/-- [gf2_core::gfp::{gf2_core::field::traits::FiniteField<u64, u128> for gf2_core::gfp::Fp<P>}::characteristic]:
    Source: 'crates/gf2-core/src/gfp/mod.rs', lines 516:4-516:35
    Name pattern: [gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::characteristic]
    Visibility: public -/
@[rust_fun
  "gf2_core::gfp::{gf2_core::field::traits::FiniteField<gf2_core::gfp::Fp<@P>, u64, u128>}::characteristic"]
axiom
  gf2_core.gfp.Fp.Insts.Gf2_coreFieldTraitsFiniteFieldU64U128.characteristic
  {P : Std.U64} : gf2_core.gfp.Fp P → Result Std.U64

