-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_algebra]: type definitions
import Aeneas
import Gf2Algebra.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace gf2_algebra

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 77:0-77:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 190:0-190:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 324:0-324:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 462:0-462:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 692:0-692:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 769:0-769:37
    Name pattern: [core::ops::arith::AddAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [gf2_core::field::traits::FiniteField]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 44:0-61:33
    Name pattern: [gf2_core::field::traits::FiniteField]
    Visibility: public -/
@[rust_trait "gf2_core::field::traits::FiniteField"
  (parentClauses := ["corecloneCloneInst", "corecmpPartialEqInst", "corecmpEqInst", "corehashHashInst", "corefmtDebugInst", "coreopsarithAddInst", "coreopsarithAddSelfSharedSelfSelfInst", "coreopsarithSubInst", "coreopsarithSubSelfSharedSelfSelfInst", "coreopsarithMulInst", "coreopsarithMulSelfSharedSelfSelfInst", "coreopsarithDivInst", "coreopsarithDivSelfSharedSelfSelfInst", "coreopsarithNegInst", "coreopsarithAddAssignInst", "coreopsarithAddAssignSelfSharedSelfInst", "corecloneCloneInst", "corefmtDebugInst", "corecmpPartialEqInst", "corecmpEqInst", "corecloneCloneInst", "coreopsarithAddInst", "coreopsarithAddAssignInst"])
  (consts := ["WINOGRAD_THRESHOLD", "TRI_BASE_THRESHOLD", "PLE_BASE_COLS", "PLE_PANEL_COLS"])]
structure gf2_core.field.traits.FiniteField (Self : Type) (Self_Characteristic
  : Type) (Self_Wide : Type) where
  WINOGRAD_THRESHOLD : Result Std.Usize
  TRI_BASE_THRESHOLD : Result Std.Usize
  PLE_BASE_COLS : Result Std.Usize
  PLE_PANEL_COLS : Result Std.Usize
  corecloneCloneInst : core.clone.Clone Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corecmpEqInst : core.cmp.Eq Self
  corehashHashInst : core.hash.Hash Self
  corefmtDebugInst : core.fmt.Debug Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  coreopsarithAddSelfSharedSelfSelfInst : core.ops.arith.Add Self Self Self
  coreopsarithSubInst : core.ops.arith.Sub Self Self Self
  coreopsarithSubSelfSharedSelfSelfInst : core.ops.arith.Sub Self Self Self
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  coreopsarithMulSelfSharedSelfSelfInst : core.ops.arith.Mul Self Self Self
  coreopsarithDivInst : core.ops.arith.Div Self Self Self
  coreopsarithDivSelfSharedSelfSelfInst : core.ops.arith.Div Self Self Self
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self Self
  coreopsarithAddAssignSelfSharedSelfInst : core.ops.arith.AddAssign Self Self
  corecloneCloneCharacteristicInst : core.clone.Clone Self_Characteristic
  corefmtDebugCharacteristicInst : core.fmt.Debug Self_Characteristic
  corecmpPartialEqCharacteristicInst : core.cmp.PartialEq Self_Characteristic
    Self_Characteristic
  corecmpEqCharacteristicInst : core.cmp.Eq Self_Characteristic
  corecloneCloneWideInst : core.clone.Clone Self_Wide
  coreopsarithAddWideInst : core.ops.arith.Add Self_Wide Self_Wide Self_Wide
  coreopsarithAddAssignWideInst : core.ops.arith.AddAssign Self_Wide Self_Wide
  characteristic : Self → Result Self_Characteristic
  extension_degree : Self → Result Std.Usize
  is_zero : Self → Result Bool
  is_one : Self → Result Bool
  inv : Self → Result (Option Self)
  zero_like : Self → Result Self
  one_like : Self → Result Self
  to_wide : Self → Result Self_Wide
  mul_to_wide : Self → Self → Result Self_Wide
  reduce_wide : Self_Wide → Result Self
  max_unreduced_additions : Result Std.Usize

/-- [gf2_algebra::gray::gray_code_iter::closure]
    Source: 'crates/gf2-algebra/src/gray.rs', lines 139:23-148:5 -/
@[reducible]
def gray.gray_code_iter.closure := Unit

/-- [gf2_algebra::packed::bipedal3::Bipedal3]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 85:0-88:1
    Visibility: public -/
structure packed.bipedal3.Bipedal3 where
  mag : Std.U64
  sgn : Std.U64

/-- [gf2_algebra::packed::bipedal3::{impl core::fmt::Debug for gf2_algebra::packed::bipedal3::Bipedal3}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 164:52-174:17 -/
@[reducible]
def packed.bipedal3.DebugBipedal3.fmt.closure := packed.bipedal3.Bipedal3

/-- Trait declaration: [gf2_algebra::packed::PackedField]
    Source: 'crates/gf2-algebra/src/packed/mod.rs', lines 88:0-324:1
    Visibility: public -/
structure packed.PackedField (Self : Type) (F : Type)
  (Self_Clause3_Characteristic : Type) (Self_Clause3_Wide : Type) where
  LANES : Result Std.Usize
  coremarkerCopyInst : core.marker.Copy Self
  corecmpEqInst : core.cmp.Eq Self
  corefmtDebugInst : core.fmt.Debug Self
  gf2_corefieldtraitsFiniteFieldInst : gf2_core.field.traits.FiniteField F
    Self_Clause3_Characteristic Self_Clause3_Wide
  zero : Result Self
  one : Result Self
  splat : F → Result Self
  add : Self → Self → Result Self
  sub : Self → Self → Result Self
  neg : Self → Result Self
  mul : Self → Self → Result Self
  lane : Self → Std.Usize → Result F
  with_lane : Self → Std.Usize → F → Result Self
  all_zero : Self → Result Bool

/-- [gf2_algebra::packed::bipedal3::Bipedal3Vec]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 1506:0-1510:1
    Visibility: public -/
structure packed.bipedal3.Bipedal3Vec where
  mag : alloc.vec.Vec Std.U64
  sgn : alloc.vec.Vec Std.U64
  len_lanes : Std.Usize

/-- [gf2_algebra::packed::bipedal3::{impl core::fmt::Debug for gf2_algebra::packed::bipedal3::Bipedal3Vec}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 1792:17-1804:13 -/
@[reducible]
def packed.bipedal3.DebugBipedal3Vec.fmt.closure := packed.bipedal3.Bipedal3Vec

/-- Trait declaration: [gf2_algebra::packed::PackedFieldVec]
    Source: 'crates/gf2-algebra/src/packed/mod.rs', lines 374:0-602:1
    Visibility: public -/
structure packed.PackedFieldVec (Self : Type) (F : Type) (Self_Element : Type)
  (Self_Clause3_Characteristic : Type) (Self_Clause3_Wide : Type)
  (Self_Clause4_Clause3_Characteristic : Type) (Self_Clause4_Clause3_Wide :
  Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecmpEqInst : core.cmp.Eq Self
  corefmtDebugInst : core.fmt.Debug Self
  gf2_corefieldtraitsFiniteFieldInst : gf2_core.field.traits.FiniteField F
    Self_Clause3_Characteristic Self_Clause3_Wide
  PackedFieldInst : packed.PackedField Self_Element F
    Self_Clause4_Clause3_Characteristic Self_Clause4_Clause3_Wide
  zeros : Std.Usize → Result Self
  from_field_slice : Slice F → Result Self
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool
  get : Self → Std.Usize → Result F
  add_assign : Self → Self → Result Self
  sub_assign : Self → Self → Result Self
  mul_assign : Self → Self → Result Self
  all_zero : Self → Result Bool

/-- [gf2_algebra::packed::bipedal3::{impl gf2_algebra::packed::PackedFieldVec<gf2_core::gfp::Fp<3 : u64>, gf2_algebra::packed::bipedal3::Bipedal3, u64, u128, u64, u128> for gf2_algebra::packed::bipedal3::Bipedal3Vec}::all_zero::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 2124:28-2124:39 -/
@[reducible]
def packed.bipedal3.PackedFieldVecBipedal3VecFp3Bipedal3U64U128U64U128.all_zero.closure
  :=
Unit

/-- [gf2_algebra::packed::bipedal3::Bipedal3Matrix]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 2874:0-2879:1
    Visibility: public -/
structure packed.bipedal3.Bipedal3Matrix where
  columns : alloc.vec.Vec packed.bipedal3.Bipedal3Vec
  rows : Std.Usize
  cols : Std.Usize

/-- [gf2_algebra::packed::bipedal3::{impl core::fmt::Debug for gf2_algebra::packed::bipedal3::Bipedal3Matrix}::fmt::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 2942:25-2942:59 -/
def packed.bipedal3.DebugBipedal3Matrix.fmt.closure.closure :=
  packed.bipedal3.Bipedal3Matrix × Std.Usize

/-- [gf2_algebra::packed::bipedal3::{impl core::fmt::Debug for gf2_algebra::packed::bipedal3::Bipedal3Matrix}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 2940:17-2944:13 -/
@[reducible]
def packed.bipedal3.DebugBipedal3Matrix.fmt.closure :=
  packed.bipedal3.Bipedal3Matrix

/-- [gf2_algebra::packed::bipedal3::{gf2_algebra::packed::bipedal3::Bipedal3Matrix}::from_row_major::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 3012:57-3012:79 -/
def packed.bipedal3.Bipedal3Matrix.from_row_major.closure.closure :=
  Slice (gf2_core.gfp.Fp 3#u64) × Std.Usize × Std.Usize

/-- [gf2_algebra::packed::bipedal3::{gf2_algebra::packed::bipedal3::Bipedal3Matrix}::from_row_major::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 3011:17-3014:13 -/
def packed.bipedal3.Bipedal3Matrix.from_row_major.closure :=
  Std.Usize × Slice (gf2_core.gfp.Fp 3#u64) × Std.Usize

/-- [gf2_algebra::packed::bipedal3::{gf2_algebra::packed::bipedal3::Bipedal3Matrix}::row::closure]
    Source: 'crates/gf2-algebra/src/packed/bipedal3.rs', lines 3187:54-3187:80 -/
def packed.bipedal3.Bipedal3Matrix.row.closure :=
  packed.bipedal3.Bipedal3Matrix × Std.Usize

/-- [gf2_algebra::packed::packed5::Packed5]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 208:0-212:1
    Visibility: public -/
structure packed.packed5.Packed5 where
  b0 : Std.U64
  b1 : Std.U64
  b2 : Std.U64

/-- [gf2_algebra::packed::packed5::{impl core::fmt::Debug for gf2_algebra::packed::packed5::Packed5}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 305:55-305:79 -/
@[reducible]
def packed.packed5.DebugPacked5.fmt.closure := packed.packed5.Packed5

/-- [gf2_algebra::packed::packed5::Packed5Vec]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 788:0-793:1
    Visibility: public -/
structure packed.packed5.Packed5Vec where
  b0 : alloc.vec.Vec Std.U64
  b1 : alloc.vec.Vec Std.U64
  b2 : alloc.vec.Vec Std.U64
  len_lanes : Std.Usize

/-- [gf2_algebra::packed::packed5::{impl core::fmt::Debug for gf2_algebra::packed::packed5::Packed5Vec}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 959:54-959:77 -/
@[reducible]
def packed.packed5.DebugPacked5Vec.fmt.closure := packed.packed5.Packed5Vec

/-- [gf2_algebra::packed::packed5::{impl gf2_algebra::packed::PackedFieldVec<gf2_core::gfp::Fp<5 : u64>, gf2_algebra::packed::packed5::Packed5, u64, u128, u64, u128> for gf2_algebra::packed::packed5::Packed5Vec}::all_zero::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1278:17-1281:13 -/
@[reducible]
def packed.packed5.PackedFieldVecPacked5VecFp5Packed5U64U128U64U128.all_zero.closure
  :=
Unit

/-- [gf2_algebra::packed::packed5::Packed5Matrix]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1399:0-1404:1
    Visibility: public -/
structure packed.packed5.Packed5Matrix where
  columns : alloc.vec.Vec packed.packed5.Packed5Vec
  rows : Std.Usize
  cols : Std.Usize

/-- [gf2_algebra::packed::packed5::{impl core::fmt::Debug for gf2_algebra::packed::packed5::Packed5Matrix}::fmt::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1428:25-1428:59 -/
def packed.packed5.DebugPacked5Matrix.fmt.closure.closure :=
  packed.packed5.Packed5Matrix × Std.Usize

/-- [gf2_algebra::packed::packed5::{impl core::fmt::Debug for gf2_algebra::packed::packed5::Packed5Matrix}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1426:17-1430:13 -/
@[reducible]
def packed.packed5.DebugPacked5Matrix.fmt.closure :=
  packed.packed5.Packed5Matrix

/-- [gf2_algebra::packed::packed5::{gf2_algebra::packed::packed5::Packed5Matrix}::from_row_major::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1495:57-1495:79 -/
def packed.packed5.Packed5Matrix.from_row_major.closure.closure :=
  Slice (gf2_core.gfp.Fp 5#u64) × Std.Usize × Std.Usize

/-- [gf2_algebra::packed::packed5::{gf2_algebra::packed::packed5::Packed5Matrix}::from_row_major::closure]
    Source: 'crates/gf2-algebra/src/packed/packed5.rs', lines 1494:17-1497:13 -/
def packed.packed5.Packed5Matrix.from_row_major.closure :=
  Std.Usize × Slice (gf2_core.gfp.Fp 5#u64) × Std.Usize

/-- [gf2_algebra::packed::packed7::Packed7]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 211:0-213:1
    Visibility: public -/
structure packed.packed7.Packed7 where
  w : Std.U64

/-- [gf2_algebra::packed::packed7::{gf2_algebra::packed::packed7::Packed7}::to_array::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 302:29-302:45 -/
@[reducible]
def packed.packed7.Packed7.to_array.closure := packed.packed7.Packed7

/-- [gf2_algebra::packed::packed7::Packed7Vec]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 866:0-869:1
    Visibility: public -/
structure packed.packed7.Packed7Vec where
  words : alloc.vec.Vec Std.U64
  len_lanes : Std.Usize

/-- [gf2_algebra::packed::packed7::{impl core::fmt::Debug for gf2_algebra::packed::packed7::Packed7Vec}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1042:17-1046:13 -/
@[reducible]
def packed.packed7.DebugPacked7Vec.fmt.closure := packed.packed7.Packed7Vec

/-- [gf2_algebra::packed::packed7::{impl gf2_algebra::packed::PackedFieldVec<gf2_core::gfp::Fp<7 : u64>, gf2_algebra::packed::packed7::Packed7, u64, u128, u64, u128> for gf2_algebra::packed::packed7::Packed7Vec}::all_zero::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1294:30-1294:41 -/
@[reducible]
def packed.packed7.PackedFieldVecPacked7VecFp7Packed7U64U128U64U128.all_zero.closure
  :=
Unit

/-- [gf2_algebra::packed::packed7::Packed7Matrix]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1345:0-1350:1
    Visibility: public -/
structure packed.packed7.Packed7Matrix where
  columns : alloc.vec.Vec packed.packed7.Packed7Vec
  rows : Std.Usize
  cols : Std.Usize

/-- [gf2_algebra::packed::packed7::{impl core::fmt::Debug for gf2_algebra::packed::packed7::Packed7Matrix}::fmt::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1399:25-1399:59 -/
def packed.packed7.DebugPacked7Matrix.fmt.closure.closure :=
  packed.packed7.Packed7Matrix × Std.Usize

/-- [gf2_algebra::packed::packed7::{impl core::fmt::Debug for gf2_algebra::packed::packed7::Packed7Matrix}::fmt::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1397:17-1401:13 -/
@[reducible]
def packed.packed7.DebugPacked7Matrix.fmt.closure :=
  packed.packed7.Packed7Matrix

/-- [gf2_algebra::packed::packed7::{gf2_algebra::packed::packed7::Packed7Matrix}::from_row_major::closure::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1459:57-1459:79 -/
def packed.packed7.Packed7Matrix.from_row_major.closure.closure :=
  Slice (gf2_core.gfp.Fp 7#u64) × Std.Usize × Std.Usize

/-- [gf2_algebra::packed::packed7::{gf2_algebra::packed::packed7::Packed7Matrix}::from_row_major::closure]
    Source: 'crates/gf2-algebra/src/packed/packed7.rs', lines 1458:17-1461:13 -/
def packed.packed7.Packed7Matrix.from_row_major.closure :=
  Std.Usize × Slice (gf2_core.gfp.Fp 7#u64) × Std.Usize

end gf2_algebra
