-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: function definitions
import Aeneas
import R7Gf2Core.Types
import R7Gf2Core.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace gf2_core

/-- [gf2_core::field::batch_ops::batch_inverse_core]:
    Source: 'crates/gf2-core/src/field/batch_ops.rs', lines 363:0-403:1 -/
def field.batch_ops.batch_inverse_core
  {F : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (traitsFiniteFieldInst : field.traits.FiniteField F Clause0_Characteristic
  Clause0_Wide) (working : Slice F) (scratch : Slice F)
  (_mode : field.batch_ops.InPlaceMode) :
  Result ((Option Unit) × (Slice F) × (Slice F))
  := do
  sorry

/-- [gf2_core::field::batch_ops::batch_inverse_with_scratch]:
    Source: 'crates/gf2-core/src/field/batch_ops.rs', lines 210:0-230:1
    Visibility: public -/
def field.batch_ops.batch_inverse_with_scratch
  {F : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (traitsFiniteFieldInst : field.traits.FiniteField F Clause0_Characteristic
  Clause0_Wide) (elements : Slice F) (output : Slice F) (scratch : Slice F) :
  Result ((Option Unit) × (Slice F) × (Slice F))
  := do
  sorry

/-- [gf2_core::field::batch_ops::batch_inverse]:
    Source: 'crates/gf2-core/src/field/batch_ops.rs', lines 115:0-126:1
    Visibility: public -/
def field.batch_ops.batch_inverse
  {F : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (traitsFiniteFieldInst : field.traits.FiniteField F Clause0_Characteristic
  Clause0_Wide) (elements : Slice F) :
  Result (Option (alloc.vec.Vec F))
  := do
  let b ← core.slice.Slice.is_empty elements
  if b
  then ok (some (alloc.vec.Vec.new F))
  else
    let output ←
      alloc.slice.Slice.to_vec traitsFiniteFieldInst.corecloneCloneInst
        elements
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut output)
    let (s1, _) ← lift (alloc.vec.Vec.deref_mut output)
    let (o, s2, _) ←
      field.batch_ops.batch_inverse_with_scratch traitsFiniteFieldInst elements
        s s1
    let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      let output1 := deref_mut_back s2
      ok (some output1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        (alloc.vec.Vec F) residual

/-- [gf2_core::field::matrix::BasisReducer::push_col_with_pivot_row]:
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 73:4-76:5
    Visibility: public -/
@[trait_default]
def field.matrix.BasisReducer.push_col_with_pivot_row.default
  {Self : Type} {F : Type} {Clause0_Clause1_Characteristic : Type}
  {Clause0_Clause1_Wide : Type} (BasisReducerInst : field.matrix.BasisReducer
  Self F Clause0_Clause1_Characteristic Clause0_Clause1_Wide) (self : Self)
  (col : Slice F) (pivot_row : Std.Usize) :
  Result Self
  := do
  BasisReducerInst.push_col self col

/-- [gf2_core::field::matrix::BasisReducer::is_empty]:
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 91:4-93:5
    Visibility: public -/
@[trait_default]
def field.matrix.BasisReducer.is_empty.default
  {Self : Type} {F : Type} {Clause0_Clause1_Characteristic : Type}
  {Clause0_Clause1_Wide : Type} (BasisReducerInst : field.matrix.BasisReducer
  Self F Clause0_Clause1_Characteristic Clause0_Clause1_Wide) (self : Self) :
  Result Bool
  := do
  let i ← BasisReducerInst.len self
  ok (i = 0#usize)

/-- [gf2_core::field::matrix::ChainPolyArith::is_empty]:
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 178:4-180:5
    Visibility: public -/
@[trait_default]
def field.matrix.ChainPolyArith.is_empty.default
  {Self : Type} {F : Type} {Clause0_Clause1_Characteristic : Type}
  {Clause0_Clause1_Wide : Type} (ChainPolyArithInst :
  field.matrix.ChainPolyArith Self F Clause0_Clause1_Characteristic
  Clause0_Clause1_Wide) (self : Self) :
  Result Bool
  := do
  let i ← ChainPolyArithInst.len self
  ok (i = 0#usize)

/-- [gf2_core::field::traits::FiniteField::zero_hint]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 147:4-149:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.zero_hint.default
  (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type) :
  Result (Option Self)
  := do
  ok none

/-- [gf2_core::field::traits::FiniteField::cardinality_log2_hint]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 180:4-182:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.cardinality_log2_hint.default
  (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type) :
  Result (Option Std.U32)
  := do
  ok none

/-- [gf2_core::field::traits::FiniteField::mul_product_sum_wide]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 270:4-272:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.mul_product_sum_wide.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) (self : Self) (rhs : Self) :
  Result Clause0_Wide
  := do
  FiniteFieldInst.mul_to_wide self rhs

/-- [gf2_core::field::traits::FiniteField::reduce_product_sum_wide]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 320:4-322:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.reduce_product_sum_wide.default
  {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide : Type}
  (FiniteFieldInst : field.traits.FiniteField Self Clause0_Characteristic
  Clause0_Wide) (wide : Clause0_Wide) :
  Result Self
  := do
  FiniteFieldInst.reduce_wide wide

/-- [gf2_core::field::traits::FiniteField::try_gf2m_u64_batch_dot_product]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 339:4-349:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_gf2m_u64_batch_dot_product.default
  {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (a : Slice Self) (b : Slice Self) (zero : Self)
  (scratch_a : alloc.vec.Vec Std.U64) (scratch_b : alloc.vec.Vec Std.U64)
  (scratch_products : alloc.vec.Vec Std.U64) :
  Result ((Option Self) × (alloc.vec.Vec Std.U64) × (alloc.vec.Vec Std.U64) ×
    (alloc.vec.Vec Std.U64))
  := do
  ok (none, scratch_a, scratch_b, scratch_products)

/-- [gf2_core::field::traits::FiniteField::try_fp_simd_dot_product]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 372:4-380:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_fp_simd_dot_product.default
  {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (a : Slice Self) (b : Slice Self) (scratch_a : alloc.vec.Vec Std.U16)
  (scratch_b : alloc.vec.Vec Std.U16) :
  Result ((Option Self) × (alloc.vec.Vec Std.U16) × (alloc.vec.Vec Std.U16))
  := do
  ok (none, scratch_a, scratch_b)

/-- [gf2_core::field::traits::FiniteField::try_pack_fp_medium_u16]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 396:4-399:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_pack_fp_medium_u16.default
  {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (xs : Slice Self) (out : alloc.vec.Vec Std.U16) :
  Result ((Option Unit) × (alloc.vec.Vec Std.U16))
  := do
  ok (none, out)

/-- [gf2_core::field::traits::FiniteField::try_fp_simd_dot_packed_u16]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 411:4-414:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_fp_simd_dot_packed_u16.default
  (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (a_packed : Slice Std.U16) (b_packed : Slice Std.U16) :
  Result (Option Self)
  := do
  ok none

/-- [gf2_core::field::traits::FiniteField::try_simd_dot_product]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 444:4-447:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_simd_dot_product.default
  {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (a : Slice Self) (b : Slice Self) :
  Result (Option Self)
  := do
  ok none

/-- [gf2_core::field::traits::FiniteField::try_simd_gemm_classical]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 474:4-484:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_simd_gemm_classical.default
  {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (a : Slice Self) (b_t : Slice Self) (m : Std.Usize) (k : Std.Usize)
  (n : Std.Usize) (out : Slice Self) :
  Result (Bool × (Slice Self))
  := do
  ok (false, out)

/-- [gf2_core::field::traits::FiniteField::has_simd_gemm_classical]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 510:4-512:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.has_simd_gemm_classical.default
  (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type) :
  Result Bool
  := do
  ok false

/-- [gf2_core::field::traits::FiniteField::try_make_basis_reducer]:
    Source: 'crates/gf2-core/src/field/traits.rs', lines 536:4-541:5
    Visibility: public -/
@[trait_default]
def field.traits.FiniteField.try_make_basis_reducer.default
  (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type)
  (n : Std.Usize) :
  Result (Option 
    /-- [gf2_core::field::traits::FiniteField::try_make_chain_poly_arith]:
        Source: 'crates/gf2-core/src/field/traits.rs', lines 556:4-561:5
        Visibility: public -/
    @[trait_default]
    def field.traits.FiniteField.try_make_chain_poly_arith.default
      (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type)
      (n : Std.Usize) :
      Result (Option 
        /-- [gf2_core::field::traits::FiniteField::chain_poly_arith_available]:
            Source: 'crates/gf2-core/src/field/traits.rs', lines 573:4-575:5
            Visibility: public -/
        @[trait_default]
        def field.traits.FiniteField.chain_poly_arith_available.default
          (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type) :
          Result Bool
          := do
          ok false
        /-- [gf2_core::field::traits::FiniteField::try_simd_axpy]:
            Source: 'crates/gf2-core/src/field/traits.rs', lines 594:4-597:5
            Visibility: public -/
        @[trait_default]
        def field.traits.FiniteField.try_simd_axpy.default
          {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
          (y : Slice Self) (a : Self) (x : Slice Self) :
          Result (Bool × (Slice Self))
          := do
          ok (false, y)
        /-- [gf2_core::field::traits::FiniteField::try_prepack_matvec]:
            Source: 'crates/gf2-core/src/field/traits.rs', lines 614:4-621:5
            Visibility: public -/
        @[trait_default]
        def field.traits.FiniteField.try_prepack_matvec.default
          {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide : Type)
          (a : Slice Self) (m : Std.Usize) (k : Std.Usize) :
          Result (Option 
            /-- [gf2_core::field::traits::FiniteField::try_simd_matvec]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 651:4-654:5
                Visibility: public -/
            @[trait_default]
            def field.traits.FiniteField.try_simd_matvec.default
              {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide :
              Type) (a : Slice Self) (x : Slice Self) (m : Std.Usize)
              (k : Std.Usize) (out : Slice Self) :
              Result (Bool × (Slice Self))
              := do
              ok (false, out)
            /-- [gf2_core::field::traits::FiniteField::try_simd_spmm]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 683:4-694:5
                Visibility: public -/
            @[trait_default]
            def field.traits.FiniteField.try_simd_spmm.default
              {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide :
              Type) (a_row_ptr : Slice Std.Usize) (a_col_idx : Slice Std.Usize)
              (a_values : Slice Self) (b : Slice Self) (b_rows : Std.Usize)
              (n : Std.Usize) (out : Slice Self) :
              Result (Bool × (Slice Self))
              := do
              ok (false, out)
            /-- [gf2_core::field::traits::FiniteField::try_extension_wiedemann_minpoly]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 722:4-727:5
                Visibility: public -/
            @[trait_default]
            def
              field.traits.FiniteField.try_extension_wiedemann_minpoly.default
              {Self : Type} {Clause0_Characteristic : Type} {Clause0_Wide :
              Type} (FiniteFieldInst : field.traits.FiniteField Self
              Clause0_Characteristic Clause0_Wide)
              (a : field.matrix.FieldMatrix Self Clause0_Characteristic
              Clause0_Wide) :
              Result (Option (field.poly.FieldPoly Self Clause0_Characteristic
                Clause0_Wide))
              := do
              ok none
            /-- [gf2_core::field::traits::FiniteField::theorem_4_operand_bound]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 803:4-805:5
                Visibility: public -/
            @[trait_default]
            def field.traits.FiniteField.theorem_4_operand_bound.default
              (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide :
              Type) :
              Result Std.U128
              := do
              ok core.num.U128.MAX
            /-- [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
                Source: 'crates/gf2-core/src/field/traits.rs', lines 825:4-825:42
                Visibility: public -/
            @[global_simps, irreducible, trait_default]
            def field.traits.FiniteField.WINOGRAD_THRESHOLD.default (Self :
              Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type)
              : Std.Usize :=
              128#usize
            /-- [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
                Source: 'crates/gf2-core/src/field/traits.rs', lines 858:4-858:40
                Visibility: public -/
            @[global_simps, irreducible, trait_default]
            def field.traits.FiniteField.TRI_BASE_THRESHOLD.default (Self :
              Type) (Clause0_Characteristic : Type) (Clause0_Wide : Type)
              : Std.Usize :=
              8#usize
            /-- [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
                Source: 'crates/gf2-core/src/field/traits.rs', lines 892:4-892:35
                Visibility: public -/
            @[global_simps, irreducible, trait_default]
            def field.traits.FiniteField.PLE_BASE_COLS.default (Self : Type)
              (Clause0_Characteristic : Type) (Clause0_Wide : Type)
              : Std.Usize :=
              1#usize
            /-- [gf2_core::field::traits::FiniteField::PLE_PANEL_COLS]
                Source: 'crates/gf2-core/src/field/traits.rs', lines 926:4-926:54
                Visibility: public -/
            @[global_simps, irreducible, trait_default]
            def field.traits.FiniteField.PLE_PANEL_COLS.default {Self : Type}
              {Clause0_Characteristic : Type} {Clause0_Wide : Type}
              (FiniteFieldInst : field.traits.FiniteField Self
              Clause0_Characteristic Clause0_Wide) : Result Std.Usize :=
              FiniteFieldInst.PLE_BASE_COLS
            /-- [gf2_core::field::traits::FiniteField::try_simd_ple_panel_base]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 961:4-972:5
                Visibility: public -/
            @[trait_default]
            def field.traits.FiniteField.try_simd_ple_panel_base.default
              {Self : Type} (Clause0_Characteristic : Type) (Clause0_Wide :
              Type) (matrix : Slice Self) (parent_cols : Std.Usize)
              (m : Std.Usize) (col_lo : Std.Usize) (col_hi : Std.Usize)
              (perm : Slice Std.Usize) (pivot_cols : alloc.vec.Vec Std.Usize) :
              Result ((Option Std.Usize) × (Slice Self) × (Slice Std.Usize) ×
                (alloc.vec.Vec Std.Usize))
              := do
              ok (none, matrix, perm, pivot_cols)
            /-- [gf2_core::field::traits::FiniteField::has_simd_ple_panel_base]:
                Source: 'crates/gf2-core/src/field/traits.rs', lines 986:4-988:5
                Visibility: public -/
            @[trait_default]
            def field.traits.FiniteField.has_simd_ple_panel_base.default
              (Self : Type) (Clause0_Characteristic : Type) (Clause0_Wide :
              Type) :
              Result Bool
              := do
              ok false
end gf2_core
