-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [gf2_core::field::poly::FieldPoly]
    Source: 'crates/gf2-core/src/field/poly.rs', lines 467:0-469:1
    Visibility: public -/
axiom field.poly.FieldPoly (F : Type) (Clause0_Characteristic : Type)
  (Clause0_Wide : Type) : Type

/-- [gf2_core::field::matrix::FieldMatrix]
    Source: 'crates/gf2-core/src/field/matrix.rs', lines 302:0-306:1
    Visibility: public -/
axiom field.matrix.FieldMatrix (F : Type) (Clause0_Characteristic : Type)
  (Clause0_Wide : Type) : Type

