#!/usr/bin/env python3
"""Render the external dispatch row from the committed ISA-L qualification."""

import hashlib
import json
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[4]
STORY = pathlib.Path("dev/active/2037941f-profile-and-optimize-mid-range-buffer-operations")
VALIDATION = STORY / "survey/logical-harness-validation.txt"
PROBE = STORY / "isal-probe-record.txt"
COMPARATOR = STORY / "isal-comparator.md"
ADDENDUM = STORY / "logical-buffer-addendum.md"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: render-isal-availability.py OUTPUT")
    validation = (ROOT / VALIDATION).read_bytes()
    probe = (ROOT / PROBE).read_bytes()
    comparator = (ROOT / COMPARATOR).read_bytes()
    addendum = (ROOT / ADDENDUM).read_bytes()
    records = [
        json.loads(line[2:])
        for line in validation.decode().splitlines()
        if line.startswith("# {") and '"library":"isa-l"' in line
    ]
    if len(records) != 1 or b"nasm=absent; public dispatched xor_gen is unavailable" not in probe:
        raise ValueError("ISA-L qualification does not establish dispatch unavailability")
    record = records[0]
    if (
        record["qualified_label"] != "xor_gen_base/scalar"
        or record["runtime_dispatch"]
        or record["public_xor_gen_available"]
        or record["unavailable_row"] != "isal-dispatched-xor-gen"
    ):
        raise ValueError("ISA-L qualification changed its dispatch contract")
    alignment = re.search(
        rb"The ISA-L header requires [0-9]+-byte-aligned source\s+"
        rb"and destination pointers for this XOR interface\.",
        comparator,
    )
    if not alignment or (
        b"an unaligned ISA-L call is outside its qualified interface and is recorded as\n"
        b"inapplicable rather than attempted."
    ) not in addendum:
        raise ValueError("ISA-L offset inapplicability lacks the qualified contract")
    alignment_reason = " ".join(alignment.group().decode().split())
    output = pathlib.Path(sys.argv[1])
    output.write_text(
        "# ISA-L comparator availability\n\n"
        "> **Diátaxis Type:** Reference\n\n"
        "Generated by `survey/render-isal-availability.py` from the committed "
        "qualification records. These cases have no runner workload.\n\n"
        f"Source: `{VALIDATION}` (SHA-256 `{hashlib.sha256(validation).hexdigest()}`); "
        f"`{PROBE}` (SHA-256 `{hashlib.sha256(probe).hexdigest()}`); "
        f"`{COMPARATOR}` (SHA-256 `{hashlib.sha256(comparator).hexdigest()}`); "
        f"`{ADDENDUM}` (SHA-256 `{hashlib.sha256(addendum).hexdigest()}`).\n\n"
        "| Route | Status | Samples | Reason |\n"
        "|---|---|---:|---|\n"
        f"| `{record['unavailable_row']}` | unavailable | 0 | "
        f"{record['unavailable_reason']} |\n"
        f"| `{record['qualified_label']}` offset pointers | inapplicable | 0 | "
        f"{alignment_reason} Unaligned ISA-L calls are outside this qualified interface. |\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
