//! The BCH construction model: independent inputs, one validating pipeline.
//!
//! A BCH code over a base field $B = \mathrm{GF}(q)$ is the cyclic ideal
//! generated by the monic polynomial $g(x) \in B[x]$ whose roots are the
//! powers $\beta^i$ named by a closed defining set, where $\beta$ lies in a
//! splitting field $E$ and has exact multiplicative order $n$. A
//! [`BchSpec`] carries only the *independent* inputs of such a code; every
//! dependent quantity — the generator, the dimension $k$, the defining set,
//! the distance bound and the correction radius — is derived exactly once by
//! [`BchCode::construct`], which is the only construction path.
//!
//! # Coordinate convention
//!
//! Coordinate $i$ of a codeword is the coefficient of $x^i$, so a codeword is
//! the coefficient vector of a multiple of $g$ modulo $x^n - 1$ in ascending
//! degree order. A systematic user layout is a separate coordinate map applied
//! above this convention; it never changes the polynomial the construction
//! derives.
//!
//! # Pipeline
//!
//! Every spec enters the same four stages.
//!
//! 1. **Validate and normalize.** Derive the length, decide coprimality and
//!    divisibility, obtain the order-$n$ root, range-check the caller's
//!    exponent and designed distance, and expand the request into an unclosed
//!    seed sequence.
//! 2. **Close.** Take the $q$-cyclotomic closure of the seeds modulo $n$; its
//!    sorted union is the defining set.
//! 3. **Generate.** Take one representative per coset, form its monic minimal
//!    polynomial over $B$, and combine the factors with the polynomial least
//!    common multiple. Validate that the result divides $x^n - 1$.
//! 4. **Derive.** Set $k = n - \deg g$, witness the classical BCH bound from
//!    the longest cyclic run of consecutive roots, and take the correction
//!    radius that bound implies.
//!
//! # Validations
//!
//! Stage 1 performs, in order:
//!
//! - the length $n$ is representable as a `u64` and as an in-memory `usize`;
//! - $n > 0$;
//! - $\gcd(n, q) = 1$, decided as $\gcd(n, p) = 1$ for the characteristic $p$,
//!   because $q$ is a power of $p$;
//! - $n$ divides $|E^{*}|$;
//! - the order-$n$ root exists; an explicitly supplied root belongs to the
//!   splitting field named by the witness and has exact order $n$;
//! - every caller-supplied root exponent satisfies $0 \le b < n$;
//! - the designed distance satisfies $1 \le \delta \le n + 1$.
//!
//! Base/splitting-field compatibility is carried by the
//! [`FieldExtension`] witness itself: its certificate already proves the
//! relation, so construction reuses that evidence rather than re-deciding it,
//! and only checks field identity where a caller supplies a splitting-field
//! element. Coefficient restriction is likewise discharged by construction for
//! root-derived generators: every factor comes from
//! [`minimal_polynomial`], which returns a `FieldPoly<X::Base>`, so the
//! generator's coefficients lie in $B$ by type.
//!
//! Stage 3 validates $g(x) \mid x^n - 1$. Every failure in stages 1 to 3 is a
//! [`BchError`]; no invalid input panics. A panic after stage 1 denotes a
//! broken internal invariant.
//!
//! # Bound semantics
//!
//! [`BchDistanceBound`] records *why* the bound holds: the start and length of
//! the canonical longest cyclic run of consecutive exponents present in the
//! defining set, ties resolved to the least starting exponent. A run of length
//! $r$ witnesses $d_{\min} \ge r + 1$ and implies the correction radius
//! $\lfloor r/2 \rfloor$. The empty defining set records no start, $r = 0$ and
//! the vacuous bound $1$; a defining set covering every exponent records start
//! $0$, $r = n$ and the bound $n + 1$. The value is always a lower bound on
//! the minimum distance, never the minimum distance itself.
//!
//! # Complexity
//!
//! For length $n$, relative degree $r = [E:B]$ and $N = |E^{*}|$:
//! deriving the root costs the deterministic order search, $O(N)$ candidates
//! each checked with $O(\log N)$ field multiplications, plus one bounded
//! factorization of $N$; the closure costs $O(n)$ time and memory; each coset
//! contributes one minimal polynomial at $O(r^2)$ extension-field operations;
//! the least-common-multiple fold and the divisibility check are quadratic in
//! $\deg g \le n$ base-field operations; the bound witness costs $O(n)$.
//!
//! # Examples
//!
//! A binary primitive narrow-sense code over $\mathrm{GF}(2^4)$. Requesting
//! $\delta = 5$ derives $\mathrm{BCH}(15, 7)$ with a witnessed run of four
//! consecutive roots.
//!
//! ```
//! use gf2_coding::bch::spec::{BchSpec, BinaryBchCode, DesignedDistance};
//! use gf2_coding::traits::block::BlockCode;
//! use gf2_core::field::extension::BinaryPrimeExt;
//! use gf2_core::gf2m::Gf2mField;
//!
//! let extension = BinaryPrimeExt::new(Gf2mField::new(4, 0b10011))?;
//! let code = BinaryBchCode::construct(BchSpec::PrimitiveNarrowSense {
//!     extension,
//!     designed_distance: DesignedDistance::try_from(5)?,
//! })?;
//!
//! assert_eq!(code.n(), 15);
//! assert_eq!(code.k(), 7);
//! assert_eq!(BlockCode::redundancy(&code), 8);
//! assert_eq!(code.distance_bound().consecutive_root_count(), 4);
//! assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 5);
//! assert_eq!(code.correction_radius(), 2);
//! # Ok::<(), gf2_coding::bch::error::BchError>(())
//! ```
//!
//! The same construction over $\mathrm{GF}(5)$, with $\mathrm{GF}(25)$ as the
//! splitting field. The closure of the requested roots also contains
//! $\beta^5$, so the witnessed run exceeds the four roots the designed
//! distance asked for.
//!
//! ```
//! use gf2_coding::bch::spec::{BchSpec, DenseBchCode, DesignedDistance};
//! use gf2_core::field::{ConstField, FieldPoly};
//! use gf2_core::gfp::Fp;
//! use gf2_core::gfpn::QuotientField;
//!
//! // GF(25) = GF(5)[x] / (x^2 + x + 1).
//! let modulus = FieldPoly::new(vec![Fp::<5>::new(1), Fp::new(1), Fp::new(1)]);
//! let extension = QuotientField::new(Fp::<5>::zero(), modulus)?;
//! let code = DenseBchCode::construct(BchSpec::PrimitiveNarrowSense {
//!     extension,
//!     designed_distance: DesignedDistance::try_from(5)?,
//! })?;
//!
//! assert_eq!(code.n(), 24);
//! assert_eq!(code.k(), 16);
//! assert_eq!(code.distance_bound().consecutive_root_count(), 5);
//! assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 6);
//! # Ok::<(), gf2_coding::bch::error::BchError>(())
//! ```

use core::marker::PhantomData;
use core::num::NonZeroU64;

use gf2_core::field::extension::{
    canonical_generator, cyclotomic_closure, element_of_exact_order, minimal_polynomial,
    BinaryPrimeExt, CosetPartition, FieldError, FieldExtension, FieldId, FieldIdentity,
};
use gf2_core::field::matrix::FieldMatrix;
use gf2_core::field::{FieldPoly, FieldVec, FiniteField, FiniteFieldExt};
use gf2_core::{BitMatrix, BitVec};

use crate::bch::error::BchError;
use crate::error::CodeError;
use crate::traits::block::{BlockCode, SymbolMatrix, SymbolSequence};

// ---------------------------------------------------------------------------
// Semantic input types
// ---------------------------------------------------------------------------

/// A nonzero caller-supplied cyclic-code length.
///
/// The underlying `u64` participates in modular and multiplicative-order
/// arithmetic, which is the width the core order helpers use. Conversion to an
/// in-memory dimension happens once, during construction.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct BchLength(NonZeroU64);

impl BchLength {
    /// Returns the length as a `u64`.
    pub const fn get(self) -> u64 {
        self.0.get()
    }
}

impl TryFrom<u64> for BchLength {
    type Error = BchError;

    /// Converts a raw length.
    ///
    /// # Errors
    ///
    /// Returns [`BchError::InvalidLength`] when `value` is zero, because no
    /// cyclic code has length zero.
    fn try_from(value: u64) -> Result<Self, Self::Error> {
        NonZeroU64::new(value)
            .map(Self)
            .ok_or(BchError::InvalidLength { length: value })
    }
}

/// A nonzero requested classical BCH bound $\delta$.
///
/// A spec requests $\delta$ consecutive roots starting at its first root
/// exponent, which contributes $\delta - 1$ seeds. The value $\delta = 1$
/// therefore requests no roots and denotes the full-space code.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct DesignedDistance(NonZeroU64);

impl DesignedDistance {
    /// Returns the designed distance as a `u64`.
    pub const fn get(self) -> u64 {
        self.0.get()
    }
}

impl TryFrom<u64> for DesignedDistance {
    type Error = BchError;

    /// Converts a raw designed distance.
    ///
    /// # Errors
    ///
    /// Returns [`BchError::InvalidDesignedDistance`] when `value` is zero. The
    /// contextual upper bound $\delta \le n + 1$ depends on the construction's
    /// length and is decided by [`BchCode::construct`].
    fn try_from(value: u64) -> Result<Self, Self::Error> {
        NonZeroU64::new(value)
            .map(Self)
            .ok_or(BchError::InvalidDesignedDistance {
                designed_distance: value,
            })
    }
}

/// An exponent of the selected order-$n$ root, naming the element $\beta^i$.
///
/// The type cannot validate its contextual upper bound alone, so construction
/// requires $0 \le i < n$ rather than silently reducing modulo $n$.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct RootExponent(u64);

impl RootExponent {
    /// Returns the exponent as a `u64`.
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl From<u64> for RootExponent {
    /// Names the exponent without deciding its range, which only a
    /// construction's length can settle.
    fn from(value: u64) -> Self {
        Self(value)
    }
}

/// How a construction obtains the element whose exact order is the length.
///
/// The two arms name one semantic role — "the order-$n$ root of unity this
/// code is built on" — filled either by derivation or by the caller.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RootSelection<E> {
    /// Derive the reproducible element of exact multiplicative order $n$.
    Canonical,
    /// Validate this supplied element as an element of the splitting field
    /// with exact multiplicative order $n$.
    Explicit(E),
}

// ---------------------------------------------------------------------------
// The spec
// ---------------------------------------------------------------------------

/// Independent inputs for one BCH construction over `X::Base`.
///
/// No variant accepts a dimension, a correction radius, a closed defining set,
/// a generator beside its roots, a length beside a primitive splitting field,
/// or a field order beside the extension witness. Each of those is dependent
/// and has exactly one derivation inside [`BchCode::construct`].
///
/// The primitive variants derive their length as $|E^{*}|$ and their root as
/// the canonical element of that exact order, so neither is an input.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BchSpec<X>
where
    X: FieldExtension,
{
    /// Primitive narrow-sense BCH code.
    ///
    /// The length is $|E^{*}|$, the root is the canonical element of that
    /// exact order, and the first root exponent is the residue of one modulo
    /// the derived length.
    PrimitiveNarrowSense {
        /// Witness relating the code-symbol field to the splitting field.
        extension: X,
        /// Requested classical BCH bound $\delta$.
        designed_distance: DesignedDistance,
    },

    /// Primitive BCH code with a caller-selected first consecutive root.
    ///
    /// The length and root are derived as in
    /// [`PrimitiveNarrowSense`](Self::PrimitiveNarrowSense); only the start of
    /// the consecutive run differs.
    PrimitiveFirstRoot {
        /// Witness relating the code-symbol field to the splitting field.
        extension: X,
        /// Exponent $b$ of the first requested consecutive root.
        first_root: RootExponent,
        /// Requested classical BCH bound $\delta$.
        designed_distance: DesignedDistance,
    },
}

// ---------------------------------------------------------------------------
// The witnessed bound
// ---------------------------------------------------------------------------

/// A witnessed classical lower bound on the minimum distance.
///
/// The witness is the canonical longest cyclic run of consecutive exponents in
/// the defining set: the run with the greatest length, and among those the one
/// with the least starting exponent. Recording it makes the bound checkable
/// against the defining set instead of merely asserted.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BchDistanceBound {
    first_root: Option<RootExponent>,
    consecutive_root_count: usize,
    minimum_distance_lower_bound: usize,
}

impl BchDistanceBound {
    /// Returns the start of the witnessing run.
    ///
    /// `None` occurs exactly for the empty defining set, which witnesses no
    /// run at all.
    pub fn first_root(&self) -> Option<RootExponent> {
        self.first_root
    }

    /// Returns the length $r$ of the witnessing run.
    pub fn consecutive_root_count(&self) -> usize {
        self.consecutive_root_count
    }

    /// Returns the bound $r + 1$ the run witnesses.
    ///
    /// This is a lower bound on the minimum distance. For a defining set
    /// covering every exponent the code contains no nonzero word, so the
    /// statement is vacuous but remains a valid bound.
    pub fn minimum_distance_lower_bound(&self) -> usize {
        self.minimum_distance_lower_bound
    }
}

// ---------------------------------------------------------------------------
// The constructed code
// ---------------------------------------------------------------------------

/// A BCH code over `X::Base` with static symbol and matrix representations.
///
/// `X` fixes the base/splitting-field relation, `S` fixes the symbol-sequence
/// storage, and `M` fixes the matrix storage. The representation parameters
/// carry no runtime data: they select monomorphized code paths, so choosing a
/// representation costs nothing at run time. Use [`DenseBchCode`] for the
/// field-generic reference representation and [`BinaryBchCode`] for packed
/// binary storage.
///
/// A value of this type is always the result of a completed
/// [`construct`](Self::construct), so its stored parameters are mutually
/// consistent by construction; no accessor accepts a replacement value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BchCode<X, S, M>
where
    X: FieldExtension,
    S: SymbolSequence<X::Base>,
    M: SymbolMatrix<X::Base>,
{
    extension: X,
    root: X::Ext,
    length: usize,
    dimension: usize,
    generator: FieldPoly<X::Base>,
    defining_set: Box<[RootExponent]>,
    distance_bound: BchDistanceBound,
    correction_radius: usize,
    representation: PhantomData<fn() -> (S, M)>,
}

/// A BCH code in the field-generic reference representation.
pub type DenseBchCode<X> =
    BchCode<X, FieldVec<<X as FieldExtension>::Base>, FieldMatrix<<X as FieldExtension>::Base>>;

/// A binary BCH code in packed representation.
///
/// Symbols are [`BitVec`] bits and matrices are [`BitMatrix`] rows, with no
/// unpacked intermediate.
pub type BinaryBchCode<V = u64> = BchCode<BinaryPrimeExt<V>, BitVec, BitMatrix>;

impl<X, S, M> BchCode<X, S, M>
where
    X: FieldExtension,
    S: SymbolSequence<X::Base>,
    M: SymbolMatrix<X::Base>,
{
    /// Validates a spec and derives the code it names.
    ///
    /// This is the only construction path: it performs every validation listed
    /// at the module level and derives the generator, the dimension, the
    /// defining set, the witnessed bound and the correction radius from the
    /// spec's independent inputs.
    ///
    /// Mathematically valid boundary results are constructed rather than
    /// rejected: a spec requesting no roots yields the full-space code with
    /// $k = n$ and $g = 1$, and one whose closure covers every exponent yields
    /// the zero-dimensional code with $k = 0$ and $g = x^n - 1$.
    ///
    /// # Errors
    ///
    /// - [`BchError::Field`] wrapping [`FieldError::UnsupportedSize`] when
    ///   $|E^{*}|$ exceeds the representable range of the core order helpers.
    /// - [`BchError::Code`] wrapping [`CodeError::UnsupportedSize`] when the
    ///   derived length does not fit a `u64` or an in-memory `usize`.
    /// - [`BchError::InvalidLength`] when the derived length is zero.
    /// - [`BchError::LengthNotCoprimeToCharacteristic`] when
    ///   $\gcd(n, q) \ne 1$, which would define a repeated-root cyclic code.
    /// - [`BchError::LengthDoesNotDivideUnitGroup`] when $n \nmid |E^{*}|$, so
    ///   no element of exact order $n$ exists.
    /// - [`BchError::RootExponentOutOfRange`] when a supplied first root
    ///   exponent is not in `0..n`.
    /// - [`BchError::DesignedDistanceOutOfRange`] when $\delta > n + 1$.
    /// - [`BchError::GeneratorNotDivisorOfCyclicPolynomial`] when the derived
    ///   generator does not divide $x^n - 1$.
    /// - [`BchError::Field`] wrapping the failure reported by the extension
    ///   surface while deriving the root or the cyclotomic closure.
    ///
    /// # Complexity
    ///
    /// See the module-level complexity summary.
    pub fn construct(spec: BchSpec<X>) -> Result<Self, BchError> {
        let derived = normalize(spec)?;
        let closure = cyclotomic_closure(&derived.extension, derived.length.get(), &derived.seeds)?;
        let generator =
            derive_generator(&derived.extension, &derived.root, &closure, derived.length)?;
        assemble(derived, &closure, generator)
    }

    /// Returns the extension witness the code was constructed with.
    pub fn extension(&self) -> &X {
        &self.extension
    }

    /// Returns the validated root of exact multiplicative order `n`.
    pub fn root(&self) -> &X::Ext {
        &self.root
    }

    /// Returns the codeword length `n`.
    pub fn n(&self) -> usize {
        self.length
    }

    /// Returns the message dimension `k`.
    pub fn k(&self) -> usize {
        self.dimension
    }

    /// Returns the monic generator polynomial over the base field.
    pub fn generator(&self) -> &FieldPoly<X::Base> {
        &self.generator
    }

    /// Returns the closed defining set in ascending exponent order.
    pub fn defining_set(&self) -> &[RootExponent] {
        &self.defining_set
    }

    /// Returns the witnessed classical distance bound.
    pub fn distance_bound(&self) -> &BchDistanceBound {
        &self.distance_bound
    }

    /// Returns the correction radius the witnessed bound implies.
    pub fn correction_radius(&self) -> usize {
        self.correction_radius
    }

    /// Returns the identity of the code-symbol field $B$.
    pub fn base_field_id(&self) -> &FieldId {
        self.extension.base_id()
    }

    /// Returns the identity of the splitting field $E$.
    pub fn splitting_field_id(&self) -> &FieldId {
        self.extension.ext_id()
    }
}

impl<X, S, M> BlockCode for BchCode<X, S, M>
where
    X: FieldExtension,
    S: SymbolSequence<X::Base>,
    M: SymbolMatrix<X::Base>,
{
    type Symbol = X::Base;
    type Symbols = S;

    fn symbol_zero(&self) -> Self::Symbol {
        self.extension.base_zero()
    }

    fn k(&self) -> usize {
        self.dimension
    }

    fn n(&self) -> usize {
        self.length
    }
}

// ---------------------------------------------------------------------------
// Stage 1: validate and normalize
// ---------------------------------------------------------------------------

/// The independent inputs after validation, in the form every later stage
/// consumes. Adding a spec flavor means producing this value; the stages
/// after it are shared unchanged.
struct DerivedInputs<X: FieldExtension> {
    extension: X,
    length: BchLength,
    root: X::Ext,
    seeds: Vec<u64>,
}

fn normalize<X: FieldExtension>(spec: BchSpec<X>) -> Result<DerivedInputs<X>, BchError> {
    match spec {
        BchSpec::PrimitiveNarrowSense {
            extension,
            designed_distance,
        } => normalize_primitive(extension, None, designed_distance),
        BchSpec::PrimitiveFirstRoot {
            extension,
            first_root,
            designed_distance,
        } => normalize_primitive(extension, Some(first_root), designed_distance),
    }
}

/// Normalizes a primitive consecutive-root request.
///
/// `first_root` of `None` selects the narrow-sense convention, whose first
/// root exponent is the residue of one modulo the derived length.
fn normalize_primitive<X: FieldExtension>(
    extension: X,
    first_root: Option<RootExponent>,
    designed_distance: DesignedDistance,
) -> Result<DerivedInputs<X>, BchError> {
    let length = primitive_length(&extension)?;
    validate_length_coprime_to_characteristic(extension.characteristic(), length)?;
    validate_length_divides_unit_group(&extension, length)?;

    let root = resolve_root(&extension, length, &RootSelection::Canonical)?;
    let first_root = match first_root {
        Some(exponent) => validate_root_exponent(exponent, length)?,
        None => RootExponent(1 % length.get()),
    };
    validate_designed_distance(designed_distance, length)?;
    let seeds = consecutive_seeds(first_root, designed_distance, length);

    Ok(DerivedInputs {
        extension,
        length,
        root,
        seeds,
    })
}

/// Derives the primitive length $n = |E^{*}|$.
fn primitive_length<X: FieldExtension>(extension: &X) -> Result<BchLength, BchError> {
    let unit_group_order =
        extension
            .ext_unit_group_order()
            .ok_or_else(|| FieldError::UnsupportedSize {
                degree: extension.ext_degree(),
                characteristic: extension.characteristic(),
            })?;
    let length = u64::try_from(unit_group_order).map_err(|_| CodeError::UnsupportedSize {
        size: unit_group_order,
    })?;
    BchLength::try_from(length)
}

/// Decides $\gcd(n, q) = 1$.
///
/// The base-field order $q$ is a power of the characteristic $p$, so the
/// condition is equivalent to $\gcd(n, p) = 1$ and needs no representation of
/// $q$ itself.
fn validate_length_coprime_to_characteristic(
    characteristic: u64,
    length: BchLength,
) -> Result<(), BchError> {
    let n = length.get();
    if integer_gcd(characteristic % n, n) == 1 {
        Ok(())
    } else {
        Err(BchError::LengthNotCoprimeToCharacteristic {
            length: n,
            characteristic,
        })
    }
}

/// Decides $n \mid |E^{*}|$, the condition for an element of exact order $n$.
fn validate_length_divides_unit_group<X: FieldExtension>(
    extension: &X,
    length: BchLength,
) -> Result<(), BchError> {
    let unit_group_order =
        extension
            .ext_unit_group_order()
            .ok_or_else(|| FieldError::UnsupportedSize {
                degree: extension.ext_degree(),
                characteristic: extension.characteristic(),
            })?;
    if unit_group_order % u128::from(length.get()) == 0 {
        Ok(())
    } else {
        Err(BchError::LengthDoesNotDivideUnitGroup {
            length: length.get(),
            unit_group_order,
        })
    }
}

/// Obtains the order-`length` root named by `selection`.
fn resolve_root<X: FieldExtension>(
    extension: &X,
    length: BchLength,
    selection: &RootSelection<X::Ext>,
) -> Result<X::Ext, BchError> {
    match selection {
        RootSelection::Canonical => {
            let (root, _certificate) = element_of_exact_order(extension, length.get())?;
            Ok(root)
        }
        RootSelection::Explicit(candidate) => {
            let expected = extension.ext_id().clone();
            let found = candidate.field_id();
            if expected != found {
                return Err(FieldError::IdentityMismatch { expected, found }.into());
            }
            let order = multiplicative_order(extension, candidate)?;
            if order == u128::from(length.get()) {
                Ok(candidate.clone())
            } else {
                Err(BchError::RootOrderMismatch {
                    expected: length.get(),
                    actual: order,
                })
            }
        }
    }
}

/// Returns the exact multiplicative order of `element`, or zero for the zero
/// element, which has no multiplicative order.
///
/// The order is reduced from $|E^{*}|$ by the primes of its factorization,
/// which the canonical generator's certificate supplies.
fn multiplicative_order<X: FieldExtension>(
    extension: &X,
    element: &X::Ext,
) -> Result<u128, BchError> {
    if element.is_zero() {
        return Ok(0);
    }
    let (_, certificate) = canonical_generator(extension)?;
    let mut order = certificate.order();
    for &prime in certificate.prime_factors() {
        while order % prime == 0 && element.pow(order / prime).is_one() {
            order /= prime;
        }
    }
    Ok(u128::from(order))
}

/// Decides $0 \le b < n$ for a caller-supplied exponent.
fn validate_root_exponent(
    exponent: RootExponent,
    length: BchLength,
) -> Result<RootExponent, BchError> {
    if exponent.get() < length.get() {
        Ok(exponent)
    } else {
        Err(BchError::RootExponentOutOfRange {
            exponent: exponent.get(),
            length: length.get(),
        })
    }
}

/// Decides $\delta \le n + 1$; the lower bound holds by construction of
/// [`DesignedDistance`].
fn validate_designed_distance(
    designed_distance: DesignedDistance,
    length: BchLength,
) -> Result<(), BchError> {
    if u128::from(designed_distance.get()) <= u128::from(length.get()) + 1 {
        Ok(())
    } else {
        Err(BchError::DesignedDistanceOutOfRange {
            designed_distance: designed_distance.get(),
            length: length.get(),
        })
    }
}

/// Expands a consecutive request into its unclosed seed sequence
/// $b, b+1, \ldots, b + \delta - 2$ modulo $n$.
///
/// The addition is performed in `u128`, so no intermediate overflows even for
/// a length near `u64::MAX`.
fn consecutive_seeds(
    first_root: RootExponent,
    designed_distance: DesignedDistance,
    length: BchLength,
) -> Vec<u64> {
    let n = u128::from(length.get());
    let start = u128::from(first_root.get());
    (0..u128::from(designed_distance.get() - 1))
        .map(|offset| ((start + offset) % n) as u64)
        .collect()
}

/// Euclid's algorithm on unsigned integers.
///
/// The field layer keeps an equivalent routine private to its own module; the
/// construction path needs the same decision one stage earlier, before any
/// cyclotomic partition is built.
fn integer_gcd(mut left: u64, mut right: u64) -> u64 {
    while right != 0 {
        let remainder = left % right;
        left = right;
        right = remainder;
    }
    left
}

// ---------------------------------------------------------------------------
// Stage 3: derive the generator
// ---------------------------------------------------------------------------

/// Forms the monic generator from the closure's coset minimal polynomials and
/// validates that it divides $x^n - 1$.
fn derive_generator<X: FieldExtension>(
    extension: &X,
    root: &X::Ext,
    closure: &CosetPartition,
    length: BchLength,
) -> Result<FieldPoly<X::Base>, BchError> {
    let mut generator = FieldPoly::one_like(&extension.base_zero());
    for coset in closure.cosets() {
        let representative = *coset
            .first()
            .expect("a cyclotomic coset contains its representative");
        let factor = minimal_polynomial(extension, &root.pow(representative))?;
        generator = FieldPoly::lcm(&generator, &factor);
    }

    let in_memory_length =
        usize::try_from(length.get()).map_err(|_| CodeError::UnsupportedSize {
            size: u128::from(length.get()),
        })?;
    let cyclic = cyclic_polynomial(&extension.base_zero(), in_memory_length);
    let (_, remainder) = cyclic.div_rem(&generator);
    if remainder.is_zero() {
        Ok(generator)
    } else {
        Err(BchError::GeneratorNotDivisorOfCyclicPolynomial {
            length: length.get(),
        })
    }
}

/// Returns $x^{n} - 1$ over the field of `zero`.
fn cyclic_polynomial<F: FiniteField>(zero: &F, length: usize) -> FieldPoly<F> {
    let one = zero.one_like();
    let mut coefficients = vec![zero.clone(); length + 1];
    coefficients[0] = -one.clone();
    coefficients[length] = one;
    FieldPoly::new(coefficients)
}

// ---------------------------------------------------------------------------
// Stage 4: derive parameters and witnesses
// ---------------------------------------------------------------------------

/// Derives the dimension, the sorted defining set, the bound witness and the
/// correction radius, and stores them beside the inputs they came from.
///
/// The two `expect` conditions restate what stage 3 already validated, so
/// either one firing means an internal invariant broke rather than that a
/// caller supplied bad input.
fn assemble<X, S, M>(
    derived: DerivedInputs<X>,
    closure: &CosetPartition,
    generator: FieldPoly<X::Base>,
) -> Result<BchCode<X, S, M>, BchError>
where
    X: FieldExtension,
    S: SymbolSequence<X::Base>,
    M: SymbolMatrix<X::Base>,
{
    let length = usize::try_from(derived.length.get()).map_err(|_| CodeError::UnsupportedSize {
        size: u128::from(derived.length.get()),
    })?;
    let degree = generator
        .degree()
        .expect("the derived generator is monic and therefore nonzero");
    let dimension = length
        .checked_sub(degree)
        .expect("a validated divisor of x^n - 1 has degree at most n");

    let defining_set: Box<[RootExponent]> = closure
        .defining_set()
        .into_iter()
        .map(RootExponent)
        .collect();
    let distance_bound = witness_longest_run(&defining_set, length);
    let correction_radius = distance_bound.consecutive_root_count / 2;

    Ok(BchCode {
        extension: derived.extension,
        root: derived.root,
        length,
        dimension,
        generator,
        defining_set,
        distance_bound,
        correction_radius,
        representation: PhantomData,
    })
}

/// Finds the canonical longest cyclic run of consecutive exponents.
///
/// Ties select the least starting exponent, which makes the witness
/// reproducible. `defining_set` holds distinct exponents below `length`.
fn witness_longest_run(defining_set: &[RootExponent], length: usize) -> BchDistanceBound {
    if defining_set.is_empty() {
        return BchDistanceBound {
            first_root: None,
            consecutive_root_count: 0,
            minimum_distance_lower_bound: 1,
        };
    }
    if defining_set.len() == length {
        return BchDistanceBound {
            first_root: Some(RootExponent(0)),
            consecutive_root_count: length,
            minimum_distance_lower_bound: length + 1,
        };
    }

    let mut present = vec![false; length];
    for exponent in defining_set {
        present[exponent.get() as usize] = true;
    }

    let mut best_start = 0usize;
    let mut best_run = 0usize;
    for start in 0..length {
        if !present[start] || present[(start + length - 1) % length] {
            continue;
        }
        let mut run = 0usize;
        while run < length && present[(start + run) % length] {
            run += 1;
        }
        if run > best_run {
            best_run = run;
            best_start = start;
        }
    }

    BchDistanceBound {
        first_root: Some(RootExponent(best_start as u64)),
        consecutive_root_count: best_run,
        minimum_distance_lower_bound: best_run + 1,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bch::BchCode as LegacyBchCode;
    use gf2_core::field::modulus_select::select_modulus;
    use gf2_core::field::ConstField;
    use gf2_core::gf2m::{Gf2mElement, Gf2mField};
    use gf2_core::gfp::Fp;
    use gf2_core::gfpn::{QuotientElement, QuotientField};
    use proptest::prelude::*;

    /// The binary parameter points the existing suite pins, as
    /// `(m, primitive polynomial, n, k, t)`.
    const LEGACY_BINARY_POINTS: &[(usize, u64, usize, usize, usize)] = &[
        (3, 0b1011, 7, 4, 1),
        (4, 0b10011, 15, 11, 1),
        (4, 0b10011, 15, 7, 2),
        (5, 0b100101, 31, 26, 1),
        (6, 0b1000011, 63, 57, 1),
        (7, 0b10000011, 127, 64, 10),
    ];

    fn binary_extension(m: usize, modulus: u64) -> BinaryPrimeExt {
        BinaryPrimeExt::new(Gf2mField::new(m, modulus)).expect("a primitive modulus")
    }

    fn binary_narrow_sense(m: usize, modulus: u64, designed_distance: u64) -> BinaryBchCode {
        BinaryBchCode::construct(BchSpec::PrimitiveNarrowSense {
            extension: binary_extension(m, modulus),
            designed_distance: DesignedDistance::try_from(designed_distance)
                .expect("a positive designed distance"),
        })
        .expect("a valid primitive narrow-sense spec")
    }

    /// GF(25) = GF(5)[x] / (x^2 + x + 1).
    fn gf25() -> QuotientField<Fp<5>> {
        let modulus = FieldPoly::new(vec![Fp::<5>::new(1), Fp::new(1), Fp::new(1)]);
        QuotientField::new(Fp::<5>::zero(), modulus).expect("an irreducible modulus")
    }

    /// GF(81) presented as a degree-two extension of GF(9).
    fn gf81_over_gf9() -> QuotientField<QuotientElement<Fp<3>>> {
        let gf9_modulus = select_modulus(&Fp::<3>::zero(), 2).expect("a GF(9) modulus");
        let gf9 = QuotientField::new(Fp::<3>::zero(), gf9_modulus).expect("GF(9)");
        let gf9_zero = gf9.ext_zero();
        let gf81_modulus = select_modulus(&gf9_zero, 2).expect("a relative GF(81) modulus");
        QuotientField::new(gf9_zero, gf81_modulus).expect("GF(81) over GF(9)")
    }

    fn generator_divides_cyclic_polynomial<X, S, M>(code: &BchCode<X, S, M>) -> bool
    where
        X: FieldExtension,
        S: SymbolSequence<X::Base>,
        M: SymbolMatrix<X::Base>,
    {
        let cyclic = cyclic_polynomial(&code.extension().base_zero(), code.n());
        cyclic.div_rem(code.generator()).1.is_zero()
    }

    /// Returns the membership table of the defining set, indexed by exponent.
    fn membership<X, S, M>(code: &BchCode<X, S, M>) -> Vec<bool>
    where
        X: FieldExtension,
        S: SymbolSequence<X::Base>,
        M: SymbolMatrix<X::Base>,
    {
        let mut present = vec![false; code.n()];
        for exponent in code.defining_set() {
            present[exponent.get() as usize] = true;
        }
        present
    }

    /// Checks every relationship the construction promises: the dimension
    /// follows the generator degree, the generator divides `x^n - 1`, the
    /// defining set is sorted and closed under multiplication by `q`, and the
    /// bound witness names a maximal run of exponents that are all present.
    fn assert_construction_is_consistent<X, S, M>(code: &BchCode<X, S, M>, base_order: u64)
    where
        X: FieldExtension,
        S: SymbolSequence<X::Base>,
        M: SymbolMatrix<X::Base>,
    {
        let n = code.n();
        let degree = code.generator().degree().expect("a nonzero generator");
        assert_eq!(code.k(), n - degree, "k must be n - deg(g)");
        assert!(
            generator_divides_cyclic_polynomial(code),
            "g must divide x^n - 1"
        );

        let exponents: Vec<u64> = code
            .defining_set()
            .iter()
            .map(|exponent| exponent.get())
            .collect();
        assert_eq!(exponents.len(), degree, "one root per generator degree");
        for window in exponents.windows(2) {
            assert!(
                window[0] < window[1],
                "the defining set is sorted and distinct"
            );
        }
        let modulus = u128::from(n as u64);
        for &exponent in &exponents {
            let image = (u128::from(exponent) * u128::from(base_order) % modulus) as u64;
            assert!(
                exponents.contains(&image),
                "the defining set must be closed under multiplication by q"
            );
        }

        assert_witnessed_run_is_maximal(code);
    }

    /// Checks the bound witness against the defining set it claims to describe.
    fn assert_witnessed_run_is_maximal<X, S, M>(code: &BchCode<X, S, M>)
    where
        X: FieldExtension,
        S: SymbolSequence<X::Base>,
        M: SymbolMatrix<X::Base>,
    {
        let n = code.n();
        let present = membership(code);
        let bound = code.distance_bound();
        let run = bound.consecutive_root_count();
        assert_eq!(bound.minimum_distance_lower_bound(), run + 1);
        assert_eq!(code.correction_radius(), run / 2);

        let Some(start) = bound.first_root() else {
            assert_eq!(run, 0);
            assert!(code.defining_set().is_empty());
            return;
        };
        let start = start.get() as usize;
        for offset in 0..run {
            let exponent = (start + offset) % n;
            assert!(present[exponent], "witnessed exponent {exponent} is absent");
        }
        if run < n {
            assert!(
                !present[(start + run) % n],
                "the witnessed run is not maximal"
            );
            assert!(
                !present[(start + n - 1) % n],
                "the witnessed run does not start where it claims"
            );
        }

        for candidate in 0..n {
            if !present[candidate] {
                continue;
            }
            let mut length = 0usize;
            while length < n && present[(candidate + length) % n] {
                length += 1;
            }
            assert!(length <= run, "a longer run starts at exponent {candidate}");
        }
    }

    // -- REQ-02: agreement with the current binary implementation ----------

    #[test]
    fn primitive_narrow_sense_agrees_with_the_current_binary_generators() {
        for &(m, modulus, n, k, t) in LEGACY_BINARY_POINTS {
            let legacy = LegacyBchCode::new(n, k, t, Gf2mField::new(m, modulus));
            let code = binary_narrow_sense(m, modulus, 2 * t as u64 + 1);

            assert_eq!(code.n(), n, "length for BCH({n}, {k}, {t})");
            assert_eq!(code.k(), k, "dimension for BCH({n}, {k}, {t})");
            assert_eq!(code.correction_radius(), t, "radius for BCH({n}, {k}, {t})");
            assert_eq!(
                code.distance_bound().minimum_distance_lower_bound(),
                legacy.designed_distance(),
                "bound for BCH({n}, {k}, {t})"
            );

            let legacy_generator = legacy.generator();
            let degree = code.generator().degree().expect("a nonzero generator");
            assert_eq!(
                legacy_generator.degree(),
                Some(degree),
                "generator degree for BCH({n}, {k}, {t})"
            );
            for index in 0..=degree {
                assert_eq!(
                    code.generator().coeff(index).is_one(),
                    legacy_generator.coeff(index).is_one(),
                    "generator coefficient {index} for BCH({n}, {k}, {t})"
                );
            }
        }
    }

    #[test]
    fn binary_generators_divide_the_cyclic_polynomial() {
        for &(m, modulus, _, _, t) in LEGACY_BINARY_POINTS {
            let code = binary_narrow_sense(m, modulus, 2 * t as u64 + 1);
            assert!(generator_divides_cyclic_polynomial(&code));
        }
    }

    // -- REQ-03: nonbinary construction ------------------------------------

    #[test]
    fn prime_base_primitive_construction_derives_a_base_field_generator() {
        let code = DenseBchCode::construct(BchSpec::PrimitiveNarrowSense {
            extension: gf25(),
            designed_distance: DesignedDistance::try_from(5).expect("positive"),
        })
        .expect("a valid GF(5) primitive spec");

        // The 5-cyclotomic closure of {1, 2, 3, 4} modulo 24 also contains 5,
        // 10, 15 and 20, so the generator has degree eight.
        assert_eq!(code.n(), 24);
        assert_eq!(code.k(), 16);
        assert_eq!(code.generator().degree(), Some(8));
        assert_eq!(code.base_field_id(), &Fp::<5>::new(0).field_id());
        assert_eq!(code.distance_bound().consecutive_root_count(), 5);
        assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 6);
        assert_eq!(code.correction_radius(), 2);
        assert_construction_is_consistent(&code, 5);
    }

    #[test]
    fn extension_base_primitive_construction_derives_a_base_field_generator() {
        let extension = gf81_over_gf9();
        let base_id = extension.base_id().clone();
        let code = DenseBchCode::construct(BchSpec::PrimitiveNarrowSense {
            extension,
            designed_distance: DesignedDistance::try_from(4).expect("positive"),
        })
        .expect("a valid GF(9) primitive spec");

        // The 9-cyclotomic cosets of 1, 2 and 3 modulo 80 are {1, 9}, {2, 18}
        // and {3, 27}, so the defining set holds six exponents.
        assert_eq!(code.n(), 80);
        assert_eq!(code.generator().degree(), Some(6));
        assert_eq!(code.k(), 74);
        assert_eq!(code.base_field_id(), &base_id);
        assert_eq!(code.distance_bound().consecutive_root_count(), 3);
        assert_eq!(code.correction_radius(), 1);
        assert_construction_is_consistent(&code, 9);
    }

    // -- The arbitrary-first-root flavor -----------------------------------

    #[test]
    fn first_root_flavor_witnesses_the_run_it_actually_has() {
        let code = BinaryBchCode::construct(BchSpec::PrimitiveFirstRoot {
            extension: binary_extension(4, 0b10011),
            first_root: RootExponent::from(2),
            designed_distance: DesignedDistance::try_from(5).expect("positive"),
        })
        .expect("a valid primitive first-root spec");

        // Seeds {2, 3, 4, 5} close to {1, 2, 3, 4, 5, 6, 8, 9, 10, 12}, whose
        // longest run starts one exponent below the requested first root.
        let exponents: Vec<u64> = code
            .defining_set()
            .iter()
            .map(|exponent| exponent.get())
            .collect();
        assert_eq!(exponents, vec![1, 2, 3, 4, 5, 6, 8, 9, 10, 12]);
        assert_eq!(code.k(), 5);
        assert_eq!(code.distance_bound().first_root(), Some(RootExponent(1)));
        assert_eq!(code.distance_bound().consecutive_root_count(), 6);
        assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 7);
        assert_eq!(code.correction_radius(), 3);
        assert_construction_is_consistent(&code, 2);
    }

    #[test]
    fn narrow_sense_is_the_first_root_flavor_at_exponent_one() {
        let narrow = binary_narrow_sense(4, 0b10011, 5);
        let explicit = BinaryBchCode::construct(BchSpec::PrimitiveFirstRoot {
            extension: binary_extension(4, 0b10011),
            first_root: RootExponent::from(1),
            designed_distance: DesignedDistance::try_from(5).expect("positive"),
        })
        .expect("a valid primitive first-root spec");

        assert_eq!(narrow, explicit);
    }

    // -- Bound witness -----------------------------------------------------

    #[test]
    fn the_witnessed_run_is_present_and_maximal_in_the_defining_set() {
        for (m, modulus, designed_distance) in [
            (4usize, 0b10011u64, 3u64),
            (4, 0b10011, 5),
            (5, 0b100101, 7),
        ] {
            assert_witnessed_run_is_maximal(&binary_narrow_sense(m, modulus, designed_distance));
        }
    }

    // -- Boundary codes ----------------------------------------------------

    #[test]
    fn a_designed_distance_of_one_yields_the_full_space_code() {
        let code = binary_narrow_sense(4, 0b10011, 1);

        assert_eq!(code.n(), 15);
        assert_eq!(code.k(), 15);
        assert_eq!(code.generator().degree(), Some(0));
        assert!(code.defining_set().is_empty());
        assert_eq!(code.distance_bound().first_root(), None);
        assert_eq!(code.distance_bound().consecutive_root_count(), 0);
        assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 1);
        assert_eq!(code.correction_radius(), 0);
    }

    #[test]
    fn a_full_defining_set_yields_the_zero_dimensional_code() {
        let code = binary_narrow_sense(4, 0b10011, 16);

        assert_eq!(code.k(), 0);
        assert_eq!(code.generator().degree(), Some(15));
        assert!(generator_divides_cyclic_polynomial(&code));
        assert_eq!(code.defining_set().len(), 15);
        assert_eq!(code.distance_bound().first_root(), Some(RootExponent(0)));
        assert_eq!(code.distance_bound().consecutive_root_count(), 15);
        assert_eq!(code.distance_bound().minimum_distance_lower_bound(), 16);
        assert_eq!(code.correction_radius(), 7);
    }

    // -- Typed errors ------------------------------------------------------

    #[test]
    fn a_designed_distance_above_the_length_bound_is_rejected() {
        let error = BinaryBchCode::construct(BchSpec::PrimitiveNarrowSense {
            extension: binary_extension(4, 0b10011),
            designed_distance: DesignedDistance::try_from(17).expect("positive"),
        })
        .expect_err("delta must not exceed n + 1");

        assert_eq!(
            error,
            BchError::DesignedDistanceOutOfRange {
                designed_distance: 17,
                length: 15,
            }
        );
    }

    #[test]
    fn a_first_root_outside_the_residue_range_is_rejected() {
        let error = BinaryBchCode::construct(BchSpec::PrimitiveFirstRoot {
            extension: binary_extension(4, 0b10011),
            first_root: RootExponent::from(15),
            designed_distance: DesignedDistance::try_from(3).expect("positive"),
        })
        .expect_err("the exponent range is 0..n");

        assert_eq!(
            error,
            BchError::RootExponentOutOfRange {
                exponent: 15,
                length: 15,
            }
        );
    }

    #[test]
    fn zero_valued_semantic_inputs_are_rejected_at_conversion() {
        assert_eq!(
            BchLength::try_from(0).expect_err("zero is not a length"),
            BchError::InvalidLength { length: 0 }
        );
        assert_eq!(
            DesignedDistance::try_from(0).expect_err("zero is not a designed distance"),
            BchError::InvalidDesignedDistance {
                designed_distance: 0
            }
        );
    }

    #[test]
    fn a_length_sharing_a_factor_with_the_characteristic_is_rejected() {
        let six = BchLength::try_from(6).expect("positive");
        assert_eq!(
            validate_length_coprime_to_characteristic(2, six).expect_err("gcd(6, 2) is two"),
            BchError::LengthNotCoprimeToCharacteristic {
                length: 6,
                characteristic: 2,
            }
        );

        let fifteen = BchLength::try_from(15).expect("positive");
        assert!(validate_length_coprime_to_characteristic(2, fifteen).is_ok());
    }

    #[test]
    fn a_length_that_does_not_divide_the_unit_group_is_rejected() {
        let extension = binary_extension(4, 0b10011);
        let seven = BchLength::try_from(7).expect("positive");

        assert_eq!(
            validate_length_divides_unit_group(&extension, seven)
                .expect_err("7 does not divide 15"),
            BchError::LengthDoesNotDivideUnitGroup {
                length: 7,
                unit_group_order: 15,
            }
        );
    }

    #[test]
    fn an_explicit_root_of_the_wrong_order_is_rejected() {
        let extension = binary_extension(4, 0b10011);
        let length = BchLength::try_from(15).expect("positive");
        let generator = resolve_root(&extension, length, &RootSelection::Canonical)
            .expect("a canonical order-15 root");

        let error = resolve_root(
            &extension,
            length,
            &RootSelection::Explicit(generator.pow(3)),
        )
        .expect_err("the cube of a primitive element has order five");

        assert_eq!(
            error,
            BchError::RootOrderMismatch {
                expected: 15,
                actual: 5,
            }
        );
    }

    #[test]
    fn an_explicit_root_from_another_presentation_is_rejected() {
        let extension = binary_extension(4, 0b10011);
        let other: Gf2mElement = Gf2mField::new(4, 0b11001).element(2);
        let length = BchLength::try_from(15).expect("positive");

        let error = resolve_root(&extension, length, &RootSelection::Explicit(other))
            .expect_err("a different defining polynomial is a different field");

        assert!(matches!(
            error,
            BchError::Field(FieldError::IdentityMismatch { .. })
        ));
    }

    #[test]
    fn an_explicit_canonical_root_resolves_to_the_derived_one() {
        let extension = binary_extension(4, 0b10011);
        let length = BchLength::try_from(15).expect("positive");
        let canonical = resolve_root(&extension, length, &RootSelection::Canonical)
            .expect("a canonical order-15 root");
        let explicit = resolve_root(
            &extension,
            length,
            &RootSelection::Explicit(canonical.clone()),
        )
        .expect("the canonical root has exact order 15");

        assert_eq!(canonical, explicit);
    }

    // -- Block-code contract -----------------------------------------------

    #[test]
    fn constructed_codes_satisfy_the_block_code_laws() {
        let packed = binary_narrow_sense(4, 0b10011, 5);
        assert!(BlockCode::k(&packed) <= BlockCode::n(&packed));
        assert_eq!(
            BlockCode::redundancy(&packed),
            packed.generator().degree().expect("a nonzero generator")
        );
        assert_eq!(packed.symbol_field_id(), *packed.base_field_id());

        let dense = DenseBchCode::construct(BchSpec::PrimitiveNarrowSense {
            extension: gf25(),
            designed_distance: DesignedDistance::try_from(3).expect("positive"),
        })
        .expect("a valid GF(5) primitive spec");
        assert!(BlockCode::k(&dense) <= BlockCode::n(&dense));
        assert_eq!(
            BlockCode::redundancy(&dense),
            dense.generator().degree().expect("a nonzero generator")
        );
        assert_eq!(dense.symbol_field_id(), *dense.base_field_id());
    }

    // -- Property suites ---------------------------------------------------

    /// Draws a valid binary primitive request as
    /// `(m, primitive polynomial, first root, designed distance)`.
    ///
    /// The exponent and the designed distance are drawn inside the ranges the
    /// derived length admits, so every generated triple is accepted and the
    /// suite tests derivation rather than rejection. Both boundary requests,
    /// `delta = 1` and `delta = n + 1`, are inside the drawn range.
    fn binary_requests() -> impl Strategy<Value = (usize, u64, u64, u64)> {
        prop_oneof![
            Just((3usize, 0b1011u64)),
            Just((4, 0b10011)),
            Just((5, 0b100101)),
            Just((6, 0b1000011)),
        ]
        .prop_flat_map(|(m, modulus)| {
            let length = (1u64 << m) - 1;
            (Just(m), Just(modulus), 0..length, 1..=length + 1)
        })
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(24))]

        #[test]
        fn prop_binary_construction_is_internally_consistent(
            (m, modulus, first_root, designed_distance) in binary_requests(),
        ) {
            let code = BinaryBchCode::construct(BchSpec::PrimitiveFirstRoot {
                extension: binary_extension(m, modulus),
                first_root: RootExponent::from(first_root),
                designed_distance: DesignedDistance::try_from(designed_distance)
                    .expect("positive"),
            })
            .expect("a valid primitive first-root spec");

            assert_construction_is_consistent(&code, 2);
        }

        #[test]
        fn prop_prime_base_construction_is_internally_consistent(
            first_root in 0u64..24,
            designed_distance in 1u64..=25,
        ) {
            let code = DenseBchCode::construct(BchSpec::PrimitiveFirstRoot {
                extension: gf25(),
                first_root: RootExponent::from(first_root),
                designed_distance: DesignedDistance::try_from(designed_distance)
                    .expect("positive"),
            })
            .expect("a valid GF(5) primitive first-root spec");

            assert_construction_is_consistent(&code, 5);
        }
    }
}
