//! CAS cross-validation of [`permanent_bipedal5`] and [`permanent_bipedal7`]
//! against [`data/cas_permanent_f5_f7.csv`], generated by
//! `scripts/generate-cas-permanent-vectors.sage` with
//! `@/citation/SageMath2026` `Matrix.permanent()`. The CSV header records the
//! generator seed and grid.

#[cfg(all(feature = "f5", feature = "f7"))]
mod tests {
    use gf2_algebra::packed::{Packed5Matrix, Packed7Matrix};
    use gf2_algebra::permanent::{permanent_bipedal5, permanent_bipedal7};
    use gf2_core::gfp::Fp;

    /// Parse the CAS CSV and return `(q, n, row_major_entries, expected)` for
    /// every data row (non-comment, non-header lines).
    fn parse_csv(csv: &str) -> Vec<(u64, usize, Vec<u64>, u64)> {
        let mut rows = Vec::new();
        for line in csv.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') || line.starts_with("q,") {
                continue;
            }
            // Row format: 5,4,2 4 4 4 / 0 0 2 1 / 0 3 2 2 / 3 3 2 2,2
            // The matrix field contains spaces and '/' but never commas.
            let parts: Vec<&str> = line.splitn(4, ',').collect();
            assert_eq!(
                parts.len(),
                4,
                "CSV line malformed (expected 4 comma-separated fields): {line:?}"
            );
            let q: u64 = parts[0].trim().parse().expect("q must be an integer");
            let n: usize = parts[1].trim().parse().expect("n must be an integer");
            let mat_str = parts[2].trim().trim_matches('"');
            let expected: u64 = parts[3]
                .trim()
                .trim_matches('"')
                .parse()
                .expect("expected_permanent must be an integer");

            let mut entries = Vec::with_capacity(n * n);
            for row_str in mat_str.split(" / ") {
                for tok in row_str.split_whitespace() {
                    let v: u64 = tok.parse().expect("matrix entry must be an integer");
                    entries.push(v);
                }
            }
            assert_eq!(
                entries.len(),
                n * n,
                "CSV row has wrong number of matrix entries: expected {}, got {}; line={line:?}",
                n * n,
                entries.len()
            );

            rows.push((q, n, entries, expected));
        }
        rows
    }

    /// `permanent_bipedal5` matches the `@/citation/SageMath2026` permanent on every `q = 5` row.
    #[test]
    fn cas_cross_validation_f5() {
        let csv = include_str!("data/cas_permanent_f5_f7.csv");
        let rows = parse_csv(csv);
        let f5_rows: Vec<_> = rows.iter().filter(|(q, _, _, _)| *q == 5).collect();
        assert!(
            !f5_rows.is_empty(),
            "cas_permanent_f5_f7.csv contains no F_5 rows"
        );
        for (idx, (q, n, entries, expected)) in f5_rows.iter().enumerate() {
            let mat_entries: Vec<Fp<5>> = entries.iter().map(|&v| Fp::<5>::new(v)).collect();
            let mat = Packed5Matrix::from_row_major(&mat_entries, *n, *n);
            let got = permanent_bipedal5(&mat);
            let exp = Fp::<5>::new(*expected);
            assert_eq!(
                got,
                exp,
                "F_5 CAS mismatch: q={q}, n={n}, row_index={idx}, \
                 computed={}, expected={}",
                got.value(),
                exp.value(),
            );
        }
    }

    /// `permanent_bipedal7` matches the `@/citation/SageMath2026` permanent on every `q = 7` row.
    #[test]
    fn cas_cross_validation_f7() {
        let csv = include_str!("data/cas_permanent_f5_f7.csv");
        let rows = parse_csv(csv);
        let f7_rows: Vec<_> = rows.iter().filter(|(q, _, _, _)| *q == 7).collect();
        assert!(
            !f7_rows.is_empty(),
            "cas_permanent_f5_f7.csv contains no F_7 rows"
        );
        for (idx, (q, n, entries, expected)) in f7_rows.iter().enumerate() {
            let mat_entries: Vec<Fp<7>> = entries.iter().map(|&v| Fp::<7>::new(v)).collect();
            let mat = Packed7Matrix::from_row_major(&mat_entries, *n, *n);
            let got = permanent_bipedal7(&mat);
            let exp = Fp::<7>::new(*expected);
            assert_eq!(
                got,
                exp,
                "F_7 CAS mismatch: q={q}, n={n}, row_index={idx}, \
                 computed={}, expected={}",
                got.value(),
                exp.value(),
            );
        }
    }
}
