-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [seam_shape]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import M5SeamShape.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open seam_shape

/-- [seam_shape::field::{impl seam_shape::field::Hooked for seam_shape::field::Elem}::value]:
    Source: 'src/field.rs', lines 40:4-42:5
    Visibility: public -/
axiom field.Elem.Insts.Seam_shapeFieldHooked.value
  : field.Elem → Result Std.U64

