-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::fmt::builders::DebugStruct]
    Source: '/rustc/library/core/src/fmt/builders.rs', lines 88:0-88:34
    Name pattern: [core::fmt::builders::DebugStruct]
    Visibility: public -/
@[rust_type "core::fmt::builders::DebugStruct" (mutRegions := #[0])]
axiom core.fmt.builders.DebugStruct : Type

