-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [seam_shape]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [seam_shape::field::Elem]
    Source: 'src/field.rs', lines 16:0-16:25
    Visibility: public -/
axiom field.Elem : Type

