#!/usr/bin/env python3
"""Project this issue's committed receipts into evidence tables.

Usage: dev/active/1d0da41f/survey/summarize.py

Reads only committed receipts, acceptance summaries, receipt-local input
snapshots, frozen addenda and the committed validation record, and writes
`dev/bench_results/1d0da41f/tables.md`. Every number in the output is
recomputed or projected from those files; nothing is transcribed by hand.

Speedups, intervals, decisions and outcomes come from the acceptance summaries
that `benchmark-acceptance` recomputes from the raw pairs. The reciprocal
columns are algebraic transformations of those same estimates and endpoints and
add no samples. Per-arm call times, window counts, selected dispatch paths and
conversion diagnostics are descriptive summaries of the per-execution values in
`receipt.json`; they carry no confidence interval and decide nothing.
"""

import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir, os.pardir))
BENCH = os.path.join(ROOT, "dev", "bench_results", "1d0da41f")
ACTIVE = os.path.join(ROOT, "dev", "active", "1d0da41f")

V1_PILOT = "2026-09-07-1d0da41f-clmul-dispatch-pilot"
V1_CONFIRMATION = "2026-09-08-1d0da41f-clmul-dispatch-confirmation"
V3_PILOT = "v3-pilot"
V3_PILOT_R2 = "v3-pilot-r2"
V3_CONFIRMATION = "v3-confirmation"

CAMPAIGNS = [V1_PILOT, V1_CONFIRMATION, V3_PILOT, V3_PILOT_R2, V3_CONFIRMATION]

ADDENDA = [
    ("Protocol-v1 exploratory pilot", "addendum-ymm-clmul-dispatch-pilot.json"),
    ("Protocol-v1 confirmation", "addendum-ymm-clmul-dispatch.json"),
    ("Protocol-v3 exploratory pilot", "addendum-ymm-clmul-v3-pilot.json"),
    ("Protocol-v3 resolution pilot", "addendum-ymm-clmul-v3-pilot-r2.json"),
    ("Protocol-v3 confirmation", "addendum-ymm-clmul-v3-confirmation.json"),
]

TAIL_DRAWS_REQUIRED = 20.0

PREAMBLE = [
    "> **Diátaxis Type:** Reference",
    "",
    "Generated by `dev/active/1d0da41f/survey/summarize.py` from the committed receipts,",
    "acceptance summaries, receipt-local snapshots, frozen addenda and validation record",
    "named in each table. Speedup is `median(baseline) / median(candidate)`: below 1 means",
    "the YMM candidate takes longer than the sequential baseline. The candidate-over-baseline",
    "columns are the algebraic reciprocals of the same estimate and endpoints, not new samples.",
    "Relative half-width is `max(estimate - lower, upper - estimate) / estimate`.",
    "Per-arm call times, selected dispatch paths and conversion diagnostics are descriptive:",
    "they carry no interval and decide nothing.",
    "",
]


def load(directory, name):
    with open(os.path.join(BENCH, directory, name), encoding="utf-8") as handle:
        return json.load(handle)


def load_active(name):
    with open(os.path.join(ACTIVE, name), encoding="utf-8") as handle:
        return json.load(handle)


def table(lines, header, rows):
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")


def fmt_interval(interval):
    return "{:.4f} [{:.4f}, {:.4f}]".format(
        interval["estimate"], interval["lower"], interval["upper"]
    )


def fmt_reciprocal(interval):
    return "{:.4f} [{:.4f}, {:.4f}]".format(
        1.0 / interval["estimate"], 1.0 / interval["upper"], 1.0 / interval["lower"]
    )


def relative_half_width(interval):
    estimate = interval["estimate"]
    return max(estimate - interval["lower"], interval["upper"] - estimate) / estimate


def flagged(cell, factor):
    windows = 0
    marked = 0
    for pair in cell["pairs"]:
        for side in ("baseline", "candidate"):
            execution = pair[side]
            medians = [w["elapsed_ns"] / w["calls"] for w in execution["windows"]]
            if not medians:
                continue
            median = statistics.median(medians)
            windows += len(medians)
            marked += sum(1 for value in medians if value >= factor * median)
    return marked, windows


def source_line(directory):
    summary = load(directory, "acceptance-summary.json")
    receipt = load(directory, "receipt.json")
    family = summary["family"]
    return summary, receipt, (
        "Source: `{}/acceptance-summary.json` (receipt `{}`), label **{}**, verdict "
        "**{}**, qualifies {}, {} findings, {} sessions, resumed {}. Family `{}`: {} "
        "comparisons, family-wise alpha {:g}, per-comparison confidence {:.6f}, {} "
        "bootstrap resamples.".format(
            directory,
            summary["receipt_sha256"],
            summary["label"],
            summary["verdict"],
            str(summary["qualifies"]).lower(),
            len(summary["findings"]),
            receipt["execution_log"]["sessions"],
            str(receipt["execution_log"]["resumed"]).lower(),
            family["family_id"],
            family["comparisons"],
            family["family_alpha"],
            family["per_comparison_confidence"],
            family["bootstrap_resamples"],
        )
    )


def cell_decisions(lines, directory):
    summary, receipt, header = source_line(directory)
    lines += [header, ""]
    factor = receipt["settings"]["flagged_window_factor"]
    verdicts = {cell["cell_id"]: cell for cell in summary["cells"]}
    rows = []
    for cell in receipt["cells"]:
        verdict = verdicts[cell["cell_id"]]
        interval = verdict["interval"]
        marked, windows = flagged(cell, factor)
        rows.append([
            "`{}`".format(cell["cell_id"]),
            cell["role"],
            ",".join(str(cpu) for cpu in cell["resolved_cpus"]),
            str(len(cell["pairs"])),
            "{}/{}".format(marked, windows),
            fmt_interval(interval),
            fmt_reciprocal(interval),
            "{:.4f}".format(relative_half_width(interval)),
            verdict["decision"],
            verdict["outcome"],
        ])
    table(lines, [
        "Cell", "Role", "CPUs", "Pairs", "Flagged windows",
        "Speedup [interval]", "Candidate/baseline time ratio [interval]",
        "Relative half-width", "Decision", "Outcome",
    ], rows)
    return summary, receipt


def findings(lines, summary):
    if not summary["findings"]:
        lines += ["No findings.", ""]
        return
    rows = [[
        finding["rule"],
        finding["severity"],
        "`{}`".format(finding["cell"]) if finding.get("cell") else "-",
        finding["message"],
    ] for finding in summary["findings"]]
    table(lines, ["Rule", "Severity", "Cell", "Message"], rows)


def arm_medians(lines, receipt):
    rows = []
    for cell in receipt["cells"]:
        for side in ("baseline", "candidate"):
            executions = [pair[side] for pair in cell["pairs"]]
            if not executions:
                continue
            per_call = [execution["ns_per_call"] for execution in executions]
            paths = sorted({execution["selected_path"] for execution in executions})
            workers = sorted({execution["workers_observed"] for execution in executions})
            states = sorted({execution["cache_state_applied"] for execution in executions})
            rows.append([
                "`{}`".format(cell["cell_id"]),
                side,
                "`{}`".format(receipt["arms"][cell[side + "_arm"]]["build"]),
                str(len(executions)),
                "{:.4f}".format(statistics.median(per_call)),
                "{:.4f}-{:.4f}".format(min(per_call), max(per_call)),
                ", ".join("`{}`".format(path) for path in paths),
                ", ".join(str(value) for value in workers),
                ", ".join(states),
            ])
    table(lines, [
        "Cell", "Side", "Build", "Executions", "Median ns/call", "Call range ns",
        "Selected path", "Workers observed", "Cache state applied",
    ], rows)


def diagnostics(lines, receipt):
    rows = []
    for cell in receipt["cells"]:
        for side in ("baseline", "candidate"):
            conversions = [pair[side]["conversion"] for pair in cell["pairs"]]
            if not conversions:
                continue
            median = lambda key: statistics.median(c[key] for c in conversions)
            rows.append([
                "`{}`".format(cell["cell_id"]),
                side,
                "{:.0f}".format(median("setup_ns")),
                "{:.0f}".format(median("pack_ns")),
                "{:.0f}".format(median("unpack_ns")),
                "{:.0f}".format(median("batch_fill_ns")),
                "{:.0f}".format(median("dispatch_ns")),
            ])
    table(lines, [
        "Cell", "Side", "Median setup ns", "Median pack ns", "Median unpack ns",
        "Median batch-fill ns", "Median dispatch ns",
    ], rows)


def family_accounting(lines, directory, summary, receipt):
    ledger_path = os.path.join(BENCH, directory, "inputs", "trial-ledger.jsonl")
    if not os.path.isfile(ledger_path):
        lines += [
            "This protocol-v1 receipt pins no receipt-local ledger prefix; its family "
            "accounting is the `family` block of its own acceptance summary, projected "
            "in the source line above.",
            "",
        ]
        return
    lines += [
        "Source: `{}/inputs/trial-ledger.jsonl`, the receipt-local ledger prefix pinned "
        "by `receipt.trial_ledger.sha256` = `{}`.".format(
            directory, receipt["trial_ledger"]["sha256"]
        ),
        "",
    ]
    entries = []
    with open(ledger_path, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    table(lines, ["Sequence", "Campaign", "Protocol", "Comparisons", "Candidate identities"], [
        [
            str(entry["sequence"]),
            "`{}`".format(entry["campaign"]),
            str(entry["protocol_version"]),
            str(entry["comparisons"]),
            str(len(entry["candidates"])),
        ]
        for entry in entries
    ])
    addendum = load(directory, os.path.join("inputs", "family-addendum.json"))
    alpha = addendum["family_wise"]["alpha"]
    comparisons = sum(entry["comparisons"] for entry in entries)
    attempts = sum(1 for entry in entries if entry["comparisons"] > 0)
    attempt_alpha = alpha / (attempts * (attempts + 1))
    corrected = attempt_alpha / comparisons
    resamples = receipt["settings"]["bootstrap_resamples"]
    draws = resamples * corrected / 2.0
    agrees = (
        abs(summary["family"]["family_alpha"] - attempt_alpha) < 1e-12
        and abs(summary["family"]["per_comparison_confidence"] - (1.0 - corrected)) < 1e-12
        and summary["family"]["comparisons"] == comparisons
    )
    table(lines, ["Quantity", "Value", "Derivation"], [
        ["family alpha", "{:g}".format(alpha), "frozen addendum `family_wise.alpha`"],
        ["m (reserved comparisons)", str(comparisons), "sum of ledger `comparisons`"],
        ["t (non-exploratory attempts)", str(attempts), "ledger entries with `comparisons` > 0"],
        ["attempt alpha", "{:.6f}".format(attempt_alpha), "alpha / (t (t + 1))"],
        ["corrected alpha", "{:.7f}".format(corrected), "attempt alpha / m"],
        ["confidence", "{:.6f}".format(1.0 - corrected), "1 - corrected alpha"],
        ["bootstrap resamples", str(resamples), "frozen shared setting"],
        ["expected draws per tail", "{:.2f}".format(draws), "resamples x corrected alpha / 2"],
        ["required draws per tail", "{:g}".format(TAIL_DRAWS_REQUIRED), "protocol P-20"],
        ["tail condition", "holds" if draws >= TAIL_DRAWS_REQUIRED else "fails", ""],
        ["summary agrees", "yes" if agrees else "no", "`family` block of the acceptance summary"],
    ])


def sessions(lines, directory, receipt):
    lines += [
        "Source: `{}/receipt.json`; toolchain `{}`.".format(directory, receipt["toolchain"]),
        "",
    ]
    observations = receipt.get("session_hosts") or [receipt["host"]]
    rows = []
    for index, host in enumerate(observations, start=1):
        governors = sorted(set(host["governors"].values()))
        load_average = host["load_average"]
        rows.append([
            str(index),
            host["observed_utc"].split(".")[0].replace("+00:00", "") + "Z"
            if "." in host["observed_utc"] else host["observed_utc"],
            host["hostname"],
            host["cpu_model"],
            host["os_kernel"],
            ", ".join(governors),
            "active" if host["smt_active"] else "inactive",
            str(len(host["affinity"])),
            " / ".join("{:.2f}".format(value) for value in load_average),
        ])
    table(lines, [
        "Session", "Observed", "Host", "CPU", "Kernel", "Governors", "SMT",
        "CPUs in mask", "Load average 1/5/15 min",
    ], rows)


def declared_effects(lines):
    rows = []
    for label, name in ADDENDA:
        addendum = load_active(name)
        effect = addendum["effect"]
        resolution = effect["measurement_resolution"]
        evidence = effect["resolution_evidence"]
        rows.append([
            label,
            "`{}`".format(name),
            "{:g}".format(effect["worthwhile_speedup"]) if effect["worthwhile_speedup"] else "-",
            "{:g}".format(effect["equivalence_margin"]),
            "{:g}".format(effect["material_gap_threshold"]),
            "{:.10g}".format(resolution) if resolution is not None else "not declared",
            "`{}`".format(evidence["sha256"]) if evidence else "-",
        ])
    table(lines, [
        "Addendum role", "File", "Worthwhile speedup", "Equivalence margin",
        "Material-gap threshold", "Declared measurement resolution", "Resolution evidence receipt",
    ], rows)


def validation_record(lines):
    path = os.path.join(ACTIVE, "evidence", "v3-validation.json")
    with open(path, encoding="utf-8") as handle:
        record = json.load(handle)
    lines += [
        "Source: `dev/active/1d0da41f/evidence/v3-validation.json`, the committed "
        "protocol-v3 validation record. Each resolution below is the conservative value "
        "that record derives from the named accepted pilot receipt.",
        "",
    ]
    rows = []
    for key, label in (("pilot", "v3 exploratory pilot"), ("resolution_pilot", "v3 resolution pilot")):
        entry = record[key]
        rows.append([
            label,
            "`{}`".format(entry["receipt_sha256"]),
            "{:.10g}".format(entry["measurement_resolution"]),
            "yes" if entry["margins_admissible"] else "no",
        ])
    table(lines, [
        "Resolution evidence", "Receipt SHA-256", "Derived measurement resolution",
        "Frozen margins admissible",
    ], rows)
    lines += [
        "P-20 incompatibility recorded with the confirmation: {}".format(
            record["confirmation"]["incompatibility"]
        ),
        "",
    ]


def executables(lines):
    rows = []
    for directory in CAMPAIGNS:
        receipt = load(directory, "receipt.json")
        for side in ("baseline", "candidate"):
            arm = receipt["arms"][side]
            rows.append([
                "`{}`".format(directory),
                side,
                arm["build"],
                arm["description"],
                "`{}`".format(arm["executable_sha256"]),
            ])
    table(lines, ["Receipt", "Side", "Build", "Description", "Executable SHA-256"], rows)


def write(path, lines):
    text = "\n".join(lines).rstrip("\n") + "\n"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def main():
    lines = ["# YMM carry-less dispatch evidence tables", ""] + PREAMBLE

    lines += ["## Protocol-v1 confirmation", ""]
    summary, receipt = cell_decisions(lines, V1_CONFIRMATION)
    lines += ["### Findings", ""]
    findings(lines, summary)
    lines += ["### Family accounting", ""]
    family_accounting(lines, V1_CONFIRMATION, summary, receipt)
    lines += ["### Per-arm call time and selected path", ""]
    arm_medians(lines, receipt)
    lines += ["### Untimed conversion diagnostics", ""]
    diagnostics(lines, receipt)
    lines += ["### Sessions and host", ""]
    sessions(lines, V1_CONFIRMATION, receipt)

    lines += ["## Protocol-v3 confirmation", ""]
    summary, receipt = cell_decisions(lines, V3_CONFIRMATION)
    lines += ["### Findings", ""]
    findings(lines, summary)
    lines += ["### Family accounting (P-20)", ""]
    family_accounting(lines, V3_CONFIRMATION, summary, receipt)
    lines += ["### Per-arm call time and selected path", ""]
    arm_medians(lines, receipt)
    lines += ["### Untimed conversion diagnostics", ""]
    diagnostics(lines, receipt)
    lines += ["### Sessions and host", ""]
    sessions(lines, V3_CONFIRMATION, receipt)

    lines += ["## Protocol-v3 exploratory pilots", ""]
    for directory in (V3_PILOT, V3_PILOT_R2):
        summary, receipt = cell_decisions(lines, directory)
        arm_medians(lines, receipt)

    lines += ["## Protocol-v1 exploratory pilot", ""]
    summary, receipt = cell_decisions(lines, V1_PILOT)
    arm_medians(lines, receipt)

    lines += ["## Measurement resolution", ""]
    validation_record(lines)

    lines += ["## Frozen margins and declared resolution", ""]
    declared_effects(lines)

    lines += ["## Arm executables", ""]
    executables(lines)

    write(os.path.join(BENCH, "tables.md"), lines)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
