#!/usr/bin/env python3
"""Checks that every addendum schema digest a receipt pins has a schema file.

The unversioned `addendum.schema.json` always describes the current protocol
version; protocol version 4 amended it in
place rather than adding a version-4 sibling, so an earlier version's schema
survived only inside the receipts whose campaigns pinned it. A frozen
addendum of that earlier version could no longer be validated against a
committed schema from a fresh checkout — only against the specific receipt's
own snapshot copy.

Version 1 itself was pinned under two distinct digests: a wording-only edit
to its `frozen.description` annotation (no `$id`, `const`, `enum`, `required`
or numeric-bound change — see `amendment-v2.md`) split the very first pilot
and confirmation receipts from every later version-1 receipt. Both texts are
committed, each under its own name
(`addendum-v1-initial.schema.json`, `addendum-v1.schema.json`), so this check
has no need for a registry of accepted exceptions: every pinned digest either
equals a committed schema file's digest or the check fails.

This check reads every committed campaign receipt's pinned addendum-schema
digest (`addendum_schema.sha256`) and confirms it equals the digest of some
committed addendum schema file. It identifies the schema files by name and
by a `$id` naming a protocol version, the receipts by the name `receipt.json`,
and the versions table by its `schema` field; receipt input snapshot copies
are not live files. No input is located by a literal repository path.

The check reads committed content only: paths come from `HEAD` (or from the
revision `--revision` names) and bytes from the blobs they name, so the
verdict is the verdict a fresh checkout gets, whatever staged or untracked
files sit in the working tree. `--write` alone reads the index, so the table
can be regenerated together with the schema files it describes before the
commit that carries both.

The version-to-digest table this check derives is recorded in
the committed `schema-versions.json`, generated by `--write` and
verified against the committed copy on every ordinary run so it never drifts.

Usage:
  check-addendum-schema-versions.py [--revision <rev>] [--self-test]
  check-addendum-schema-versions.py --write
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import NamedTuple

from repository_files import is_snapshot_copy, repository_root

SCHEMA_FILE_RE = re.compile(r"^addendum\.schema\.json$|^addendum-v\d+(?:-[a-z]+)?\.schema\.json$")
SCHEMA_ID_RE = re.compile(r"^zen3-benchmark-addendum-v(\d+)$")
VERSIONS_TABLE_NAME = "schema-versions.json"
VERSIONS_TABLE_SCHEMA = "addendum-schema-versions-v1"

UNMATCHED_DIGEST = "addendum schema digest matches no committed schema file"


class SchemaFile(NamedTuple):
    """One committed addendum schema, keyed by its own declared identity."""

    path: str
    sha256: str
    schema_id: str
    version: int


class Pin(NamedTuple):
    """One receipt's pinned addendum-schema digest."""

    receipt: str
    sha256: str


def git(root: Path, *arguments: str) -> bytes:
    """Runs one git command in `root` and returns its raw stdout."""
    return subprocess.run(
        ["git", "-C", str(root), *arguments], capture_output=True, check=True
    ).stdout


def committed_oids(root: Path, revision: str | None = None) -> dict[str, str]:
    """Maps every committed path to the blob it names, in `revision` or the index."""
    listing = (
        git(root, "ls-tree", "-r", "-z", revision)
        if revision is not None
        else git(root, "ls-files", "-s", "-z")
    )
    oids: dict[str, str] = {}
    for record in listing.decode().split("\0"):
        if record:
            metadata, path = record.split("\t", 1)
            oids[path] = metadata.split(" ")[2 if revision is not None else 1]
    return oids


class BlobReader:
    """Reads committed bytes by repository-relative path.

    One `git cat-file --batch` serves every read, following the pattern
    `check-receipt-input-snapshots.py` uses for the same reason: a process per
    file dominates the run once there are more than a handful.
    """

    def __init__(self, root: Path, oids: dict[str, str]) -> None:
        self.oids = oids
        self.process = subprocess.Popen(
            ["git", "-C", str(root), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
        )

    def __call__(self, path: str) -> bytes | None:
        oid = self.oids.get(path)
        if oid is None:
            return None
        self.process.stdin.write(f"{oid}\n".encode())
        self.process.stdin.flush()
        header = self.process.stdout.readline().split()
        if len(header) != 3:
            raise RuntimeError(f"git cat-file does not serve {path}: {header}")
        content = self.process.stdout.read(int(header[2]))
        self.process.stdout.read(1)
        return content

    def close(self) -> None:
        self.process.stdin.close()
        self.process.stdout.close()
        self.process.wait()


def decode(read, path: str) -> object | None:
    """Decodes a committed JSON document, or returns None if it is unusable."""
    content = read(path)
    if content is None:
        return None
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        return None


def versions_table_path(oids: dict[str, str], read, files: list[SchemaFile]) -> str:
    """The committed versions table, else the place `--write` creates it.

    The table is the live `VERSIONS_TABLE_NAME` file whose `schema` field is
    `VERSIONS_TABLE_SCHEMA`; absent one, it belongs beside the schema files.
    """
    for path in sorted(oids):
        if Path(path).name != VERSIONS_TABLE_NAME or is_snapshot_copy(path):
            continue
        document = decode(read, path)
        if isinstance(document, dict) and document.get("schema") == VERSIONS_TABLE_SCHEMA:
            return path
    return str(Path(files[0].path).with_name(VERSIONS_TABLE_NAME))


def schema_files(oids: dict[str, str], read) -> list[SchemaFile]:
    """Lists every live committed addendum schema file.

    More than one file may name the same protocol version: version 1 has two
    (`addendum-v1-initial.schema.json`, `addendum-v1.schema.json`), one per
    digest a committed receipt pins.
    """
    files: list[SchemaFile] = []
    for path in sorted(oids):
        if not SCHEMA_FILE_RE.match(Path(path).name) or is_snapshot_copy(path):
            continue
        content = read(path)
        document = json.loads(content)
        schema_id = document["$id"]
        match = SCHEMA_ID_RE.match(schema_id)
        if not match:
            raise ValueError(f"{path}: $id {schema_id!r} does not name a protocol version")
        files.append(
            SchemaFile(
                path=path,
                sha256=hashlib.sha256(content).hexdigest(),
                schema_id=schema_id,
                version=int(match.group(1)),
            )
        )
    return files


def receipt_paths(oids: dict[str, str]) -> list[str]:
    """Lists every committed campaign receipt, snapshot copies excluded."""
    return sorted(
        path
        for path in oids
        if Path(path).name == "receipt.json" and not is_snapshot_copy(path)
    )


def all_receipt_paths(oids: dict[str, str]) -> list[str]:
    """Lists every committed file named `receipt.json`, snapshot copies included.

    A citation embedded as another receipt's resolution evidence is a
    distinct committed blob that a fresh checkout also carries, so its pinned
    digest is checked too even though `receipt_paths` excludes it from the
    version table's counts to avoid double-counting one campaign.
    """
    return sorted(
        path
        for path in oids
        if Path(path).name == "receipt.json"
    )


def pinned_schema_digests(paths: list[str], read) -> list[Pin]:
    """Collects the addendum-schema digest every listed receipt pins, if any."""
    pins: list[Pin] = []
    for path in paths:
        receipt = decode(read, path)
        if not isinstance(receipt, dict):
            continue
        addendum_schema = receipt.get("addendum_schema")
        if isinstance(addendum_schema, dict) and isinstance(
            addendum_schema.get("sha256"), str
        ):
            pins.append(Pin(receipt=path, sha256=addendum_schema["sha256"]))
    return pins


def build_table(files: list[SchemaFile], counted_pins: list[Pin]) -> dict:
    """Builds the version-to-digest table the versions table records.

    `pinning_receipts` counts committed campaign receipts only (snapshot
    copies excluded), so one campaign is counted once regardless of how many
    resolution-evidence citations repeat its receipt bytes elsewhere. A
    version with two committed schema files (version 1) gets two rows, one
    per file, each counting only the receipts that pin its own digest.
    """
    counts: dict[str, int] = {}
    for pin in counted_pins:
        counts[pin.sha256] = counts.get(pin.sha256, 0) + 1
    versions = [
        {
            "version": file.version,
            "schema_id": file.schema_id,
            "path": file.path,
            "sha256": file.sha256,
            "pinning_receipts": counts.get(file.sha256, 0),
        }
        for file in sorted(files, key=lambda file: (file.version, file.path))
    ]
    return {"schema": VERSIONS_TABLE_SCHEMA, "versions": versions}


def render_table(table: dict) -> bytes:
    return (json.dumps(table, indent=2, sort_keys=False) + "\n").encode()


class Findings(NamedTuple):
    unmatched: list[Pin]
    table: dict
    table_mismatch: str | None


def check(root: Path, revision: str = "HEAD") -> Findings:
    """Evaluates every committed receipt's pinned addendum-schema digest."""
    oids = committed_oids(root, revision)
    read = BlobReader(root, oids)
    try:
        files = schema_files(oids, read)
        known_digests = {file.sha256 for file in files}

        counted_pins = pinned_schema_digests(receipt_paths(oids), read)
        all_pins = pinned_schema_digests(all_receipt_paths(oids), read)
        unmatched = [pin for pin in all_pins if pin.sha256 not in known_digests]

        table = build_table(files, counted_pins)
        table_path = versions_table_path(oids, read, files)
        committed_table = read(table_path)
        rendered = render_table(table)
        table_mismatch = None
        if committed_table != rendered:
            table_mismatch = (
                f"{table_path} is stale: regenerate with --write and commit it"
                if committed_table is not None
                else f"{table_path} is not committed: regenerate with --write"
            )
        return Findings(unmatched=unmatched, table=table, table_mismatch=table_mismatch)
    finally:
        read.close()


def report(pins: list[Pin], stream) -> None:
    for pin in pins:
        print(f"    {pin.receipt}: {pin.sha256} ({UNMATCHED_DIGEST})", file=stream)


FIXTURE_SCHEMAS = "fixture/schemas"
FIXTURE_TABLE = f"{FIXTURE_SCHEMAS}/{VERSIONS_TABLE_NAME}"


def fixture_schema_name(version: int, name: str | None) -> str:
    """The file name a fixture schema takes: the unversioned name for version 4."""
    return name or ("addendum.schema.json" if version == 4 else f"addendum-v{version}.schema.json")


def fixture_schema_content(version: int, schema_id: str, filename: str) -> bytes:
    """A minimal schema whose bytes, and so whose digest, differ per file name."""
    return json.dumps(
        {
            "$id": schema_id,
            "title": filename,
            "properties": {"protocol": {"properties": {"version": {"const": version}}}},
        }
    ).encode()


def write_fixture_schema(root: Path, version: int, schema_id: str, name: str | None = None) -> str:
    """Writes and stages a minimal schema file for `version` and returns its digest."""
    filename = fixture_schema_name(version, name)
    path = f"{FIXTURE_SCHEMAS}/{filename}"
    content = fixture_schema_content(version, schema_id, filename)
    full = root / path
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_bytes(content)
    git(root, "add", "-f", path)
    return hashlib.sha256(content).hexdigest()


def write_fixture_receipt(root: Path, name: str, sha256: str) -> str:
    """Writes and stages a minimal receipt pinning `sha256` and returns its path."""
    path = f"fixture/receipts/{name}/receipt.json"
    full = root / path
    full.parent.mkdir(parents=True)
    full.write_text(json.dumps({"addendum_schema": {"sha256": sha256}}))
    git(root, "add", path)
    return path


def self_test() -> int:
    """Asserts the check accepts every matched digest and rejects an orphan one.

    Exercises the version-1 two-digest case directly: two committed schema
    files legitimately name the same protocol version, and a receipt pinning
    either digest passes. The orphan receipt pins the digest of a schema file
    that is staged but not committed, so the check fails it only because it
    reads `HEAD`; a check that read the index would accept it.
    """
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        git(root, "init", "-q")
        initial = write_fixture_schema(
            root, 1, "zen3-benchmark-addendum-v1", name="addendum-v1-initial.schema.json"
        )
        edited = write_fixture_schema(root, 1, "zen3-benchmark-addendum-v1")
        initial_receipt = write_fixture_receipt(root, "initial", initial)
        edited_receipt = write_fixture_receipt(root, "edited", edited)
        staged_name = "addendum-v1-staged.schema.json"
        staged_digest = hashlib.sha256(
            fixture_schema_content(1, "zen3-benchmark-addendum-v1", staged_name)
        ).hexdigest()
        orphan_receipt = write_fixture_receipt(root, "orphan", staged_digest)
        files = [
            SchemaFile(
                f"{FIXTURE_SCHEMAS}/addendum-v1-initial.schema.json",
                initial,
                "zen3-benchmark-addendum-v1",
                1,
            ),
            SchemaFile(
                f"{FIXTURE_SCHEMAS}/addendum-v1.schema.json", edited, "zen3-benchmark-addendum-v1", 1
            ),
        ]
        table = build_table(files, [Pin(initial_receipt, initial), Pin(edited_receipt, edited)])
        (root / FIXTURE_TABLE).write_bytes(render_table(table))
        git(root, "add", FIXTURE_TABLE)
        git(
            root,
            "-c", "user.name=self-test", "-c", "user.email=self-test@localhost",
            "commit", "-q", "-m", "fixtures",
        )
        staged = write_fixture_schema(root, 1, "zen3-benchmark-addendum-v1", name=staged_name)
        if staged != staged_digest:
            print("self-test: the staged fixture digest is not the one the orphan pins", file=sys.stderr)
            return 1

        findings = check(root)
        if findings.unmatched != [Pin(orphan_receipt, staged_digest)]:
            print(
                f"self-test: expected only the orphan pin unmatched, got {findings.unmatched}",
                file=sys.stderr,
            )
            return 1
        if findings.table_mismatch:
            print(
                f"self-test: expected the fixture table to match, got {findings.table_mismatch}",
                file=sys.stderr,
            )
            return 1

    print("check-addendum-schema-versions: self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true", help="check the checker itself")
    parser.add_argument(
        "--revision", default="HEAD", help="check this committed revision (default HEAD)"
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the versions table on disk from the git index instead of checking it",
    )
    arguments = parser.parse_args()
    if arguments.self_test:
        return self_test()
    root = repository_root(Path(__file__).resolve())
    if arguments.write:
        oids = committed_oids(root)
        read = BlobReader(root, oids)
        try:
            files = schema_files(oids, read)
            table = build_table(files, pinned_schema_digests(receipt_paths(oids), read))
            table_path = versions_table_path(oids, read, files)
        finally:
            read.close()
        (root / table_path).write_bytes(render_table(table))
        print(f"wrote {table_path}")
        return 0

    findings = check(root, arguments.revision)
    if findings.unmatched:
        report(findings.unmatched, sys.stderr)
        print(
            f"{len(findings.unmatched)} receipts pin an addendum schema digest "
            "with no committed schema file",
            file=sys.stderr,
        )
    if findings.table_mismatch:
        print(findings.table_mismatch, file=sys.stderr)
    if findings.unmatched or findings.table_mismatch:
        return 1
    print(
        "check-addendum-schema-versions: every pinned addendum schema digest matches a "
        "committed schema file"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
