#!/usr/bin/env python3
"""Checks that every addendum schema digest a receipt pins has a schema file.

`dev/active/f547c394/addendum.schema.json` is the shared path and always
describes the current protocol version; protocol version 4 amended it in
place rather than adding a version-4 sibling, so an earlier version's schema
survived only inside the receipts whose campaigns pinned it. A frozen
addendum of that earlier version could no longer be validated against a
committed schema from a fresh checkout — only against the specific receipt's
own snapshot copy.

This check reads every committed campaign receipt's pinned addendum-schema
digest (`addendum_schema.sha256`) and confirms it equals the digest of some
committed `dev/active/f547c394/addendum*.schema.json` file. A digest with no
match fails the check unless it is registered in
`dev/scripts/addendum-schema-digest-exceptions.json` — reserved for a receipt
whose pinned bytes differ from the committed schema of its own version by
annotation text only (no `$id`, `const`, `enum`, `required` or numeric-bound
difference), so every instance the two schema texts accept or reject is
identical; see the registered entries for the specific receipts and cause.

The check reads committed content only: paths come from the git index, or
from a named revision, and bytes from the blobs they name, so the verdict is
the verdict a fresh checkout gets, whatever untracked files sit in the
working tree.

The version-to-digest table this check derives is recorded in
`dev/active/f547c394/schema-versions.json`, generated by `--write` and
verified against the committed copy on every ordinary run so it never drifts.

Usage:
  dev/scripts/check-addendum-schema-versions.py [--revision <rev>] [--self-test]
  dev/scripts/check-addendum-schema-versions.py --write
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import NamedTuple

SCHEMA_DIR = "dev/active/f547c394"
SCHEMA_FILE_RE = re.compile(r"^addendum(?:-v\d+)?\.schema\.json$")
SCHEMA_ID_RE = re.compile(r"^zen3-benchmark-addendum-v(\d+)$")
VERSIONS_TABLE = f"{SCHEMA_DIR}/schema-versions.json"
VERSIONS_TABLE_SCHEMA = "addendum-schema-versions-v1"
EXCEPTIONS = "dev/scripts/addendum-schema-digest-exceptions.json"
EXCEPTIONS_SCHEMA = "addendum-schema-digest-exceptions-v1"

UNKNOWN_DIGEST = "addendum schema digest matches no committed schema file"


class SchemaFile(NamedTuple):
    """One committed addendum schema, keyed by its own declared identity."""

    path: str
    sha256: str
    schema_id: str
    version: int


class Pin(NamedTuple):
    """One receipt's pinned addendum-schema digest."""

    receipt: str
    sha256: str


def git(root: Path, *arguments: str) -> bytes:
    """Runs one git command in `root` and returns its raw stdout."""
    return subprocess.run(
        ["git", "-C", str(root), *arguments], capture_output=True, check=True
    ).stdout


def committed_oids(root: Path, revision: str | None = None) -> dict[str, str]:
    """Maps every committed path to the blob it names, in `revision` or the index."""
    listing = (
        git(root, "ls-tree", "-r", "-z", revision)
        if revision is not None
        else git(root, "ls-files", "-s", "-z")
    )
    oids: dict[str, str] = {}
    for record in listing.decode().split("\0"):
        if record:
            metadata, path = record.split("\t", 1)
            oids[path] = metadata.split(" ")[2 if revision is not None else 1]
    return oids


class BlobReader:
    """Reads committed bytes by repository-relative path.

    One `git cat-file --batch` serves every read, following the pattern
    `check-receipt-input-snapshots.py` uses for the same reason: a process per
    file dominates the run once there are more than a handful.
    """

    def __init__(self, root: Path, oids: dict[str, str]) -> None:
        self.oids = oids
        self.process = subprocess.Popen(
            ["git", "-C", str(root), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
        )

    def __call__(self, path: str) -> bytes | None:
        oid = self.oids.get(path)
        if oid is None:
            return None
        self.process.stdin.write(f"{oid}\n".encode())
        self.process.stdin.flush()
        header = self.process.stdout.readline().split()
        if len(header) != 3:
            raise RuntimeError(f"git cat-file does not serve {path}: {header}")
        content = self.process.stdout.read(int(header[2]))
        self.process.stdout.read(1)
        return content

    def close(self) -> None:
        self.process.stdin.close()
        self.process.stdout.close()
        self.process.wait()


def decode(read, path: str) -> object | None:
    """Decodes a committed JSON document, or returns None if it is unusable."""
    content = read(path)
    if content is None:
        return None
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        return None


def schema_files(oids: dict[str, str], read) -> list[SchemaFile]:
    """Lists every committed addendum schema file under `SCHEMA_DIR`."""
    files: list[SchemaFile] = []
    for path in sorted(oids):
        if not path.startswith(f"{SCHEMA_DIR}/"):
            continue
        if not SCHEMA_FILE_RE.match(Path(path).name):
            continue
        content = read(path)
        document = json.loads(content)
        schema_id = document["$id"]
        match = SCHEMA_ID_RE.match(schema_id)
        if not match:
            raise ValueError(f"{path}: $id {schema_id!r} does not name a protocol version")
        files.append(
            SchemaFile(
                path=path,
                sha256=hashlib.sha256(content).hexdigest(),
                schema_id=schema_id,
                version=int(match.group(1)),
            )
        )
    return files


def receipt_paths(oids: dict[str, str]) -> list[str]:
    """Lists every committed campaign receipt, snapshot copies excluded."""
    return sorted(
        path
        for path in oids
        if path.startswith("dev/bench_results/")
        and path.endswith("/receipt.json")
        and "/inputs/" not in path
    )


def all_receipt_paths(oids: dict[str, str]) -> list[str]:
    """Lists every committed file named `receipt.json`, snapshot copies included.

    A citation embedded as another receipt's resolution evidence is a
    distinct committed blob that a fresh checkout also carries, so its pinned
    digest is checked too even though `receipt_paths` excludes it from the
    version table's counts to avoid double-counting one campaign.
    """
    return sorted(
        path
        for path in oids
        if path.startswith("dev/bench_results/") and path.endswith("/receipt.json")
    )


def pinned_schema_digests(paths: list[str], read) -> list[Pin]:
    """Collects the addendum-schema digest every listed receipt pins, if any."""
    pins: list[Pin] = []
    for path in paths:
        receipt = decode(read, path)
        if not isinstance(receipt, dict):
            continue
        addendum_schema = receipt.get("addendum_schema")
        if isinstance(addendum_schema, dict) and isinstance(
            addendum_schema.get("sha256"), str
        ):
            pins.append(Pin(receipt=path, sha256=addendum_schema["sha256"]))
    return pins


def registered_exceptions(read) -> tuple[set[tuple[str, str]], list[str]]:
    """Reads the registry of receipts whose pinned digest is a named exception."""
    registry = decode(read, EXCEPTIONS)
    if registry is None:
        return set(), []
    if not isinstance(registry, dict) or registry.get("schema") != EXCEPTIONS_SCHEMA:
        return set(), [f"{EXCEPTIONS}: schema is not {EXCEPTIONS_SCHEMA}"]
    return {
        (entry["receipt"], entry["sha256"]) for entry in registry["exceptions"]
    }, []


def build_table(files: list[SchemaFile], counted_pins: list[Pin]) -> dict:
    """Builds the version-to-digest table `VERSIONS_TABLE` records.

    `pinning_receipts` counts committed campaign receipts only (snapshot
    copies excluded), so one campaign is counted once regardless of how many
    resolution-evidence citations repeat its receipt bytes elsewhere.
    """
    counts: dict[str, int] = {}
    for pin in counted_pins:
        counts[pin.sha256] = counts.get(pin.sha256, 0) + 1
    versions = [
        {
            "version": file.version,
            "schema_id": file.schema_id,
            "path": file.path,
            "sha256": file.sha256,
            "pinning_receipts": counts.get(file.sha256, 0),
        }
        for file in sorted(files, key=lambda file: file.version)
    ]
    return {"schema": VERSIONS_TABLE_SCHEMA, "versions": versions}


def render_table(table: dict) -> bytes:
    return (json.dumps(table, indent=2, sort_keys=False) + "\n").encode()


class Findings(NamedTuple):
    unregistered: list[Pin]
    recorded: list[Pin]
    stale: list[str]
    duplicate_versions: list[str]
    table: dict
    table_mismatch: str | None


def check(root: Path, revision: str | None = None) -> Findings:
    """Evaluates every committed receipt's pinned addendum-schema digest."""
    oids = committed_oids(root, revision)
    read = BlobReader(root, oids)
    try:
        files = schema_files(oids, read)
        by_version: dict[int, list[SchemaFile]] = {}
        for file in files:
            by_version.setdefault(file.version, []).append(file)
        duplicate_versions = [
            f"protocol version {version} has {len(group)} committed schema files: "
            f"{', '.join(sorted(file.path for file in group))}"
            for version, group in sorted(by_version.items())
            if len(group) > 1
        ]
        known_digests = {file.sha256 for file in files}

        counted_pins = pinned_schema_digests(receipt_paths(oids), read)
        all_pins = pinned_schema_digests(all_receipt_paths(oids), read)
        exceptions, exception_errors = registered_exceptions(read)

        # A "problem" pin is one whose digest matches no committed schema
        # file; every other pin needs no exception and is dropped here.
        problems = [pin for pin in all_pins if pin.sha256 not in known_digests]
        problem_keys = {(pin.receipt, pin.sha256) for pin in problems}
        unregistered = [
            pin for pin in problems if (pin.receipt, pin.sha256) not in exceptions
        ]
        recorded = [pin for pin in problems if (pin.receipt, pin.sha256) in exceptions]
        stale = exception_errors + [
            f"{EXCEPTIONS} registers {sha256} for {receipt}, which is not a problem"
            for receipt, sha256 in sorted(exceptions - problem_keys)
        ]

        table = build_table(files, counted_pins)
        committed_table = read(VERSIONS_TABLE)
        rendered = render_table(table)
        table_mismatch = None
        if committed_table != rendered:
            table_mismatch = (
                f"{VERSIONS_TABLE} is stale: regenerate with --write and commit it"
                if committed_table is not None
                else f"{VERSIONS_TABLE} is not committed: regenerate with --write"
            )
        return Findings(
            unregistered=unregistered,
            recorded=recorded,
            stale=stale,
            duplicate_versions=duplicate_versions,
            table=table,
            table_mismatch=table_mismatch,
        )
    finally:
        read.close()


def report(pins: list[Pin], stream) -> None:
    for pin in pins:
        print(f"    {pin.receipt}: {pin.sha256} ({UNKNOWN_DIGEST})", file=stream)


def write_fixture_schema(root: Path, version: int, schema_id: str) -> str:
    """Stages a minimal committed schema file for `version` and returns its digest."""
    name = "addendum.schema.json" if version == 4 else f"addendum-v{version}.schema.json"
    path = f"{SCHEMA_DIR}/{name}"
    content = json.dumps(
        {
            "$id": schema_id,
            "properties": {"protocol": {"properties": {"version": {"const": version}}}},
        }
    ).encode()
    full = root / path
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_bytes(content)
    git(root, "add", "-f", path)
    return hashlib.sha256(content).hexdigest()


def write_fixture_receipt(root: Path, name: str, sha256: str) -> str:
    """Stages a minimal committed receipt pinning `sha256` and returns its path."""
    path = f"dev/bench_results/fixture/{name}/receipt.json"
    full = root / path
    full.parent.mkdir(parents=True)
    full.write_text(json.dumps({"addendum_schema": {"sha256": sha256}}))
    git(root, "add", path)
    return path


def self_test() -> int:
    """Asserts the check accepts a matched digest and rejects an orphan one."""
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        git(root, "init", "-q")
        known = write_fixture_schema(root, 1, "zen3-benchmark-addendum-v1")
        known_receipt = write_fixture_receipt(root, "known", known)
        orphan_receipt = write_fixture_receipt(
            root, "orphan", "0" * 64
        )
        table = build_table(
            [
                SchemaFile(
                    f"{SCHEMA_DIR}/addendum-v1.schema.json", known, "zen3-benchmark-addendum-v1", 1
                )
            ],
            [Pin(known_receipt, known)],
        )
        (root / VERSIONS_TABLE).parent.mkdir(parents=True, exist_ok=True)
        (root / VERSIONS_TABLE).write_bytes(render_table(table))
        git(root, "add", VERSIONS_TABLE)

        findings = check(root)
        if findings.unregistered != [Pin(orphan_receipt, "0" * 64)]:
            print(
                f"self-test: expected the orphan pin unregistered, got {findings.unregistered}",
                file=sys.stderr,
            )
            return 1
        if findings.recorded or findings.stale or findings.duplicate_versions:
            print(f"self-test: expected a clean pass otherwise, got {findings}", file=sys.stderr)
            return 1
        if findings.table_mismatch:
            print(f"self-test: expected the fixture table to match, got {findings.table_mismatch}", file=sys.stderr)
            return 1

        registry = root / EXCEPTIONS
        registry.parent.mkdir(parents=True, exist_ok=True)
        registry.write_text(
            json.dumps(
                {
                    "schema": EXCEPTIONS_SCHEMA,
                    "exceptions": [{"receipt": orphan_receipt, "sha256": "0" * 64}],
                }
            )
        )
        git(root, "add", EXCEPTIONS)
        findings = check(root)
        if findings.unregistered or not findings.recorded:
            print(
                f"self-test: expected the registered pin recorded, got {findings}",
                file=sys.stderr,
            )
            return 1

        stale_receipt = write_fixture_receipt(root, "stale", known)
        registry.write_text(
            json.dumps(
                {
                    "schema": EXCEPTIONS_SCHEMA,
                    "exceptions": [
                        {"receipt": orphan_receipt, "sha256": "0" * 64},
                        {"receipt": stale_receipt, "sha256": known},
                    ],
                }
            )
        )
        table = build_table(
            [
                SchemaFile(
                    f"{SCHEMA_DIR}/addendum-v1.schema.json", known, "zen3-benchmark-addendum-v1", 1
                )
            ],
            [Pin(known_receipt, known), Pin(stale_receipt, known)],
        )
        (root / VERSIONS_TABLE).write_bytes(render_table(table))
        git(root, "add", EXCEPTIONS, VERSIONS_TABLE)
        findings = check(root)
        if not findings.stale:
            print("self-test: expected the now-matched exception flagged stale", file=sys.stderr)
            return 1

    print("check-addendum-schema-versions: self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true", help="check the checker itself")
    parser.add_argument("--revision", help="check this revision instead of the git index")
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"regenerate {VERSIONS_TABLE} on disk from the git index instead of checking it",
    )
    arguments = parser.parse_args()
    if arguments.self_test:
        return self_test()
    root = Path(git(Path.cwd(), "rev-parse", "--show-toplevel").decode().strip())
    if arguments.write:
        oids = committed_oids(root)
        read = BlobReader(root, oids)
        try:
            table = build_table(schema_files(oids, read), pinned_schema_digests(receipt_paths(oids), read))
        finally:
            read.close()
        (root / VERSIONS_TABLE).write_bytes(render_table(table))
        print(f"wrote {VERSIONS_TABLE}")
        return 0

    findings = check(root, arguments.revision)
    if findings.duplicate_versions:
        for message in findings.duplicate_versions:
            print(message, file=sys.stderr)
    if findings.recorded:
        print(f"recorded in {EXCEPTIONS}:")
        for pin in findings.recorded:
            print(f"    {pin.receipt}: {pin.sha256}")
    for message in findings.stale:
        print(message, file=sys.stderr)
    if findings.unregistered:
        report(findings.unregistered, sys.stderr)
        print(
            f"{len(findings.unregistered)} receipts pin an addendum schema digest "
            "with no committed schema file",
            file=sys.stderr,
        )
    if findings.table_mismatch:
        print(findings.table_mismatch, file=sys.stderr)
    if findings.unregistered or findings.stale or findings.duplicate_versions or findings.table_mismatch:
        return 1
    print(
        "check-addendum-schema-versions: every pinned addendum schema digest matches a "
        "committed schema file"
        + (f", {len(findings.recorded)} recorded as a named exception" if findings.recorded else "")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
