//! `SparseFieldMatrix::matvec` — Criterion benchmarks at every
//! (field, density, size) cell of the `64c88ae4` story matrix's sparse
//! arm, plus the issue `8a90882e` deliverable.
//!
//! Issue `6ed7f050`. Sibling of (the deferred T2 sparse arm of) the
//! reference container harness. Sparse SpMV reference numbers come
//! from a separate harness — fflas-ffpack's sparse interface is via
//! LinBox proper, not fflas-ffpack itself. The gf2 side keeps its own
//! seeded generators here and the cross-library comparison lands when
//! the LinBox harness is added.
//!
//! ## Coverage
//!
//! - **Sizes**: `n ∈ {256, 1024, 4096}`.
//! - **Densities**: `0.01` (1 %), `0.05` (5 %).
//! - **Fields**: `Fp<7>`, `Fp<251>`, `Fp<65521>`, `Fp<2^31-1>`,
//!   `Gf2mWide<1, M=8 AES>`, `Gf2mWide<1, M=16 Conway>`.
//!
//! ## Determinism contract
//!
//! Sparse fixtures consume the same SplitMix64 stream as the dense
//! benches, **but** the support pattern (which `(i, j)` cells are
//! non-zero) is generated by an additional Bernoulli draw per cell from
//! the same stream, *before* the value draw. The fixture is therefore
//! a deterministic function of `(field, density, size)` and the master
//! seed, but it is **not** byte-comparable to a hypothetical fflas /
//! M4RI sparse fixture that uses a different sparsity-sampling scheme.
//! Documented here as the contract a future LinBox harness must match.
//!
//! ## Usage
//!
//! ```bash
//! cargo bench -p gf2-core --bench sparse_spmv --features rand
//! cargo bench -p gf2-core --bench sparse_spmv --features rand -- --test
//! cargo bench -p gf2-core --bench sparse_spmv --features rand -- spmv/Fp_M31/0.01/1024
//! ```

use criterion::{black_box, criterion_group, criterion_main, BenchmarkId, Criterion};
use gf2_core::field::matrix::FieldMatrix;
use gf2_core::field::sparse_matrix::SparseFieldMatrix;
use gf2_core::field::vec::FieldVec;
use gf2_core::field::FiniteField;
use gf2_core::gf2m::{Gf2mWide, Gf2mWideConfig};
use gf2_core::gfp::Fp;

#[path = "common/seed.rs"]
mod seed;

use seed::{derive_seed, splitmix64, MASTER_SEED};

const PRIME_7: u64 = 7;
const PRIME_251: u64 = 251;
const PRIME_65521: u64 = 65521;
const MERSENNE_31: u64 = 2_147_483_647;

/// GF(2^8) AES irreducible.
struct SpGf2m8Cfg;
impl Gf2mWideConfig<1> for SpGf2m8Cfg {
    const M: usize = 8;
    const MODULUS: [u64; 1] = [0x1B];
    const NAME: &'static str = "SpGf2m8Cfg";
}
type Gf2m8 = Gf2mWide<1, SpGf2m8Cfg>;

/// GF(2^16) Conway polynomial.
struct SpGf2m16Cfg;
impl Gf2mWideConfig<1> for SpGf2m16Cfg {
    const M: usize = 16;
    const MODULUS: [u64; 1] = [0x002D];
    const NAME: &'static str = "SpGf2m16Cfg";
}
type Gf2m16 = Gf2mWide<1, SpGf2m16Cfg>;

const SIZES: &[usize] = &[256, 1024, 4096];
const DENSITIES: &[(f64, &str)] = &[(0.01, "0.01"), (0.05, "0.05")];

// ─── Sparse fillers ─────────────────────────────────────────────────────────
//
// Each cell `(i, j)` is included iff a SplitMix64 draw in `[0, 1)` is
// below `density`. When included, a second SplitMix64 draw becomes the
// non-zero value (reduced into the field). This keeps both the support
// pattern and the values deterministic in the row seed.
//
// Non-zero values are clamped away from zero so the support pattern
// matches the include-decision exactly: a 0-valued included cell would
// not appear as a stored entry in the CSR conversion.

fn random_sparse_fp<const P: u64>(
    rows: usize,
    cols: usize,
    density: f64,
    seed_val: u64,
) -> SparseFieldMatrix<Fp<P>> {
    let mut st = seed_val;
    let mut m = FieldMatrix::<Fp<P>>::zeros(rows, cols);
    let threshold = (density * (u64::MAX as f64 + 1.0)) as u64;
    for r in 0..rows {
        for c in 0..cols {
            let draw = splitmix64(&mut st);
            if draw < threshold {
                let v_raw = splitmix64(&mut st);
                // Avoid zero so the included cell shows up in CSR.
                let v = (v_raw % (P - 1)) + 1;
                m.set(r, c, Fp::<P>::new(v));
            }
        }
    }
    SparseFieldMatrix::from_dense(&m)
}

fn random_sparse_gf2m_wide_1<C: Gf2mWideConfig<1>>(
    rows: usize,
    cols: usize,
    density: f64,
    seed_val: u64,
) -> SparseFieldMatrix<Gf2mWide<1, C>> {
    let mask: u64 = if C::M >= 64 {
        u64::MAX
    } else {
        (1u64 << C::M) - 1
    };
    let mut st = seed_val;
    let mut m = FieldMatrix::<Gf2mWide<1, C>>::zeros(rows, cols);
    let threshold = (density * (u64::MAX as f64 + 1.0)) as u64;
    for r in 0..rows {
        for c in 0..cols {
            let draw = splitmix64(&mut st);
            if draw < threshold {
                let v_raw = splitmix64(&mut st) & mask;
                let v = if v_raw == 0 { 1 } else { v_raw };
                m.set(r, c, Gf2mWide::<1, C>::new([v]));
            }
        }
    }
    SparseFieldMatrix::from_dense(&m)
}

fn fp_vec<const P: u64>(n: usize, seed_val: u64) -> FieldVec<Fp<P>> {
    let mut st = seed_val;
    (0..n)
        .map(|_| Fp::<P>::new(splitmix64(&mut st) % P))
        .collect()
}

fn gf2m_vec<C: Gf2mWideConfig<1>>(n: usize, seed_val: u64) -> FieldVec<Gf2mWide<1, C>> {
    let mask: u64 = if C::M >= 64 {
        u64::MAX
    } else {
        (1u64 << C::M) - 1
    };
    let mut st = seed_val;
    (0..n)
        .map(|_| Gf2mWide::<1, C>::new([splitmix64(&mut st) & mask]))
        .collect()
}

fn run_field<F, BuildSparse, BuildVec>(
    c: &mut Criterion,
    field_label: &str,
    sizes: &[usize],
    densities: &[(f64, &str)],
    build_sparse: BuildSparse,
    build_vec: BuildVec,
) where
    F: FiniteField,
    BuildSparse: Fn(usize, usize, f64, u64) -> SparseFieldMatrix<F>,
    BuildVec: Fn(usize, u64) -> FieldVec<F>,
{
    for (di, &(density, density_label)) in densities.iter().enumerate() {
        let group_name = format!("spmv/{field_label}/{density_label}");
        let mut group = c.benchmark_group(&group_name);
        group.sample_size(10);
        group.measurement_time(std::time::Duration::from_secs(5));
        for (si, &n) in sizes.iter().enumerate() {
            let row_seed = derive_seed(MASTER_SEED, "spmv", 11, si as u64, di as u64);
            let vec_seed = derive_seed(MASTER_SEED, "spmv_vec", 11, si as u64, di as u64);
            let a = build_sparse(n, n, density, row_seed);
            let x = build_vec(n, vec_seed);
            group.bench_with_input(BenchmarkId::from_parameter(n), &n, |bench, _| {
                bench.iter(|| {
                    let y = black_box(&a).matvec(black_box(&x));
                    black_box(y);
                });
            });
        }
        group.finish();
    }
}

fn bench_fp_7(c: &mut Criterion) {
    run_field::<Fp<PRIME_7>, _, _>(
        c,
        "Fp_7",
        SIZES,
        DENSITIES,
        random_sparse_fp::<PRIME_7>,
        fp_vec::<PRIME_7>,
    );
}

fn bench_fp_251(c: &mut Criterion) {
    run_field::<Fp<PRIME_251>, _, _>(
        c,
        "Fp_251",
        SIZES,
        DENSITIES,
        random_sparse_fp::<PRIME_251>,
        fp_vec::<PRIME_251>,
    );
}

fn bench_fp_65521(c: &mut Criterion) {
    run_field::<Fp<PRIME_65521>, _, _>(
        c,
        "Fp_65521",
        SIZES,
        DENSITIES,
        random_sparse_fp::<PRIME_65521>,
        fp_vec::<PRIME_65521>,
    );
}

fn bench_fp_m31(c: &mut Criterion) {
    run_field::<Fp<MERSENNE_31>, _, _>(
        c,
        "Fp_M31",
        SIZES,
        DENSITIES,
        random_sparse_fp::<MERSENNE_31>,
        fp_vec::<MERSENNE_31>,
    );
}

fn bench_gf2m8(c: &mut Criterion) {
    run_field::<Gf2m8, _, _>(
        c,
        "Gf2m8",
        SIZES,
        DENSITIES,
        random_sparse_gf2m_wide_1::<SpGf2m8Cfg>,
        gf2m_vec::<SpGf2m8Cfg>,
    );
}

fn bench_gf2m16(c: &mut Criterion) {
    run_field::<Gf2m16, _, _>(
        c,
        "Gf2m16",
        SIZES,
        DENSITIES,
        random_sparse_gf2m_wide_1::<SpGf2m16Cfg>,
        gf2m_vec::<SpGf2m16Cfg>,
    );
}

criterion_group! {
    name = spmv_benches;
    config = Criterion::default()
        .sample_size(10)
        .measurement_time(std::time::Duration::from_secs(5));
    targets =
        bench_fp_7,
        bench_fp_251,
        bench_fp_65521,
        bench_fp_m31,
        bench_gf2m8,
        bench_gf2m16
}
criterion_main!(spmv_benches);
