#!/usr/bin/env bash
# Record why the stock gf2x build configuration fails on this host
# (jit:c7113c5a).
#
# Usage:
#   ./probe-stock-build.sh [output-file] [staging-directory]
#
# Configures and builds the exported gf2x source with the flags of the
# conservative variant but without the CC_FOR_BUILD override fetch-build.sh
# passes, in a scratch directory under the staging area, and extracts the
# build-compiler probe results and the first build errors into the output.
# The survey's builds never use this configuration; the record is the
# evidence for the override.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(git -C "${HERE}" rev-parse --show-toplevel)"
ISSUE=c7113c5a
OUT="${1:-${HERE}/gf2x-stock-build-probe.txt}"
EXT="${2:-${GF2_SURVEY_EXT:-${REPO}/target/${ISSUE}-ext}}"
DIR="${EXT}/stock-cc-for-build"
shared() { "${REPO}/scripts/cargo-budget.sh" "$@"; }

rm -rf "${DIR}"
mkdir -p "${DIR}"
cd "${DIR}"
set +e
CFLAGS="-O2" shared "${EXT}/gf2x/configure" --prefix="${DIR}/prefix" \
    --disable-static --enable-shared >configure.log 2>&1
configure_status=$?
shared make -j12 >make.log 2>&1
make_status=$?
set -e

{
    echo "# gf2x stock build probe (jit:${ISSUE})"
    echo "# generated by dev/active/${ISSUE}/survey/probe-stock-build.sh"
    echo
    echo "source commit  $(cat "${EXT}/gf2x/.source-commit")"
    echo "cc             $(gcc --version | head -1)"
    echo "configure      CFLAGS=-O2 configure --disable-static --enable-shared (no CC_FOR_BUILD)"
    echo "configure exit ${configure_status}"
    echo
    echo "build-compiler probe (configure output)"
    grep -E '^checking build system compiler' configure.log | sed 's/^/  /'
    echo
    echo "first rejection of gcc as build compiler (config.log)"
    grep -m1 -A2 "error: implicit declaration of function 'exit'" config.log | sed 's/^/  /'
    echo
    echo "make exit ${make_status}"
    echo "first build errors (make output)"
    grep -m6 -E 'error|Error' make.log | sed 's/^/  /'
} >"${OUT}"
echo "wrote ${OUT}" >&2
