#!/usr/bin/env bash
# Record the gf2x build evidence REQ-02 requires (jit:c7113c5a).
#
# Usage:
#   ./record-build-evidence.sh [output-file] [staging-directory]
#
# Reads the three build trees `fetch-build.sh` produced and emits, for each
# variant: the source pin, the configure-resolved ABI/CFLAGS/hwdir, the
# already_tuned basecase headers configure linked in, the algorithm thresholds
# those headers install, the library digest, and the carry-less-multiply
# instruction census with the symbols that carry it. Every line is extracted
# from the build tree at run time; nothing here is transcribed by hand.
# Re-running it after a rebuild refreshes the artifact.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(git -C "${HERE}" rev-parse --show-toplevel)"
ISSUE=c7113c5a
OUT="${1:-${HERE}/gf2x-build-evidence.txt}"
EXT="${2:-${GF2_SURVEY_EXT:-${REPO}/.agents/ext/${ISSUE}}}"
LIB=lib/libgf2x.so.3.0.0

emit() {
    echo "# gf2x build evidence (jit:${ISSUE})"
    echo "# generated by dev/active/${ISSUE}/survey/record-build-evidence.sh"
    echo
    echo "source"
    echo "  url          $(git -C "${EXT}/gf2x" remote get-url origin)"
    echo "  commit       $(git -C "${EXT}/gf2x" rev-parse HEAD)"
    echo "  tag          $(git -C "${EXT}/gf2x" describe --tags --exact-match 2>/dev/null || echo '(detached)')"
    echo "  toom-gpl.c   $(stat -c %s "${EXT}/gf2x/toom-gpl.c") bytes (placeholder is 1384; a real file selects GPL-3.0-or-later)"
    echo "  version code $(grep -h 'define GF2X_VERSION_STRING' "${EXT}/build-native/gf2x/gf2x-config-export.h" 2>/dev/null || echo '(not exported)')"
    echo
    echo "build host"
    echo "  cc           $(gcc --version | head -1)"
    echo "  cc for build gcc -std=gnu99 -Wno-implicit-function-declaration"
    echo "               (the stock CC_FOR_BUILD candidate c89 rejects the C++"
    echo "                comments in lowlevel/gen_bb_mul_code.c under this gcc;"
    echo "                that generator emits the bit-by-bit fallback basecases"
    echo "                only and none of the measured PCLMUL code)"
    echo "  cpu          $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | sed 's/^ //')"
    echo
    for name in conservative tuned native; do
        local_dir="${EXT}/build-${name}"
        prefix="${EXT}/prefix-${name}"
        echo "variant ${name}"
        sed -n 's/^configure: *//p' "${local_dir}/configure.stdout.log" \
            | grep -E '^(using ABI|CC=|CFLAGS=|CPPFLAGS=|hwdir=)' | sed 's/^/  /'
        echo "  selected basecase headers (config.status link records)"
        grep -o 'already_tuned/[a-z0-9_]*/[a-z0-9_.-]*\.h' "${local_dir}/configure.stdout.log" \
            | sort -u | sed 's/^/    /'
        echo "  algorithm thresholds (installed gf2x-thresholds.h, sizes in 64-bit words)"
        sed -n 's/^#define[[:space:]]*\(GF2X_MUL_[A-Z0-9_]*THRESHOLD\)[[:space:]]*\([0-9]*\).*/    \1 \2/p' \
            "${prefix}/include/gf2x/gf2x-thresholds.h"
        echo "    GF2X_MUL_FFT_TABLE smallest tabulated size beyond the leading entry"
        echo "      $(tr -d '\\\n\t ' <"${prefix}/include/gf2x/gf2x-thresholds.h" \
            | sed -n 's/.*GF2X_MUL_FFT_TABLE{{1,1},{\([0-9]*\),.*/\1/p')"
        echo "  library      ${prefix}/${LIB}"
        echo "  sha256       $(sha256sum "${prefix}/${LIB}" | cut -d' ' -f1)"
        echo "  size         $(stat -c %s "${prefix}/${LIB}") bytes"
        echo "  carry-less multiply instruction census (objdump -d)"
        objdump -d "${prefix}/${LIB}" \
            | awk '{for (i = 1; i <= NF; i++) if ($i ~ /^v?pclmul/) { print $i; break }}' \
            | sort | uniq -c | sed 's/^/    /'
        echo "  ymm-operand carry-less multiplies (256-bit VPCLMULQDQ)"
        echo "    $(objdump -d "${prefix}/${LIB}" | grep -E 'v?pclmul' | grep -c ymm || true)"
        echo "  symbols carrying carry-less multiplies"
        objdump -d "${prefix}/${LIB}" \
            | awk '/^[0-9a-f]+ </ { symbol = $2 } /v?pclmul/ { count[symbol]++ } END { for (s in count) print count[s], s }' \
            | sort -rn | sed 's/^/    /'
        echo
    done
    echo "measured entry point"
    echo "  gf2x_mul_r(c, a, an, b, bn, pool): unreduced product of two"
    echo "  polynomials over GF(2), operands spanning an and bn unsigned longs,"
    echo "  product an+bn words, little-endian words with bit i of word j the"
    echo "  coefficient of x^(64j+i). Declared in gf2x.h.in.in."
    nm -D --defined-only "${EXT}/prefix-native/${LIB}" | grep -E ' T gf2x_mul(_r|_pool_(init|clear))?$' | sed 's/^/  /'
}

emit >"${OUT}"
echo "wrote ${OUT}" >&2
