#!/usr/bin/env bash
# Re-evaluate committed c7113c5a receipts with the current acceptance tool
# (jit:c7113c5a).
#
# Usage (from the repository root):
#   dev/active/c7113c5a/survey/reevaluate.sh <output-file> <receipt-dir>...
#
# Each receipt directory is copied to a scratch directory and evaluated there,
# so committed acceptance summaries stay byte-identical. The output records the
# tool's verdict line, the committed and fresh summary digests, and every cell
# whose verdict, decision or outcome differs between the two summaries.

set -euo pipefail
repo=$(git rev-parse --show-toplevel)
[[ "$PWD" == "$repo" ]] || { echo 'invoke from the repository root' >&2; exit 2; }
OUT=${1:?output file}
shift
ACCEPTANCE=$repo/target/release/benchmark-acceptance
SCRATCH=$(mktemp -d "$repo/target/c7113c5a-reevaluate.XXXXXX")
trap 'rm -rf "$SCRATCH"' EXIT

{
  echo "# re-evaluation with the current benchmark-acceptance (jit:c7113c5a)"
  echo "# generated by dev/active/c7113c5a/survey/reevaluate.sh"
  echo "# acceptance executable sha256 $(sha256sum "$ACCEPTANCE" | cut -d' ' -f1)"
  echo "# evaluator source dev/tools/tuning-campaign-support/src/receipt.rs sha256 $(sha256sum dev/tools/tuning-campaign-support/src/receipt.rs | cut -d' ' -f1)"
  for dir in "$@"; do
    dir=${dir%/}
    copy="$SCRATCH/$(basename "$dir")"
    cp -r "$dir" "$copy"
    echo
    echo "receipt $dir/receipt.json sha256 $(sha256sum "$dir/receipt.json" | cut -d' ' -f1)"
    set +e
    verdict=$("$ACCEPTANCE" "$copy")
    status=$?
    set -e
    echo "  $verdict (exit $status)"
    echo "  committed summary sha256 $(sha256sum "$dir/acceptance-summary.json" | cut -d' ' -f1)"
    echo "  fresh summary sha256     $(sha256sum "$copy/acceptance-summary.json" | cut -d' ' -f1)"
    python3 - "$dir/acceptance-summary.json" "$copy/acceptance-summary.json" <<'PY'
import json, sys
old, new = (json.load(open(path)) for path in sys.argv[1:])
keys = ("verdict", "qualifies", "label")
changed = [f"{k}: {old[k]} -> {new[k]}" for k in keys if old[k] != new[k]]
for before, after in zip(old["cells"], new["cells"]):
    for field in ("outcome", "decision"):
        if before.get(field) != after.get(field):
            changed.append(f"{before['cell_id']} {field}: {before.get(field)} -> {after.get(field)}")
    for field in ("estimate", "lower", "upper", "confidence"):
        if (before.get("interval") or {}).get(field) != (after.get("interval") or {}).get(field):
            changed.append(f"{before['cell_id']} interval.{field} differs")
added = sorted({key for cell in new["cells"] for key in (cell.get("interval") or {})}
               - {key for cell in old["cells"] for key in (cell.get("interval") or {})})
print(f"  differing verdicts, decisions, outcomes or interval bounds: {len(changed)}")
for line in changed:
    print(f"    {line}")
print(f"  interval fields the fresh summary adds: {', '.join(added) or 'none'}")
PY
  done
} >"$OUT"
echo "wrote $OUT" >&2
