#!/usr/bin/env bash
# Re-derive excerpts/llbc-item-counts.txt from the .llbc files produced by
# run.sh.  The .llbc files themselves are not committed (see .gitignore); run
# the R*/P* commands again to regenerate them.
set -euo pipefail

# With no arguments this summarises the baseline leg; the upgrade leg passes
# its own extraction directory and output file.
HERE="${1:-$(cd "$(dirname "$0")" && pwd)}"
OUT="${2:-$HERE/excerpts/llbc-item-counts.txt}"
mkdir -p "$HERE/excerpts"

{
  echo "# LLBC item counts and on-disk byte sizes per run."
  echo "# bytes = size of the .llbc file emitted by --dest-file; these are the"
  echo "# files excluded by .gitignore, so this receipt is their size of record."
  echo "# generated by dev/active/34d85cb9/extraction/llbc-summary.sh"
  python3 - "$HERE" <<'PY'
import glob, json, os, sys

here = sys.argv[1]
paths = sorted(glob.glob(f"{here}/*_gf2_core.llbc")) + sorted(glob.glob(f"{here}/*_probe.llbc"))
for p in paths:
    d = json.load(open(p))
    t = d["translated"]
    print(
        f"{os.path.basename(p):26s} bytes={os.path.getsize(p):9d} "
        f"has_errors={d['has_errors']!s:5s} "
        f"type_decls={len(t['type_decls']):4d} fun_decls={len(t['fun_decls']):4d} "
        f"trait_decls={len(t['trait_decls']):3d} trait_impls={len(t['trait_impls']):3d}"
    )
PY
} >"$OUT"

echo "wrote $OUT"
