//! Integration tests for nested tower extensions: GF(p⁴), GF(p⁶), GF(p¹²).
//!
//! This file complements `gfpn_wide_nested.rs` (which already covers the `Wide`
//! accumulator plumbing for GF(p⁴)) by:
//!
//! 1. Running focused field-axiom checks (add/mul/distributivity + inverse
//!    roundtrip + hash stability + Frobenius consistency) over all three
//!    chains via proptest.
//! 2. Cross-verifying the optimised Karatsuba multiplication against a
//!    fresh, independent schoolbook implementation for each tower shape.
//!    The naive routines here take deliberately different coordinate-
//!    mixing shapes from those in `karatsuba_cross_verify.rs` so no helper
//!    is shared with the Karatsuba code path or a common reference.
//! 3. Cross-verifying a handful of hard-coded products, sums, and inverses
//!    against SageMath (vectors generated with Sage 10.8 using the
//!    regenerator script documented below).
//!
//! # Tower chains
//!
//! | GF        | Rust type                                                        | Irreducibles                              |
//! |-----------|------------------------------------------------------------------|-------------------------------------------|
//! | 65537²    | `Fp<65537>`                                                      | base                                       |
//! | 65537⁴    | `QuadraticExt<QuadraticExt<Fp<65537>>>`                          | `u²=3`, `w²=u`                             |
//! | 7²        | `QuadraticExt<Fp<7>>`                                            | `u²=3`                                     |
//! | 7⁶        | `CubicExt<QuadraticExt<Fp<7>>>`                                  | `u²=3`, `v³=u`                             |
//! | 7¹²       | `QuadraticExt<CubicExt<QuadraticExt<Fp<7>>>>`                    | `u²=3`, `v³=u`, `z²=v+1`                   |
//!
//! Non-residue choices were validated with SageMath by checking that each
//! defining polynomial is irreducible over its base. Sage notes:
//!
//! * GF(7²): `x² − 3` irreducible iff `3` is a QR-non-residue mod 7 — yes
//!   (Legendre `(3/7) = −1`).
//! * GF(7⁶): `x³ − u` irreducible over GF(7²) — yes (Sage `.is_irreducible()`
//!   returned `True`; `u` is a cubic non-residue in GF(7²)).
//! * GF(7¹²): `x² − (v + 1)` irreducible over GF(7⁶) — yes, confirmed via
//!   Sage; `v + 1` is a quadratic non-residue in GF(7⁶).
//! * GF(65537⁴): `x² − u` irreducible over GF(65537²) (same construction as
//!   in `gfpn_wide_nested.rs`, reused here for the Sage cross-verify).
//!
//! # SageMath cross-verification
//!
//! SageMath was available on the build host at the time this test was
//! written. Test vectors were generated by the Sage script embedded below
//! and hard-coded as the `SAGE_*` arrays. To regenerate (for example if a
//! tower definition changes) run:
//!
//! ```bash
//! sage -c "$(cat <<'PY'
//! from random import Random
//! rng = Random(int(42))
//! p = 65537
//! Fp = GF(p); R.<x> = PolynomialRing(Fp)
//! Fq2.<u> = Fp.extension(x^2 - 3)
//! R4.<y> = PolynomialRing(Fq2); Fq4.<w> = Fq2.extension(y^2 - u)
//! # ... (see the full script in scripts/sage_vectors_nested_towers.sage or
//! #      recover from the task description of jit issue 86b3dc7d).
//! PY
//! )"
//! ```
//!
//! If SageMath becomes unavailable (e.g., on a CI host without a Sage
//! install), the Sage cross-verify tests still build and run — the vectors
//! are static constants — but regeneration would need Sage reinstalled.
//! **At the time of writing, `which sage` returned `/usr/bin/sage`
//! (version 10.8), so the criterion is satisfied.**

#![allow(clippy::excessive_precision)]
#![deny(unsafe_code)]

use std::hash::{Hash, Hasher};

use gf2_core::field::{ConstField, FiniteField, FiniteFieldExt};
use gf2_core::gfp::Fp;
use gf2_core::gfpn::{CubicExt, ExtConfig, QuadraticExt};
use proptest::prelude::*;

// ---------------------------------------------------------------------------
// Tower configurations
// ---------------------------------------------------------------------------

/// GF(65537²) = `Fp<65537>[u]/(u² − 3)`. `3` is a QNR mod 65537 (Legendre).
struct Fp65537Ext2;
impl ExtConfig for Fp65537Ext2 {
    type BaseField = Fp<65537>;
    const NON_RESIDUE: Fp<65537> = Fp::<65537>::new(3);
}
type Fq2Large = QuadraticExt<Fp65537Ext2>;

/// GF(65537⁴) = `Fq2Large[w]/(w² − u)` — same construction as
/// `gfpn_wide_nested.rs`, repeated here for axiom tests and Sage cross-verify.
struct Fp65537Ext4;
impl ExtConfig for Fp65537Ext4 {
    type BaseField = Fq2Large;
    const NON_RESIDUE: Fq2Large = Fq2Large::new(Fp::<65537>::new(0), Fp::<65537>::new(1));
}
type Fq4Large = QuadraticExt<Fp65537Ext4>;

/// GF(7²) = `Fp<7>[u]/(u² − 3)`. Base for the GF(7⁶) and GF(7¹²) towers.
struct Fp7Ext2;
impl ExtConfig for Fp7Ext2 {
    type BaseField = Fp<7>;
    const NON_RESIDUE: Fp<7> = Fp::<7>::new(3);
}
type Fq2 = QuadraticExt<Fp7Ext2>;

/// GF(7⁶) = `Fq2[v]/(v³ − u)`. `u` is a cubic non-residue in GF(7²) — verified
/// via SageMath (`(t^3 - u).is_irreducible() == True` over GF(7²)).
struct Fp7Ext6;
impl ExtConfig for Fp7Ext6 {
    type BaseField = Fq2;
    const NON_RESIDUE: Fq2 = Fq2::new(Fp::<7>::new(0), Fp::<7>::new(1));
}
type Fq6 = CubicExt<Fp7Ext6>;

/// GF(7¹²) = `Fq6[z]/(z² − (v + 1))`. `v + 1` is a quadratic non-residue in
/// GF(7⁶) — verified via SageMath. This is the BLS12-381-shape tower
/// (quad-over-cubic-over-quad), but with p = 7 for speed.
struct Fp7Ext12;
impl ExtConfig for Fp7Ext12 {
    type BaseField = Fq6;
    /// v + 1, i.e., `c0 = 1, c1 = 1·u^0 · v^1 term = 1, c2 = 0`. In coefficient
    /// tuple notation over Fp: `(1, 0, 1, 0, 0, 0)` meaning
    /// `(1+0·u) + (1+0·u)·v + (0+0·u)·v²`.
    const NON_RESIDUE: Fq6 = Fq6::new(
        Fq2::new(Fp::<7>::new(1), Fp::<7>::new(0)),
        Fq2::new(Fp::<7>::new(1), Fp::<7>::new(0)),
        Fq2::new(Fp::<7>::new(0), Fp::<7>::new(0)),
    );
}
type Fq12 = QuadraticExt<Fp7Ext12>;

// ---------------------------------------------------------------------------
// Element-construction helpers from flat coefficient tuples.
//
// All tuples are in the canonical "coefficients of Fp, innermost varying
// fastest" order used by the Sage generator, so the cross-verify data and the
// Rust construction agree.
// ---------------------------------------------------------------------------

fn fq4_from_flat(c: [u64; 4]) -> Fq4Large {
    let c0 = Fq2Large::new(Fp::<65537>::new(c[0]), Fp::<65537>::new(c[1]));
    let c1 = Fq2Large::new(Fp::<65537>::new(c[2]), Fp::<65537>::new(c[3]));
    Fq4Large::new(c0, c1)
}

fn fq4_to_flat(e: Fq4Large) -> [u64; 4] {
    [
        e.c0().c0().value(),
        e.c0().c1().value(),
        e.c1().c0().value(),
        e.c1().c1().value(),
    ]
}

fn fq6_from_flat(c: [u64; 6]) -> Fq6 {
    let c0 = Fq2::new(Fp::<7>::new(c[0]), Fp::<7>::new(c[1]));
    let c1 = Fq2::new(Fp::<7>::new(c[2]), Fp::<7>::new(c[3]));
    let c2 = Fq2::new(Fp::<7>::new(c[4]), Fp::<7>::new(c[5]));
    Fq6::new(c0, c1, c2)
}

fn fq6_to_flat(e: Fq6) -> [u64; 6] {
    [
        e.c0().c0().value(),
        e.c0().c1().value(),
        e.c1().c0().value(),
        e.c1().c1().value(),
        e.c2().c0().value(),
        e.c2().c1().value(),
    ]
}

fn fq12_from_flat(c: [u64; 12]) -> Fq12 {
    let lo: [u64; 6] = [c[0], c[1], c[2], c[3], c[4], c[5]];
    let hi: [u64; 6] = [c[6], c[7], c[8], c[9], c[10], c[11]];
    Fq12::new(fq6_from_flat(lo), fq6_from_flat(hi))
}

fn fq12_to_flat(e: Fq12) -> [u64; 12] {
    let lo = fq6_to_flat(e.c0());
    let hi = fq6_to_flat(e.c1());
    [
        lo[0], lo[1], lo[2], lo[3], lo[4], lo[5], hi[0], hi[1], hi[2], hi[3], hi[4], hi[5],
    ]
}

// ---------------------------------------------------------------------------
// Independent naive schoolbook multiplication, one per tower shape.
//
// These implementations use ONLY public accessors (`c0`, `c1`, `c2`) and the
// base field's `*`/`+`/`-` operators. They deliberately re-derive the
// reduction formulas (so a Karatsuba bug cannot hide behind a shared helper),
// and they perform the polynomial unrolling at the outermost tower level to
// decouple them from `karatsuba_cross_verify.rs`.
// ---------------------------------------------------------------------------

/// Naive schoolbook QuadraticExt multiplication (4 base muls, no Karatsuba).
/// `a · b = (a0 b0 + β · a1 b1) + (a0 b1 + a1 b0) · u`.
#[inline(never)]
fn naive_quad_mul<C: ExtConfig>(a: QuadraticExt<C>, b: QuadraticExt<C>) -> QuadraticExt<C> {
    let a0 = a.c0();
    let a1 = a.c1();
    let b0 = b.c0();
    let b1 = b.c1();
    let m00 = a0 * b0;
    let m01 = a0 * b1;
    let m10 = a1 * b0;
    let m11 = a1 * b1;
    let c0 = m00 + C::mul_by_non_residue(m11);
    let c1 = m01 + m10;
    QuadraticExt::new(c0, c1)
}

/// Naive schoolbook CubicExt multiplication (9 base muls, no Karatsuba).
/// `a · b = d0 + d1·v + d2·v² + d3·v³ + d4·v⁴` reduced via `v³ = β`.
#[inline(never)]
fn naive_cubic_mul<C: ExtConfig>(a: CubicExt<C>, b: CubicExt<C>) -> CubicExt<C> {
    let a0 = a.c0();
    let a1 = a.c1();
    let a2 = a.c2();
    let b0 = b.c0();
    let b1 = b.c1();
    let b2 = b.c2();

    let d0 = a0 * b0;
    let d1 = a0 * b1 + a1 * b0;
    let d2 = a0 * b2 + a1 * b1 + a2 * b0;
    let d3 = a1 * b2 + a2 * b1;
    let d4 = a2 * b2;

    let c0 = d0 + C::mul_by_non_residue(d3);
    let c1 = d1 + C::mul_by_non_residue(d4);
    let c2 = d2;

    CubicExt::new(c0, c1, c2)
}

// ---------------------------------------------------------------------------
// Hand-computed reference for the schoolbook routines over the actual towers
// used below (so the naive references are themselves sanity-checked before
// being used to judge Karatsuba).
// ---------------------------------------------------------------------------

#[test]
fn naive_quad_reference_hand_check_fq4() {
    // In Fq4: (0 + 1·w) · (0 + 1·w) = w² = u. Verify at the outer level.
    let w = Fq4Large::new(Fq2Large::new(Fp::new(0), Fp::new(0)), Fq2Large::one());
    let w_sq = naive_quad_mul(w, w);
    assert_eq!(fq4_to_flat(w_sq), [0, 1, 0, 0]); // = u = (0 + 1·u) as base
}

#[test]
fn naive_cubic_reference_hand_check_fq6() {
    // In Fq6: v³ = u. Compute v·v = v², then v·v² = u.
    let v_elem = Fq6::new(Fq2::zero(), Fq2::one(), Fq2::zero());
    let v_sq = naive_cubic_mul(v_elem, v_elem);
    assert_eq!(fq6_to_flat(v_sq), [0, 0, 0, 0, 1, 0]); // v²
    let v_cubed = naive_cubic_mul(v_sq, v_elem);
    // v³ = u → flat (0, 1, 0, 0, 0, 0).
    assert_eq!(fq6_to_flat(v_cubed), [0, 1, 0, 0, 0, 0]);
}

#[test]
fn naive_quad_reference_hand_check_fq12() {
    // In Fq12: z² = v + 1. Verify at the outer level.
    let z = Fq12::new(Fq6::zero(), Fq6::one());
    let z_sq = naive_quad_mul(z, z);
    // z² should equal the non-residue = v + 1, whose Fp-flat form is
    // (1, 0, 1, 0, 0, 0) in the Fq6 part + (0,0,0,0,0,0) in the Fq6 part 2
    // but since z² has no z-term, hi = 0.
    assert_eq!(fq12_to_flat(z_sq), [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
}

// ---------------------------------------------------------------------------
// Karatsuba vs naive cross-verification: one test per tower shape, with
// reasonable proptest budgets so the full file still finishes quickly.
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 500,
        .. ProptestConfig::default()
    })]

    /// GF(65537⁴): Karatsuba-at-outer-quadratic must match schoolbook at the
    /// outer quadratic level (with Karatsuba preserved at the inner quadratic).
    /// This exercises the Karatsuba identity at the top level of the tower.
    #[test]
    fn karatsuba_matches_naive_fq4_large(
        a in any::<[u64; 4]>(),
        b in any::<[u64; 4]>(),
    ) {
        let a_c = a.map(|v| v % 65537);
        let b_c = b.map(|v| v % 65537);
        let a = fq4_from_flat(a_c);
        let b = fq4_from_flat(b_c);
        prop_assert_eq!(a * b, naive_quad_mul(a, b));
    }

    /// GF(7⁶): Karatsuba-at-outer-cubic must match schoolbook at the outer
    /// cubic level.
    #[test]
    fn karatsuba_matches_naive_fq6(
        a in proptest::array::uniform6(0u64..7),
        b in proptest::array::uniform6(0u64..7),
    ) {
        let a = fq6_from_flat(a);
        let b = fq6_from_flat(b);
        prop_assert_eq!(a * b, naive_cubic_mul(a, b));
    }
}

// GF(7¹²) is heavier: every base multiplication at the top level is a full
// GF(7⁶) multiplication (6 Fp muls inside a 6-mul Karatsuba). Cut the case
// count to respect the overall 60 s workspace budget.
proptest! {
    #![proptest_config(ProptestConfig {
        cases: 150,
        .. ProptestConfig::default()
    })]

    #[test]
    fn karatsuba_matches_naive_fq12(
        a in proptest::array::uniform12(0u64..7),
        b in proptest::array::uniform12(0u64..7),
    ) {
        let a = fq12_from_flat(a);
        let b = fq12_from_flat(b);
        prop_assert_eq!(a * b, naive_quad_mul(a, b));
    }
}

// ---------------------------------------------------------------------------
// Axiom harness — focused re-implementation for integration tests.
//
// The full `crate::field::axiom_tests::test_const_field_axioms` is
// `pub(crate)` and unreachable from an integration test. This re-does the
// essential axioms (add/mul/distributivity/inverse roundtrip/hash/Frobenius)
// for each tower level with the requested per-axiom case budget.
// ---------------------------------------------------------------------------

fn compute_hash<T: Hash>(v: &T) -> u64 {
    use std::collections::hash_map::DefaultHasher;
    let mut h = DefaultHasher::new();
    v.hash(&mut h);
    h.finish()
}

/// Run every axiom we care about for the supplied strategy / field. The
/// parameter `p` is the field characteristic (needed for Frobenius + p·x=0).
///
/// The `.clone()` calls below are on `F: Copy` (via `ConstField: Copy`), which
/// clippy flags as unnecessary. We allow them here to keep the harness body
/// structurally identical to the (pub(crate)) `field::axiom_tests` harness,
/// which works for non-`Copy` fields as well — a future refactor that shares
/// code between the two should not have to touch this harness.
#[allow(clippy::clone_on_copy)]
fn run_axioms<F: ConstField + std::fmt::Debug>(
    strategy: BoxedStrategy<F>,
    p: u64,
    cases_per_axiom: u32,
) where
    F::Characteristic: Into<u64>,
{
    let cfg = proptest::test_runner::Config::with_cases(cases_per_axiom);
    let mut runner = proptest::test_runner::TestRunner::new(cfg);

    // (a + b) + c == a + (b + c)
    runner
        .run(
            &(strategy.clone(), strategy.clone(), strategy.clone()),
            |(a, b, c)| {
                let lhs = (a.clone() + b.clone()) + c.clone();
                let rhs = a + (b + c);
                prop_assert_eq!(lhs, rhs);
                Ok(())
            },
        )
        .expect("additive associativity");

    // a + b == b + a
    runner
        .run(&(strategy.clone(), strategy.clone()), |(a, b)| {
            prop_assert_eq!(a.clone() + b.clone(), b + a);
            Ok(())
        })
        .expect("additive commutativity");

    // a + (-a) == 0
    runner
        .run(&strategy, |a| {
            prop_assert!((a.clone() + (-a)).is_zero());
            Ok(())
        })
        .expect("additive inverse");

    // (a * b) * c == a * (b * c)
    runner
        .run(
            &(strategy.clone(), strategy.clone(), strategy.clone()),
            |(a, b, c)| {
                let lhs = (a.clone() * b.clone()) * c.clone();
                let rhs = a * (b * c);
                prop_assert_eq!(lhs, rhs);
                Ok(())
            },
        )
        .expect("multiplicative associativity");

    // a * b == b * a
    runner
        .run(&(strategy.clone(), strategy.clone()), |(a, b)| {
            prop_assert_eq!(a.clone() * b.clone(), b * a);
            Ok(())
        })
        .expect("multiplicative commutativity");

    // a * (b + c) == a*b + a*c
    runner
        .run(
            &(strategy.clone(), strategy.clone(), strategy.clone()),
            |(a, b, c)| {
                let lhs = a.clone() * (b.clone() + c.clone());
                let rhs = (a.clone() * b) + (a * c);
                prop_assert_eq!(lhs, rhs);
                Ok(())
            },
        )
        .expect("distributivity");

    // a * 0 == 0
    runner
        .run(&strategy, |a| {
            prop_assert!((a.clone() * F::zero()).is_zero());
            Ok(())
        })
        .expect("zero annihilation");

    // Non-zero a: a * inv(a) == 1
    runner
        .run(
            &strategy.clone().prop_filter("non-zero", |a| !a.is_zero()),
            |a| {
                let inv = a.inv().expect("non-zero element must have inverse");
                prop_assert!((a * inv).is_one());
                Ok(())
            },
        )
        .expect("inversion roundtrip");

    // Sum of p copies of any element is zero.
    runner
        .run(&strategy, |a| {
            let mut acc = a.zero_like();
            for _ in 0..p {
                acc += a.clone();
            }
            prop_assert!(acc.is_zero());
            Ok(())
        })
        .expect("characteristic p");

    // Equal elements hash equal.
    runner
        .run(&strategy, |a| {
            let b = a.clone();
            prop_assert_eq!(compute_hash(&a), compute_hash(&b));
            Ok(())
        })
        .expect("hash consistency");

    // Frobenius: x^p == frobenius(x, 1).
    runner
        .run(&strategy, |a| {
            let lhs = a.frobenius(1);
            let rhs = a.pow(p);
            prop_assert_eq!(lhs, rhs);
            Ok(())
        })
        .expect("Frobenius vs pow");
}

fn fq2_large_strategy() -> BoxedStrategy<Fq2Large> {
    (0..65537u64, 0..65537u64)
        .prop_map(|(c0, c1)| Fq2Large::new(Fp::new(c0), Fp::new(c1)))
        .boxed()
}

fn fq4_large_strategy() -> BoxedStrategy<Fq4Large> {
    (0..65537u64, 0..65537u64, 0..65537u64, 0..65537u64)
        .prop_map(|(c00, c01, c10, c11)| {
            Fq4Large::new(
                Fq2Large::new(Fp::new(c00), Fp::new(c01)),
                Fq2Large::new(Fp::new(c10), Fp::new(c11)),
            )
        })
        .boxed()
}

fn fq6_strategy() -> BoxedStrategy<Fq6> {
    proptest::array::uniform6(0u64..7)
        .prop_map(fq6_from_flat)
        .boxed()
}

fn fq12_strategy() -> BoxedStrategy<Fq12> {
    proptest::array::uniform12(0u64..7)
        .prop_map(fq12_from_flat)
        .boxed()
}

#[test]
fn axioms_gf_65537_sq() {
    // GF(p²) — very cheap; give it the full 200 cases for thorough coverage.
    run_axioms(fq2_large_strategy(), 65537, 200);
}

#[test]
fn axioms_gf_65537_quart() {
    // GF(p⁴) — still cheap (Karatsuba over u64-range); 100 cases.
    run_axioms(fq4_large_strategy(), 65537, 100);
}

#[test]
fn axioms_gf_7_6() {
    // GF(p⁶) over small prime — cheap; 100 cases.
    run_axioms(fq6_strategy(), 7, 100);
}

#[test]
fn axioms_gf_7_12() {
    // GF(p¹²) over p = 7: each operation is heaviest in the file. Reduce
    // the per-axiom budget to keep the integration test well under the
    // workspace's 60 s wall clock limit.
    run_axioms(fq12_strategy(), 7, 50);
}

// ---------------------------------------------------------------------------
// Direct sanity checks: basic identities at every tower level.
// ---------------------------------------------------------------------------

#[test]
fn tower_orders() {
    assert_eq!(Fq2Large::order(), (65537u128).pow(2));
    assert_eq!(Fq4Large::order(), (65537u128).pow(4));
    assert_eq!(Fq6::order(), 7u128.pow(6));
    assert_eq!(Fq12::order(), 7u128.pow(12));
}

#[test]
fn tower_extension_degrees() {
    assert_eq!(Fq2Large::one().extension_degree(), 2);
    assert_eq!(Fq4Large::one().extension_degree(), 4);
    assert_eq!(Fq6::one().extension_degree(), 6);
    assert_eq!(Fq12::one().extension_degree(), 12);
}

#[test]
fn tower_non_residue_reduction_identities() {
    // u² = 3 in Fq2 (p = 7, 65537).
    let u_small = Fq2::new(Fp::<7>::new(0), Fp::<7>::new(1));
    assert_eq!(u_small * u_small, Fq2::new(Fp::new(3), Fp::new(0)));
    let u_large = Fq2Large::new(Fp::<65537>::new(0), Fp::<65537>::new(1));
    assert_eq!(u_large * u_large, Fq2Large::new(Fp::new(3), Fp::new(0)));

    // w² = u in Fq4 (p = 65537).
    let w = Fq4Large::new(
        Fq2Large::new(Fp::new(0), Fp::new(0)),
        Fq2Large::new(Fp::new(1), Fp::new(0)),
    );
    let w_sq = w * w;
    assert_eq!(fq4_to_flat(w_sq), [0, 1, 0, 0]); // = u at Fq2 level

    // v³ = u in Fq6.
    let v = Fq6::new(Fq2::zero(), Fq2::one(), Fq2::zero());
    let v3 = v * v * v;
    assert_eq!(fq6_to_flat(v3), [0, 1, 0, 0, 0, 0]); // = u at Fq2 level

    // z² = v + 1 in Fq12.
    let z = Fq12::new(Fq6::zero(), Fq6::one());
    let z_sq = z * z;
    assert_eq!(fq12_to_flat(z_sq), [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
}

// ---------------------------------------------------------------------------
// SageMath-generated cross-verification vectors.
//
// Each row contains flat Fp-coefficient tuples for a, b, a·b, a+b, and a⁻¹,
// as produced by the Sage script documented in this file's module docs. The
// coordinate order matches the `fqN_from_flat` helpers above.
// ---------------------------------------------------------------------------

struct Fq4Vec {
    a: [u64; 4],
    b: [u64; 4],
    prod: [u64; 4],
    sum: [u64; 4],
    inv_a: [u64; 4],
}

const SAGE_FQ4: &[Fq4Vec] = &[
    Fq4Vec {
        a: [14592, 3278, 36048, 32098],
        b: [29256, 18289, 13434, 11395],
        prod: [3454, 27039, 7507, 28863],
        sum: [43848, 21567, 49482, 43493],
        inv_a: [33295, 32371, 19200, 61142],
    },
    Fq4Vec {
        a: [55302, 4165, 3905, 12280],
        b: [28657, 30495, 3478, 26062],
        prod: [26256, 6858, 15070, 35266],
        sum: [18422, 34660, 7383, 38342],
        inv_a: [2650, 5393, 9627, 7810],
    },
    Fq4Vec {
        a: [54987, 28893, 58878, 36463],
        b: [851, 20926, 55392, 44597],
        prod: [25586, 1356, 29572, 35729],
        sum: [55838, 49819, 48733, 15523],
        inv_a: [43837, 32194, 176, 61668],
    },
    Fq4Vec {
        a: [36421, 20379, 28221, 44118],
        b: [13396, 12156, 49797, 12676],
        prod: [22552, 50070, 41697, 28466],
        sum: [49817, 32535, 12481, 56794],
        inv_a: [43523, 39413, 19395, 42833],
    },
    Fq4Vec {
        a: [47052, 45082, 34671, 5695],
        b: [60217, 16361, 49615, 10328],
        prod: [49252, 64115, 5888, 37548],
        sum: [41732, 61443, 18749, 16023],
        inv_a: [1983, 40397, 26057, 8455],
    },
    Fq4Vec {
        a: [38427, 47400, 25203, 9116],
        b: [6006, 29871, 37930, 10458],
        prod: [48425, 58595, 58451, 44756],
        sum: [44433, 11734, 63133, 19574],
        inv_a: [44042, 13242, 31563, 50821],
    },
    Fq4Vec {
        a: [30512, 13238, 49823, 36434],
        b: [59429, 47819, 21319, 48520],
        prod: [56349, 49892, 9930, 24266],
        sum: [24404, 61057, 5605, 19417],
        inv_a: [20756, 19370, 45804, 1120],
    },
    Fq4Vec {
        a: [46566, 27460, 34993, 9358],
        b: [22431, 32087, 21417, 60589],
        prod: [51069, 15950, 47100, 36100],
        sum: [3460, 59547, 56410, 4410],
        inv_a: [36243, 6826, 32816, 19932],
    },
    Fq4Vec {
        a: [49735, 35382, 28785, 42504],
        b: [7331, 30021, 4207, 41347],
        prod: [49996, 55778, 58701, 8135],
        sum: [57066, 65403, 32992, 18314],
        inv_a: [48568, 30893, 1428, 21954],
    },
    Fq4Vec {
        a: [52581, 35093, 8675, 27653],
        b: [41245, 27869, 65435, 51856],
        prod: [19927, 39064, 64936, 3656],
        sum: [28289, 62962, 8573, 13972],
        inv_a: [47980, 48117, 13543, 53194],
    },
];

struct Fq6Vec {
    a: [u64; 6],
    b: [u64; 6],
    prod: [u64; 6],
    sum: [u64; 6],
    inv_a: [u64; 6],
}

const SAGE_FQ6: &[Fq6Vec] = &[
    Fq6Vec {
        a: [5, 3, 1, 2, 1, 1],
        b: [5, 4, 4, 2, 5, 4],
        prod: [2, 4, 3, 4, 3, 5],
        sum: [3, 0, 5, 4, 6, 5],
        inv_a: [2, 4, 1, 3, 5, 6],
    },
    Fq6Vec {
        a: [3, 4, 3, 2, 1, 1],
        b: [4, 3, 0, 6, 0, 6],
        prod: [1, 2, 1, 4, 2, 1],
        sum: [0, 0, 3, 1, 1, 0],
        inv_a: [1, 1, 1, 5, 4, 0],
    },
    Fq6Vec {
        a: [0, 1, 5, 1, 6, 5],
        b: [3, 4, 0, 3, 3, 4],
        prod: [2, 5, 6, 3, 1, 1],
        sum: [3, 5, 5, 4, 2, 2],
        inv_a: [3, 5, 6, 3, 4, 5],
    },
    Fq6Vec {
        a: [3, 4, 2, 4, 6, 0],
        b: [5, 5, 0, 5, 4, 6],
        prod: [4, 3, 0, 6, 6, 4],
        sum: [1, 2, 2, 2, 3, 6],
        inv_a: [0, 1, 2, 1, 6, 3],
    },
    Fq6Vec {
        a: [2, 6, 5, 2, 0, 2],
        b: [3, 1, 3, 0, 5, 5],
        prod: [0, 5, 1, 3, 2, 3],
        sum: [5, 0, 1, 2, 5, 0],
        inv_a: [6, 2, 3, 4, 1, 6],
    },
    Fq6Vec {
        a: [2, 4, 6, 1, 4, 0],
        b: [6, 5, 2, 6, 5, 4],
        prod: [0, 0, 0, 6, 0, 2],
        sum: [1, 2, 1, 0, 2, 4],
        inv_a: [0, 5, 3, 6, 4, 1],
    },
    Fq6Vec {
        a: [4, 1, 1, 2, 6, 1],
        b: [4, 6, 4, 0, 4, 2],
        prod: [6, 5, 6, 6, 5, 4],
        sum: [1, 0, 5, 2, 3, 3],
        inv_a: [1, 1, 2, 1, 4, 3],
    },
    Fq6Vec {
        a: [3, 0, 0, 2, 6, 6],
        b: [2, 1, 0, 1, 4, 0],
        prod: [6, 0, 1, 3, 6, 4],
        sum: [5, 1, 0, 3, 3, 6],
        inv_a: [0, 5, 5, 0, 5, 3],
    },
    Fq6Vec {
        a: [0, 5, 3, 6, 0, 6],
        b: [4, 6, 1, 1, 5, 3],
        prod: [1, 2, 1, 3, 6, 2],
        sum: [4, 4, 4, 0, 5, 2],
        inv_a: [6, 1, 5, 1, 3, 5],
    },
    Fq6Vec {
        a: [4, 1, 2, 4, 6, 4],
        b: [3, 1, 4, 6, 5, 5],
        prod: [2, 5, 6, 6, 5, 1],
        sum: [0, 2, 6, 3, 4, 2],
        inv_a: [0, 2, 6, 5, 1, 4],
    },
];

struct Fq12Vec {
    a: [u64; 12],
    b: [u64; 12],
    prod: [u64; 12],
    sum: [u64; 12],
    inv_a: [u64; 12],
}

const SAGE_FQ12: &[Fq12Vec] = &[
    Fq12Vec {
        a: [1, 5, 2, 3, 5, 5, 2, 3, 4, 3, 0, 1],
        b: [1, 0, 2, 0, 4, 4, 1, 4, 1, 0, 0, 5],
        prod: [3, 1, 1, 4, 1, 2, 2, 2, 1, 0, 5, 4],
        sum: [2, 5, 4, 3, 2, 2, 3, 0, 5, 3, 0, 6],
        inv_a: [1, 5, 3, 1, 1, 6, 6, 1, 2, 5, 2, 1],
    },
    Fq12Vec {
        a: [5, 0, 1, 0, 0, 6, 2, 0, 4, 1, 2, 5],
        b: [3, 1, 4, 1, 5, 4, 4, 3, 1, 6, 3, 6],
        prod: [1, 6, 4, 1, 5, 2, 2, 1, 3, 3, 1, 2],
        sum: [1, 1, 5, 1, 5, 3, 6, 3, 5, 0, 5, 4],
        inv_a: [0, 2, 6, 6, 0, 4, 2, 1, 6, 1, 6, 3],
    },
    Fq12Vec {
        a: [3, 1, 0, 0, 5, 3, 2, 3, 3, 3, 6, 5],
        b: [0, 5, 5, 5, 0, 0, 3, 5, 2, 6, 6, 0],
        prod: [2, 4, 6, 6, 6, 1, 6, 1, 3, 6, 3, 2],
        sum: [3, 6, 5, 5, 5, 3, 5, 1, 5, 2, 5, 5],
        inv_a: [0, 5, 4, 3, 1, 0, 4, 3, 3, 1, 1, 3],
    },
    Fq12Vec {
        a: [1, 1, 1, 4, 3, 1, 3, 1, 2, 3, 1, 6],
        b: [0, 3, 6, 6, 6, 4, 0, 0, 5, 4, 6, 0],
        prod: [2, 1, 6, 3, 3, 3, 0, 1, 1, 2, 6, 4],
        sum: [1, 4, 0, 3, 2, 5, 3, 1, 0, 0, 0, 6],
        inv_a: [5, 3, 4, 2, 6, 4, 1, 0, 3, 1, 1, 2],
    },
    Fq12Vec {
        a: [0, 6, 6, 1, 1, 3, 3, 3, 1, 6, 3, 0],
        b: [1, 3, 0, 3, 2, 6, 6, 3, 2, 3, 5, 5],
        prod: [5, 3, 0, 6, 4, 5, 3, 1, 1, 5, 2, 2],
        sum: [1, 2, 6, 4, 3, 2, 2, 6, 3, 2, 1, 5],
        inv_a: [6, 2, 4, 6, 0, 6, 5, 3, 4, 6, 0, 2],
    },
    Fq12Vec {
        a: [6, 4, 5, 5, 3, 1, 1, 2, 1, 0, 4, 5],
        b: [4, 0, 5, 2, 0, 0, 4, 3, 4, 6, 4, 1],
        prod: [5, 2, 4, 4, 6, 1, 3, 3, 0, 2, 6, 2],
        sum: [3, 4, 3, 0, 3, 1, 5, 5, 5, 6, 1, 6],
        inv_a: [2, 5, 6, 3, 0, 1, 1, 3, 4, 0, 3, 6],
    },
    Fq12Vec {
        a: [0, 4, 0, 6, 1, 0, 4, 0, 5, 6, 1, 3],
        b: [0, 4, 1, 4, 4, 0, 4, 0, 3, 5, 4, 4],
        prod: [3, 0, 5, 1, 4, 6, 5, 3, 2, 3, 5, 1],
        sum: [0, 1, 1, 3, 5, 0, 1, 0, 1, 4, 5, 0],
        inv_a: [1, 5, 5, 3, 0, 5, 6, 4, 5, 1, 3, 1],
    },
    Fq12Vec {
        a: [4, 2, 2, 1, 5, 5, 2, 1, 2, 3, 1, 5],
        b: [5, 2, 3, 2, 6, 0, 0, 3, 4, 4, 0, 0],
        prod: [2, 3, 6, 1, 3, 4, 0, 6, 4, 6, 3, 3],
        sum: [2, 4, 5, 3, 4, 5, 2, 4, 6, 0, 1, 5],
        inv_a: [1, 0, 0, 0, 0, 4, 6, 0, 2, 1, 3, 6],
    },
    Fq12Vec {
        a: [4, 1, 4, 2, 1, 2, 0, 1, 2, 2, 1, 3],
        b: [6, 4, 5, 2, 4, 6, 5, 4, 0, 5, 6, 4],
        prod: [3, 1, 3, 3, 0, 3, 2, 4, 0, 5, 2, 5],
        sum: [3, 5, 2, 4, 5, 1, 5, 5, 2, 0, 0, 0],
        inv_a: [0, 0, 1, 3, 4, 2, 5, 2, 2, 4, 0, 3],
    },
    Fq12Vec {
        a: [2, 5, 0, 1, 2, 0, 0, 5, 4, 1, 2, 2],
        b: [4, 1, 5, 2, 1, 5, 5, 6, 2, 4, 3, 2],
        prod: [5, 4, 3, 2, 0, 1, 1, 3, 4, 3, 5, 5],
        sum: [6, 6, 5, 3, 3, 5, 5, 4, 6, 5, 5, 4],
        inv_a: [4, 5, 2, 2, 6, 2, 0, 4, 4, 0, 3, 3],
    },
];

#[test]
fn sage_cross_verify_fq4() {
    for (i, v) in SAGE_FQ4.iter().enumerate() {
        let a = fq4_from_flat(v.a);
        let b = fq4_from_flat(v.b);
        assert_eq!(fq4_to_flat(a * b), v.prod, "Fq4 prod mismatch at {i}");
        assert_eq!(fq4_to_flat(a + b), v.sum, "Fq4 sum mismatch at {i}");
        let inv = a.inv().expect("Sage-generated a is non-zero");
        assert_eq!(fq4_to_flat(inv), v.inv_a, "Fq4 inv mismatch at {i}");
    }
}

#[test]
fn sage_cross_verify_fq6() {
    for (i, v) in SAGE_FQ6.iter().enumerate() {
        let a = fq6_from_flat(v.a);
        let b = fq6_from_flat(v.b);
        assert_eq!(fq6_to_flat(a * b), v.prod, "Fq6 prod mismatch at {i}");
        assert_eq!(fq6_to_flat(a + b), v.sum, "Fq6 sum mismatch at {i}");
        let inv = a.inv().expect("Sage-generated a is non-zero");
        assert_eq!(fq6_to_flat(inv), v.inv_a, "Fq6 inv mismatch at {i}");
    }
}

#[test]
fn sage_cross_verify_fq12() {
    for (i, v) in SAGE_FQ12.iter().enumerate() {
        let a = fq12_from_flat(v.a);
        let b = fq12_from_flat(v.b);
        assert_eq!(fq12_to_flat(a * b), v.prod, "Fq12 prod mismatch at {i}");
        assert_eq!(fq12_to_flat(a + b), v.sum, "Fq12 sum mismatch at {i}");
        let inv = a.inv().expect("Sage-generated a is non-zero");
        assert_eq!(fq12_to_flat(inv), v.inv_a, "Fq12 inv mismatch at {i}");
    }
}
