#!/usr/bin/env sage
# scripts/generate-cas-permanent-vectors.sage
#
# Generates CAS cross-validation test vectors for the F_5 and F_7 matrix
# permanent functions (`permanent_bipedal5`, `permanent_bipedal7`) in
# `crates/gf2-algebra`.
#
# The output CSV is committed to
# `crates/gf2-algebra/tests/data/cas_permanent_f5_f7.csv` and is read
# verbatim by the Rust integration test
# `crates/gf2-algebra/tests/cas_cross_validation.rs`.  The Sage script is
# the single source of truth (SSOT) for the expected permanent values; the
# Rust implementations are validated against these values bit-for-bit.
#
# Usage:
#   /usr/bin/sage scripts/generate-cas-permanent-vectors.sage
#
# Re-running with the same seed produces a bit-identical CSV.
#
# Parameters:
#   qs       = [5, 7]          — prime fields to cover
#   ns       = [4, 6, 8, 10, 12] — matrix sizes
#   per_cell = 100             — vectors per (q, n) cell
#   Total:   5 cells * 2 fields * 100 = 1000 vectors (minimum per criteria)
#
# RNG:
#   Python `random` module, seeded with 0xc0ffee0000000000.  The seed is
#   embedded in the CSV header; re-running yields the same output.
#
# Sage version used when generating the committed vectors: 10.9
#
# Expected file size: approximately 1000 data rows + comment/header lines.
# Row count (excluding comments): exactly 1000.

import csv
import random
import os
import sys

SEED = "0xc0ffee0000000000"
random.seed(SEED)

qs = [5, 7]
ns = [4, 6, 8, 10, 12]
per_cell = 100

# Output path: always relative to the current working directory (the repo root).
# The script must be run from the repo root (the default for `sage scripts/...`).
out_path = os.path.join(
    "crates", "gf2-algebra", "tests", "data", "cas_permanent_f5_f7.csv"
)

os.makedirs(os.path.dirname(out_path), exist_ok=True)

rows = []
for q in qs:
    F = GF(q)
    for n in ns:
        for _ in range(per_cell):
            # Draw n*n random integers in [0, q) from the pinned RNG stream.
            entries = [random.randrange(q) for _ in range(n * n)]
            # Compute the permanent via SageMath's built-in method.
            M = Matrix(F, n, n, entries)
            perm = int(M.permanent())
            # Serialise the matrix as a row-major space-separated list of
            # integers with '/' as the row separator.
            rows_str = " / ".join(
                " ".join(str(entries[i * n + j]) for j in range(n))
                for i in range(n)
            )
            rows.append((q, n, rows_str, perm))

with open(out_path, "w", newline="") as f:
    f.write(f"# CAS permanent cross-validation vectors for F_5 and F_7\n")
    f.write(f"# Generated by: scripts/generate-cas-permanent-vectors.sage\n")
    # Sage version is pinned to the value at commit time (see header comment
    # at line 30). Hardcoding it here — rather than calling
    # `sage.version.version` at runtime — keeps the CSV byte-identical across
    # reruns regardless of the host Sage release (criterion 3 reproducibility).
    f.write(f"# Sage version: 10.9 (pinned; matches the run that generated the committed CSV)\n")
    f.write(f"# RNG seed: {SEED}\n")
    f.write(f"# Cell grid: q in {{5, 7}}, n in {{4, 6, 8, 10, 12}}, {per_cell} vectors per cell\n")
    f.write(f"# Total data rows: {len(rows)}\n")
    writer = csv.writer(f)
    writer.writerow(["q", "n", "matrix", "expected_permanent"])
    for (q, n, mat_str, perm) in rows:
        writer.writerow([q, n, mat_str, perm])

print(f"Wrote {len(rows)} vectors to {out_path}")
