-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import X1Gf2Core.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open gf2_core

/-- [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 825:4-825:42
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.WINOGRAD_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 858:4-858:40
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.TRI_BASE_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 892:4-892:35
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_BASE_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_PANEL_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 926:4-926:54
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_PANEL_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} {Clause0_Wide : Type} (FiniteFieldInst :
  field.traits.FiniteField Self Clause0_Characteristic Clause0_Wide)
  : Result Std.Usize

