#!/usr/bin/env python3
"""Project the frozen logical candidate pilots and profiles into review tables."""

import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
ACTIVE = ROOT / "dev/active/bc091474"
RESULTS = ROOT / "dev/bench_results"
FAMILIES = {
    "isolated": "2037941f-logical-isolated-xor",
    "row": "2037941f-logical-public-row-xor",
}
PROFILE_CASES = (
    "xor-8w-a64-warm@public-xor-a",
    "xor-9w-a64-warm@public-xor-a",
    "xor-64w-a64-warm@public-xor-a",
    "xor-64w-a64-streaming@public-xor-a",
    "row-xor-8w-full-warm@row-xor-a",
    "row-xor-9w-full-warm@row-xor-a",
    "row-xor-64w-full-warm@row-xor-a",
    "row-xor-64w-full-streaming@row-xor-a",
)


def receipt(factor, family):
    path = RESULTS / "2037941f" / FAMILIES[family] / f"bc091474-u{factor}-pilot"
    data = json.loads((path / "acceptance-summary.json").read_text())
    assert data["label"] == "pilot" and data["verdict"] == "accepted"
    assert not data["qualifies"] and not data["findings"]
    cells = {cell["cell_id"]: cell for cell in data["cells"]}
    assert len(cells) == 17
    assert all(
        cell["role"] == "exploratory"
        and cell["status"] == "measured"
        and cell["pairs"] == 24
        and cell["interval"]["resamples"] == 10000
        for cell in cells.values()
    )
    return path, cells


def point(cell):
    interval = cell["interval"]
    return interval["estimate"]


def rendered_cell(cell):
    interval = cell["interval"]
    return (
        f"{interval['estimate']:.4f} [{interval['lower']:.4f}, "
        f"{interval['upper']:.4f}]; {cell['decision']}"
    )


def anchor(family, words):
    if family == "isolated":
        return f"xor-{words}w-a64-warm"
    return f"row-xor-{words}w-full-warm"


def profile_cost(path, case):
    for line in path.read_text().splitlines():
        columns = [item.strip() for item in line.strip("|").split("|")]
        if columns[0] == f"`{case}`" and len(columns) == 7:
            return columns[1], columns[3]
    raise ValueError(f"missing profile case {case} in {path}")


def ledger_comparisons(family):
    name = "logical-isolated-xor" if family == "isolated" else "logical-public-row-xor"
    path = RESULTS / "2037941f" / f"{name}-ledger.jsonl"
    entries = [json.loads(line) for line in path.read_text().splitlines()]
    assert [entry["sequence"] for entry in entries] == list(range(len(entries)))
    return sum(entry["comparisons"] for entry in entries)


def added_nonblank_source_lines():
    patch = subprocess.check_output(
        ["git", "diff", "c30102763^", "c30102763", "--",
         "crates/gf2-kernels-simd/src/x86/avx2.rs"],
        cwd=ROOT, text=True,
    )
    return sum(line.startswith("+") and not line.startswith("+++")
               and bool(line[1:].strip()) for line in patch.splitlines())


def assembly_size(variant):
    path = ACTIVE / "asm" / f"{variant}-avx2-xor.asm.txt"
    match = re.search(r"^# address: .*; size: (\d+) bytes$", path.read_text(), re.M)
    assert match, path
    return int(match.group(1))


def main():
    sources = {(factor, family): receipt(factor, family)
               for factor in (2, 4) for family in FAMILIES}
    lines = [
        "# Logical candidate pilot and profile tables",
        "",
        "Generated by `dev/active/bc091474/make-candidate-tables.py` from committed "
        "acceptance JSON and profile summaries. Pilot intervals use 24 pairs and "
        "10,000 bootstrap resamples at confidence 0.975; they select a confirmation "
        "target only. Speedup above one favors the candidate.",
        "",
    ]
    for family, label in (("isolated", "Isolated XOR"), ("row", "Public row XOR")):
        lines += [f"## {label}", "", "| Cell | Factor 2 speedup [interval]; decision | Factor 4 speedup [interval]; decision |",
                  "|---|---|---|"]
        cells2 = sources[(2, family)][1]
        cells4 = sources[(4, family)][1]
        assert cells2.keys() == cells4.keys()
        for cell_id, cell in cells2.items():
            lines.append(f"| `{cell_id}` | {rendered_cell(cell)} | {rendered_cell(cells4[cell_id])} |")
        lines.append("")
        for factor in (2, 4):
            path = sources[(factor, family)][0]
            rel = path.relative_to(ROOT)
            lines.append(f"Source factor {factor}: [acceptance and raw receipt](../../bench_results/2037941f/{FAMILIES[family]}/bc091474-u{factor}-pilot/acceptance-summary.md), "
                         f"[execution log](../../bench_results/2037941f/{FAMILIES[family]}/bc091474-u{factor}-pilot/execution.log); `{rel}`.")
        lines.append("")

    lines += ["## Frozen pilot screen", "",
              "A factor-band pair passes only when every in-band aligned warm anchor "
              "has a point estimate above one in both families and its adjacent "
              "out-of-band anchor has a point estimate at least one in both families.",
              "", "| Factor | Band | In-band misses | Adjacent misses | Eligible |",
              "|---:|---|---|---|---|"]
    eligible = []
    for factor in (2, 4):
        for band, adjacent in (((8, 9), 7), ((63, 64, 65), 66)):
            misses = []
            adjacent_misses = []
            for family in FAMILIES:
                cells = sources[(factor, family)][1]
                misses += [f"{family} {width}w" for width in band
                           if point(cells[anchor(family, width)]) <= 1]
                if point(cells[anchor(family, adjacent)]) < 1:
                    adjacent_misses.append(f"{family} {adjacent}w")
            passes = not misses and not adjacent_misses
            if passes:
                eligible.append((factor, band))
            lines.append(f"| {factor} | `{','.join(map(str, band))}` | "
                         f"{', '.join(misses) or 'none'} | "
                         f"{', '.join(adjacent_misses) or 'none'} | "
                         f"{'yes' if passes else 'no'} |")
    assert not eligible, "the decision prose must be revisited if the screen changes"
    counts = {family: ledger_comparisons(family) for family in FAMILIES}
    assert counts == {"isolated": 0, "row": 0}
    lines += ["", "The frozen screen selects no confirmatory identity. The "
              f"[isolated ledger](../../bench_results/2037941f/logical-isolated-xor-ledger.jsonl) "
              f"reserves {counts['isolated']} comparisons and the "
              f"[public-row ledger](../../bench_results/2037941f/logical-public-row-xor-ledger.jsonl) "
              f"reserves {counts['row']}. A first five-cell confirmation would use "
              "$\\alpha_1=0.05/(1\\cdot2)=0.025$ and "
              "$\\alpha_c=0.025/5=0.005$. Its bootstrap tail support would be "
              "$10000\\alpha_c/2=25\\ge20$. The point-estimate screen stops "
              "before any reservation or candidate confirmation.", ""]

    added = added_nonblank_source_lines()
    assert added <= 80
    lines += ["## Code complexity", "",
              "The candidate source commit changes the existing AVX2 XOR file. "
              f"Its diff adds {added} nonblank source lines against its parent, "
              "within the frozen 80-line cap. The measured symbol sizes below "
              "come from the release disassembly headers; size is not a speed result.",
              "", "| Body | Symbol bytes | Assembly |", "|---|---:|---|"]
    for variant, label in (("baseline", "Baseline"), ("unroll2", "Factor 2"),
                           ("unroll4", "Factor 4")):
        lines.append(f"| {label} | {assembly_size(variant)} | "
                     f"[disassembly](asm/{variant}-avx2-xor.asm.txt) |")
    lines.append("")

    profiles = {
        "baseline": RESULTS / "2037941f/logical-profile/profile-summary.md",
        "factor 2": RESULTS / "bc091474/profile-unroll2/profile-summary.md",
        "factor 4": RESULTS / "bc091474/profile-unroll4/profile-summary.md",
    }
    lines += ["## Profile context", "",
              "Each entry is the per-call process cost in nanoseconds with its "
              "nine-repetition order-statistic interval. The profile includes "
              "driver and fixture work and is attribution evidence, not a paired "
              "candidate comparison.", "",
              "| Case | Baseline ns/call | Factor 2 ns/call | Factor 4 ns/call |",
              "|---|---|---|---|"]
    for case in PROFILE_CASES:
        values = [profile_cost(path, case)[0] for path in profiles.values()]
        lines.append(f"| `{case}` | {' | '.join(values)} |")
    lines += ["", "Sources: [baseline](../../bench_results/2037941f/logical-profile/profile-summary.md), "
              "[factor 2](../../bench_results/bc091474/profile-unroll2/profile-summary.md), "
              "[factor 4](../../bench_results/bc091474/profile-unroll4/profile-summary.md).", ""]
    (ACTIVE / "candidate-tables.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
