#!/usr/bin/env python3
"""Project the v3 receipts and acceptance summaries into `tables.md`.

Usage: dev/active/6fb89a3c/survey/summarize.py  (from the repo root)

Every number in the tables is read from a committed receipt or from the
acceptance summary the independent evaluator wrote for it; nothing is
transcribed. Speedups are median(baseline)/median(candidate) with the
candidate always the external arm, so a value above 1 means the external arm
is ahead of gf2.
"""
from __future__ import annotations

import json
import pathlib
import statistics

RESULTS = pathlib.Path("dev/bench_results/6fb89a3c")
FAMILIES = [
    ("Transpose and conversion (`transpose-vs-external`)", "transpose"),
    ("Logical buffers (`logical-buffer-vs-isal`)", "logical"),
    ("BCH generator-matrix conversion (`bch-genmatrix-consumer`)", "bch"),
]


def median(values):
    return statistics.median(values) if values else float("nan")


def cell_rows(receipt, summary):
    verdicts = {cell["cell_id"]: cell for cell in summary["cells"]}
    for cell in receipt["cells"]:
        verdict = verdicts[cell["cell_id"]]
        interval = verdict.get("interval")
        pairs = cell["pairs"]
        base_ns = median([p["baseline"]["ns_per_call"] for p in pairs])
        cand_ns = median([p["candidate"]["ns_per_call"] for p in pairs])
        paths = {arm: sorted({p[arm]["selected_path"] for p in pairs}) for arm in ("baseline", "candidate")}
        flagged = f"{verdict['flagged_windows']}/{verdict['total_windows']}"
        yield cell, verdict, interval, base_ns, cand_ns, paths, flagged


def conversion_rows(receipt):
    for cell in receipt["cells"]:
        for arm in ("baseline", "candidate"):
            records = [p[arm]["conversion"] for p in cell["pairs"] if p[arm].get("conversion")]
            if not records:
                continue
            yield cell["cell_id"], cell[f"{arm}_arm"], {
                key: median([r[key] for r in records]) for key in ("setup_ns", "pack_ns", "unpack_ns", "dispatch_ns")
            }


def render(directory: pathlib.Path) -> list[str]:
    receipt = json.loads((directory / "receipt.json").read_text())
    summary = json.loads((directory / "acceptance-summary.json").read_text())
    family = summary.get("family") or {}
    lines = [
        f"Source: `{directory.relative_to(RESULTS)}/receipt.json` (SHA-256 `{summary['receipt_sha256']}`) and its acceptance summary.",
        f"Label **{summary['label']}**; verdict **{summary['verdict']}**; qualifies {summary['qualifies']}; sessions {summary['sessions']}; "
        f"ledger comparisons {family.get('comparisons')}; attempt alpha {family.get('family_alpha')}; "
        f"per-comparison confidence {family.get('per_comparison_confidence')}; findings {len(summary['findings'])}.",
        "",
        "| Cell | Role | Pairs | Flagged | gf2 median ns/call | External median ns/call | Speedup [interval] | Decision | Outcome | gf2 path | External path |",
        "|---|---|---:|---:|---:|---:|---|---|---|---|---|",
    ]
    for cell, verdict, interval, base_ns, cand_ns, paths, flagged in cell_rows(receipt, summary):
        if interval:
            speedup = f"{interval['estimate']:.4g} [{interval['lower']:.4g}, {interval['upper']:.4g}]"
        else:
            speedup = "-"
        lines.append(
            f"| `{cell['cell_id']}` | {cell['role']} | {len(cell['pairs'])} | {flagged} | {base_ns:.4g} | {cand_ns:.4g} | {speedup} | "
            f"{verdict.get('decision') or '-'} | **{verdict['outcome']}** | {', '.join(paths['baseline'])} | {', '.join(paths['candidate'])} |"
        )
    conversions = list(conversion_rows(receipt))
    if conversions:
        lines += [
            "",
            "Setup and arrangement probes (median over executions, nanoseconds; measured outside the timed windows and reported beside them, "
            "the arrangement work itself is inside every timed call):",
            "",
            "| Cell | Arm | setup | pack | unpack | dispatch |",
            "|---|---|---:|---:|---:|---:|",
        ]
        for cell_id, arm, record in conversions:
            lines.append(f"| `{cell_id}` | {arm} | {record['setup_ns']:.4g} | {record['pack_ns']:.4g} | {record['unpack_ns']:.4g} | {record['dispatch_ns']:.4g} |")
    for finding in summary["findings"]:
        lines.append(f"- Finding `{finding['rule']}` ({finding['severity']}) {finding.get('cell') or ''}: {finding['message']}")
    return lines


def main() -> None:
    out = [
        "# Comparator survey evidence tables",
        "",
        "> **Diátaxis Type:** Reference",
        "",
        "Generated by `dev/active/6fb89a3c/survey/summarize.py` from the committed protocol-v3 receipts and their independently "
        "recomputed acceptance summaries. Speedup is median(gf2)/median(external): above 1 the external arm is ahead. "
        "`regressed`/`fail` in a comparator-gap cell means gf2 is materially ahead of the external arm; `improved`/`pass` means "
        "the external arm holds a material gap that needs attribution; `not-material` means neither.",
        "",
    ]
    for title, family in FAMILIES:
        out += [f"## {title}", ""]
        for mode in ("pilot", "confirmation"):
            for directory in sorted(RESULTS.glob(f"v3-*-6fb89a3c-{family}-{mode}")):
                if (directory / "acceptance-summary.json").exists():
                    out += [f"### {mode} `{directory.name}`", ""] + render(directory) + [""]
    (RESULTS / "tables.md").write_text("\n".join(out))
    print(f"-> {RESULTS / 'tables.md'}")


if __name__ == "__main__":
    main()
