#!/usr/bin/env bash
# Generated by dev/scripts/migrate-link-labels.py. Idempotent: removing an absent
# label and adding a present one are no-ops.
set -euo pipefail
JIT="${JIT:-jit}"
"$JIT" issue update 00dd43c3-2335-40bd-948a-32f95bd450ce --remove-label satisfies:REQ-01 --label satisfies:c04dd4ac/REQ-01 --remove-label satisfies:REQ-07 --label satisfies:c04dd4ac/REQ-07 --remove-label satisfies:REQ-11 --label satisfies:c04dd4ac/REQ-11
"$JIT" issue update 01c20b61-4dce-4437-baab-9c9d03d1d2c1 --remove-label satisfies:REQ-06 --label satisfies:fa787f85/REQ-06
"$JIT" issue update 030496bd-633a-4ed0-81dd-77cdea296b01 --remove-label satisfies:REQ-24 --label satisfies:ffc35b8c/REQ-24 --remove-label satisfies:REQ-27 --label satisfies:ffc35b8c/REQ-27
"$JIT" issue update 032cc754-c88c-4e1b-b56d-6511d0a70c3c --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 03594635-8397-43a0-b0e8-e1ae1113ef08 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 036615b0-6ab3-4bc8-a8e2-c36837296111 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 047b62ed-5184-4295-b4bd-d31263411b53 --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03 --remove-label satisfies:REQ-09 --label satisfies:0de41c82/REQ-09 --remove-label satisfies:REQ-10 --label satisfies:0de41c82/REQ-10 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 04b85d10-fb4f-467c-b6e5-869c99018adc --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01
"$JIT" issue update 0665e7be-6150-45a0-94bc-1ce11c61bd2b --remove-label satisfies:REQ-05 --label satisfies:b8206228/REQ-05 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update 06ba0418-f933-4037-b3d2-bd2b6dc6a1d5 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 07ca8585-d822-49e7-96b8-18f6a3d73d4e --remove-label satisfies:REQ-03 --label satisfies:1a379447/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update 0a0ece44-5efc-46ca-bbf5-5fb2674c570f --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 0a357f94-0c89-4bee-9330-a4fc1da7f076 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04
"$JIT" issue update 0c21cb1e-e08a-4232-a1bc-4b7aef095c9e --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 0c4d84cf-fd75-459f-bdd1-0087d8269a9a --remove-label satisfies:REQ-06 --label satisfies:ae03bcd0/REQ-06 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 0c5aa3b7-4846-4ec8-a578-14e6b35e78dd --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14
"$JIT" issue update 0d819b62-f6ad-49e0-add7-fd9f3486fe42 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 0de41c82-fb20-4adb-ba6e-30061a83c301 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 0dffa759-8ff3-4198-a901-23bedf6667e0 --remove-label satisfies:REQ-01 --label satisfies:0de41c82/REQ-01 --remove-label satisfies:REQ-05 --label satisfies:0de41c82/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:0de41c82/REQ-06 --remove-label satisfies:REQ-11 --label satisfies:0de41c82/REQ-11 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 0e706bf5-2057-43e7-9aeb-ec21539c48a4 --remove-label satisfies:REQ-02 --label satisfies:ae03bcd0/REQ-02
"$JIT" issue update 103a792a-4168-44d5-9a0f-9373e002b793 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 11964cb8-75c9-4413-bff8-d781d6b3e7eb --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 12907582-b66a-4bd7-b50c-4d0e743c89a0 --remove-label satisfies:REQ-17 --label satisfies:fa787f85/REQ-17
"$JIT" issue update 12fdeb5b-685d-4232-a350-2585c29cfed6 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Srsran2026 --label cites:@/citation/Srsran2026 --remove-label cites:ThreeGpp2017 --label cites:@/citation/ThreeGpp2017
"$JIT" issue update 130d5fd7-4540-4a29-9bd5-67d755bae78c --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 1362381c-78c0-42eb-bdc9-4327f20bc343 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label satisfies:REQ-03 --label satisfies:1a379447/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:1a379447/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:1a379447/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:GfComplete2026 --label cites:@/citation/GfComplete2026 --remove-label cites:Libpopcnt2026 --label cites:@/citation/Libpopcnt2026 --remove-label cites:Mula2018 --label cites:@/citation/Mula2018 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026 --remove-label cites:Bitshuffle2026 --label cites:@/citation/Bitshuffle2026 --remove-label cites:GfTwoX2026 --label cites:@/citation/GfTwoX2026 --remove-label cites:Srsran2026 --label cites:@/citation/Srsran2026 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026 --remove-label cites:OpenAirInterface2026 --label cites:@/citation/OpenAirInterface2026 --remove-label cites:Mfourrie2026 --label cites:@/citation/Mfourrie2026
"$JIT" issue update 13dfe1a5-a770-4910-b6b3-36e4b2a91cca --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 153297cf-7687-4599-be56-23e038efee3d --remove-label satisfies:REQ-07 --label satisfies:fa787f85/REQ-07
"$JIT" issue update 16560579-abd8-446c-9a02-9715feeee1af --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update 175972df-556d-437f-a9cd-10f08eed03d6 --remove-label satisfies:REQ-04 --label satisfies:b8206228/REQ-04 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update 177bdc85-11ac-4ed8-94ef-ae2876e44045 --remove-label satisfies:REQ-07 --label satisfies:ae03bcd0/REQ-07
"$JIT" issue update 18a160f5-6c08-4690-81db-e4049f771fa4 --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:ae03bcd0/REQ-04
"$JIT" issue update 18a87159-ff6a-483b-ade2-9830ed0f1a69 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update 19424a0f-38d5-4578-bde6-0e18e18abccd --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 1947125e-33eb-4442-b717-24442cc35ca1 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 19513245-7fb9-4490-8e41-d9c01405db01 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:GfComplete2026 --label cites:@/citation/GfComplete2026 --remove-label cites:Mfourrie2026 --label cites:@/citation/Mfourrie2026
"$JIT" issue update 198aafa3-0553-4a93-8dab-6e971fe3048b --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 19fe9394-5220-4f74-adb9-34280ecd6fc1 --remove-label satisfies:REQ-02 --label satisfies:ae03bcd0/REQ-02
"$JIT" issue update 1ac74567-fa48-405a-a35a-a4f2bcb16fe5 --remove-label satisfies:REQ-05 --label satisfies:6dc81018/REQ-05
"$JIT" issue update 1adfe2e9-2e12-4851-a341-69c36d50d63f --remove-label satisfies:REQ-09 --label satisfies:fa787f85/REQ-09
"$JIT" issue update 1b113b9d-4ccc-4c79-94cc-b5746aa4724d --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 1c602857-5e5b-4981-949a-09bb7639476b --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02
"$JIT" issue update 1c9a0f9f-3fa5-4728-85b7-5354448af01f --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03
"$JIT" issue update 1ca94ec2-5e10-4a27-95cf-e743a64ac9e2 --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update 1d0b3ec4-f4b1-4dba-91b0-4afbaca71b48 --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update 1d0da41f-f366-4a81-ab1a-016f8395db94 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update 1d4fd63d-c522-47cb-9448-fe8f5220f0ed --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026 --remove-label cites:Bitshuffle2026 --label cites:@/citation/Bitshuffle2026 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Djelic2011 --label cites:@/citation/Djelic2011
"$JIT" issue update 1fca3739-f773-4736-bb4b-ff6c5ec30ee9 --remove-label satisfies:REQ-06 --label satisfies:fa787f85/REQ-06
"$JIT" issue update 2037941f-852c-4d94-9d49-ad06a364dca8 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 203ee826-87bf-469b-abaa-a9128869f645 --remove-label satisfies:REQ-05 --label satisfies:ae03bcd0/REQ-05 --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13
"$JIT" issue update 217deff3-904b-42ba-b14d-bd89344761d2 --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03
"$JIT" issue update 220cab0b-2197-4d43-a1c9-a46ebe7d6706 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 227ac5c8-b286-4483-9a49-f876f02daa96 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 22c7a3cd-b231-424e-86e5-2a0ad47aeacc --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 230dd84d-de00-4d79-b74b-f1a8d244da48 --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:ae03bcd0/REQ-04
"$JIT" issue update 23219502-6312-45e5-88cd-08f4b0f95aa8 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 23f22f53-2c4a-489c-bc85-52ff4ccc6629 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 24701af9-138e-4c45-85a9-60debe9458d0 --remove-label cites:Lch2014 --label cites:@/citation/Lch2014 --remove-label cites:DiamondPosen2023 --label cites:@/citation/DiamondPosen2023
"$JIT" issue update 2596b143-9284-450b-bf60-8e6510c7032b --remove-label satisfies:REQ-07 --label satisfies:fa787f85/REQ-07
"$JIT" issue update 26465e6c-6852-44b6-9183-ba2cb5a5fca5 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:Libpopcnt2026 --label cites:@/citation/Libpopcnt2026 --remove-label cites:Mula2018 --label cites:@/citation/Mula2018
"$JIT" issue update 265997f9-a947-4fbc-9161-a9f3a252bd01 --remove-label satisfies:REQ-01 --label satisfies:6dc81018/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:6dc81018/REQ-02
"$JIT" issue update 26ae7d6b-e526-41cd-b0d6-3dac68d362e0 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 278acf3a-3a49-4c79-8d54-8eb6c934c834 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 27f0f3b1-df9b-4836-a5f6-7313d794a9be --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 290b8716-2442-42af-9383-08f9d629219d --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 29331bd3-e56a-4521-8db9-096152ee8482 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 2a85f728-4f9f-40f3-a9ee-ab7655d83b9f --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 2ad3a3e0-0143-4ebb-98fb-07eda92b7ca0 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update 2b6968d3-1a00-4958-bdd0-4c86d548be00 --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13
"$JIT" issue update 2ff9953a-8d33-449f-80ac-f1564fefa14a --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05 --remove-label satisfies:REQ-17 --label satisfies:fa787f85/REQ-17
"$JIT" issue update 30c3aef1-9272-425d-8ac5-276cca22a8c7 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 312200e4-dce9-44d3-8b55-c20c610e1c03 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020
"$JIT" issue update 3243bc1f-83ce-48e3-9cc2-9f8b45038624 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 325e5c89-3362-40d0-ad63-a97fab53202b --remove-label cites:PPV2010 --label cites:@/citation/PPV2010
"$JIT" issue update 32f53280-fb5c-4a95-aeb9-15507fba6ac8 --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update 33812b86-ce1e-419e-9c96-c782fd1def8d --remove-label satisfies:REQ-05 --label satisfies:ae03bcd0/REQ-05
"$JIT" issue update 342710ef-ea5a-4f44-9884-cb08d13f1ee6 --remove-label satisfies:REQ-09 --label satisfies:0de41c82/REQ-09
"$JIT" issue update 34adff85-7b63-43fa-9a4f-324961b6cf21 --remove-label satisfies:REQ-38 --label satisfies:3f29e945/REQ-38
"$JIT" issue update 34d85cb9-1ff4-4adb-a09e-7305dee0b0dc --remove-label satisfies:REQ-05 --label satisfies:6dc81018/REQ-05
"$JIT" issue update 37099e5b-66ef-44ef-a6ef-a58dafd93c9e --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14
"$JIT" issue update 3759f995-edc4-4061-8b45-0ec30078a691 --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update 377a7a62-ae1f-486f-bac9-2106095d7cb0 --remove-label satisfies:REQ-01 --label satisfies:cce5da8c/REQ-01 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update 37c288cf-fe3d-436c-8310-9f428dada164 --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:ae03bcd0/REQ-04
"$JIT" issue update 395fc8e1-2ad6-4100-a578-f14398268fdf --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 3aef9e33-d0e5-4de7-b73b-d0a99839829b --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 3be770d5-779b-4a82-ad66-f9cec35057dc --remove-label satisfies:REQ-01 --label satisfies:d77176e5/REQ-01 --remove-label satisfies:REQ-03 --label satisfies:1a379447/REQ-03 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update 3d34f504-4adb-453c-b5a6-3d4e6d2dc223 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 3da13f39-225c-4615-9f68-f1daa76af90b --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 3e83c116-4623-4f45-a9bd-b45712a3dc17 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026
"$JIT" issue update 3ea122df-f38e-4ce7-8c8b-4b594a8cf139 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026
"$JIT" issue update 3ea744cf-6d0b-41e7-834d-efffac55f5c0 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 3f29e945-8b12-4862-82c8-f2ec6573287c --remove-label satisfies:REQ-01 --label satisfies:f357b3dc/REQ-01 --remove-label satisfies:REQ-16 --label satisfies:fa787f85/REQ-16
"$JIT" issue update 3f664839-fb97-4bb5-8141-7c39026325fe --remove-label satisfies:REQ-06 --label satisfies:b8206228/REQ-06 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update 3f7edef1-1b3b-4aa4-a813-bf96ee78d6ee --remove-label satisfies:REQ-11 --label satisfies:ae03bcd0/REQ-11
"$JIT" issue update 3fa7c9d0-2353-48bf-bd37-ef34e36dea27 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 3fd3db5e-60ea-41c1-b95a-144d9ae02e4a --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 4058e0ac-8405-4266-9ec2-05f2e0430ae9 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update 41090b8d-bcf4-4e79-9cca-54070b5b589e --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update 41c3d91d-5eeb-4173-9fb9-fe7a3e3bb39d --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 41e1d47d-046e-4808-a424-83898cf9b1ee --remove-label satisfies:REQ-18 --label satisfies:fa787f85/REQ-18 --remove-label satisfies:REQ-20 --label satisfies:fa787f85/REQ-20
"$JIT" issue update 42037c91-71ad-431b-b27a-e9826e5354a9 --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update 444c06bc-7a0a-4e00-899a-c74815793fe9 --remove-label satisfies:REQ-07 --label satisfies:ae03bcd0/REQ-07 --remove-label satisfies:REQ-08 --label satisfies:ae03bcd0/REQ-08
"$JIT" issue update 44534b2f-b92a-4758-9e78-3a93ce4a209c --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 44f4586d-5d13-42a3-b6ff-1be4ae2bc18d --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 44fcbdc2-07dc-453c-b061-84b135b628e0 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 493a5330-be91-41a6-b83d-eb5201394724 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 495807a3-caeb-4680-8429-13d7da4a590d --remove-label satisfies:REQ-31 --label satisfies:3f29e945/REQ-31 --remove-label satisfies:REQ-32 --label satisfies:3f29e945/REQ-32 --remove-label satisfies:REQ-33 --label satisfies:3f29e945/REQ-33
"$JIT" issue update 4997a3ed-0791-41b2-b19c-5f5ff8ed943f --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 49cbb131-cae2-4e8e-97d4-759ecbb11297 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 4a2baa12-af89-47f2-abb4-90b741929b5e --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 4a6bdcff-9342-47d1-ace9-b3a5c0eeb98b --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 4ad869d6-901d-465d-9d29-7c3a4f34ee8e --remove-label satisfies:REQ-15 --label satisfies:ae03bcd0/REQ-15
"$JIT" issue update 4bdcd65a-e338-488b-b42e-19bee4a875a9 --remove-label satisfies:REQ-08 --label satisfies:fa787f85/REQ-08
"$JIT" issue update 4c1e441f-2bb4-43dd-bd73-256c3721800a --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:1a379447/REQ-04
"$JIT" issue update 4d0ae96f-d2d2-46a4-b1a1-0b30a92800e4 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 4e732b56-b6ab-451b-959e-ff4ea09a59d2 --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13
"$JIT" issue update 4f161183-869b-4369-83e9-46dc023720d5 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 4f752758-6fd7-45f6-880c-3c8b853e1783 --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 50b47eae-05c8-4704-91c0-ac0816a76496 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 50f0bd42-56d8-4905-a0d5-409b7aa32ba7 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 51058f8e-6bad-443c-aa5b-14d430bcd0c7 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 5143ee0b-cd9b-4323-a41d-104e176143ed --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02
"$JIT" issue update 51498b90-ae91-449f-bcc2-0f209bd16284 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 5194f470-1703-4564-8057-37fc4efb39b2 --remove-label satisfies:REQ-04 --label satisfies:b7157be6/REQ-04
"$JIT" issue update 5233867e-19bb-4b9f-a308-ee49c2578dde --remove-label satisfies:REQ-05 --label satisfies:ae03bcd0/REQ-05
"$JIT" issue update 52fb615b-0294-4452-bf34-2d7a178029b0 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 531695da-f7a4-45e7-b982-cbe27bd41745 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 53c5a8c0-ad93-4fdb-8319-aea18c3c257c --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:GfTwoX2026 --label cites:@/citation/GfTwoX2026
"$JIT" issue update 53d8e438-7bbe-4397-b43c-c9e100e145b1 --remove-label satisfies:REQ-05 --label satisfies:b8206228/REQ-05 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update 54278d0c-8fe8-4022-b560-584c26e6d41d --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 55087229-89d6-4e23-afb2-96fd62de0cda --remove-label cites:Arikan2019 --label cites:@/citation/Arikan2019 --remove-label cites:Yao2020 --label cites:@/citation/Yao2020 --remove-label cites:PacScl2024 --label cites:@/citation/PacScl2024 --remove-label cites:Aed2024 --label cites:@/citation/Aed2024 --remove-label cites:Rcaed2023 --label cites:@/citation/Rcaed2023 --remove-label cites:Rowshan2024 --label cites:@/citation/Rowshan2024
"$JIT" issue update 5625a423-3ccc-4d11-b839-52c8fd311601 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 56378e82-2a72-44ef-96b6-1d12d7332976 --remove-label satisfies:REQ-34 --label satisfies:3f29e945/REQ-34
"$JIT" issue update 56c69654-694b-45cd-bb4b-3e4a798f4c08 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label satisfies:REQ-05 --label satisfies:0de41c82/REQ-05 --remove-label satisfies:REQ-08 --label satisfies:0de41c82/REQ-08 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 571aaf80-625e-49d3-8562-90cad90e2fc1 --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03
"$JIT" issue update 57436474-9b84-4d68-804f-070c10b673d9 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 5758790d-421b-47d2-a6f0-c40d1c5dc465 --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03
"$JIT" issue update 583ec31c-dc85-4751-8531-687ce6e7fd7d --remove-label satisfies:REQ-03 --label satisfies:cce5da8c/REQ-03 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020
"$JIT" issue update 59024f1a-23b1-422a-b2b4-d09f13db5661 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 591a1c5e-d36b-42be-b27e-65bc9a7b3e9a --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 595415c8-f396-4c5b-a5b8-c5f1000e644c --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 5a25717c-83f4-453c-8866-cab67ecf2103 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 5bdc9552-0290-4dca-b0a6-bc7009837875 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 5c0b9635-86f6-4e9b-8ff9-e12af604395a --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 5c65e724-a1a7-49ed-ad0a-878ca3bfb23c --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 5cbb6545-4496-4325-8fa9-d50aaa9fcf50 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Libpopcnt2026 --label cites:@/citation/Libpopcnt2026 --remove-label cites:Mula2018 --label cites:@/citation/Mula2018
"$JIT" issue update 5cbdec87-a157-4b20-8766-6d24400b0184 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 5d45dc2a-814b-4d30-9c51-847fec848a29 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 5dd3539f-3c3a-413e-956d-87596d346263 --remove-label satisfies:REQ-01 --label satisfies:cce5da8c/REQ-01 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995
"$JIT" issue update 5ec5dcc1-5344-4754-ad35-3e6ce3a327e7 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 5ecc9bf8-3d62-408e-aba8-53ad2790a49d --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 5ee83cd3-cbdf-42cb-a465-6941852016f3 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 602652bf-0388-4604-882b-f874efff83c2 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 60652fe4-d6dd-49e9-97f1-db99b4c73111 --remove-label satisfies:REQ-08 --label satisfies:fa787f85/REQ-08
"$JIT" issue update 613574db-f283-425f-b664-369f3e93d756 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update 616e1d7c-1e65-45f0-91d4-2eb194746882 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 62f0d0e6-0d54-44a6-a5d7-31b09c33976d --remove-label satisfies:REQ-27 --label satisfies:ffc35b8c/REQ-27
"$JIT" issue update 63bad95d-0e69-459b-840b-c37521036f52 --remove-label satisfies:REQ-04 --label satisfies:1a379447/REQ-04 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update 64fd3afd-98c0-4a21-b225-43c612d1ea82 --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update 65a5436a-3ee5-4df9-9a9c-8ad79f41c566 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 65c0e13d-74af-4f66-8b08-d2eba04e2a5b --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026
"$JIT" issue update 6639435f-8be8-4408-b6ab-759fe0099bd2 --remove-label satisfies:REQ-06 --label satisfies:b8206228/REQ-06 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update 66858db0-c5c6-45a7-9c3d-c1a58f0f9f24 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 67048b47-ed17-4672-822a-829a796420c2 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 676f55a2-ae5e-45c6-b1ab-db2dee71770b --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 67b5d1d8-b6e2-4687-ae5f-fd36bcee334a --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 687c694d-cb6a-49fc-ade1-b8c0f3d4309e --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 697fc55b-4b36-4cb5-8106-a811b1772e44 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 698fa793-8c74-4019-a605-9d078f023cbc --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 69aa6896-4c6e-42bb-90b6-d7237a31dc14 --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04
"$JIT" issue update 69ff9f3c-8886-4d18-8b80-fa412739946c --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 6a1b2404-1241-4f0e-b471-7f619cadbd9f --remove-label satisfies:REQ-07 --label satisfies:ae03bcd0/REQ-07
"$JIT" issue update 6aac5c44-c545-4f4f-bbd1-87c90588953c --remove-label satisfies:REQ-01 --label satisfies:ae03bcd0/REQ-01
"$JIT" issue update 6ae9f4ac-3a71-4db5-b7d7-51b0f92fdc8f --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update 6beaf008-b524-4922-b77f-3f1a838635d4 --remove-label satisfies:REQ-01 --label satisfies:cce5da8c/REQ-01 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update 6c314026-6f34-490d-9403-39b7ecc89ea5 --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 6c6b09b1-7fa8-4ec2-b37f-e3894ead9de2 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:Mfourrie2026 --label cites:@/citation/Mfourrie2026 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:GfComplete2026 --label cites:@/citation/GfComplete2026
"$JIT" issue update 6c7fcb38-559e-4c52-8104-d9d3758ad40b --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03 --remove-label satisfies:REQ-07 --label satisfies:0de41c82/REQ-07 --remove-label satisfies:REQ-09 --label satisfies:0de41c82/REQ-09 --remove-label satisfies:REQ-10 --label satisfies:0de41c82/REQ-10 --remove-label satisfies:REQ-11 --label satisfies:0de41c82/REQ-11 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 6d0ff83c-8355-40e3-819d-3eca22501bf7 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label satisfies:REQ-10 --label satisfies:0de41c82/REQ-10
"$JIT" issue update 6d2ab2bd-2af6-4b29-b640-f5411140d1ac --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 6d67e57e-0dac-44a4-afa8-b5c1eb33aff7 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 6e87c436-53d2-4fd4-bf58-aee2c7ed97fb --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update 6fb89a3c-f1a7-439d-a397-add1782afe2b --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026 --remove-label cites:Bitshuffle2026 --label cites:@/citation/Bitshuffle2026 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026
"$JIT" issue update 7039d680-06da-481e-b000-5f9bba44e9ee --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 704c90b8-6fdc-4584-ba78-f2bbee136917 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 72768e37-a609-427c-a3e6-8a4efcf4c8b8 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 73317b2e-8f01-472e-b04f-05ff9ef2b8be --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update 739f43b0-4672-46e5-9a68-afaa1610d5c1 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label satisfies:REQ-08 --label satisfies:0de41c82/REQ-08 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 769c3144-318c-4c3c-9258-ba36a4f5bd80 --remove-label satisfies:REQ-02 --label satisfies:ae03bcd0/REQ-02
"$JIT" issue update 773a5378-964c-473c-9161-e519d3470d35 --remove-label satisfies:REQ-04 --label satisfies:0de41c82/REQ-04
"$JIT" issue update 77c21ecd-5350-449f-ba32-dab1b2c6a8a6 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update 799af6fe-985b-430b-9a7f-1dffac8a2528 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 7a3a6738-3ec0-42ea-86dd-c2d845689e1a --remove-label satisfies:REQ-03 --label satisfies:ae03bcd0/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:ae03bcd0/REQ-06
"$JIT" issue update 7b998fb9-77db-429b-8609-64cd0c7f8600 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label satisfies:REQ-05 --label satisfies:0de41c82/REQ-05 --remove-label satisfies:REQ-08 --label satisfies:0de41c82/REQ-08 --remove-label satisfies:REQ-10 --label satisfies:0de41c82/REQ-10 --remove-label satisfies:REQ-11 --label satisfies:0de41c82/REQ-11 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 7bac1303-eed8-443a-a504-593a87710cb4 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 7bfad039-1fd6-4738-a845-b9c738458968 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 7cdc28e9-b18a-45e4-b430-4e8a59dff8e3 --remove-label satisfies:REQ-05 --label satisfies:1a379447/REQ-05
"$JIT" issue update 7d7c647c-bcf4-4333-bffb-8b92f515d544 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 7d824b2f-13a6-4d19-a8bc-5581a42e7a76 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 7dbcde0c-3a5c-472e-8c41-e5e1e8d71bfa --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 7edd421d-30a1-41e4-96f6-b46b8beac04d --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03
"$JIT" issue update 7f818151-9268-4f6d-b29e-508eb95ba12c --remove-label satisfies:REQ-02 --label satisfies:6dc81018/REQ-02
"$JIT" issue update 807ddab2-f77b-4276-9430-e397258499c7 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update 8275a6f8-0a9f-40f9-b6ed-e17e355c5905 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01
"$JIT" issue update 835e15fb-a402-44b8-9928-98b10776782a --remove-label satisfies:REQ-03 --label satisfies:b7157be6/REQ-03 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020
"$JIT" issue update 83eedd07-9710-4109-98a3-2b839f3cee98 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 83f9ce69-6d18-4767-ac9c-6b2f00485581 --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update 8434e0e1-859d-4b18-ad3c-2942ae248b60 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update 856f1b48-e518-4329-889f-e2589629622d --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 85fc5ff4-b6c0-4cc2-ab31-6df8df98bdce --remove-label satisfies:REQ-01 --label satisfies:c04dd4ac/REQ-01 --remove-label satisfies:REQ-07 --label satisfies:c04dd4ac/REQ-07 --remove-label satisfies:REQ-08 --label satisfies:c04dd4ac/REQ-08 --remove-label satisfies:REQ-09 --label satisfies:c04dd4ac/REQ-09 --remove-label satisfies:REQ-11 --label satisfies:c04dd4ac/REQ-11
"$JIT" issue update 871b401d-59f7-4fa4-86b6-9c067795ff06 --remove-label satisfies:REQ-01 --label satisfies:fa787f85/REQ-01
"$JIT" issue update 875914b3-38c8-4ec2-a13f-009fc620f7d4 --remove-label satisfies:REQ-08 --label satisfies:fa787f85/REQ-08
"$JIT" issue update 88441adb-3956-4bf2-bfe9-284e7dcc5c10 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 88942e12-2ece-4f31-b907-99b7d73b4c7d --remove-label cites:Lch2014 --label cites:@/citation/Lch2014 --remove-label cites:DiamondPosen2023 --label cites:@/citation/DiamondPosen2023
"$JIT" issue update 88f0bb88-1971-4ad8-9210-0e94a5b5eee1 --remove-label satisfies:REQ-09 --label satisfies:ae03bcd0/REQ-09
"$JIT" issue update 8a9156fc-3015-47c7-8a7f-2e549962252d --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 8a9db61a-115b-4f07-9baf-97e6545525a5 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 8aa98a25-9c61-4f26-87d1-3b65f8324bd8 --remove-label satisfies:REQ-05 --label satisfies:ae03bcd0/REQ-05
"$JIT" issue update 8b42d23b-d94b-4c2b-84a5-9776619123c5 --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 8bd873f7-4758-44cd-91aa-03db3a7a533b --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 8d8be934-347f-4d7a-a53a-e7f8e13aaad8 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 8dbb27e9-e1d9-4d14-9d40-babec27d1216 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update 8ec10dde-07db-40f8-bac6-094cbe2635c0 --remove-label satisfies:REQ-06 --label satisfies:b8206228/REQ-06 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update 8ed3ac58-48a7-4a3b-8a4d-475e23eadcdd --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update 8f451167-c774-42d0-b8e6-346a6df8ee7a --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 8f51d6cf-873a-4b30-8f98-58875cfd79d2 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update 8f61d6de-e29a-4d83-8bab-4ac61df0b2bf --remove-label satisfies:REQ-36 --label satisfies:3f29e945/REQ-36 --remove-label satisfies:REQ-37 --label satisfies:3f29e945/REQ-37 --remove-label satisfies:REQ-40 --label satisfies:3f29e945/REQ-40
"$JIT" issue update 8f68699b-d66a-45f2-a276-b8700bd4cc65 --remove-label satisfies:REQ-07 --label satisfies:ae03bcd0/REQ-07
"$JIT" issue update 90a61cd4-c48d-4097-ae2c-e628163a754a --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 912f1008-dee5-435e-98b3-974c40449efc --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 91605d4d-8c30-43d6-b1bd-26f277b31120 --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03 --remove-label satisfies:REQ-07 --label satisfies:0de41c82/REQ-07 --remove-label satisfies:REQ-09 --label satisfies:0de41c82/REQ-09 --remove-label satisfies:REQ-10 --label satisfies:0de41c82/REQ-10 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 9162956b-9891-49c8-81f5-80ba066ba532 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 922f0cac-5a45-429b-9706-fbab0a09a063 --remove-label cites:Lch2014 --label cites:@/citation/Lch2014 --remove-label cites:DiamondPosen2023 --label cites:@/citation/DiamondPosen2023
"$JIT" issue update 92385645-25ab-480c-996b-61049d186a70 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 93aed46a-441a-488e-8d25-651abc1897a0 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 9451498f-62f6-4e28-bd93-dffc836fdf02 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update 94597a51-67af-4ac3-b106-be82b9b1a34a --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update 96c94b81-f0d9-4122-9fae-027ae3f6bb01 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-03 --label satisfies:2037941f/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06 --remove-label cites:AlbrechtBard2026 --label cites:@/citation/AlbrechtBard2026
"$JIT" issue update 972e2b88-d75c-411b-a6b5-06318fa84305 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update 97410c80-aba2-420f-870c-b71a5066d5e4 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update 9798835a-c5d1-495d-bdef-eb78f8580b46 --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03
"$JIT" issue update 981c5ae3-f2af-405c-8c98-620d991c9fb5 --remove-label satisfies:REQ-05 --label satisfies:ae03bcd0/REQ-05
"$JIT" issue update 992c6c6e-47a6-4e9b-9393-d9dfe33fab3e --remove-label satisfies:REQ-06 --label satisfies:ae03bcd0/REQ-06
"$JIT" issue update 997f0ab9-c591-4bfb-ad3b-b2b48336fe35 --remove-label satisfies:REQ-16 --label satisfies:ae03bcd0/REQ-16
"$JIT" issue update 9b2886a7-35af-45cc-9200-dddea1c0323a --remove-label satisfies:REQ-01 --label satisfies:fa787f85/REQ-01
"$JIT" issue update 9c5b26fb-a505-492e-8e9f-d8d520496ad0 --remove-label satisfies:REQ-01 --label satisfies:b8206228/REQ-01 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update 9dcc0cae-ef55-4f02-9446-83a0822ec158 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update 9dda3958-4e62-4bb2-89e4-a1999e000a09 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 9f47bb94-c7cd-4de9-b57f-0ea3cdeee282 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update 9fb40c83-7f48-4b39-afce-9e0f4f84c044 --remove-label satisfies:REQ-01 --label satisfies:c04dd4ac/REQ-01 --remove-label satisfies:REQ-07 --label satisfies:c04dd4ac/REQ-07 --remove-label satisfies:REQ-08 --label satisfies:c04dd4ac/REQ-08 --remove-label satisfies:REQ-09 --label satisfies:c04dd4ac/REQ-09 --remove-label satisfies:REQ-10 --label satisfies:c04dd4ac/REQ-10 --remove-label satisfies:REQ-11 --label satisfies:c04dd4ac/REQ-11 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026 --remove-label cites:Etsi2015 --label cites:@/citation/Etsi2015
"$JIT" issue update a0812b83-3d03-4317-aad4-f0d702444f14 --remove-label satisfies:REQ-01 --label satisfies:c04dd4ac/REQ-01 --remove-label satisfies:REQ-07 --label satisfies:c04dd4ac/REQ-07 --remove-label satisfies:REQ-08 --label satisfies:c04dd4ac/REQ-08 --remove-label satisfies:REQ-09 --label satisfies:c04dd4ac/REQ-09 --remove-label satisfies:REQ-10 --label satisfies:c04dd4ac/REQ-10 --remove-label satisfies:REQ-11 --label satisfies:c04dd4ac/REQ-11 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026 --remove-label cites:Etsi2015 --label cites:@/citation/Etsi2015
"$JIT" issue update a0a29512-ce14-4110-a541-65ef6612278d --remove-label satisfies:REQ-07 --label satisfies:fa787f85/REQ-07
"$JIT" issue update a1ad6d4e-c682-4af6-ada5-36ccfd9101e4 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update a1c801cb-5fc1-4094-83a1-6c16d0fb41b4 --remove-label cites:Fossorier1994 --label cites:@/citation/Fossorier1994
"$JIT" issue update a24b2af7-81ce-4442-9ee3-6ce096c36537 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13
"$JIT" issue update a2b00bd6-8944-4e91-b27b-5a39bb44e69a --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update a39bb161-0746-4f24-9057-32c9c2fa09fd --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update a82d2347-18ac-4cf4-8de5-8e7fe93be744 --remove-label satisfies:REQ-02 --label satisfies:fa787f85/REQ-02
"$JIT" issue update a82f2dd9-07b6-434e-806b-76b40ba43006 --remove-label satisfies:REQ-02 --label satisfies:b7157be6/REQ-02 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022 --remove-label cites:Fossorier1994 --label cites:@/citation/Fossorier1994 --remove-label cites:Isaka1999 --label cites:@/citation/Isaka1999
"$JIT" issue update a83583e0-7cfb-4e65-9273-69631929e297 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update a9284086-fbf3-4dad-975d-bcc74024e031 --remove-label satisfies:REQ-04 --label satisfies:0de41c82/REQ-04
"$JIT" issue update aa0558c1-8143-44b9-a2ca-27282d1cf015 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update aa904331-5c13-4d99-b2e2-590c7db7918a --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update abd48d99-1204-42d5-ae81-d0fd56a24f14 --remove-label satisfies:REQ-01 --label satisfies:cce5da8c/REQ-01 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update ad2a6a58-39f1-4d1e-bdcc-e6a1e909fe67 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:1a379447/REQ-04
"$JIT" issue update ad6778e8-bc9d-4e04-a85a-3e048b2bf428 --remove-label satisfies:REQ-01 --label satisfies:ae03bcd0/REQ-01
"$JIT" issue update aec4b6c8-d66d-45f2-ae53-211cff95c5e6 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update aed96ef9-2247-4d8a-94f2-681a277a7acd --remove-label cites:PPV2010 --label cites:@/citation/PPV2010 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022 --remove-label cites:LiZhang2026 --label cites:@/citation/LiZhang2026
"$JIT" issue update af302aa9-5f6e-438e-8c9f-67b455d3ebee --remove-label satisfies:REQ-09 --label satisfies:0de41c82/REQ-09
"$JIT" issue update af84619e-a2e1-4b3d-af9e-4120a43e4130 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13
"$JIT" issue update afbe89f5-ba5b-44cf-870c-00b3d8509a45 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update b05c908b-690d-4caa-9e2d-46d0f9ae0acc --remove-label satisfies:REQ-06 --label satisfies:b8206228/REQ-06 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update b146e998-e8a2-418c-a2cb-63debc4e6df4 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update b16d013a-c200-4e75-8c57-6638a313438e --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update b1bd75ca-5003-4597-87c0-0f9808a7b760 --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update b2bb1065-a8aa-4af7-a7d8-4f800ec8cf5a --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14
"$JIT" issue update b3cab18e-0ce0-427c-9e11-048a5578ec1a --remove-label satisfies:REQ-04 --label satisfies:b7157be6/REQ-04 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update b43158dc-91d0-42d8-a3aa-a62a042486d8 --remove-label satisfies:REQ-03 --label satisfies:b4b4b9ee/REQ-03 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update b488f02c-b16b-4444-9274-1cfc95172d3b --remove-label satisfies:REQ-01 --label satisfies:b8206228/REQ-01 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update b494fec8-579f-4a2d-8579-4fa58d50e3b1 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update b5d45bcd-05b8-42cd-a418-b73b47a15dac --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update b60de44f-ed6d-4c73-a759-6643391b94c0 --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update b64dc9c4-be76-4409-82fb-c4356d5c5521 --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06
"$JIT" issue update b6fdb815-20da-4ea9-af21-351b01746aee --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04
"$JIT" issue update b7157be6-16d8-4050-834c-e996d4fa27c3 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020
"$JIT" issue update b749bdfc-63e1-41c6-b8dc-65d334fdd652 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update b8206228-77d2-49ab-aaba-a16830d75cca --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update b9302771-703c-4f47-adb7-a7469d855b7b --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label cites:IsaL2026 --label cites:@/citation/IsaL2026
"$JIT" issue update b9539134-d320-44f0-abf9-a5c27243a1ec --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update b959ffe8-5a4a-406c-91fa-acc6a01a3167 --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14
"$JIT" issue update bb769456-6803-49ec-ae91-f1619dd0f278 --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update bc091474-8c85-4758-aef6-fffb012fad36 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update bd0edfa2-092e-4844-9291-3dd8fbd43d3e --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13
"$JIT" issue update bebe485c-82c8-49a5-aea8-20b44ad4fb3a --remove-label satisfies:REQ-02 --label satisfies:b7157be6/REQ-02 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995
"$JIT" issue update bfb37a21-1608-4ed9-a016-c60d0c87b4c9 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update c04dd4ac-8103-47bb-b504-7cca92417dfc --remove-label satisfies:REQ-02 --label satisfies:1a379447/REQ-02 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update c077a88b-2d35-49ed-bfe0-6fbc7055cea1 --remove-label satisfies:REQ-01 --label satisfies:d77176e5/REQ-01 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Srsran2026 --label cites:@/citation/Srsran2026 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026 --remove-label cites:OpenAirInterface2026 --label cites:@/citation/OpenAirInterface2026
"$JIT" issue update c31671ea-8da0-4c11-adfa-bc4ec5cdc49b --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update c3cc5226-2edf-40f7-a95d-b35bdcc1da57 --remove-label satisfies:REQ-09 --label satisfies:ae03bcd0/REQ-09
"$JIT" issue update c3d5cea5-71ac-4cd8-bddf-40be7e243526 --remove-label satisfies:REQ-01 --label satisfies:ae03bcd0/REQ-01
"$JIT" issue update c41d7e80-24dc-4c82-af4c-64674ad65a2a --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update c42720ce-1f7b-4058-97bf-de165786b8a0 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update c6aa0e84-072e-4671-9c50-0c8e9d0d4f66 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update c7113c5a-94da-462f-954e-3b7894bb95df --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:GfTwoX2026 --label cites:@/citation/GfTwoX2026
"$JIT" issue update c73ffa25-2ac2-4660-9f7e-330d0f818f1d --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update c7cfd37e-866e-42fd-9ad3-d33bc61e2f2b --remove-label cites:Lch2014 --label cites:@/citation/Lch2014 --remove-label cites:DiamondPosen2023 --label cites:@/citation/DiamondPosen2023 --remove-label cites:DiamondPosen2024 --label cites:@/citation/DiamondPosen2024 --remove-label cites:Blaze2024 --label cites:@/citation/Blaze2024 --remove-label cites:Jang2026 --label cites:@/citation/Jang2026
"$JIT" issue update c8322eff-8122-41bc-9209-9bcc9f591655 --remove-label satisfies:REQ-02 --label satisfies:b7157be6/REQ-02 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995
"$JIT" issue update c84ac71a-b9e8-4b10-9ebb-b433f7077dae --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update c852d9b2-3251-44c2-917f-00be035bbd07 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update c97b2961-6101-4383-9505-d69b380c5457 --remove-label satisfies:REQ-01 --label satisfies:cce5da8c/REQ-01 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update cafb463c-59ea-4dd5-8bc4-c7cc4521c00f --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update cc162697-2566-4b21-9b20-a97d3d293e58 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label satisfies:REQ-08 --label satisfies:0de41c82/REQ-08 --remove-label satisfies:REQ-11 --label satisfies:0de41c82/REQ-11 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update cce5da8c-acba-47f2-a629-ecc6cb7f593c --remove-label cites:Gidney2021 --label cites:@/citation/Gidney2021 --remove-label cites:Bravyi2024 --label cites:@/citation/Bravyi2024 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020 --remove-label cites:Muller2025 --label cites:@/citation/Muller2025 --remove-label cites:Hillmann2024 --label cites:@/citation/Hillmann2024
"$JIT" issue update cdaf5da9-280b-4d74-bd95-653e900adf10 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update cdba4e71-4444-41e0-b34e-904f3fb20ab4 --remove-label satisfies:REQ-04 --label satisfies:fa787f85/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update cef1ae5f-a971-464f-979e-61043ade81eb --remove-label satisfies:REQ-02 --label satisfies:b7157be6/REQ-02 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Fossorier1994 --label cites:@/citation/Fossorier1994
"$JIT" issue update d0365895-ee84-4d40-a8d3-8c9d767b9fa7 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update d1b4f85e-acb7-4a73-bf4f-7bc10ac5d512 --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13
"$JIT" issue update d1b6a182-ffcd-4efb-b4da-73331c63a699 --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update d1f6b2c9-4b2d-40a5-bea8-ce8b1ea601a9 --remove-label satisfies:REQ-13 --label satisfies:fa787f85/REQ-13 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update d36810e7-d000-4514-b18f-9a63a1403ba9 --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03
"$JIT" issue update d53cba10-d5ee-4764-8626-968ba5e6642c --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update d54cf660-6839-41cd-9637-18bb290da6ca --remove-label satisfies:REQ-08 --label satisfies:ae03bcd0/REQ-08
"$JIT" issue update d6ebc4ec-aa63-4c1d-bd0a-7ef4c33e9db6 --remove-label satisfies:REQ-15 --label satisfies:fa787f85/REQ-15 --remove-label satisfies:REQ-16 --label satisfies:fa787f85/REQ-16
"$JIT" issue update d76ffd12-2528-4e9f-b871-cc807ac2436d --remove-label satisfies:REQ-03 --label satisfies:b7157be6/REQ-03 --remove-label cites:Roffe2020 --label cites:@/citation/Roffe2020
"$JIT" issue update d7749931-bcf1-4e5b-bbcd-4d845ff1ede7 --remove-label satisfies:REQ-12 --label satisfies:ae03bcd0/REQ-12
"$JIT" issue update da120b98-4a6b-44f4-9597-a9dc55a667f9 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update dbd8787d-fee6-49db-be64-b055796f8756 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update dcd38c45-66ae-43ed-b689-3a9dcd2600b3 --remove-label satisfies:REQ-35 --label satisfies:3f29e945/REQ-35
"$JIT" issue update ddac2d5d-095d-4d0f-8935-f714256c4c64 --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03
"$JIT" issue update ddd0c6ee-8f3d-401d-ba7e-7fadc1ee0e79 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update de2522d6-0dc1-4763-a20d-e7dd991722df --remove-label satisfies:REQ-01 --label satisfies:0de41c82/REQ-01 --remove-label satisfies:REQ-02 --label satisfies:0de41c82/REQ-02 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update deda0962-2366-493d-b0fd-c65874ba7cbe --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05
"$JIT" issue update df385aa7-89e0-4684-8cbf-3ce782a26694 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update e0251af3-25c3-4914-8018-c3b66dd9561a --remove-label satisfies:REQ-04 --label satisfies:b8206228/REQ-04 --remove-label cites:GGK2025 --label cites:@/citation/GGK2025
"$JIT" issue update e02ee7ce-c6e7-4af7-96c3-2cbf635d2e83 --remove-label satisfies:REQ-03 --label satisfies:0de41c82/REQ-03
"$JIT" issue update e1e0e7ff-36f3-46e4-8bcb-db406c526bcb --remove-label satisfies:REQ-11 --label satisfies:ae03bcd0/REQ-11
"$JIT" issue update e1f262a7-668d-421f-9bea-13f80fdb81e0 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update e1f9a78f-1a3e-4066-8744-aa55d10f85db --remove-label satisfies:REQ-01 --label satisfies:2037941f/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update e2744fcf-470b-45d6-8750-0413620eb151 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update e6ea0dde-185f-4a0f-91fe-13cc6ac32648 --remove-label satisfies:REQ-05 --label satisfies:6dc81018/REQ-05
"$JIT" issue update e85b8edf-f35f-49b5-bdb1-65502b7d30e1 --remove-label satisfies:REQ-08 --label satisfies:fa787f85/REQ-08
"$JIT" issue update e8a727ff-44b8-48d2-9368-8dedf774777c --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update e8fe47f5-5098-4500-b8ce-8e4a062a7787 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update e992c5b0-d3c0-4b4c-a2f0-44b5c00594db --remove-label satisfies:REQ-08 --label satisfies:ae03bcd0/REQ-08
"$JIT" issue update eaae1b56-e58c-408e-969e-9f407bf8120f --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update eace5009-d595-4a23-bd68-6034df5e5352 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update eb2a833d-75b4-45b7-89ea-b8aafcd36cb1 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update eb8825c8-058c-43af-bb46-e79759c7e90d --remove-label satisfies:REQ-02 --label satisfies:b8206228/REQ-02
"$JIT" issue update eb9b324c-d9d3-425d-93a6-d0253033a710 --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update eba21481-61e7-4e27-b2e0-4701f08c4f5a --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update ebdbd228-cc01-4b49-b961-cda8b32a7935 --remove-label satisfies:REQ-04 --label satisfies:ae03bcd0/REQ-04
"$JIT" issue update ec655592-d647-4fbc-90de-ef44ed313067 --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14 --remove-label satisfies:REQ-12 --label satisfies:fa787f85/REQ-12
"$JIT" issue update ec7d2aec-e7f4-472b-99cf-52d4b09f3bfa --remove-label satisfies:REQ-15 --label satisfies:fa787f85/REQ-15
"$JIT" issue update ed3d490e-8cd9-4564-a763-72a2fa641425 --remove-label satisfies:REQ-03 --label satisfies:1a379447/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Srsran2026 --label cites:@/citation/Srsran2026 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026
"$JIT" issue update ed494117-4245-4e92-855b-3c54e207697d --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026
"$JIT" issue update ed51b844-0e96-475a-8f5c-e4ac1d95862a --remove-label satisfies:REQ-1 --label satisfies:7be754bd/REQ-1 --remove-label satisfies:REQ-2 --label satisfies:7be754bd/REQ-2 --remove-label satisfies:REQ-3 --label satisfies:7be754bd/REQ-3
"$JIT" issue update eda07788-23a0-4852-939b-2cfcda36f9d1 --remove-label satisfies:REQ-01 --label satisfies:1a379447/REQ-01 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019
"$JIT" issue update ee2b0c0c-a88d-4ab7-aeb4-58cbd4ad0ca4 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update ee50e270-74ea-4566-a0a7-69791af66e8a --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05 --remove-label satisfies:REQ-17 --label satisfies:fa787f85/REQ-17
"$JIT" issue update ef5b75f4-657b-45ea-a167-cd79ea26fb30 --remove-label satisfies:REQ-01 --label satisfies:b4b4b9ee/REQ-01 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update ef8ff9c4-94e2-4e83-8167-f786a1e02906 --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update f048383f-8a85-4ef6-849e-f75b628e9450 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update f0d6fb9a-e138-4267-8a81-a5170ebf8e72 --remove-label satisfies:REQ-02 --label satisfies:b7157be6/REQ-02 --remove-label cites:Fossorier1995 --label cites:@/citation/Fossorier1995 --remove-label cites:Yue2022 --label cites:@/citation/Yue2022
"$JIT" issue update f0dd63f1-e326-406b-a7b3-6f68e43d2143 --remove-label satisfies:REQ-14 --label satisfies:fa787f85/REQ-14
"$JIT" issue update f2064e90-ad75-4253-8402-41d63d38af41 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update f22ec590-b185-4444-903b-e9623a183213 --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update f27150a5-8713-4bce-b404-9e477937d498 --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03
"$JIT" issue update f29a9225-0cd6-4fb2-91a5-7ba56b1b706b --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10 --remove-label satisfies:REQ-19 --label satisfies:fa787f85/REQ-19
"$JIT" issue update f35daec0-f729-48f7-8c06-2180d815a222 --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update f3dc1bb1-526f-42e2-860a-66d0d0e8279b --remove-label cites:GGK2025 --label cites:@/citation/GGK2025 --remove-label cites:HKS2026 --label cites:@/citation/HKS2026 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update f46046f0-3672-4bec-8d57-83bc77a6043b --remove-label satisfies:REQ-21 --label satisfies:ffc35b8c/REQ-21 --remove-label satisfies:REQ-22 --label satisfies:ffc35b8c/REQ-22 --remove-label satisfies:REQ-23 --label satisfies:ffc35b8c/REQ-23 --remove-label satisfies:REQ-25 --label satisfies:ffc35b8c/REQ-25 --remove-label satisfies:REQ-26 --label satisfies:ffc35b8c/REQ-26
"$JIT" issue update f547c394-9f05-4207-8f7f-2dcbb9e56999 --remove-label satisfies:REQ-01 --label satisfies:d77176e5/REQ-01 --remove-label satisfies:REQ-05 --label satisfies:1a379447/REQ-05
"$JIT" issue update f6148d1e-d151-4c21-8507-7efd39044548 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update f63a2464-424d-4def-a740-8ff1471f0108 --remove-label satisfies:REQ-01 --label satisfies:ed3d490e/REQ-01 --remove-label satisfies:REQ-03 --label satisfies:1a379447/REQ-03 --remove-label satisfies:REQ-06 --label satisfies:1a379447/REQ-06 --remove-label cites:Cassagne2019 --label cites:@/citation/Cassagne2019 --remove-label cites:Srsran2026 --label cites:@/citation/Srsran2026 --remove-label cites:Xdsopl2026 --label cites:@/citation/Xdsopl2026
"$JIT" issue update f694f59a-bf27-42d5-8197-b68b60b5bf37 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update f74e327d-688d-4ffe-880f-a01b471e33d8 --remove-label satisfies:REQ-03 --label satisfies:b8206228/REQ-03 --remove-label cites:Scheinerman2024 --label cites:@/citation/Scheinerman2024
"$JIT" issue update f759d724-e1e3-466b-9d57-a3d1a57123ab --remove-label satisfies:REQ-10 --label satisfies:ae03bcd0/REQ-10
"$JIT" issue update f79bcba3-ec86-49c2-82a1-1689a67e6015 --remove-label satisfies:REQ-11 --label satisfies:fa787f85/REQ-11
"$JIT" issue update f8dd4dde-bafd-42a2-a329-5edcf900b520 --remove-label satisfies:REQ-07 --label satisfies:c04dd4ac/REQ-07 --remove-label satisfies:REQ-08 --label satisfies:c04dd4ac/REQ-08 --remove-label satisfies:REQ-09 --label satisfies:c04dd4ac/REQ-09 --remove-label satisfies:REQ-11 --label satisfies:c04dd4ac/REQ-11
"$JIT" issue update f902240f-f550-47ea-84fa-326f3d3f96a1 --remove-label satisfies:REQ-10 --label satisfies:fa787f85/REQ-10
"$JIT" issue update fa85c403-1166-4578-a9b3-ed58d4d1f870 --remove-label satisfies:REQ-02 --label satisfies:ae03bcd0/REQ-02
"$JIT" issue update fa92608b-5f8a-47c3-ae35-a6a70a85db7a --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update fb209a81-59cf-4bb1-86c9-597637a4bba2 --remove-label satisfies:REQ-09 --label satisfies:fa787f85/REQ-09
"$JIT" issue update fbe66a7a-454c-459a-a231-63f4adcf3dcb --remove-label satisfies:REQ-03 --label satisfies:6dc81018/REQ-03
"$JIT" issue update fc2fa0b6-d169-4741-918d-d690c0f06333 --remove-label satisfies:REQ-01 --label satisfies:ae03bcd0/REQ-01
"$JIT" issue update fc976a80-d046-41ca-b97e-766bdf8c37ce --remove-label satisfies:REQ-04 --label satisfies:6dc81018/REQ-04
"$JIT" issue update fca578b1-2593-4bc4-8f08-8a425f3b237f --remove-label satisfies:REQ-17 --label satisfies:fa787f85/REQ-17 --remove-label satisfies:REQ-01 --label satisfies:fa787f85/REQ-01 --remove-label satisfies:REQ-05 --label satisfies:fa787f85/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:fa787f85/REQ-06
"$JIT" issue update fcb04d66-e997-491e-8855-a505e139a39b --remove-label satisfies:REQ-02 --label satisfies:2037941f/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:2037941f/REQ-04 --remove-label satisfies:REQ-05 --label satisfies:2037941f/REQ-05 --remove-label satisfies:REQ-06 --label satisfies:2037941f/REQ-06
"$JIT" issue update fd9d5416-d529-427d-a273-10e6468b9a19 --remove-label satisfies:REQ-13 --label satisfies:ae03bcd0/REQ-13 --remove-label satisfies:REQ-14 --label satisfies:ae03bcd0/REQ-14
"$JIT" issue update fdb998ec-6042-4112-8bf9-1f179128d62b --remove-label satisfies:REQ-03 --label satisfies:fa787f85/REQ-03
"$JIT" issue update fe26dc9a-be55-4be6-a911-c5328cd7b1d8 --remove-label satisfies:REQ-02 --label satisfies:b4b4b9ee/REQ-02 --remove-label satisfies:REQ-04 --label satisfies:b4b4b9ee/REQ-04
"$JIT" issue update ffc35b8c-5f2a-4a37-8eef-905b362b615d --remove-label satisfies:REQ-17 --label satisfies:fa787f85/REQ-17
