-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [probe]: function definitions
import Aeneas
import P2Probe.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace probe

/-- [probe::pow_concrete]: loop body 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 33:4-41:5
    Visibility: public -/
@[rust_loop_body]
def pow_concrete_loop.body
  (result : Std.U64) (base : Std.U64) (e : Std.U64) :
  Result (ControlFlow (Std.U64 × Std.U64 × Std.U64) Std.U64)
  := do
  if e > 0#u64
  then
    let i ← lift (e &&& 1#u64)
    let result1 ←
      if i = 1#u64
      then ok (core.num.U64.wrapping_mul result base)
      else ok result
    let e1 ← e >>> 1#i32
    if e1 > 0#u64
    then
      let base1 ← lift (core.num.U64.wrapping_mul base base)
      ok (cont (result1, base1, e1))
    else ok (cont (result1, base, e1))
  else ok (done result)

/-- [probe::pow_concrete]: loop 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 33:4-41:5
    Visibility: public -/
@[rust_loop]
def pow_concrete_loop
  (result : Std.U64) (base : Std.U64) (e : Std.U64) : Result Std.U64 := do
  loop
    (fun (result1, base1, e1) => pow_concrete_loop.body result1 base1 e1)
    (result, base, e)

/-- [probe::pow_concrete]:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 26:0-43:1
    Visibility: public -/
def pow_concrete (x : Std.U64) (exp : Std.U64) : Result Std.U64 := do
  if exp = 0#u64
  then ok 1#u64
  else pow_concrete_loop 1#u64 x exp

/-- [probe::pow_simple]: loop body 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 52:4-60:5
    Visibility: public -/
@[rust_loop_body]
def pow_simple_loop.body
  {F : Type} (SimpleInst : Simple F) (result : F) (base : F) (e : Std.U64) :
  Result (ControlFlow (F × F × Std.U64) F)
  := do
  if e > 0#u64
  then
    let i ← lift (e &&& 1#u64)
    let result1 ←
      if i = 1#u64
      then SimpleInst.mul_ref result base
      else ok result
    let e1 ← e >>> 1#i32
    if e1 > 0#u64
    then
      let base1 ← SimpleInst.mul_ref base base
      ok (cont (result1, base1, e1))
    else ok (cont (result1, base, e1))
  else ok (done result)

/-- [probe::pow_simple]: loop 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 52:4-60:5
    Visibility: public -/
@[rust_loop]
def pow_simple_loop
  {F : Type} (SimpleInst : Simple F) (result : F) (base : F) (e : Std.U64) :
  Result F
  := do
  loop
    (fun (result1, base1, e1) => pow_simple_loop.body SimpleInst result1 base1
      e1)
    (result, base, e)

/-- [probe::pow_simple]:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 45:0-62:1
    Visibility: public -/
def pow_simple
  {F : Type} (SimpleInst : Simple F) (x : F) (exp : Std.U64) : Result F := do
  if exp = 0#u64
  then SimpleInst.one_like x
  else
    let result ← SimpleInst.one_like x
    let base ← SimpleInst.corecloneCloneInst.clone x
    pow_simple_loop SimpleInst result base exp

/-- [probe::pow_assoc]: loop body 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 71:4-79:5
    Visibility: public -/
@[rust_loop_body]
def pow_assoc_loop.body
  {F : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc F Clause0_Ch Clause0_Wide) (result : F) (base : F) (e : Std.U64) :
  Result (ControlFlow (F × F × Std.U64) F)
  := do
  if e > 0#u64
  then
    let i ← lift (e &&& 1#u64)
    let result1 ←
      if i = 1#u64
      then WithAssocInst.mul_ref result base
      else ok result
    let e1 ← e >>> 1#i32
    if e1 > 0#u64
    then
      let base1 ← WithAssocInst.mul_ref base base
      ok (cont (result1, base1, e1))
    else ok (cont (result1, base, e1))
  else ok (done result)

/-- [probe::pow_assoc]: loop 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 71:4-79:5
    Visibility: public -/
@[rust_loop]
def pow_assoc_loop
  {F : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc F Clause0_Ch Clause0_Wide) (result : F) (base : F) (e : Std.U64) :
  Result F
  := do
  loop
    (fun (result1, base1, e1) => pow_assoc_loop.body WithAssocInst result1
      base1 e1)
    (result, base, e)

/-- [probe::pow_assoc]:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 64:0-81:1
    Visibility: public -/
def pow_assoc
  {F : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc F Clause0_Ch Clause0_Wide) (x : F) (exp : Std.U64) :
  Result F
  := do
  if exp = 0#u64
  then WithAssocInst.one_like x
  else
    let result ← WithAssocInst.one_like x
    let base ← WithAssocInst.corecloneCloneInst.clone x
    pow_assoc_loop WithAssocInst result base exp

/-- [probe::WithAssocExt::pow_default]: loop body 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 94:8-102:9
    Visibility: public -/
@[rust_loop_body]
def WithAssocExt.pow_default.default_loop.body
  {Self : Type} {Clause0_Clause0_Ch : Type} {Clause0_Clause0_Wide : Type}
  (WithAssocExtInst : WithAssocExt Self Clause0_Clause0_Ch
  Clause0_Clause0_Wide) (result : Self) (base : Self) (e : Std.U64) :
  Result (ControlFlow (Self × Self × Std.U64) Self)
  := do
  if e > 0#u64
  then
    let i ← lift (e &&& 1#u64)
    let result1 ←
      if i = 1#u64
      then WithAssocExtInst.WithAssocInst.mul_ref result base
      else ok result
    let e1 ← e >>> 1#i32
    if e1 > 0#u64
    then
      let base1 ← WithAssocExtInst.WithAssocInst.mul_ref base base
      ok (cont (result1, base1, e1))
    else ok (cont (result1, base, e1))
  else ok (done result)

/-- [probe::WithAssocExt::pow_default]: loop 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 94:8-102:9
    Visibility: public -/
@[rust_loop]
def WithAssocExt.pow_default.default_loop
  {Self : Type} {Clause0_Clause0_Ch : Type} {Clause0_Clause0_Wide : Type}
  (WithAssocExtInst : WithAssocExt Self Clause0_Clause0_Ch
  Clause0_Clause0_Wide) (result : Self) (base : Self) (e : Std.U64) :
  Result Self
  := do
  loop
    (fun (result1, base1, e1) => WithAssocExt.pow_default.default_loop.body
      WithAssocExtInst result1 base1 e1)
    (result, base, e)

/-- [probe::WithAssocExt::pow_default]:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 87:4-104:5
    Visibility: public -/
def WithAssocExt.pow_default.default
  {Self : Type} {Clause0_Clause0_Ch : Type} {Clause0_Clause0_Wide : Type}
  (WithAssocExtInst : WithAssocExt Self Clause0_Clause0_Ch
  Clause0_Clause0_Wide) (self : Self) (exp : Std.U64) :
  Result Self
  := do
  if exp = 0#u64
  then WithAssocExtInst.WithAssocInst.one_like self
  else
    let result ← WithAssocExtInst.WithAssocInst.one_like self
    let base ← WithAssocExtInst.WithAssocInst.corecloneCloneInst.clone self
    WithAssocExt.pow_default.default_loop WithAssocExtInst result base exp

/-- [probe::{impl probe::WithAssocExt<Clause0_Ch, Clause0_Wide> for T}::pow_default]: loop body 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 94:8-102:9
    Visibility: public -/
@[rust_loop_body]
def WithAssocExt.Blanket.pow_default_loop.body
  {T : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc T Clause0_Ch Clause0_Wide) (result : T) (base : T) (e : Std.U64) :
  Result (ControlFlow (T × T × Std.U64) T)
  := do
  if e > 0#u64
  then
    let i ← lift (e &&& 1#u64)
    let result1 ←
      if i = 1#u64
      then
        (WithAssocExt.Blanket WithAssocInst).WithAssocInst.mul_ref result base
      else ok result
    let e1 ← e >>> 1#i32
    if e1 > 0#u64
    then
      let base1 ←
        (WithAssocExt.Blanket WithAssocInst).WithAssocInst.mul_ref base base
      ok (cont (result1, base1, e1))
    else ok (cont (result1, base, e1))
  else ok (done result)

/-- [probe::{impl probe::WithAssocExt<Clause0_Ch, Clause0_Wide> for T}::pow_default]: loop 0:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 94:8-102:9
    Visibility: public -/
@[rust_loop]
def WithAssocExt.Blanket.pow_default_loop
  {T : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc T Clause0_Ch Clause0_Wide) (result : T) (base : T) (e : Std.U64) :
  Result T
  := do
  loop
    (fun (result1, base1, e1) => WithAssocExt.Blanket.pow_default_loop.body
      WithAssocInst result1 base1 e1)
    (result, base, e)

/-- [probe::{impl probe::WithAssocExt<Clause0_Ch, Clause0_Wide> for T}::pow_default]:
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 107:0-107:40
    Visibility: public -/
def WithAssocExt.Blanket.pow_default
  {T : Type} {Clause0_Ch : Type} {Clause0_Wide : Type} (WithAssocInst :
  WithAssoc T Clause0_Ch Clause0_Wide) (self : T) (exp : Std.U64) :
  Result T
  := do
  if exp = 0#u64
  then (WithAssocExt.Blanket WithAssocInst).WithAssocInst.one_like self
  else
    let result ←
      (WithAssocExt.Blanket WithAssocInst).WithAssocInst.one_like self
    let base ←
      (WithAssocExt.Blanket
        WithAssocInst).WithAssocInst.corecloneCloneInst.clone self
    WithAssocExt.Blanket.pow_default_loop WithAssocInst result base exp

/-- Trait implementation: [probe::{impl probe::WithAssocExt<Clause0_Ch, Clause0_Wide> for T}]
    Source: 'dev/active/34d85cb9/extraction/probe.rs', lines 107:0-107:40 -/
@[reducible]
def WithAssocExt.Blanket {T : Type} {Clause0_Ch : Type} {Clause0_Wide : Type}
  (WithAssocInst1 : WithAssoc T Clause0_Ch Clause0_Wide) : WithAssocExt T
  Clause0_Ch Clause0_Wide := {
  WithAssocInst := WithAssocInst1
  pow_default := WithAssocExt.Blanket.pow_default WithAssocInst1
}

end probe
