#!/usr/bin/env bash
# Disassembles the arms this survey times and records what this host actually
# emits (jit:26465e6c REQ-04).
#
# REQ-04 requires the emitted instructions be observed rather than another
# processor's published dispatch thresholds imported. Every threshold this
# survey reports therefore comes from one of two places, both captured here:
# a compare constant visible in the disassembly of the shipped code, or a loop
# stride visible in the disassembly of the reference implementation.
#
# Usage: dev/active/26465e6c/survey/observe-instructions.sh > objdump-evidence.txt
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GF2_SIDE="${HERE}/gf2-side/target/release/popcount-gf2-side"
LIBPOPCNT="${HERE}/libpopcnt-arm"
MULA="${HERE}/mula-avx2-harleyseal-arm"
for bin in "${GF2_SIDE}" "${LIBPOPCNT}" "${MULA}"; do
  [[ -x "${bin}" ]] || { echo "missing binary: ${bin}" >&2; exit 2; }
done

# Prints the disassembly of one symbol, demangled, without the file header.
disassemble() {
  local binary="$1" symbol="$2"
  objdump --disassemble="${symbol}" -C -M att --no-show-raw-insn "${binary}" |
    sed -e '1,/^$/d' -e '/^Disassembly of section/d' -e '/^$/d'
}

# Prints only the instruction mnemonics of one symbol with their counts, which
# is the evidence for "which instruction family does this path use".
mnemonics() {
  local binary="$1" symbol="$2"
  disassemble "${binary}" "${symbol}" |
    awk '{ for (i = 1; i <= NF; ++i) if ($i ~ /^[a-z][a-z0-9]*$/ && $(i-1) ~ /:$/) { print $i; break } }' |
    sort | uniq -c | sort -rn
}

echo "# Emitted-instruction evidence for jit:26465e6c"
echo "# host: $(uname -srm)"
echo "# cpu: $(awk -F': ' '/^model name/ { print $2; exit }' /proc/cpuinfo)"
echo "# generated by dev/active/26465e6c/survey/observe-instructions.sh"
echo "# objdump: $(objdump --version | head -1)"
echo

echo "=== 1. gf2 production dispatcher: the scalar/vector selection threshold ==="
echo "# gf2_core::kernels::backend::select_backend_for_size compares the word"
echo "# count against SIMD_MIN_WORDS and is inlined into the dispatcher, so the"
echo "# threshold appears as a compare constant inside production_dispatch."
disassemble "${GF2_SIDE}" popcount_gf2_side::production_dispatch | grep -E "cmp|jae|jb|call" | head -20
echo
echo "# The compare constant above is the observed threshold. Source constant:"
grep -n "SIMD_MIN_WORDS_DEFAULT: usize" "${HERE}/../../../../crates/gf2-core/src/kernels/backend.rs"
echo

echo "=== 2. gf2 AVX2 nibble-LUT popcount (avx2_popcnt) ==="
echo "# Expect vpshufb nibble lookup plus vpsadbw byte-sum; no popcnt."
mnemonics "${GF2_SIDE}" gf2_kernels_simd::x86::avx2::avx2_popcnt
echo

echo "=== 3. gf2 fused AVX2 AND+popcount (avx2_and_popcnt) ==="
echo "# Expect the same nibble-LUT reduction with a vpand fused into the load."
mnemonics "${GF2_SIDE}" gf2_kernels_simd::x86::avx2::avx2_and_popcnt
echo

echo "=== 4. internal control: forced scalar POPCNT instruction loop ==="
echo "# Expect the popcnt instruction, which #[target_feature(enable = \"popcnt\")]"
echo "# authorizes in this otherwise baseline-x86-64 build."
mnemonics "${GF2_SIDE}" popcount_gf2_side::scalar_popcnt_instruction_loop_inner
echo

echo "=== 5. internal control: portable compiler count_ones loop ==="
echo "# Expect NO popcnt and NO AVX2: this build carries no target-cpu flag, so"
echo "# count_ones() lowers to the portable SWAR sequence. That is the control's"
echo "# whole point and the reason its build identity is conservative-portable."
mnemonics "${GF2_SIDE}" popcount_gf2_side::compiler_count_ones
echo

echo "=== 6. internal control: gf2 production dispatcher scalar path ==="
echo "# The dispatcher's below-threshold path reaches the same portable"
echo "# count_ones lowering as control 5."
mnemonics "${GF2_SIDE}" popcount_gf2_side::production_dispatch
echo

echo "=== 7. external: libpopcnt runtime CPUID dispatch ==="
echo "# Expect a cached CPUID word, an AVX2 vpshufb path and an AVX-512 branch"
echo "# this Zen 3 host's CPUID never selects."
mnemonics "${LIBPOPCNT}" popcnt
echo "# The AVX-512 entry point libpopcnt keeps but this host does not reach:"
disassemble "${LIBPOPCNT}" popcnt | grep -E "popcnt_avx512" | head -5
echo

echo "=== 8. external: Mula AVX2 Harley-Seal, and its observed CSA threshold ==="
echo "# AVX2_harley_seal::popcnt runs its 16-way carry-save network over"
echo "# 'limit = size - size % 16' 256-bit words, so the network engages only at"
echo "# 16 vectors = 512 bytes = 64 u64 words. Below that the loop body never"
echo "# runs and only the per-vector tail reduction executes. The stride is"
echo "# visible as the loop's pointer advance and its trip-count masking."
disassemble "${MULA}" "AVX2_harley_seal::popcnt(long long __vector(4) const*, unsigned long)" |
  grep -E "and|sub|add.*\\\$0x|cmp" | head -12
echo "# Vendored source line fixing the same stride:"
grep -n "size % 16" "${HERE}/vendor/mula/popcnt-avx2-harley-seal.cpp"
echo "# And its 32-byte byte-tail boundary:"
grep -n "size % 32" "${HERE}/vendor/mula/popcnt-avx2-harley-seal.cpp"
echo
echo "# Aligned-load evidence: the reference dereferences a __m256i*, which the"
echo "# compiler lowers to vmovdqa. This is why the arm refuses word_offset != 0."
# `grep -c` exits non-zero on zero matches, which is a real answer here, not a
# failure; count into a variable so `pipefail` does not stop the report.
count_instruction() {
  local binary="$1" symbol="$2" pattern="$3" label="$4" total
  total=$(disassemble "${binary}" "${symbol}" | grep -cE "${pattern}" || true)
  echo "${label}: ${total}"
}
mula_symbol="AVX2_harley_seal::popcnt(long long __vector(4) const*, unsigned long)"
count_instruction "${MULA}" "${mula_symbol}" "vmovdqa" "mula aligned loads (vmovdqa)"
count_instruction "${MULA}" "${mula_symbol}" "vmovdqu|vlddqu" "mula unaligned loads (vmovdqu/vlddqu)"
echo
echo "# gf2's own kernels load through _mm256_loadu_si256 and tolerate any"
echo "# alignment; libpopcnt does the same. Their unaligned-load counts:"
count_instruction "${GF2_SIDE}" gf2_kernels_simd::x86::avx2::avx2_popcnt "vmovdqu|vlddqu" "gf2 avx2_popcnt unaligned loads"
count_instruction "${GF2_SIDE}" gf2_kernels_simd::x86::avx2::avx2_and_popcnt "vmovdqu|vlddqu" "gf2 avx2_and_popcnt unaligned loads"
count_instruction "${LIBPOPCNT}" popcnt "vmovdqu|vlddqu" "libpopcnt unaligned loads"
