#!/usr/bin/env bash
# Re-evaluate every committed 26465e6c receipt with the current acceptance
# tool (jit:26465e6c).
#
# Usage (from the repository root):
#   dev/active/26465e6c/survey/reevaluate.sh
#
# Writes dev/bench_results/26465e6c/reevaluation.txt. Each receipt directory is
# copied to a scratch directory under target/ and evaluated there, so the
# committed acceptance summaries, protocol-v1 history included, stay
# byte-identical. The record gives the tool's verdict line and its findings
# grouped by rule and message, whether each fresh summary file equals the
# committed one, every verdict, cell decision, outcome or interval bound that
# differs between the two summaries, and every producing input the receipt
# pins that its committed snapshot lacks.

set -euo pipefail
repo=$(git rev-parse --show-toplevel)
[[ "$PWD" == "$repo" ]] || { echo 'invoke from the repository root' >&2; exit 2; }
RESULTS=dev/bench_results/26465e6c
OUT=$RESULTS/reevaluation.txt
ACCEPTANCE=$repo/target/release/benchmark-acceptance
mkdir -p "$repo/target"
SCRATCH=$(mktemp -d "$repo/target/26465e6c-reevaluate.XXXXXX")
trap 'rm -rf "$SCRATCH"' EXIT

{
  echo "# re-evaluation with the current benchmark-acceptance (jit:26465e6c)"
  echo "# generated by dev/active/26465e6c/survey/reevaluate.sh"
  echo "# acceptance executable sha256 $(sha256sum "$ACCEPTANCE" | cut -d' ' -f1)"
  echo "# evaluator source dev/tools/tuning-campaign-support/src/receipt.rs sha256 $(sha256sum dev/tools/tuning-campaign-support/src/receipt.rs | cut -d' ' -f1)"
  for receipt in "$RESULTS"/*/receipt.json; do
    dir=$(dirname "$receipt")
    copy="$SCRATCH/$(basename "$dir")"
    cp -r "$dir" "$copy"
    echo
    echo "receipt $receipt sha256 $(sha256sum "$receipt" | cut -d' ' -f1)"
    set +e
    verdict=$("$ACCEPTANCE" "$copy")
    status=$?
    set -e
    echo "  $verdict (exit $status)"
    for file in acceptance-summary.json acceptance-summary.md; do
      if cmp -s "$dir/$file" "$copy/$file"; then
        echo "  $file: byte-identical to the committed file"
      else
        echo "  $file: differs from the committed file"
      fi
    done
    python3 - "$dir" "$copy" <<'PY'
import json, pathlib, sys
committed, fresh = (pathlib.Path(path) for path in sys.argv[1:])
old, new = (json.loads((path / "acceptance-summary.json").read_text(encoding="utf-8"))
            for path in (committed, fresh))
producing = json.loads((committed / "receipt.json").read_text(encoding="utf-8"))["source"]["producing"]
missing = [path for group in ("behavior_sha256", "lifecycle_sha256", "build_inputs_sha256")
           for path in producing.get(group, {})
           if not (committed / "inputs" / "producing" / path).is_file()]
print(f"  pinned producing inputs absent from the committed snapshot: {', '.join(missing) or 'none'}")
changed = [f"{key}: {old[key]} -> {new[key]}"
           for key in ("verdict", "qualifies", "label") if old[key] != new[key]]
for before, after in zip(old["cells"], new["cells"]):
    for field in ("outcome", "decision"):
        if before.get(field) != after.get(field):
            changed.append(f"{before['cell_id']} {field}: {before.get(field)} -> {after.get(field)}")
    for field in ("estimate", "lower", "upper", "confidence"):
        if (before.get("interval") or {}).get(field) != (after.get("interval") or {}).get(field):
            changed.append(f"{before['cell_id']} interval.{field} differs")
added = sorted({key for cell in new["cells"] for key in (cell.get("interval") or {})}
               - {key for cell in old["cells"] for key in (cell.get("interval") or {})})
print(f"  differing verdicts, decisions, outcomes or interval bounds: {len(changed)}")
for line in changed:
    print(f"    {line}")
print(f"  interval fields the fresh summary adds: {', '.join(added) or 'none'}")
groups = {}
for finding in new["findings"]:
    key = (finding["rule"], finding["severity"], finding["message"])
    groups.setdefault(key, set()).add(finding["cell"])
for (rule, severity, message), cells in sorted(groups.items()):
    named = sorted(cell for cell in cells if cell)
    where = (f" on {', '.join(named)}" if len(named) <= 3 else f" on {len(named)} cells"
             ) if named else ""
    print(f"  fresh finding {rule} {severity}{where}: {message}")
PY
  done
} >"$OUT"
echo "wrote $OUT" >&2
