-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [seam_shape]: function definitions
import Aeneas
import M2SeamShape.Types
import M2SeamShape.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace seam_shape

/-- [seam_shape::driver::route_seam]:
    Source: 'src/driver.rs', lines 16:0-22:1
    Visibility: public -/
def driver.route_seam
  {F : Type} (fieldSelectorInst : field.Selector F) (n : Std.Usize) (x : F) :
  Result Std.U64
  := do
  let i ← tuning.winograd_min_dim
  if n <= i
  then fieldSelectorInst.value x
  else let i1 ← fieldSelectorInst.value x
       i1 + 1#u64

/-- [seam_shape::field::Selector::THRESHOLD]
    Source: 'src/field.rs', lines 8:4-8:33
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def field.Selector.THRESHOLD.default (Self : Type) : Std.Usize := 128#usize

/-- [seam_shape::field::Selector::PANEL]
    Source: 'src/field.rs', lines 10:4-10:41
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def field.Selector.PANEL.default {Self : Type} (SelectorInst : field.Selector
  Self) : Result Std.Usize :=
  SelectorInst.THRESHOLD

end seam_shape
