-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace gf2_core

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 768:0-768:37
    Name pattern: [core::ops::arith::AddAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [gf2_core::field::traits::FiniteField]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 44:0-868:1
    Visibility: public -/
structure field.traits.FiniteField (Self : Type) (Self_Characteristic : Type)
  (Self_Wide : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corecmpEqInst : core.cmp.Eq Self
  corehashHashInst : core.hash.Hash Self
  corefmtDebugInst : core.fmt.Debug Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  coreopsarithAddSelfSharedSelfSelfInst : core.ops.arith.Add Self Self Self
  coreopsarithSubInst : core.ops.arith.Sub Self Self Self
  coreopsarithSubSelfSharedSelfSelfInst : core.ops.arith.Sub Self Self Self
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  coreopsarithMulSelfSharedSelfSelfInst : core.ops.arith.Mul Self Self Self
  coreopsarithDivInst : core.ops.arith.Div Self Self Self
  coreopsarithDivSelfSharedSelfSelfInst : core.ops.arith.Div Self Self Self
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self Self
  coreopsarithAddAssignSelfSharedSelfInst : core.ops.arith.AddAssign Self Self
  corecloneCloneInst : core.clone.Clone Self_Characteristic
  corefmtDebugInst : core.fmt.Debug Self_Characteristic
  corecmpPartialEqInst : core.cmp.PartialEq Self_Characteristic
    Self_Characteristic
  corecmpEqInst : core.cmp.Eq Self_Characteristic
  corecloneCloneInst : core.clone.Clone Self_Wide
  coreopsarithAddInst : core.ops.arith.Add Self_Wide Self_Wide Self_Wide
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self_Wide Self_Wide
  characteristic : Self → Result Self_Characteristic
  extension_degree : Self → Result Std.Usize
  is_zero : Self → Result Bool
  is_one : Self → Result Bool
  inv : Self → Result (Option Self)
  zero_like : Self → Result Self
  one_like : Self → Result Self
  to_wide : Self → Result Self_Wide
  mul_to_wide : Self → Self → Result Self_Wide
  reduce_wide : Self_Wide → Result Self
  max_unreduced_additions : Result Std.Usize

/-- Trait declaration: [gf2_core::field::traits::FiniteFieldExt]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 918:0-1011:1
    Visibility: public -/
structure field.traits.FiniteFieldExt (Self : Type)
  (Self_Clause0_Characteristic : Type) (Self_Clause0_Wide : Type) where
  FiniteFieldInst : field.traits.FiniteField Self Self_Clause0_Characteristic
    Self_Clause0_Wide
  square : Self → Result Self
  pow : Self → Std.U64 → Result Self
  frobenius : forall (coreconvertIntoPU64Inst : core.convert.Into
    Self_Clause0_Characteristic Std.U64), Self → Std.Usize → Result Self

end gf2_core
