-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gf2_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Q5Gf2Core.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open gf2_core

/-- [core::iter::traits::collect::{impl core::iter::traits::collect::IntoIterator<Clause0_Item> for I}::into_iter]:
    Source: '/rustc/library/core/src/iter/traits/collect.rs', lines 322:4-322:27
    Name pattern: [core::iter::traits::collect::{core::iter::traits::collect::IntoIterator<@I, @Clause0_Item>}::into_iter]
    Visibility: public -/
@[rust_fun
  "core::iter::traits::collect::{core::iter::traits::collect::IntoIterator<@I, @Clause0_Item>}::into_iter"]
axiom core.iter.traits.collect.IntoIterator.Blanket.into_iter
  {I : Type} {Clause0_Item : Type} (iteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  I → Result I

/-- [gf2_core::field::traits::FiniteField::WINOGRAD_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 825:4-825:42
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.WINOGRAD_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} (FiniteFieldInst :
  sorry /- Could not find: trait_decl_id: 2-/ Self Clause0_Characteristic)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::TRI_BASE_THRESHOLD]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 858:4-858:40
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.TRI_BASE_THRESHOLD.default {Self : Type}
  {Clause0_Characteristic : Type} (FiniteFieldInst :
  sorry /- Could not find: trait_decl_id: 2-/ Self Clause0_Characteristic)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_BASE_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 892:4-892:35
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_BASE_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} (FiniteFieldInst :
  sorry /- Could not find: trait_decl_id: 2-/ Self Clause0_Characteristic)
  : Result Std.Usize

/-- [gf2_core::field::traits::FiniteField::PLE_PANEL_COLS]
    Source: 'crates/gf2-core/src/field/traits.rs', lines 926:4-926:54
    Visibility: public -/
@[trait_default]
axiom field.traits.FiniteField.PLE_PANEL_COLS.default {Self : Type}
  {Clause0_Characteristic : Type} (FiniteFieldInst :
  sorry /- Could not find: trait_decl_id: 2-/ Self Clause0_Characteristic)
  : Result Std.Usize

