-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [seam_shape]: function definitions
import Aeneas
import M4SeamShape.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace seam_shape

/-- [seam_shape::driver::route_hooked]:
    Source: 'src/driver.rs', lines 26:0-28:1
    Visibility: public -/
def driver.route_hooked
  {F : Type} (fieldHookedInst : field.Hooked F) (x : F) : Result Std.U64 := do
  fieldHookedInst.value x

/-- [seam_shape::field::Hooked::has_panel_kernel]:
    Source: 'src/field.rs', lines 30:4-32:5
    Visibility: public -/
def field.Hooked.has_panel_kernel.default (Self : Type) : Result Bool := do
  ok false

/-- [seam_shape::field::Hooked::UNREAD]
    Source: 'src/field.rs', lines 34:4-34:28
    Visibility: public -/
@[global_simps, irreducible, trait_default]
def field.Hooked.UNREAD.default (Self : Type) : Std.Usize := 7#usize

end seam_shape
